### ISSUE TITLE
Vendor and Buyer Need ability to Switch Moderators

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#1003]
If a moderator is unresponsive, or if a moderator refuses to moderate per #1002 then the buyer and vendor need the ability to agree upon a new moderator. This would create a 2-of-3 transaction and send to a new 2-of-3 address and automatically open a new dispute.

Pinging @cpacia since this would require a lot of server work as well.

**Comment by jjeffryes** [comment]
Switching moderators is a feature we're working on adding to v2.
