### ISSUE TITLE
Add a simple photo editor

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1008]
When uploading photos of physical goods, sometimes you want to crop or otherwise modify the image. For now users will have to do that outside the client before they upload, but it would be nice to have some basic functionality in the client itself.

**Comment by CobraX03** [comment]
This would be very helpful. I have noticed on Windows 10 that the image looks normal and after uploading the orientation is rotated for some reason and I am unable to fix this. When opening the image in Windows the orientation is correct but it is not displaying that way in the client.

**Comment by jjeffryes** [comment]
We're not planning to add a photo editor to v1. This might be a feature that is included in v2.
