### ISSUE TITLE
User search using @ handles throws error.

### ISSUE THREAD

**Issue by votaguz** [OpenBazaar/OpenBazaar-Client#1013]
Brief Description: 
When you try to make a search using an user handle ( @votaguz for example ). Client shows that get an invalid response from server, but the "Developer Tool" view shows all the data correctly.

Operating System (OS and version): 
Mac OSX 10.11.3

OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Version 1.0.7

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Open the Developer Tools console.
2. Do a search using a "handle" for an user. ( @votaguz for example ) 

Additional info (links, images, etc go here):
![screen shot 2016-03-07 at 7 18 00 pm](https://cloud.githubusercontent.com/assets/368680/13588059/c24788ac-e49a-11e5-930d-36aee748c6d6.png)

**Comment by rmisio** [comment]
The code is expecting the API to return an `account` object with a `service` key equal to `openbazaar` with your OB GUID as the `identifier`. It looks like you need to register your ob GUID with Onename for this to happen. Once you do so, I think it takes a day or two for the API to pick it up.

![image](https://cloud.githubusercontent.com/assets/794517/13794956/e9170418-eabb-11e5-8797-583045474617.png)
