### ISSUE TITLE
Buying multiple items from vendor and shipping.

### ISSUE THREAD

**Issue by jondale** [OpenBazaar/OpenBazaar-Client#1014]
Currently OpenBazaar only allows you to purchase one item at a time.  If you buy many items from the same vendor you have to do a transaction for each item and pay for shipping of each item individually.  Most buyers and sellers would like to buy all the items together in one transaction and have them shipped together to save on shipping.

One solution would be a cart for each store where you can select items and then create a transaction once all items are selected.

Shipping calculations could be done in a few ways.
1.  Each item could be assigned a weight/size and then prices could be given based on total weight/size for each region.
2.  A flat fee could calculated based on number of items chosen.
3.  Shipping cost could be based off orders total cost.

**Comment by TheButterZone** [comment]
Cart would be good.

Pre-order shipping calculations may be the death of OB for me, since flat-rate shipping isn't necessarily cheaper than non-flat rate for 100% of the things I could ship. https://github.com/OpenBazaar/OpenBazaar-Client/issues/905

**Comment by Dekker3D** [comment]
TheButterZone, I'm not sure I understand your situation very well (give some examples?), but would it help if you could disable that sort of combined shipping for certain items? That way, you'd have the best of both worlds.

**Comment by TheButterZone** [comment]
Github seems to be getting DOS'd... when that's over, see https://github.com/OpenBazaar/OpenBazaar-Client/issues/905

**Comment by LiteBit** [comment]
A work around to this atm is to encourage buyers PM vendor before ordering somehow (graphics, twitter). Then vendor creates custom order with items and makes a combined shipping price. Product(s) can be deleted after purchase.

Not ideal, but works for both parties and allows 1 moderator for full order.

**Comment by jjeffryes** [comment]
We're not planning to add a cart or grouping of items in v1. This might be a feature that is added to v2.
