### ISSUE TITLE
Refund address

### ISSUE THREAD

**Issue by nelsonpk** [OpenBazaar/OpenBazaar-Client#1015]
Brief Description: Refund address for purchase not being accepted

Operating System (OS and version): Win 8.1
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.6
Hardware: Inter i7

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Paste address into refund address
2. Attempt to go go nest
3. Red dotted box around address (assume not verifying)

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):
![image](https://cloud.githubusercontent.com/assets/16044038/13604505/da536470-e53a-11e5-98cd-50229262ee22.png)

**Comment by jjeffryes** [comment]
@nelsonpk are you using a testnet address?

**Comment by nelsonpk** [comment]
Ah – didn’t appreciate that was necessary – I’ll get one – thanks.

Didn’t see a mention in the documentation (although I might have missed that – newbie!!)

Best regards

 Philip Ketteringham

M: 07808 056332

H: 01494 725943

O: 01494 258551

F: 0203 637 5371

 41 Highland Rd

Amersham

Bucks HP7 9AX

**Comment by jjeffryes** [comment]
No worries. In the 1.0.7 build, we added a warning to that field so it's clear it needs to be a testnet address. You should see something like this:

![image](https://cloud.githubusercontent.com/assets/1584275/13605126/0b7a6c32-e514-11e5-803f-c081a918da25.png)

**Comment by nelsonpk** [comment]
Thanks – are the 1.0.7 windows binaries available as of yet?

Best regards

 Philip Ketteringham

M: 07808 056332

H: 01494 725943

O: 01494 258551

F: 0203 637 5371

 41 Highland Rd

Amersham

Bucks HP7 9AX
