### ISSUE TITLE
Can't change Location info for Digital Item & Service listings

### ISSUE THREAD

**Issue by JoshuaOpolko** [OpenBazaar/OpenBazaar-Client#1017]
Brief Description: When I create a listing as "Physical Item" I can specify "Ships to Canada" and the location will indicate Canada as expected.

But if I create a "Digital Item" or a "Service" the location defaults to "United States" and I can't seem to change it.

Operating System (OS and version):  Ubuntu 14.04 x86_64

OpenBazaar version:  1.0.7

Hardware: Dual-quad Intel(R) Xeon(R) CPU X5450  @ 3.00GHz 12 GB RAM

Reproducible: Always

Steps to reproduce:
1. Create a new listing with Type: "Digital Item" or "Service"
2. Select "Save"

Observed Behavior:
The Location info defaults to "United States".

Expected Behavior:
I'd expect to be able to change the location for "Digital Items" and "Service" types.

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
@JoshuaOpolko  Where do you see the location set to United States?

**Comment by JoshuaOpolko** [comment]
It's on the "Store" tab. I've attached a screenshot.

**Comment by JoshuaOpolko** [comment]
![location](https://cloud.githubusercontent.com/assets/13841672/13614957/f4681ea4-e540-11e5-8b5e-09f49deb3e20.png)
