### ISSUE TITLE
Exact same store present 4 times in a row

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1018]
In the `Pages` tab, I see the same store (same GUID) 4 times. See the screenshot below.

![screen shot 2016-03-08 at 19 44 07](https://cloud.githubusercontent.com/assets/731743/13612155/4692c966-e566-11e5-9e38-f8ba15a78635.png)

**Comment by jjeffryes** [comment]
This is a server issue, I am closing it here.
