### ISSUE TITLE
Lazy load is not working correctly on followers/following tab

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1021]
Look at @themes followers tab. It lazy loads in the same 20ish listings over and over as you start scrolling. Not sure if this is a server issue or client issue.

**Comment by jjeffryes** [comment]
Looks like a server issue. get_followers is sending duplicates.

**Comment by jjeffryes** [comment]
Let me retract that. 

It looks like a combination of zombie stores with the same name and avatar but different guids, and the script appending the new followers to the top instead of the bottom.

**Comment by morebrownies** [comment]
New followers should display at the top, otherwise the list will always look stale.

**Comment by jjeffryes** [comment]
Not new followers that just happened. New followers loaded as you scroll down.

**Comment by morebrownies** [comment]
ahhh
