### ISSUE TITLE
I'm following @themes, but they're not displaying in my Following tab

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1022]
As the title says...

The button displays "Unfollow" when I visit @themes:

<img width="1280" alt="screenshot 2016-03-08 14 55 20" src="https://cloud.githubusercontent.com/assets/13066886/13616072/ee2037f0-e53d-11e5-8116-d13fc7d56f3e.png">

However when I visit my page, it shows I'm following zero pages:

<img width="1280" alt="screenshot 2016-03-08 14 54 11" src="https://cloud.githubusercontent.com/assets/13066886/13616097/0414ad8e-e53e-11e5-8d53-33d6ddf5bd4a.png">

I tried refreshing, unfollowing and re-following and it results in the same issue.

**Comment by morebrownies** [comment]
When I follow other pages, it appears to work ok.

**Comment by morebrownies** [comment]
So maybe it's a bug associated to pages that are in the recommended pages to follow list?

**Comment by jjeffryes** [comment]
Following doesn't work until you get a message back from the node you're following. Themes might be running really slow, and if you close the page before it replies, I don't think the follow will be acknowledged.

That's something we'd have to look at, and see if we can fix.

Try following themes and then don't touch it for a long time.

**Comment by morebrownies** [comment]
Still seeing the same issue with each new follower.
