### ISSUE TITLE
Show Avatar and Consistent Terminology in Dispute Close modal

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1027]
This is the current dispute close modal:

![image](https://cloud.githubusercontent.com/assets/3887694/13623363/da73a778-e5f1-11e5-9718-538bba3bcfc7.png)

In the Discussion tab, the Vendor is called 'Vendor', but we then call them the 'Seller' when determining the split of funds. It's a possible stumbling block for users, so it should be changed to Vendor. To make it even easier, we should show the avatar of the Buyer and Vendor.

**Comment by morebrownies** [comment]
Yes avatars are extremely helpful here. Moderator is not going to easily remember who is who.
