### ISSUE TITLE
Filter by shipping destination matching my location

### ISSUE THREAD

**Issue by ulrichard** [OpenBazaar/OpenBazaar-Client#1028]
Brief Description: 
It happens very ofter that I want to buy something and click through a couple of dialogs just to discover that it won't be shipped to my location.
Would be nice if I could filter beforehand.

Reproducible : Always

**Comment by drwasho** [comment]
I think this will require some changes to the `get_listings` API to return regions where the item will ship. Is that right @cpacia @jjeffryes ?

**Comment by jjeffryes** [comment]
The listings already have ships_to, so this is just a client side change.

We'll probably need a toggle button for it.

**Comment by drwasho** [comment]
We're going to approach this in a slightly different way: https://github.com/OpenBazaar/OpenBazaar-Client/issues/1444

Future versions (post-IPFS) and channels can allow for more sophisticated filtering.
