### ISSUE TITLE
No default selection for purchases

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#1029]
I think this should probably default to moderated selection. Also when there is only one option just auto-select it.

![image](https://cloud.githubusercontent.com/assets/45482/13642162/5dcbcf50-e5e9-11e5-82b6-02e55108259f.png)

Sorry disable was momentarily not working but i struck that from the issue.

**Comment by morebrownies** [comment]
Sounds good to me. I'll add in the branch I'm working on.

**Comment by TheButterZone** [comment]
Disagree. I will be selecting Direct Payment over the "RECOMMENDED" and cannot afford a default to ever accidentally be selected.

**Comment by drwasho** [comment]
Feel free to explain why @TheButterZone, but the trust properties significantly deteriorate with 'Direct Payment' compared to Moderated transactions. Better to default to Moderated payments.

**Comment by TheButterZone** [comment]
My [WoT](http://b-otc.com/vg?nick=TheButterZone) standing since 2012 either means something or it doesn't. I will not be coerced.

**Comment by drwasho** [comment]
> 0 coercion marketplace, or not?

Forgive me, but that's being hyperbolic. It's a default `option` (being the keyword) that takes 0.5 seconds to change if the user doesn't want to do a moderated transaction to use escrow to protect themselves from scammers. 

Anyway, it's up to Vendors to decide whether they want to use a Moderator, and Buyers to decide to use that Moderator or not purchase your items if they're not comfortable handing over their funds before you ship an item.

**Comment by TheButterZone** [comment]
You clearly haven't had my brutal sales experience, including default overriding for hundreds of items, then.

This would be making it up to Vendors to decide whether they DON'T want to use a moderator, rather than making a choice from a blank slate.

**Comment by drwasho** [comment]
> That default is making it up to Vendors to decide they DON'T want to use a moderator, rather than making a choice from a blank slate.

Currently the default is for Vendors to not have a Moderator, so technically the default option is Direct Payments. But as soon as the Vendor has selected a Moderator, moderated transactions will be the default option for Buyers when making purchases. If they're not happy with this, they can move their mouse by ~3 cm down to click 'Direct Purchase'.

**Comment by TheButterZone** [comment]
Not according to the screenshot in the OP, where nothing is selected by default.

**Comment by drwasho** [comment]
> Not according to the screenshot in the OP, where nothing is selected by default.

That is when the Buyer goes to make a purchase. When the Vendor creates a store, no Moderators are auto-selected, which means anything they list will only have Direct Payment as an option. During the Vendor on-boarding, we do give them the option to select from a list of moderators... but if they don't select a moderator then Direct Payment will be the only option.

**Comment by TheButterZone** [comment]
Never mind... /headdesk
