### ISSUE TITLE
Make GUID selectable

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1030]
At the moment the GUID in the following screenshot is not selectable. I've seen several people frustrated by that.

![screen shot 2016-03-09 at 19 20 54](https://cloud.githubusercontent.com/assets/731743/13645644/302e32ac-e62c-11e5-84d3-d5e83e750fe3.png)

**Comment by Nogreedy** [comment]
Hello,
Why don't you use an handle (tied with Onename) ? : it's more convenient...

![capture](https://cloud.githubusercontent.com/assets/6340683/13701963/972497e8-e78b-11e5-9ea8-84a614e8099d.PNG)

**Comment by mariodian** [comment]
I'll fix it
