### ISSUE TITLE
Menu opens when clicking on tooltip

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1031]
To reproduce:
- Hover to get the Menu tooltip showing
- Staying on the tooltip, move your mouse to the bottom-left corner of the tooltip
- Notice that your mouse cursor is far away from the "Menu button
- Click and notice the Menu open, despite the cursor not being on the button

![screen shot 2016-03-09 at 19 24 59](https://cloud.githubusercontent.com/assets/731743/13645743/b9b73686-e62c-11e5-8cab-3f4e3721c07f.png)

**Comment by drwasho** [comment]
Can't decide if this is a feature or not lol. Thoughts @jjeffryes and @morebrownies ?

**Comment by jjeffryes** [comment]
A bug. I just removed pointer events from tooltips, so you can't click on it any more.
