### ISSUE TITLE
No scrollbar for list of followers

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1032]
Steps the reproduce:
- Go to ob://@helpdesk/followers
- Scroll through the many followers
- Notice the lack of scrollbar (I find it disorientating/dizzying)

![screen shot 2016-03-09 at 19 31 26](https://cloud.githubusercontent.com/assets/731743/13645966/a8d8191a-e62d-11e5-905e-d7a6cce1ac1a.png)

**Comment by morebrownies** [comment]
This is my fault. I'll fix.
