### ISSUE TITLE
[Mac OS] Crash on exit

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1033]
I'm using master's HEAD on Mac OS. Steps to repro:
- Open the frontend
- Do `cmd + w`
- Frontend disappears then crashes (see screenshot below)

![screen shot 2016-03-09 at 19 34 53](https://cloud.githubusercontent.com/assets/731743/13646046/0279356c-e62e-11e5-9785-a043f1c0d2df.png)

**Comment by mariodian** [comment]
I can't reproduce it. I don't even see any error in terminal (do you?).

**Comment by rmisio** [comment]
I believe this is fixed.

Cmd + W is to close a window. Since we are a one-window app, we close the app then the window is closed. I'm not seeing the 'quit unexpectedly' error.
