### ISSUE TITLE
Can't save PGP key or PGP signature.

### ISSUE THREAD

**Issue by JoshuaOpolko** [OpenBazaar/OpenBazaar-Client#1038]
Brief Description: Can't save PGP key or PGP signature. 
Operating System (OS and version): ubuntu 14.04 amd64
OpenBazaar version (shown on `About OpenBazaar` page in menu):  1.0.7
Reproducible: Always

Steps to reproduce:
1. Select Menu->Settings->Page->PGP Key
2. Enter PGP Public Key
3. Enter PGP Signature (signed OB ID)
4. Click "Save Changes"

Observed Behavior:
Message box displays "Your Changes Have Been Saved", however the PGP key and signature fields are blank, the values were not saved. 

Expected Behavior:
The key and sig should be saved.

Additional info (links, images, etc go here):
![pgp](https://cloud.githubusercontent.com/assets/13841672/13647121/95bdd8e2-e600-11e5-8b62-2ffa454ddf56.png)

**Comment by SavageCore** [comment]
Also discussion here: https://github.com/OpenBazaar/OpenBazaar-Server/issues/260

**Comment by drwasho** [comment]
@jjeffryes should we just remove the PGP field if it's not going to be ready by the mainnet release?

**Comment by jjeffryes** [comment]
If @cpacia can't fix the server issue for launch, then we'll put TODO on these elements which will remove them from the UI.

**Comment by jjeffryes** [comment]
The fields have been hidden, I am assuming the server issue will not be fixed by v1 release.
