### ISSUE TITLE
Add padding below (and above) QR code

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1039]
The QR code feels really tight in the screenshot below, especially relative to the text underneath.

![screen shot 2016-03-09 at 20 15 56](https://cloud.githubusercontent.com/assets/731743/13647313/cd09cab2-e633-11e5-8541-481184227488.png)

**Comment by hoffmabc** [comment]
Are you having problems with it being recognized? We have a comfortably larger size than is required by the standard and I haven't seen issues. If you are truly having problems please reopen and let me know in what circumstances it doesn't resolve.

**Comment by JustinDrake** [comment]
This report is about aesthetics. Generally images and text have "breathing space" between them. Check out the lack of padding in the screenshot below. Please reopen.

![screen shot 2016-03-09 at 20 34 42](https://cloud.githubusercontent.com/assets/731743/13647871/5fdeda1a-e636-11e5-87d2-2ab2c1c9bd5e.png)

**Comment by hoffmabc** [comment]
I renamed the issue because it was confusing. Spacing below the QR code is what you were asking for.

**Comment by JustinDrake** [comment]
Cheers. In CSS there's a property called `padding` which is may do the job here.
