### ISSUE TITLE
Improperly centered Support page

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1040]
Please see the screenshot below. The centering of the Support page is off (to the left) because of the messages bar being expanded.

![screen shot 2016-03-09 at 20 17 31](https://cloud.githubusercontent.com/assets/731743/13647387/2ad7d3a0-e634-11e5-8fb2-0bb1b7c6e99e.png)

**Comment by jjeffryes** [comment]
That is functioning as intended.
