### ISSUE TITLE
Unprofessional looking Slack invite URL

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1041]
The Slack invite URL is `https://openbazaar-slackin-drwasho.herokuapp.com/`. This feels unprofessional. What about something like `https://slack.openbazaar.org`?

**Comment by hoffmabc** [comment]
It already is that and has been for a while.

**Comment by hoffmabc** [comment]
![image](https://cloud.githubusercontent.com/assets/45482/13647778/9e92164c-e603-11e5-9e9a-23627d89cb5a.png)

**Comment by morebrownies** [comment]
Mental note: we need to add this updated URL to the website too

**Comment by JustinDrake** [comment]
@hoffmabc: The OpenBazaar client does not have the updated link. Please reopen.

**Comment by JustinDrake** [comment]
@hoffmabc: See screenshot below for the offending link (taken from master's HEAD)

![screen shot 2016-03-09 at 20 39 46](https://cloud.githubusercontent.com/assets/731743/13648066/39f655c0-e637-11e5-8b74-2a8cdc27f66c.png)
