### ISSUE TITLE
Menu openable when Support page is open

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1043]
Steps to repro:
- Open "Support OpenBazaar"
- While "Support OpenBazaar" is open, click on Menu
- Notice the menu opens and is greyed out (see screenshot below)

![screen shot 2016-03-09 at 20 26 07](https://cloud.githubusercontent.com/assets/731743/13647677/7488096a-e635-11e5-9616-4f22a71df69f.png)

**Comment by jjeffryes** [comment]
It should be possible to open the menu when the about modal is showing. The issue with the menu being behind the modal has been resolved.
