### ISSUE TITLE
Moderator fee rounding issue

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1045]
See screenshot. A moderator has a 4.19999980927% fee. Looks like a rounding issue.

![screen shot 2016-03-09 at 20 42 44](https://cloud.githubusercontent.com/assets/731743/13648144/878df19e-e637-11e5-9ef0-3b6b63eaba38.png)

**Comment by mariodian** [comment]
It seems it's not possible to input such crazy float numbers in your moderator settings anymore (I get an error). I'd say it doesn't need to be fixed for this particular case then.
