### ISSUE TITLE
UI doesn't cue user when no moderator is selected

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1046]
To repro:
- Click on Buy
- Choose a "Moderated Payment"
- Click Next without selecting a moderator
- Notice nothing happens

The UI doesn't cue the user when no moderator is selected. The next button is not greyed out, for example. See screenshot

![screen shot 2016-03-09 at 20 45 30](https://cloud.githubusercontent.com/assets/731743/13648272/158bad56-e638-11e5-8355-f3c73a50d262.png)

**Comment by jjeffryes** [comment]
I can't reproduce this on master.

![image](https://cloud.githubusercontent.com/assets/1584275/13648568/4e644c4a-e607-11e5-9837-f14f710ec08d.png)

**Comment by JustinDrake** [comment]
Hum. I just pulled from master's `HEAD` and this is 100% reproducible for me. Maybe a Mac specific issue?

**Comment by drwasho** [comment]
Fixed.

**Comment by JustinDrake** [comment]
Wow, you guys are on fire today!
