### ISSUE TITLE
Description in Become a Store required but no indicator

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#1059]
The indicator only shows if you click the description input and then hit next. If the user just hits next it won't highlight the input red like it should and there is no indication that it's required.
![image](https://cloud.githubusercontent.com/assets/45482/13658512/a1fb435c-e645-11e5-9425-5699e113ae9e.png)

**Comment by rmisio** [comment]
When I click next, the field does highlight in red. Maybe somebody fixed this?

**Comment by jjeffryes** [comment]
I fixed this, I forgot to close the issue.
