### ISSUE TITLE
Language file languagesMd.js became clumsy (10526 lines) and needs splitting into many parts.

### ISSUE THREAD

**Issue by Squirrel2020** [OpenBazaar/OpenBazaar-Client#1060]
There is a few inconveniences of using 1 file for all languages:
- Hard to use search. When I need to find "VendorShipsTo" it finds this variable at many languages
- Can't edit in GitHub, because internal GitHub's editor in Chrome become working incredibly slowly (10526 lines!!! almost impossible to edit anything).
- I have to copy stuff to Notepad++ and if I forgot to upload (as it was yesterday), +100 lines get added by developers and my revision is not topical anymore :( few hours of checking if it LGTM with interface with language just gone

Too many problems to deal with, and too many technical skills required for potential translators and very annoying even for technically skilled person.

**Comment by mariodian** [comment]
It was already brought up here #420.
