### ISSUE TITLE
Page Loader Off-Center When Chat is Open

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#1063]
![image](https://cloud.githubusercontent.com/assets/45482/13674013/d7bf1612-e6a9-11e5-8db4-ed40952aa891.png)

**Comment by jjeffryes** [comment]
Is this on the latest master?

It looks like this when I test it.

![image](https://cloud.githubusercontent.com/assets/1584275/13674057/035e37a8-e6aa-11e5-9f26-852cd8397af2.png)

**Comment by rmisio** [comment]
this was fixed.
https://github.com/OpenBazaar/OpenBazaar-Client/pull/1058
