### ISSUE TITLE
[Error] A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Kirvx** [OpenBazaar/OpenBazaar-Client#1068]
Windows 10 x64
OpenBazaar 1.0.8 x64
Always Reproducible

No problem with OpenBazaar 1.0.7 x64

**When closing OpenBazaar:**

![sans titre](https://cloud.githubusercontent.com/assets/6627786/13682811/c62b7512-e703-11e5-9f47-3fba82a0034b.png)

**Comment by jjeffryes** [comment]
@Kirvx does this happen with both the installer and the version installed from Github, or just the installer version?

**Comment by hoffmabc** [comment]
I'm seeing this as well so I'll fix it.

**Comment by hoffmabc** [comment]
I think it's that Windows doesn't support the SIGHUP call to kill the server.

**Comment by Kirvx** [comment]
@jjeffryes Just with the installer

**Comment by hoffmabc** [comment]
This is because it doesn't try to kill the server for manual install.
