### ISSUE TITLE
Client stuck loading

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#107]
With server running client loads but is stuck here:

![screenshot from 2015-10-28 09 35 36](https://cloud.githubusercontent.com/assets/6955773/10790345/242195e4-7d59-11e5-8ce8-b435b217e531.png)

Nothing in console. Client log:

```
[15253:1028/094659:ERROR:browser_main_loop.cc(185)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[15278:1028/094700:INFO:renderer_main.cc(200)] Renderer process started
[15282:1028/094700:INFO:renderer_main.cc(200)] Renderer process started
```

**Comment by jjeffryes** [comment]
I have found on situation that can cause this, if a module can't be found it can break things at the beginning of the current view file and lock you in this state. 

If that happened, however, there would be a JavaScript error in the console (web dev tools and in the command window). 

Just adding that to the record as a possible clue.

**Comment by SamPatt** [comment]
@jjeffryes I now see this in console though it's likely unrelated:

```
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

**Comment by hoffmabc** [comment]
I think it's in one of the modules. Didn't seem problematic.

**Comment by SamPatt** [comment]
Is there any way to manually force a profile call?

**Comment by jjeffryes** [comment]
Starting the client makes a profile call.

**Comment by SamPatt** [comment]
Mine doesn't, that's the problem here. Didn't know if I could do that manually with the dev tools in client.

**Comment by jjeffryes** [comment]
The app tries to load the profile 10 times when it starts up, and if all 10 fails, tries again with the default local server. If all of those fail, there is probably something wrong with your server or your installation.

**Comment by jjeffryes** [comment]
@SamPatt, are you still running into this problem?

**Comment by SamPatt** [comment]
On my local Ubuntu 12.04, yes, this is still a problem.

I upgraded my laptop to Ubuntu 14.04 and it isn't a problem on there.
