### ISSUE TITLE
Not been able to connect for a couple of days

### ISSUE THREAD

**Issue by bangers89** [OpenBazaar/OpenBazaar-Client#1071]
Brief Description: I keep hitting "Retry connection" but it won;t connect

Operating System (OS and version): OSX Yosemite v 10.10.4
OpenBazaar version (shown on About OpenBazaar page in menu): 1.0.8
Hardware: MacBook Pro (Retina, 13-inch, Late 2013)

Reproducible (*_Always *_/ Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
Open app and keep trying to make it connect

Observed Behavior: Constantly get "Unable to connect to your server" - I can see my own page but can;t view any listings

Expected Behavior: To connect and be able to see other listings

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
If you installed manually, make sure you are starting your server with the testnet flag, -t.

if you used the installer, or are sure you're on the testnet, try shutting down your server (in settings/adanced), then find your OpenBazaar folder on your computer, and delete the cache.pickle file, and the OB-Testnet database. Then restart your client, and then your server (in that order).

**Comment by M45t3rJC** [comment]
[https://openbazaar.zendesk.com/hc/en-us/articles/208277053-Authentication-Failed](url)

**Comment by drwasho** [comment]
Please join slack.openbazaar.org for closer support.
