### ISSUE TITLE
Can't add address or refund address

### ISSUE THREAD

**Issue by JTuwiner** [OpenBazaar/OpenBazaar-Client#1076]
**Brief Description:** I tried adding a refund address for a transaction and wasn't able to continue to the next step. I thought maybe it was because I had not included an address in my profile. When I went to add an address there, I also got an error. This first happened to be on 1.0.7. Updated to 1.0.8 and get same error. Both are pictured below. 

**Operating System (OS and version):** Mac OS X 10.10.5
**OpenBazaar version (shown on `About OpenBazaar` page in menu):** 1.0.7/1.0.8
**Hardware:** Macbook Pro 13-inch, early 2011

*_Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): *_
Tried four times, got same error. 

**Steps to reproduce:**
1. Click "buy now" on item
2. try to add refund address

**Observed Behavior**: red background, error, not able to continue to payment

**Expected Behavior:** Continue to next step to complete payment

**Additional info (links, images, etc go here):**
Screenshots of errors http://imgur.com/a/W41yJ 
http://imgur.com/6NzkXTp

**Comment by jjeffryes** [comment]
What address are you trying to use? Is it a valid testnet address?

**Comment by jjeffryes** [comment]
If you don't see a testnet label on that field, you are using an older release. Try installing version 1.0.8 and then use a testnet address.

![image](https://cloud.githubusercontent.com/assets/1584275/13707800/64898648-e779-11e5-8d17-4973cb211815.png)

**Comment by mariodian** [comment]
It seems (the second screenshot) that you are trying to use a mainnet address. You need to use a testnet one that doesn't start with "1".

**Comment by drwasho** [comment]
Definitely need to use a testnet address. Let us know if you need any testnet coins.
