### ISSUE TITLE
Text overlaps profile image

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Client#110]
This is when you scroll to the bottom and it shrinks the avatar image. (on ubuntu, don't know about others)

![image](https://cloud.githubusercontent.com/assets/4504708/10806296/af0bcab6-7daa-11e5-89f7-3b05ddd7e538.png)

**Comment by morebrownies** [comment]
Fixed this is header2, will be merged soon.

**Comment by jjeffryes** [comment]
Fixed and merged.
