### ISSUE TITLE
Blocking single items

### ISSUE THREAD

**Issue by jondale** [OpenBazaar/OpenBazaar-Client#1102]
The problem at hand is when a store owner has a product that contains mature content (but they have not marked the item as having mature content).  If you want to block that item but not the rest of the store there is no current solution.  The only option is to block the entire store.

A solution would be the ability to block single listings and/or mark them as mature.

**Comment by jjeffryes** [comment]
Can't that vendor just make more NSFW listings that are also not marked as NSFW that you would then see and have to block?

**Comment by drwasho** [comment]
@jjeffryes maybe the way to approach this is to 'hide' the listing on the client side. Is that possible?

**Comment by jondale** [comment]
If they are intentionally trying to circumvent the filter then I would just block the store completely.  This would be more for a store that is generally not mature content but has one or two items (and maybe forgets to mark them)... such as what's on OB atm.

**Comment by drwasho** [comment]
We had some debate and we came to a rough consensus that hiding/blocking individual listings doesn't really make a lot of sense. Gonna pass on it for now. Thanks for the suggestion.
