### ISSUE TITLE
Photo upload failing

### ISSUE THREAD

**Issue by M45t3rJC** [OpenBazaar/OpenBazaar-Client#1109]
Brief Description: Photos (JPG) not always uploading for new listings...

Operating System (OS and version): OSX 10.10.5
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.8
Hardware: MacBook Pro - 2.3GHz i7 -- 4GM DDR3

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Sometimes

Steps to reproduce:
1. take Photo with iPhone
2. upload Photo to MacBook
3. Drag & Drop into OpenBazaar/click Select photos
4. choose Photo, click Open

Observed Behavior:
Acts like Photos are uploading, and then no Photos appear in added Photos box 

Expected Behavior:
Photos appear in added Photos box

Additional info (links, images, etc go here):
I added a new listing 
Computer #1  ob://b3803528b1598a279e7bc01fd9e6e8831574927f/listing/f123dbfa99fbbd1bad70e18183aaa431f11bcb35
Everything worked correctly.
Attempted to add another listing (Computer #2) used same process to upload photos and nothing.
I even attempted to clone Computer #1 listing and just changing information as needed including photos, photos still wouldn't upload.
I've quit and re-started OB several time to see if it would "fix" this bug, it hasn't.
I attempted to upload other random JPG's and some will upload and others won't.
Editing photos in Preview seems to increase the likelihood of upload not completing, but this isn't consistent either.

**Comment by rmisio** [comment]
The file you're trying to uploaded must be a image (have an image mime type) and the browser must be able to load it. At this time we don't have any messaging to indicate if either of those are not true, the image is silently ignored.

When you right click on the file and select Get Info, what does it say in the Kind: section?

If it passes these first two tests, then we upload the image to the server. If it fails, you would see some errors in your browser console. If that's the case, please let us know what you're seeing.

**Comment by M45t3rJC** [comment]
Kind: JPEG image
There isn't an error "pop-up" when upload fails.

**Comment by rmisio** [comment]
it appears your image is failing on the upload to the server. To see the error, you would open up your console, via View > Toggle Developer Tool, then click on the Network tab. When you upload the image, you'll see an upload_image entry appear on the left half of the screen. Click on that and then your error will be in the Response tab. Would you please let us know what you see?

![image](https://cloud.githubusercontent.com/assets/794517/13796368/8481d46c-eac3-11e5-82a6-206ab70e675d.png)

(We understand this isn't the most user friendly way to see why your upload is failing. Looking ahead, we should probably display the errors in the UI.)

**Comment by M45t3rJC** [comment]
Thank you rmisio
I had the photos in files with # signs and once I deleted non-alphanumeric characters and spaces from file and folder name the photo uploads like it should.
IMO: This info needs to be added into into the next update, at the very least added to the tutorial...

**Comment by M45t3rJC** [comment]
I can recreate it, but keep getting "Failed to Load Response Data" message in Dev.Tools.

**Comment by drwasho** [comment]
@SamPatt Something to add to the tutorials.
