### ISSUE TITLE
Text still not translated

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1126]
The following texts are still not being translated into any language:

Page tab in Settings
- "Avatar" (title)

Advanced tab in Settings
- "Severely Restricted" (text)

**Comment by mariodian** [comment]
I'll fix it

**Comment by mariodian** [comment]
I'm getting the version number from package.json. Hope it's ok. I'm not getting it directly from electron instance, because it shows the version of electron on this dev repo, not the version OB. However in the production it would work ok. The way I did it, it's ok on both.

**Comment by jjeffryes** [comment]
Accidentally closed by a typo in a commit summary.

**Comment by ghost** [comment]
Updated:

The following texts are still not being translated into any language:

Page tab in Settings
- "Avatar" (title)

Advanced tab in Settings
- "Severely Restricted" (text)
