### ISSUE TITLE
I'm seeing another nodes items on my store page

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#113]
This happened randomly. I went to Brian's page first and then back to my page. It doesn't happen every time.

http://i.imgur.com/13FPI8W.png

**Comment by hoffmabc** [comment]
I think this can happen if you quickly go between stores. It's the asynchronous items loading in I think.

**Comment by jjeffryes** [comment]
The store items come from get_listings, they aren't asynchronous. I've been trying to reproduce this, but haven't seen it so far.

If either of you see this again, can you look at your network tab to see if get_listings was called, what guid was on the call, and whether it returned the listings you're seeing?
