### ISSUE TITLE
Listings stock units

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1133]
When the user creates a listing, they need to be able to set the quantity of units available for purchase. When an item is purchased, the stock available for purchase should reduce until it is out of stock. 

I believe the listing Ricardian Contract has a `quantity` field, but I'll check up on that. One approach would be to auto-edit the original listing to reduce the `quantity` value **after** the order has been funded. So the edit may be triggered with the 'order funded' notification/event?

Related server issue: https://github.com/OpenBazaar/OpenBazaar-Server/issues/299

**Comment by jjeffryes** [comment]
This will need a matching backend ticket, the changes there are more complicated.

**Comment by jjeffryes** [comment]
This would require the following modifications on the client:
1. if get_homepage_listings and get_listings return the inventory for each item, the client would display them, and have filtering to show or hide zero inventory listings.
2. the inventory would be displayed on the item view
3. in the buying flow, the user would be prevented from purchasing a quantity above the current inventory.
4. when purchase_contract is called, it should reject purchases that exceed the current inventory of the contract, the client will need to display that error and show the remaining inventory

**Comment by drwasho** [comment]
I mentioned this in the server issue, but we should only be reducing the inventory after an order has been funded. This will prevent an attacker performing a near zero-cost attack to deplete a target Vendor's inventory for sale.

For changing the inventory number after a funded order, are we making a simple edit of the original listing or do you suggest something more sophisticated @jjeffryes ?

**Comment by jjeffryes** [comment]
Editing the original contract after an order is funded is what I was thinking.

Comments left in the other issue re: subtracting inventory.

**Comment by pryds** [comment]
If possible, would it make sense to let the seller choose whether they want to reveal the exact remaining stock quantity, or just show "available" or "out of stock" (and maybe "few left") to potential buyers?

Also, if stock count is only decreased after seller receives payment (which is good), I think that needs to be communicated clearly to buyers ("Your item is only reserved for you once your payment clears").

**Comment by drwasho** [comment]
Great suggestion.

**Comment by ghost** [comment]
You should also set a limit to the maximum number of items and the total value of an order.

![limit number](https://cloud.githubusercontent.com/assets/10789865/14096857/2f252206-f542-11e5-8063-4eac2e2d9ebe.png)

**Comment by jjeffryes** [comment]
This will be in v2, we're not planning to include it in v1.
