### ISSUE TITLE
Avatars on the 'Funds' tab of an 'Order Details' modal fail

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1137]
![image](https://cloud.githubusercontent.com/assets/3887694/13868819/b012712a-ed18-11e5-8fa4-4b60262ae639.png)

This is a long-standing bug I've seen, but can someone please confirm that one or both of these avatar images aren't loading?

**Comment by Kirvx** [comment]
Can confirm, but no problem with moderators:
![3](https://cloud.githubusercontent.com/assets/6627786/13874781/398e1478-ecfa-11e5-990b-190d2203ba68.png)

**Comment by jjeffryes** [comment]
The buyer's avatar can be easily fixed, but not the vendor's avatar. The avatar_hash for the vendor isn't in the data for the contract. We could make a call to the profile for it, but that would slow things down, especially if the vendor is on a slow connection.
