### ISSUE TITLE
When pasting bitcoin address, leading spaces cause input to be rejected as invalid

### ISSUE THREAD

**Issue by 8vkt97npu8** [OpenBazaar/OpenBazaar-Client#1139]
Brief Description: 

Operating System (OS and version): Ubuntu
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: 1.0.9

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Buy something
2. Paste in bitcoin address when paying (paste in leading space and address)
3. 

Observed Behavior:
Field is highlighted red but there is no help or text about what is wrong.

Expected Behavior:
OB would ignore leading white-space and accept input.

Additional info (links, images, etc go here):

**Comment by mariodian** [comment]
I'll fix it
