### ISSUE TITLE
Checkboxes no longer look like checkboxes

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1140]
I just noticed these changed. Can we restore them to how they use to look? Or was there a reason for the change @jjeffryes?

<img width="111" alt="screenshot 2016-03-18 13 58 18" src="https://cloud.githubusercontent.com/assets/13066886/13888845/956f826a-ed11-11e5-9efc-c9ba24722a18.png">

**Comment by jjeffryes** [comment]
The checkboxes weren't lining up right, so I switched them to use a variation of the radio button classes. They're supposed to be squares, not rectangles.

It's just temporary until I switch both radio buttons and checkboxes to use icons from the ionic set. Once that's done they'll automatically pick up the text color, and we won't have to add a bunch of styles in setTheme to cover checkboxes and radio buttons.

**Comment by jjeffryes** [comment]
this was fixed
