### ISSUE TITLE
ob:// links and handles within conversations should be clickable

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1141]
It would be very nice if users could click the links instead of having to copy and paste them into the address bar.

<img width="240" alt="screenshot 2016-03-18 14 45 44" src="https://cloud.githubusercontent.com/assets/13066886/13890201/39dd17a8-ed18-11e5-9d07-881bef02189a.png">

**Comment by morebrownies** [comment]
Same goes with http:// urls, especially in the discussion tab. The buyer/seller will probably want to include links to images and not being able to click to open them is a minor inconvenience.

**Comment by mariodian** [comment]
I think this should be done on the server side in one place instead of multiple places in the client's app.

**Comment by morebrownies** [comment]
:+1:
