### ISSUE TITLE
We need a better empty state for the Shipping & Returns tab on a listing

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1142]
If the shipping tab is completely empty, can we output a simple message "No details specified" instead of the empty table?

<img width="1075" alt="screenshot 2016-03-18 15 30 04" src="https://cloud.githubusercontent.com/assets/13066886/13891316/62b58dc6-ed1e-11e5-8b82-74f07d7fa3de.png">

**Comment by drwasho** [comment]
Agreed. Basic placeholder text needs to be there, otherwise we should remove the tab altogether (which I don't think we should do).

**Comment by drwasho** [comment]
This looks weird, a placeholder is really needed:

![image](https://cloud.githubusercontent.com/assets/3887694/14094472/f76f5644-f599-11e5-9ab5-1f2c53556e68.png)
