### ISSUE TITLE
Creating new item with UTF-8 character in name says "Data could not be saved"

### ISSUE THREAD

**Issue by jooray** [OpenBazaar/OpenBazaar-Client#1152]
Brief Description: I fill in all the required fields in new item, with the name
containing an UTF-8 enhanced character, I use

"Tajné plány"

and click save changes and I get an error "Data could not be saved" without any other
information.

I am testing OpenBazaar in a Slovak translation, but
I tried in English as well with the same result. 

Operating System (OS and version): Mac OS 10.11.3 (15D21)
OpenBazaar version (shown on `About OpenBazaar` page in menu): Version 1.0.9

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Go to my store, create new item
2. Fill in all the fields marked as required, with name containing an UTF-8 enhanced character like "á"
3. Click Save changes

Observed Behavior:
"Data could not be saved" error without any further explanation.

Expected Behavior:
Item created

Additional info (links, images, etc go here):

**Comment by mariodian** [comment]
I have the same issue. This is what API returns:

`{
    "reason": "", 
    "success": false
}`

**Comment by jjeffryes** [comment]
This is a server issue, the client just passes the data along. I'll open an issue there.

**Comment by drwasho** [comment]
Closed, as this is a server issue.

**Comment by chris-zeng** [comment]
Is this issue still happening? I just checked on my openbazaar and it seems like I can create an item listing with the name "Tajné plány"
