### ISSUE TITLE
Invoice QR code privacy leak

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1158]
The invoice QR code generated for a purchase has quite a bit of information about the purchase. Here is an example purchase for listing `ob://72aceac3d5d0b7aa5d209b003f4e1d6cf6167781/listing/07fa322011ae2ca0fa278cd6944fccdc700c562d`:

> bitcoin:n28zp31uhaCWx4kt9bC1AS7oTzCZYCdCmD?amount=0.12082483&label=Ledger&message=Ledger%20Nano%20Testnet%20Edition%20fdb15a13f6904ce4c63ad7b674dafe12ffb2a7c6

The `message` tag has the full description "Ledger Nano Testnet Edition". This means that the average mainstream user who uses a centralised service (e.g. Coinbase, Circle, Duo Money) will be giving away that information away to regulated companies that will have no choice but snoop on users (and ban/report 'suspicious' purchases).

Does OpenBazaar really want the invoice QR code to leak so much information?

**Comment by hoffmabc** [comment]
That's a good point and probably should be able to disable this. It's also a very useful feature for remembering your purchases. People who are paranoid could probably just copy the stuff over for now, but maybe a checkbox to not include the description would be easy to implement and helpful.

**Comment by SamPatt** [comment]
This is a good point. It's certainly very convenient for a user who controls their own wallet but we don't want to be leaking info to others. @hoffmabc, your thoughts on this?

**Comment by JustinDrake** [comment]
@hoffmabc The real question is opt-in or opt-out?

**Comment by mariodian** [comment]
I think users should always decide on their level of privacy, thus opt-in.

**Comment by drwasho** [comment]
This helps more than it harms users. I think it should be opt-out.

**Comment by JustinDrake** [comment]
> This helps more than it harms users.

@drwasho Why is `help > harm`?

**Comment by drwasho** [comment]
For the reasons that Brian stated.

**Comment by dsmurrell** [comment]
@drwasho @hoffmabc What do you guys think about the seller's server making a suggestion to the buyer's client that this metadata should or should not be encoded in the QR code? One possibility at the moment is to use the NSFW tag to suggest that the metadata shouldn't be encoded, but for extra flexibility this may be a separate option. Then on the buyer's side, there could be an option to 1) not encode metadata, 2) accept seller's suggestions for encoding 3) encode metadata. I realise that these options are not easy to explain to new users, so maybe they are put on the advanced tab for privacy conscious sellers and buyers.

**Comment by JustinDrake** [comment]
+1 In the case of NSFW content the default should probably be opt-in.

**Comment by hoffmabc** [comment]
I think most people will overwhelmingly be purchasing items that they are comfortable with having in their memo fields. If they are purchasing things that would get them booted from a centralized service then I have three suggestions:
1. You shouldn't be using a hosted wallet solution that can scan your purchases 
2. We can provide opt-out checkbox or the like and then it's no longer an issue.
3. You can just copy paste the address and payment amount

I think making the default case less useful is more harmful to the UX as @drwasho stated. I think the intersection of those who are performing sketchy or sensitive purchases and using hosted wallets contains unsophisticated users and I'm not that interested in prioritizing them over the average majority user.

**Comment by drwasho** [comment]
Ok this issue will be about adding an opt-out button to remove the metadata of the item from the QR code @jjeffryes.

**Comment by kristovatlas** [comment]
For what it's worth, I like @JustinDrake's idea of making it opt-in for NSFW content.

**Comment by hoffmabc** [comment]
:+1:
