### ISSUE TITLE
Reviews Tab in Items Should be Reverse Chronological

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#1164]
Self-explanatory.

**Comment by jjeffryes** [comment]
Contracts and ratings don't have any time data recorded in them. That would have to be added on the server before ratings can be sorted using that data.

**Comment by SamPatt** [comment]
@cpacia and @jjeffryes Any updates on this? Would need to be implemented into the new reviews tab at the store level as well.

**Comment by jjeffryes** [comment]
I don't believe we've added the time data to the reviews.
