### ISSUE TITLE
Show Toggle and Warning for Global Listings

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1169]
Something that we've discussed internally is to show listings from nodes that the user is following by default. The user can then select a toggle to show global listings, which will trigger a popup modal to warn them that they are going to see random listings, some of which may be offensive. The user would then have to press 'ok' or 'cancel' to proceed from there.

Some designs from @morebrownies: 

**The Toggle**
![image](https://cloud.githubusercontent.com/assets/3887694/14009941/5ded8d4e-f1dc-11e5-8235-d01d050b8b69.png)

**The Warning**
![image](https://cloud.githubusercontent.com/assets/3887694/14009954/7bd17956-f1dc-11e5-819a-43fb6e7bda38.png)

**Comment by pryds** [comment]
But, but... Isn't this warning valid no matter which countries a user is seeing listings from, global or not? So if I deselect "Global listings", what keeps me from seeing listings from MY country that "may contain adult or illicit content and/or photos [I] may find offensive"?

Or is "Global" not to be interpreted in the geographic sense here?

**Comment by drwasho** [comment]
This is a good point @morebrownies and @jjeffryes... the term 'Global Listings' may be confused as a geographic thing rather than listings from random nodes.

**Comment by jjeffryes** [comment]
"all listings" is a better term.

**Comment by morebrownies** [comment]
Good point. All listings > Off reads a bit strange too. I wouldn't expect to see anything when it's in the off position. hmm...

**Comment by morebrownies** [comment]
What about Market listings? 

Off = You're only seeing listings from stores you follow
On = You're seeing random listings from the market

**Comment by pryds** [comment]
What about turning it upside down and make it "Show only listings from followees: on/off"? -- with possibly a better term than "followee" ;-)
