### ISSUE TITLE
Non-English characters not accepted in the listing title

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1170]
Brief Description:
If you use a non-english character in the listing title (such as ´ that is used oftenly in Spanish, like in "selección") the data can't be saved and it doesn't indicate what's the problem. It just says "Data could not be saved."

Operating System (OS and version): Windows 7 Ultimate
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.9
Hardware: AMD Athlon x64 Dual Core, 4Gb RAM, 500Gb hard drive (would you need more specific info here?)

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Create a new listing
2. Use some non-English character, like: á é í ó ú
3. Try to save the changes

Observed Behavior:
It throws a "Data could not be saved." message

Expected Behavior:
The new listing should be saved as usual.

Additional info (links, images, etc go here):
![001](https://cloud.githubusercontent.com/assets/18052769/14021357/f21dcc4a-f1b9-11e5-9894-96428a4613a0.JPG)
![002](https://cloud.githubusercontent.com/assets/18052769/14021368/f9d3fb30-f1b9-11e5-805a-8933f93d2d0f.JPG)

**Comment by jjeffryes** [comment]
The rejection is happening on the server, I have opened a server issue for this.

**Comment by ghost** [comment]
Oh! Ok, I didn't know that. Thanks!

**Comment by jjeffryes** [comment]
@dropestein no worries. There was no way for you to know where the error was happening. We only closed the issue here and moved it to the server repo so the right developers see it.

**Comment by jjeffryes** [comment]
Thank you for reporting it.
