### ISSUE TITLE
Advanced Tab Settings

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#1171]
- No libbitcoin info for new type of multiple server connection (encrypted)
- Disable Visual Effects helper text messed up

![image](https://cloud.githubusercontent.com/assets/45482/14024789/5c97e400-f1c1-11e5-8ad9-e82920f09239.png)

**Comment by jjeffryes** [comment]
I can't replicate the text alignment issue. Can someone with a Mac confirm whether this is showing up on OSX?

**Comment by mariodian** [comment]
I could replicate it on OSX. I'll fix it, please post a screenshot of what it's suppose to look like.

**Comment by jjeffryes** [comment]
It should be vertically centered.

**Comment by jjeffryes** [comment]
It may be a float issue, making the text smaller, two lines, or removing some text may fix it.

**Comment by mariodian** [comment]
Removing some text will only fix it for English. It should be 2 lines instead. I'll look into it.
