### ISSUE TITLE
In listings, item condition and item type are not translated

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#1178]
Brief Description: When viewing a listing, the item condition and item type (physical, service, etc.) are not translated, even though they _are_ translated when creating a new listing.

Operating System (OS and version): Ubuntu 14.04
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.10

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Observed Behavior:
The texts, e.g. "Physical Good" or "Used - Excellent" are shown in English, even though a non-English language has been chosen for the UI.

Expected Behavior:
The texts are expected to be shown in their translated versions, like they are when you create a new listing.

Additional info (links, images, etc go here):
![openbazaar-conditionetc](https://cloud.githubusercontent.com/assets/4420584/14033720/d61f4966-f21c-11e5-8b63-1b230f2df887.png)

**Comment by mariodian** [comment]
I'll fix it.
