### ISSUE TITLE
'Terms and Conditions' absent when none, but not 'Returns'

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#118]
I actually suggest that if it is 'none', but you still see that T&C and Returns are none, rather than just hide them.

**Comment by jjeffryes** [comment]
Recommended Solution:

In the userPage template, change the logic so that when when Terms and Conditions have no value, the value displayed in the template is "none". Do the same for Returns. 

This logic should be in the template, no changes to the view should be required.
