### ISSUE TITLE
Shipping and Processing Time using plain text

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1180]
Another issue in internationalization:

"Processing Time", "Domestic Shipping Time", and "International Shipping Time" are now written in plain text like "3 Business Days".

It would be better for translation to have two separated select boxes, one for the number, and the other for "day(s)", "week(s)", "month(s)".

**Comment by jjeffryes** [comment]
We're consolidating shipping issues in #1263
