### ISSUE TITLE
Error on edit button on about page (tooltip showing)

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1183]
When mouse is over edit button on about page, a tooltip "#settings/page" appears on the left.
![edit button on about](https://cloud.githubusercontent.com/assets/10789865/14039125/b686d496-f237-11e5-8f92-6870d38e0f82.png)

Operating System: Win 7 64 bits
OpenBazaar version: 1.0.10

**Comment by mariodian** [comment]
I'll fix it.

**Comment by mariodian** [comment]
Fixed, will create a pull request with more views related changes later.
