### ISSUE TITLE
Variables in UI strings concatenated outside of i18n handling software

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#1184]
Some translatable strings seem to be concatenated with variables outside of the i18n handling software. This has the clear disadvantage that the coder, not the translator, decides at which place the variable goes into the string (usually post- or prefixed), which makes translation into some languages clunky.

For instance the string "noTaggedResults" in English is "No listings found in your network tagged with" (and then clearly the actual tags are postfixed), but in Danish this string would translate into "Ingen listninger tagget med [TAGS] blev fundet i dit netværk". Instead a clunky translation that forces the tags to go last in the string had to be used.

From what I can see, the following strings may potentially suffer from this problem, and proper i18n variables need to be used:
- NotificationPaymentSent
- NotificationOrderFor
- NotificationFollow
- NotificationDispute
- NotificationRefund
- NotificationNewOrder
- noTaggedResult
- ShipTo
- MinimumIs
- ShippingTo
- ModeratedBy
- BTCto
- SendBTCtoAddress (contains variable for amount, but not for receiver)
- summaryMsg2
- summaryMsg3
- NotificationRatingRecieved

Note that some of the above strings may be used in a way that prevents the use of i18n variables, though, e.g. the variable may not be a part of the sentence as such (maybe it's a user input field, or maybe it's displayed as part of a table layout "away" from the rest of the string). These cases are of course fine to leave as is.

**Comment by rmisio** [comment]
I'm working on this one.

**Comment by rmisio** [comment]
This one is fixed. Some of the listed strings are no longer being used, so they were removed from the translation file.

If we missed any or there are any new ones that need this treatment, please let us know.
