### ISSUE TITLE
DKK has disappeared as a local currency

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#1185]
Brief Description: Danish krone, DKK, seems to have disappeared as an option for local currency pinning, even though it was present in earlier versions.

Operating System (OS and version): Ubuntu 14.04 LTS
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.10

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Open Settings
2. Open the dropdown under Local currency

Observed Behavior:
DKK (Danish krone) is not to be found.

Expected Behavior:
I expected DKK to be found among currencies, as it was in earlier versions.

**Comment by jjeffryes** [comment]
The available local currencies are based on what the 3rd party APIs we use for the fiat to BTC exchange rate provide. 

We recently consolidated that code, so we check bitcoinaverages, then stop if it returns valid results. We only check other APIs if bitcoinaverages fails.

Previously we checked 4 APIs, and allowed any currency that returned from at least one of them. Unfortunately, this could take a long time, and resulted in some users having long delays. 

One of the results is the list of currencies returned by bitcoinaverages is not as comprehensive as compiling all the currencies from multiple APIs. But we feel that's an acceptable exchange for significantly speeding up the experience.

**Comment by pryds** [comment]
That's too bad. Would have been a nice feature.

Any chance for a user to be able to select their own exchange rate source, or maybe just switch between the four you mentioned?

**Comment by pryds** [comment]
@jjeffryes It's a bit weird, though, because Bitcoinaverage _does_ seem to include DKK
https://bitcoinaverage.com/#DKK
https://api.bitcoinaverage.com/ticker/global/DKK/

**Comment by jjeffryes** [comment]
Do they? I'll have to look more closely, maybe we're dropping that currency out for some reason.

**Comment by jjeffryes** [comment]
I checked, https://api.bitcoinaverage.com/all does not return DKK.

**Comment by Nerzahd** [comment]
@jjeffryes CHF is also disappeared
can you use https://api.bitcoinaverage.com/ticker/global/all instead?

**Comment by jjeffryes** [comment]
Unfortunately, /global/all doesn't return the average exchange rate, which is what we want.

If this continues to be a significant problem, we'll look into creating our own service for exchange rates.

**Comment by jjeffryes** [comment]
I'll look into this further.

**Comment by jjeffryes** [comment]
We've updated the endpoint on both the server and the client.
