### ISSUE TITLE
support for more flexible, global address systems

### ISSUE THREAD

**Issue by bumi** [OpenBazaar/OpenBazaar-Client#1187]
_I am not sure if this topic was already raised but I have not found any related issues. If so please move or close this issue. thanks._

---

Currently it seems OB has a very US centric concept of an address with [street, city, state, country](http://share-michaelbumann-com.s3-website-eu-west-1.amazonaws.com/screenshots/ob-address.jpg).
This system does not work in most countries. 
Already in many European countries for example the usage of the _state_ in the address is not common. Some places use building names, apt. numbers, don't have streets, etc. Here is a [wikipedia article about addresses](https://en.wikipedia.org/wiki/Address_%28geography%29) (which is still missing most of the countries.)

Many places need more descriptive addresses, like for example: _second door next to the supermarket across red-house at junction_ 
and many areas of the world do not have a formal address system where descriptions and phone numbers are even more important. 

Respecting the nature of a **global** decentralized network I think this should be adjusted and be more flexible. My suggestion would be to simply use a plain text field for the address or let the user choose to enter a US like address or a simple text field. 

This also slightly relates to calculating shipping prices, but again shows that once you are leaving the typical US/EU system it gets hard to formalize and apply rules in code for the whole world.

**further links:**
There are several projects working on the address system problem (including ones from the US)
- [eddress.co](http://www.eddress.co/)
- [3words.com](http://what3words.com/)
- [zi.pr](http://zip.pr/)
- [OkHi.com](http://okhi.com/)

**Comment by mariodian** [comment]
Using just a single plain text field leaves us with no easy option to create filtering by country/city in the future.

I think omitting fields that are not applicable to your specific use case is a way to go. In case it's confusing I think we could rename the "state" field to an option "state/region" field. I'm pretty sure every country (or at least the majority) has a region that a city belongs to.

**Comment by bumi** [comment]
thanks for your reply. filtering is a good point, but imho that should be attributes on the shop/product and not be related to the shipping information.

The state field was an example, which maybe could be made not mandatory. But it is not about the state field. The representation of a location is just very different from country to country especially considering non USA/EU countries. As a global market place I think we should respect those different systems and not force people to adopt foreign ones. 
A lot of things about local UX can be learned if we look at existing lcoal e-commerce websites. (for example here the [address form from jumia.co.ke](http://share-michaelbumann-com.s3-website-eu-west-1.amazonaws.com/screenshots/jumia.co.ke-address.jpg) )

additionally, without knowing the code, I'd assume having less fields and restrictions should actually make also the code easier.

**Comment by drwasho** [comment]
Also discussed in #1199

**Comment by jjeffryes** [comment]
We're consolidating shipping issues in #1263
