### ISSUE TITLE
[Idea] Add `test` flag to contracts

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#119]
A lot of users will want to kick the tires on OpenBazaar when the start it up. What if we allowed users to create listings with a flag that said this was a test contract?

Additional thoughts:
- In these contracts, the `buy` button could be disabled.
- In the settings, there could be an option to display `test` listings or not

**Comment by gubatron** [comment]
sort of like a `--dry-run` flag on some software?

**Comment by drwasho** [comment]
Sorry @gubatron the issue was launched prematurely (I swear that never happens).

**Comment by drwasho** [comment]
Kinda like this (I guess more like a ribbon):

![image](https://cloud.githubusercontent.com/assets/3887694/10836300/a1dd17de-7ef7-11e5-95ef-e87963ab275e.png)

**Comment by drwasho** [comment]
The big reason for this is that we're just going to see a lot of supposedly _real_ with titles like 'Shoes [TEST]' all over the network. We can get ahead of this and just mark these listings as test listings and filter them out if the user wants.

**Comment by gubatron** [comment]
makes sense +1.

I'd the visual rep a bit more obvious, took me a while to see the band there.

Something a bit less exagerated than this perhaps?
![test](https://cloud.githubusercontent.com/assets/163977/10836464/42a1d1a6-7e84-11e5-978f-eec6a6b0df4b.jpg)

I'm sure the design oriented contributors will have a good way to do it.

**Comment by drwasho** [comment]
Haha, yeah. @morebrownies can take this on.

**Comment by cpacia** [comment]
This is what the test network is for. All contracts on the testnet are test. Main net is for real contracts.
