### ISSUE TITLE
All digital goods and services are shown to originate from buyer's country, not seller's

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#1193]
Brief Description: No matter which digital good or service I view, it is shown to originate from my own country. Living in a very small country, I find this quite odd. Even one of Sam's listings is from my country ;-)

Operating System (OS and version): Ubuntu 14.04 LTS
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.10

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Find a listing that is either a service or a digital good which you know is originating from another country than your own. Alternatively, if you're not based in Denmark, look at one of the auctions in the screenshots below and see if shows to be originating from your country instead of from Denmark like in the screenshot.

Observed Behavior:
Listing appears to originate from buyer's country.

Expected Behavior:
Listing appears to originate from seller's country. Maybe not even relevant for digital goods?

Additional info (links, images, etc go here):
![openbazaar-digital1](https://cloud.githubusercontent.com/assets/4420584/14059086/13f2d2ec-f337-11e5-9411-ec8c0f0b3804.png)

![openbazaar-digital2](https://cloud.githubusercontent.com/assets/4420584/14059087/1733d6ea-f337-11e5-853e-2fc08e7af1f2.png)

![openbazaar-service1](https://cloud.githubusercontent.com/assets/4420584/14059089/1b017282-f337-11e5-93f5-b72af2f1a4ab.png)

![openbazaar-service2](https://cloud.githubusercontent.com/assets/4420584/14059090/21c6ad30-f337-11e5-9f7f-203136aa3396.png)

**Comment by ghost** [comment]
I got the same error on my client.

I believe that informing country of origin for these types of items (digital/service) should be optional.

**Comment by drwasho** [comment]
Thoughts @jjeffryes and @morebrownies ?

I think that locations should still be mandatory for services... but perhaps optional for digital items?

**Comment by morebrownies** [comment]
It's definitely nice to know where the creator is from.

**Comment by ghost** [comment]
Location is important only for physical items that need delivery (should be mandatory) or services that are done locally (should be optional). There are many services that location doesn't really matter to be done.

Making unnecessary information (country) mandatory for digital items and services is going to be a source for potential discrimination built into the system. Some people prefer not to reveal their location, skin color, or gender, because it could put themselves at a commercial disadvantage.

**Comment by jjeffryes** [comment]
The country of origin is in the contract, so it's available regardless of whether it's on the screen or not. Hiding it in the interface won't protect the privacy of anyone that doesn't want that data to be public, and it won't matter to anyone that doesn't mind.

If it's not consistently showing the right country of origin, that's a bug, and needs to be fixed.

**Comment by ghost** [comment]
Well, if display of "country of origin" is going to be mandatory on all listings, there should also be a "country of origin" item on user's about page. The only way I can see where a user is from is by visiting one of his listings.
