### ISSUE TITLE
Not translated strings on order screens

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1195]
Untranslated texts are marked in red below:

![untranslated1](https://cloud.githubusercontent.com/assets/10789865/14061871/eaa287be-f36a-11e5-9b45-6518642f999d.png)
![untranslated2](https://cloud.githubusercontent.com/assets/10789865/14061872/ed8fb83e-f36a-11e5-90aa-4bcd5a724b39.png)
![untranslated3](https://cloud.githubusercontent.com/assets/10789865/14061875/f1120af2-f36a-11e5-8f9a-9d16037aa244.png)

**Comment by drwasho** [comment]
They need to be translated in the JSON language file. You can make the updates via Transifex OpenBazaar page: https://www.transifex.com/ob1/openbazaar/

**Comment by ghost** [comment]
@drwasho These texts are coded in source code and don't have language strings. They are not included in JSON language file. This issue should be reopened.

**Comment by jjeffryes** [comment]
The word "Order" is using the Order phrase, it appears to have been removed from the language file. I'll add it back in.

**Comment by jjeffryes** [comment]
Some of the others are set in models, I'll fix those too.
