### ISSUE TITLE
Editing contracts - changes only visible after refresh

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#120]
Editing works amazingly well, however changes to the listing on the Store page aren't visible until refresh.

**Comment by drwasho** [comment]
If you click the 'unedited' contract, it returns this (because it's not there of course):

![image](https://cloud.githubusercontent.com/assets/3887694/10836539/5fd001f0-7efa-11e5-90ef-2cd208083bb7.png)

**Comment by jjeffryes** [comment]
I can't reproduce this, I think it was fixed a while ago.
