### ISSUE TITLE
Can't Reset Default Server Configuration

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1200]
Brief Description: My local server is not starting ([bug](https://github.com/OpenBazaar/OpenBazaar-Server/issues/251)), I tried to run the server on a remote machine but [failed](https://github.com/OpenBazaar/OpenBazaar-Server/issues/305). Now I installed latest beta version to check maybe the problem is fixed. I want to reset default server settings but [I can't](https://vid.me/8RFh), it asks me username and password.

Operating System (OS and version): Ubuntu 14.04 x64
OpenBazaar version: 1.0.10 Beta 5
Hardware: Notebook

Reproducible: Always

Steps to reproduce:
1. Start OpenBazaar (for the first time)
2. Change Server Configuration
3. Reset Server Configuration and try to connect

Observed Behavior: It asks me username/password

Expected Behavior: Should try to connect to local server without username/password

**Comment by jjeffryes** [comment]
The username and password are generated by the server. The client gets them when it connects to the server during GUID generation, and saves them in localStorage. 

When you restore your default settings, the client will reset to the local server, and if it has a valid username and password saved in local storage, it will use that.

If you are using a new install that has never connected to a local server successfully, it won't have a saved username and password. Is that what happened in this case?

If it is, you will need to get the current username and password out of the database, or set it using the config file.

**Comment by ghost** [comment]
> Is that what happened in this case?

Yes.

> you will need to get the current username and password out of the database, or set it using the config file.

Thank you
