### ISSUE TITLE
Prevent subsequent Follow messages

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#1204]
Follow spam will irritate and annoy users. Please only fire a notification when the first follow message comes in.

**Comment by morebrownies** [comment]
+1

**Comment by drwasho** [comment]
Looks like this will be addressed on the server side here: OpenBazaar/OpenBazaar-Server#319 

Follow/unfollowing a node will be included in the ban score. Not sure if you want to add something client-side @jjeffryes ?
