### ISSUE TITLE
Loading screen when navigating

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1206]
The loading screen currently used is annoying: it occupies all the screen, it appears every time a listing link is clicked (or when user hits back/forward button) and it takes some seconds to disappear.
I believe the user experience should simulate visiting a store website on a browser, therefore a "loading..." text/animation on a corner or an animated progress bar at header/bottom would be a better design.

![loading](https://cloud.githubusercontent.com/assets/10789865/14096435/37efcbc8-f53f-11e5-9bef-c0b9f527fb80.png)

**Comment by morebrownies** [comment]
Until we have IPFS in place, I'd like to keep the loading screen as is. The reason being is there are a lot of failed connections and stores offline and we need to keep the user informed on what is happening. On the web, pages rarely fail to load so a simpler indicator is sufficient in that use case.
