### ISSUE TITLE
Image gallery error

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1207]
I got these errors when clicking on the images of the gallery of this specific listing (couldn't reproduce it on other listings): ob://@serp/listing/f5172b1a2554d41a5d5961f320d034b48dc71966

Operating System: Win 7 64 bits
OpenBazaar version:  1.0.10

![image error](https://cloud.githubusercontent.com/assets/10789865/14097529/77c3877c-f548-11e5-80c3-c688bc094c32.png)
![image error2](https://cloud.githubusercontent.com/assets/10789865/14097532/7b0ac3f0-f548-11e5-8c10-f3cf3d30e223.png)

**Comment by drwasho** [comment]
I've seen this bug before, but I can see the images just fine via my node. I'm guessing this may have something to do with a connection timeout @cpacia @jjeffryes?

**Comment by jjeffryes** [comment]
It looks like the base64 data for the image got corrupted. I can see that image fine from my computer, it's possible it was only partially downloaded, which gave the results above.

**Comment by drwasho** [comment]
Would the solution be to clear the cache and try and download it from scratch? Wider question should be whether we should have a 'clear cache' button in the Advanced settings?

**Comment by ghost** [comment]
To reproduce the bug you have to click the images multiple times (at least 3 times) in a short period of time.

**Comment by nimchak** [comment]
I have experienced this as well

**Comment by SamPatt** [comment]
I'm going to close based on being unable to reproduce. @rhcastilhos if this is still a problem please reopen and give us more information.

**Comment by ghost** [comment]
@SamPatt It is still present in v1.1.5 win7 64 bits

Steps to easily reproduce it:
1. Open listing ob://@legolas/listing/0ecf22ef41484584e7d05498b72e813ab3e9f6d7
2. Hold right arrow key on keyboard to fast switch between photos
