### ISSUE TITLE
Minimum price, domestic & international fees are too high [when BTC is set as the currency]

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#121]
At the moment they're set at 0.01 BTC. If we ever see a significant price run up to $1,000, that means items less than $10 can't be sold. I suggest we lower the minimum to 0.0001 BTC, which is pretty close to the default minimum Bitcoin transaction fee.

**Comment by gubatron** [comment]
how about the default fee is based on a US dollar amount and automatically converted to BTC...?
#VolatilityLife

**Comment by drwasho** [comment]
Well it would be if you set your client to a particularly currency. If you choose to only transact in Bitcoin, then you're restricted in the way I described.

**Comment by drwasho** [comment]
That minimum definitely needs to be reduced to 0.0001 BTC @jjeffryes

**Comment by morebrownies** [comment]
We're approaching this problem in the wrong way. Contracts that sit on the network for years can still eventually fall under the minimum miner fee. There's no protection on existing items.

Instead, what we need to do is display a warning during checkout or disable checkout all together on items that are under the minimum miner fee. That way, not only new items are protected against items under the minimum fee, but existing items are as well.

I'd suggest removing the minimums during contract creation and hiding the buy now button + display a warning on the contract detail screen of items that are priced too low.

**Comment by SamPatt** [comment]
It would be good to have @cpacia's opinion since this will impact how a miner fee is paid out from the multisig. I expect we'll need to ensure there's at least a minimum amount in multisig or else payment won't release reliably.

> disable checkout all together on items that are under the minimum miner fee. 

That's probably a good idea.

**Comment by drwasho** [comment]
+1

**Comment by drwasho** [comment]
This issue should also address if and how we communicate the minimum bitcoin price (#116). Note that this is only relevant when items are priced in bitcoin.

**Comment by jjeffryes** [comment]
Partially dealt with in #212 

PR 212 does not address the issue of warning about prices being under the minimum miner fee.

**Comment by drwasho** [comment]
I think this is good for now.
