### ISSUE TITLE
Problems with shipping price on Shipping & Returns tab

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1215]
When using only bitcoin, bitcoin price should be displayed with currency unit and using less decimal digits for easy reading:
- 0.01354 BTC

When using local currency, converted price should be displayed after bitcoin price:
- 0.01354 BTC ($5.63)

![shipping](https://cloud.githubusercontent.com/assets/10789865/14129214/863e95b0-f5fe-11e5-95ec-f5096e1e1e53.png)

**Comment by jjeffryes** [comment]
Fixed in commit a85c258
