### ISSUE TITLE
Text and background with same color

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1218]
Text color should not be allowed to be of the same color of the background.

An alternative would be an option "Disable other users pages color schemes", like "Disable Visual Effects" on settings.

![colors](https://cloud.githubusercontent.com/assets/10789865/14130240/06f750da-f608-11e5-8a67-3f7410ec698d.png)

**Comment by morebrownies** [comment]
Just like on the web, people simply wont buy on pages with bad aesthetics. On the web you could also build a page with a black background and black text and there aren't any filters built into the web browser to prevent it from happening. We could spend a lot of time trying to prevent this, but any legit store on OpenBazaar will want to ensure that their text is legible if they expect to sell anything.
