### ISSUE TITLE
External images <img> in the client: fixes + tweaks

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1225]
# Part 1

There are some wrapping problems when you use `<img>` to add a wide image in the following locations:

**Listing - Description**
![image](https://cloud.githubusercontent.com/assets/3887694/14193838/b5fa05fc-f7eb-11e5-8fd0-cd61e061cddb.png)

**Chat**
![image](https://cloud.githubusercontent.com/assets/3887694/14193865/fb51338c-f7eb-11e5-8ee3-4cc562e4455e.png)

![image](https://cloud.githubusercontent.com/assets/3887694/14193868/0d3da436-f7ec-11e5-856e-164e126e1b0f.png)

**About**
![image](https://cloud.githubusercontent.com/assets/3887694/14193885/44c57640-f7ec-11e5-840e-480321ede8a8.png)
# Part 2
1. Create a listing with an `<img>` in the description (e.g. `<img src="https://images.unsplash.com/photo-1444005233317-7fb24f0da789">`)
2. Save the listing
3. Edit the listing and you'll see the image itself rather than the original link.
4. If you save the edited listing, the image is removed from the description.

**Comment by jjeffryes** [comment]
It looks like the only place the image size is an issue is in the item description? Or do you think there are problems in the other screenshots you posted?

**Comment by drwasho** [comment]
In the About page, the image stays at its original dimensions and is cut-off, similar to the Item Description. They really need to resize to fit the dimension of the frame, like it does in the Chat messages (not the conversation bar, which has its own issues).

**Comment by jjeffryes** [comment]
Also, what's the issue? If the images are too large, they should look exactly like they do in the screenshots.

Editing the image is going to be a problem. The Medium Editor renders the HTML in the description field. That means the images will always be images, not code. 

The easy answer is to get rid of it, but then people will have to put in bold tags and things themselves.

The harder answer is do some custom stuff to un-render image tags only when they're in the editor. I'm not sure how much work that would be.

**Comment by jjeffryes** [comment]
I could maybe put in some code that only resizes images that are too big.

**Comment by jjeffryes** [comment]
I think my opinion here is if you use an image that is too big, it's up to you to fix it.

That can be either adding the right size in the HTML you're posting, or using a smaller image.

Painting the HTML to the DOM, then checking each element to see if it's too big, and then adding a 100% width to those elements is possible, but non-trivial to do. And could introduce weird bugs.

**Comment by jjeffryes** [comment]
BTW, that image in chat is only visible on your side, it gets stripped on the recipient's side, and when you reload the page.

**Comment by drwasho** [comment]
Sounds good. I'll mark this as a future thing to deal with then.

**Comment by morebrownies** [comment]
@jjeffryes we could probably do the following to handle auto resizing of the images within about:

```
.userPageAboutSection img {
    max-width: 100%;
}
```

**Comment by jjeffryes** [comment]
Currently this is on hold because image tags were producing invalid JSON on the server, so they've been removed on the client.

**Comment by jjeffryes** [comment]
This was done, including enabling image tags in chat.
