### ISSUE TITLE
btc_price request fail / Local Currency list NOT populating, only BTC available

### ISSUE THREAD

**Issue by M45t3rJC** [OpenBazaar/OpenBazaar-Client#1234]
Brief Description: I installed 1.0.10 from the installer and now BTC is the only currency that can be set.
I can run OB1.0.9 and OB1.0.10 side by side and 1.0.9 is still populating local currencies...

Operating System (OS and version): OSX 10.10.5
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.10
Hardware: MacBook Pro 
2.3 GHz i7
4GB DDR3

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Yes I've reinstalled 1.0.9 and 1.0.10 several times and still get same error pop-up

Steps to reproduce:
1. run dmg
2. open OB
3. error pops up before My Page comes up

Observed Behavior:
In general tab in settings there is no other options besides BTC for currency 

Expected Behavior:
a drop down of other available local currencies

Additional info (links, images, etc go here):
I recorded the reboot

GET http://localhost:18469/api/v1/btc_price 404 (Not Found)send @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8630jQuery.extend.ajax @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8166getBTCPrices @ /Applications/OpenBazaar.app/Contents/Resources/app/js/utils/getBitcoinPrice.js:26module.exports @ /Applications/OpenBazaar.app/Contents/Resources/app/js/utils/getBitcoinPrice.js:49setCurrentBitCoin @ /Applications/OpenBazaar.app/Contents/Resources/app/js/main.js:249user.fetch.success @ /Applications/OpenBazaar.app/Contents/Resources/app/js/main.js:283options.success @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:594fire @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3099self.fireWith @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3211done @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8264(anonymous function) @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8605
/Applications/OpenBazaar.app/Contents/Resources/app/js/utils/getBitcoinPrice.js:105 Call to btc_price request failed: 
/Applications/OpenBazaar.app/Contents/Resources/app/js/utils/getBitcoinPrice.js:106 Object {readyState: 4, responseText: "↵<html>↵  <head><title>404 - No Such Resource</tit…uck finding that resource.</p>↵  </body>↵</html>↵", status: 404, statusText: "Not Found"}
/Applications/OpenBazaar.app/Contents/Resources/app/js/utils/getBitcoinPrice.js:107 error
/Applications/OpenBazaar.app/Contents/Resources/app/js/utils/getBitcoinPrice.js:108 Not Found
/Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:109 GET http://localhost:18469/api/v1/get_image?hash=&guid=23cc2d3191b0d82e2451265214694987ba383f12 404 (Not Found)module.exports.baseVw.extend.addNotificationsToDom @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:109collection.forEach @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:148_.each._.forEach @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/underscore/underscore.js:153(anonymous function) @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:87loadTemplate @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:146module.exports @ /Applications/OpenBazaar.app/Contents/Resources/app/js/utils/loadTemplate.js:21module.exports.baseVw.extend.render @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:131triggerEvents @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:370triggerApi @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:356eventsApi @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:155Events.trigger @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:346_.extend.reset @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:935options.success @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:1026fire @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3099self.fireWith @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3211done @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8264(anonymous function) @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8605
/Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:109 GET http://localhost:18469/api/v1/get_image?hash=&guid=4404a7e2e3e35b1a084d8aadb7cd9306aa8eb664 404 (Not Found)module.exports.baseVw.extend.addNotificationsToDom @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:109collection.forEach @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:148_.each._.forEach @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/underscore/underscore.js:153(anonymous function) @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:87loadTemplate @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:146module.exports @ /Applications/OpenBazaar.app/Contents/Resources/app/js/utils/loadTemplate.js:21module.exports.baseVw.extend.render @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:131triggerEvents @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:370triggerApi @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:356eventsApi @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:155Events.trigger @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:346_.extend.reset @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:935options.success @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:1026fire @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3099self.fireWith @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3211done @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8264(anonymous function) @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8605
/Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:5221 GET http://localhost:18469/api/v1/get_image?hash=dfd6f6ab1c9b9b9707f56a816bac028956aade08&guid=a816adab7f8b4e567767ceb558a99869651da80e 404 (Not Found)(anonymous function) @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:5221jQuery.fn.extend.domManip @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:5414jQuery.fn.extend.append @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:5218(anonymous function) @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:5333jQuery.access @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3491jQuery.fn.extend.html @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:5300listenTo @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/chatVw.js:66triggerEvents @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:370triggerApi @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:356eventsApi @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:155Events.trigger @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:346_.extend.reset @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:935options.success @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:1026fire @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3099self.fireWith @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3211done @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8264(anonymous function) @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8605
/Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:114 GET http://localhost:18469/api/v1/get_image?hash=9bd215566884b186ffc96a85765d3549304c3257&guid=ad2e3f8069e819d5362a810742a4243c599110f9 404 (Not Found)module.exports.baseVw.extend.addNotificationsToDom @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:114collection.forEach @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:148_.each._.forEach @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/underscore/underscore.js:153(anonymous function) @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:87loadTemplate @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:146module.exports @ /Applications/OpenBazaar.app/Contents/Resources/app/js/utils/loadTemplate.js:21module.exports.baseVw.extend.render @ /Applications/OpenBazaar.app/Contents/Resources/app/js/views/notificationsVw.js:131triggerEvents @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:370triggerApi @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:356eventsApi @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:155Events.trigger @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:346_.extend.reset @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:935options.success @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/backbone/backbone.js:1026fire @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3099self.fireWith @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3211done @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8264(anonymous function) @ /Applications/OpenBazaar.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8605
localhost:18469/api/v1/get_image?hash=6b853864ba463f0907579c8891d57165fb981e2c:1 GET http://localhost:18469/api/v1/get_image?hash=6b853864ba463f0907579c8891d57165fb981e2c net::ERR_CACHE_READ_FAILURE
/Applications/OpenBazaar.app/Contents/Resources/app/js/views/settingsVw.js:184 Object {code: 0, message: "Image failed to load."}
/Applications/OpenBazaar.app/Contents/Resources/app/js/views/settingsVw.js:185 undefined
/Applications/OpenBazaar.app/Contents/Resources/app/js/views/settingsVw.js:186 undefined

**Comment by M45t3rJC** [comment]
I updated to 1.1.0 and still having the same issue...
Manually deleted OB from Application folder re-installed, I also restarted computer after deleting and before re-installing as well...

**Comment by jjeffryes** [comment]
This issue is being tracked in the server repo, please add any updates there. https://github.com/OpenBazaar/OpenBazaar-Server/issues/328
