### ISSUE TITLE
freezing on start

### ISSUE THREAD

**Issue by shalnoff** [OpenBazaar/OpenBazaar-Client#1235]
Brief Description: 
just can't start installed application

Operating System (OS and version): 
Release Linux Mint 17.3 Rosa 64-bit
Kernel Linux 3.19.0
MATE 1.1

OpenBazaar version (shown on `About OpenBazaar` page in menu): 
openbazaar_1.0.10_amd64

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always 

Steps to reproduce:
1. download package
2. install 
3. run 

Observed Behavior:
the empty frame window appearing (contains part of the screen, it is happens somtimes when Compiz  activated, But I was try with Marco with turned off all composing as well. same result)

In terminal "Starting OpenBazaar Server" and freeze after that (waiting for ~15 minutes)

Expected Behavior:
starting application

**Comment by jjeffryes** [comment]
This appears to be an environment-specific issue. We haven't been able to reproduce it. 

If you're still seeing this occur, join the installation-issues channel on our Slack, and we'll troubleshoot it there. 

https://openbazaar-slackin-drwasho.herokuapp.com/
