### ISSUE TITLE
Post-purchase link issue

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1236]
The OpenBazaar helpdesk got the following report which I'm proxying here:

> Issue with links not working after a purchase
> 
> First purchase link: `http://%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20open%20file/`
> 
> Second purchase link: `%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20open%20file/`

**Comment by jjeffryes** [comment]
This was solved in #1252
