### ISSUE TITLE
Message offline vendor

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1239]
It should be possible to message offline vendors. Here is a discussion from the OpenBazaar helpdesk:

> (user) I was wondering why sometimes it says that the page is unavailable, i ordered from a vendor and i cant figure out how to message him cuz the page is not available
> 
> (Helpdesk) Aha. If your computer cannot contact the vendor (e.g. the vendor goes offline) then it will say the page is unavailable. OpenBazaar does not yet have guaranteed vendor uptime like eBay or Amazon have.
> 
> (user) oh i see so there is no way to message the vendor?
> 
> (Helpdesk) You should be able to send a message to offline vendors, which they will receive when they get back online. (The message is stored in the OpenBazaar network while the vendor is offline.)
> 
> (user) how do you do that? the message button is on the vendor page no?
> 
> (Helpdesk) If you've already messaged that vendor you should be able to send a message from the right "Messages" column. If you haven't, I don't know! :) I will submit a bug report to the developers.

**Comment by BugsBunE** [comment]
this is where https://bitmessage.org/wiki/Main_Page fits, maybe adding this next to the PGP Key field on the about page as a default

**Comment by BugsBunE** [comment]
![openbazaar_2016-04-06_12-47-05](https://cloud.githubusercontent.com/assets/18311119/14325389/1d47c0a0-fbf7-11e5-9fd0-545900b0e308.png)

something like this

**Comment by morebrownies** [comment]
A IPFS integration should fix this issue in the future. Adding the BitMessage ID to the about page isn't user friendly enough imo.

**Comment by jjeffryes** [comment]
We don't have any plans to make nodes visible when they are offline (which isn't possible with the way the network currently works) in v1.
