### ISSUE TITLE
Cannot enter @ symbol in text fields

### ISSUE THREAD

**Issue by Grix** [OpenBazaar/OpenBazaar-Client#1241]
Brief Description: 

When I try to enter the symbol @ into any text field, it takes me to the "Sales" page. It appears there is a keyboard shortcut tied to the same combination of keys as is used to write @, which is AltGr+2 on my keyboard layout (norwegian qwerty)

Operating System (OS and version): Windows 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.0

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Have nordic keyboard layout
2. Press AltGr+2

Observed Behavior:

Pressing AltGr+2 takes me to the Sales page.

Expected Behavior:

Write symbol @

Additional info (links, images, etc go here):

**Comment by ElucGeek** [comment]
Issue confirmed, same issue with Swiss keyboard.

**Comment by sondreb** [comment]
Same issue in Scandinavia.
