### ISSUE TITLE
Impossible to come back to a form after clicking a link

### ISSUE THREAD

**Issue by ElucGeek** [OpenBazaar/OpenBazaar-Client#1242]
Brief Description: Clicking links while filling a form (store creation form, listing creation...) will take you to another page with not possiblity to resume the previous form, you loose all your work.

Operating System (OS and version): Windows 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.0

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Create listing
2. Start filling form
3. Click "change currency" link
4. Try to come back, no way.

Observed Behavior:
You loose your on going work.

Expected Behavior:
Possibility to resume the form without starting again from zero.

**Comment by jjeffryes** [comment]
This is normal behavior. We'll look into saving in-progress data for a future iteration.
