### ISSUE TITLE
Special characters in description not supported

### ISSUE THREAD

**Issue by ElucGeek** [OpenBazaar/OpenBazaar-Client#1245]
Brief Description: Special characters in description not supported

Operating System (OS and version): Windows 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.0

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Use special character in description
2. Save change - error "Data could not be saved"

Observed Behavior:
Impossible to use special character in description, can be problematic for some languages, at least it will look very unprofessional.

Expected Behavior:
Special characters supported in title

**Comment by jjeffryes** [comment]
I think you meant title, not description. Special characters appear to be working normally in the description.

This is being tracked as a server bug. https://github.com/OpenBazaar/OpenBazaar-Server/issues/307
