### ISSUE TITLE
Can't create listing: "data could not be saved"

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1249]
Proxying from the @helpdesk:

> "data could not be saved"
> 
> I can't save a listing

**Comment by MorgUK** [comment]
I'm getting the same issue, field all filled in except the the odd optional one. Can't save at all.

**Comment by drwasho** [comment]
Can you post some more information so we can try and replicate the problem?

**Comment by MorgUK** [comment]
Not sure what I can add. I created the account, set up my page, set up everything. Then went to create a listing, added info to all sections except optionals and added pictures. Went to save and got "data could not be saved".

**Comment by JustinDrake** [comment]
We've got about 5 people on the @helpdesk with this issue.

**Comment by jjeffryes** [comment]
This is being tracked as a server issue. https://github.com/OpenBazaar/OpenBazaar-Server/issues/329

**Comment by MorgUK** [comment]
I removed hyphens/dashes from the title and it saved! Please look into this. Also it didnt work with a "®" in the title. So it looks like it doesn't like some formatting. Surely a "-" should be allowed though.

**Comment by SamPatt** [comment]
This is a server issue and there are two open issues to address this, so I'm closing on the client side.
