### ISSUE TITLE
Reloading should re-render the current view, not everything.

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#125]
I find it strange that reloading makes the the header reload too. If it could reload everything underneath the header, it should better match the expectations of a refresh action.

**Comment by jjeffryes** [comment]
The reload button is a "stop the application, and restart it" button.

What you're describing is a reload view button, which is something different. 

If we want that functionality, we should have 2 different buttons.

**Comment by morebrownies** [comment]
Agreed. 

The stop and restart button should be in settings or the user navigation and the reload view should be in the header. Now that I think about it, is there even a need for a reload view button?

**Comment by jjeffryes** [comment]
A reload view button is the same as navigating away from a view and back again.

I could see the use of it if you think someone may have added or removed items if you've had their user page open for a long time. Or just for people that want to mash the button a bunch to make sure what they're looking at is up to date.

**Comment by morebrownies** [comment]
Good point. We'll need both then.

**Comment by jjeffryes** [comment]
Recommended Solution: 
1. add a text link for "Restart Application" in the nav dropdown menu on the right side. Clicking that link should fire the ravRefreshClick function.
2. clicking the .js-navRefresh should instead trigger a new function with Backbone.history.loadUrl();

**Comment by morebrownies** [comment]
Perfect!

**Comment by JustinDrake** [comment]
What's the point of "Restart Application"?

**Comment by jjeffryes** [comment]
It restarts the application.

**Comment by JustinDrake** [comment]
@jjeffryes: Lol. Why would the user be interested in restarting the application? Is that a feature other applications have? (Just checked my top apps, Spotify, Chrome, Xcode, Sublime, Skype, etc. None have a "Restart Application" button.)

**Comment by jjeffryes** [comment]
A better phrase would be "reload the page". It is equivalent to the Chrome refresh button. 

There may be situations where you want to do that.

**Comment by mariodian** [comment]
I use a "Restart application" button every time I change the code and/or add new translations and I want to check if it works alright. However I'm not sure if an ordinary user needs it. Perhaps if something gets "stuck".

**Comment by hoffmabc** [comment]
Is this completed?

**Comment by jjeffryes** [comment]
No work has been done on this yet.
