### ISSUE TITLE
Cannot save data with accents

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1251]
I think this is a non-ASCII problem. Proxying from @helpdesk:

> Error message was just saying that it could not save data,, I figure it out that the accents could be the problem

**Comment by jjeffryes** [comment]
This is probably the same as the issue we're having with UTF-8 characters.

**Comment by jjeffryes** [comment]
This is being tracked as a server bug. https://github.com/OpenBazaar/OpenBazaar-Server/issues/307
