### ISSUE TITLE
About one in three people ask "How do I find stuff?"

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1253]
We're getting hundreds of message on the @helpdesk. Many many people who ask for help want to know "How do I find stuff?" and we point them to the Discover button. Maybe the Discover button can be highlighted when the app launches for the first time?

**Comment by morebrownies** [comment]
We do have that. Is it not working Josh?

**Comment by jjeffryes** [comment]
Apparently not.

**Comment by jjeffryes** [comment]
This is fixed in #1252 

A timing issue was re-hiding it right after it was shown.
