### ISSUE TITLE
Shipping options not flexible enough

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1255]
Proxying from @helpdesk:

> So it's pretty good. I'm trying to put in more than one region though. I want to ship it worldwide, but have two different prices for shipping, one domestic, and one international, however, when I say ships worlwide, it won't add another country. How does it determine the shipping price used at the time of purchase?

**Comment by jjeffryes** [comment]
We're consolidating shipping issues in #1263
