### ISSUE TITLE
NSFW content option during setup does not do anything. Set to 'No' regardless of what is chosen.

### ISSUE THREAD

**Issue by pgalvin-original** [OpenBazaar/OpenBazaar-Client#1257]
**Brief Description:**
During the setup process, you're given the option to show or not show NSFW content. By default, it is set to not show. However, setting it to show doesn't do anything. If you view your settings later in the "General" section, it is still set to 'No'. However, setting it to 'Yes' here does work.

**Operating System (OS and version):** Linux, Ubuntu 16.04 (tested on 15.10 too)
**OpenBazaar version (shown on `About OpenBazaar` page in menu):** 1.1.0
**Hardware:** Intel Core i7-4650U CPU @ 3.3GHz, 8GB RAM

**Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce):** Always

**Steps to reproduce:**
1. Go through setup and set Show NSFW content to 'Yes'
2. Go to the 'Settings' and select 'General'
3. Ta-da. NSFW section is set to not show.

**Observed Behavior:**
After choosing to show NSFW content during setup, it instead does not show NSFW content - as seen in the settings after setup.

**Expected Behavior:**
NSFW content should show, and be set as 'Yes' in the settings after setup.

**Additional info (links, images, etc go here):**
Nothing necessary here.

**Comment by drwasho** [comment]
Yep, this is a known issue. We'll try and patch this by the next release.
