### ISSUE TITLE
JS error when selecting top menu items

### ISSUE THREAD

**Issue by mirelon** [OpenBazaar/OpenBazaar-Client#1260]
Operating System: Ubuntu 15.10
OpenBazaar version: 1.1.0

Reproducible Always

Steps to reproduce:
1. Start openbazaar
2. In the top menu, select Window -> Minimize

Observed Behavior:
Error message appears:
Uncaught Exception:
TypeError: Menu.sendActionToFirstResponder is not a function
    at MenuItem.click (/usr/share/openbazaar/resources/atom.asar/browser/api/lib/menu-item.js:71:23)
    at Function.delegate.executeCommand (/usr/share/openbazaar/resources/atom.asar/browser/api/lib/menu.js:128:69)

**Comment by mariodian** [comment]
FYI it works fine on the latest OS X.

**Comment by mirelon** [comment]
Ubuntu 15.10 (4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

Actually the safari-like minimize button works fine: 
![image](https://cloud.githubusercontent.com/assets/1101497/14282222/bd40ccf6-fb3d-11e5-94d1-627e063c006a.png)

The top menu is available only in maximized mode: 
![image](https://cloud.githubusercontent.com/assets/1101497/14282277/f5a2d1a2-fb3d-11e5-85e7-c710b45866f1.png) 
so now there are two ways to minimize - the safari like button still works and the classic Window -> Minimize does not: 
![image](https://cloud.githubusercontent.com/assets/1101497/14282381/61839140-fb3e-11e5-8f9d-5e3322afb627.png)

The same result is also for other items in menu Window. Other menus (OpenBazaar, Edit, View) work fine.

**Comment by jjeffryes** [comment]
Can you post a screenshot of the top menu items that cause this error, @mirelon ?

**Comment by mirelon** [comment]
I am not able to make a screenshot when the menu Window is rolled out, because at the pressing PrtScr button the menu fades out. But there are items "Minimize", "Close" and "Bring All to Front" and all are behaving the same

**Comment by jjeffryes** [comment]
We may need to disable that section on Ubuntu.

**Comment by mirelon** [comment]
Yeah it's kind of duplicate
