### ISSUE TITLE
Shipping costs options too restrictive

### ISSUE THREAD

**Issue by Morveus** [OpenBazaar/OpenBazaar-Client#1262]
Hi!

Some critics from us as a company (Ledger): having only "Domestic" and "International" is the first problem we encountered when starting selling our products on OB.

The problem being that in some countries, shipping options are almost non-existant and the only service available can be very expensive. Having the possibility to specify costs per-country or geo-zone would be great, and different shipping options ("mail", "registered", "express"...)

Even something simple like an optional table with one line per country and one column per shipping option would work for us. Cells would contain the costs (empty when not applicable and 0 for "Free" for instance).

Right now as a company, we don't have any other choice than offering international shipping for a fixed 10€ fee. It's that, or create multiple listings of each product and each zone (which is far, far too much and not practical).

**Comment by jjeffryes** [comment]
We're consolidating shipping issues in #1263

**Comment by Morveus** [comment]
Thank you
