### ISSUE TITLE
Respect native OS UI

### ISSUE THREAD

**Issue by nhantrn** [OpenBazaar/OpenBazaar-Client#1267]
Please localize the GUI of whatever OS the client is running on. I'm on Windows 10 and the UI of OB client is terrible. I hate the location of the close/min/max buttom and they are too small. Also the dragging area is terrible. Please please please whoever is in charge of the GUI consider making native GUI for whatever OS the client is running on.

**Comment by jjeffryes** [comment]
Your opinion has been noted, we'll consider that when revising the design in the future.
