### ISSUE TITLE
Add more timezones, not just 24 different choises

### ISSUE THREAD

**Issue by ripper234** [OpenBazaar/OpenBazaar-Client#1271]
In the installation wizard, give the user the full list of timezones to choose from, not just 24 options. Some timezones e.g. Israel shift from GMT+2 to GMT+3 according to daylight savings time in a unique manner. To have a correct timezone in Israel, I need to be able to select "Jerusalem".

**Comment by Grix** [comment]
A good solution would be to be able to simply use the local system time

**Comment by rmisio** [comment]
If someone wants to provide us a more definitive list, we'd be happy to update.

Alternatively, we would welcome a PR, updating `timezonesMd.js` and the `timezones` section of `en-US.json`.

**Comment by jjeffryes** [comment]
We are removing the timezones, they are not used for anything.
