### ISSUE TITLE
Two pieces of feedback from a buyer

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1273]
Proxying from the @helpdesk

> Hi, I just made a buy and I have a few remarks: 
> - state should not be mandatory in the shipping informations for country like France 
> - The payment window even though i clicked the "refresh status" several time never showed that my payment was received

**Comment by jjeffryes** [comment]
Shipping issues have been consolidated in #1262.

The payment received notification can sometimes take a long time if the libbitcoin server is backlogged.
