### ISSUE TITLE
Feedback regarding digital goods

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1275]
Proxying from the @helpdesk:

> Hi There. Thanks for the offer. All going fairly well, but one thing I need a solution for is to manage and automate the delivery of digital content after a purchase by a buyer. I understand this not a feature that OB necessarily supports or will implement, but what is your recommendation for a seller to deliver digital content (e.g. picture/zip file)? Your seller guide mentions "download from a URL", which is rather obscure/limited. In and ideal world, I would like my buyer to access the file/archive as soon as payment is complete, meaning receiving an automatic notification from OB that payment has cleared and the file/archive is avalaible to download from URL abc (e.g. Dropbox) using credential xyz. Any idea if such a service already exists or if there are plans to implement this in the future?

**Comment by jjeffryes** [comment]
It's likely we will add something like this in the future.
