### ISSUE TITLE
clickable links bug on product page description

### ISSUE THREAD

**Issue by BugsBunE** [OpenBazaar/OpenBazaar-Client#1276]
Brief Description:  there is a bug with the product page description allowing clickable links that overlay the whole OB rendering it impossible to navigate back to a working UI

Operating System (OS and version): windows 64bit
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware:  1.1.0

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
always

Steps to reproduce:
1. copy paste steam product description (including the links to tags ect)
2. save new product
3.  view new product and click on the phantom link using another non seller account

Observed Behavior:
overlay of a whitepage happens within whole application and no way of going back or undoing.
forced to reload the whole OB

Expected Behavior:
ask to open default browser

**Comment by jjeffryes** [comment]
Thank you for reporting this, @BugsBunE. This issue has been fixed in the master branch, that fix will be included in the next release.
