### ISSUE TITLE
The reimbursement address is asked too innocently

### ISSUE THREAD

**Issue by Giszmo** [OpenBazaar/OpenBazaar-Client#1285]
On my first purchase I was asked for a reimbursement address and conveniently linked to rushwallet. After a successful purchase, I closed the rushwallet tab, believing this was something temporary, only to find the address in my settings later. Bad surprise that will make people lose money.

Why not have a wallet in OB over trusting rushwallet not to steal my funds?

**Comment by Bitfinger** [comment]
Adding wallet functionality to OB can cause serious problems when inexperienced bitcoin users unwittingly delete their OB installation and their wallet keys along with it.

**Comment by jjeffryes** [comment]
Additional details were added to the return address.

**Comment by Giszmo** [comment]
The very concept of a static bitcoin address is a fading one. At least, OB should allow me to provide an XPUB.

And regarding the issue, it should ask for the address making clear that this will be the one and only bitcoin address used accross OB for whenever I receive funds (is that the case?).

**Comment by jjeffryes** [comment]
That is not the case. This is just the address used for any refunds for transactions, and it may be changed for each transaction.

When sellers wish to receive funds, they have to input a bitcoin address each time, whether they reuse one is up to them.
