### ISSUE TITLE
Purchasing (Payment pending)

### ISSUE THREAD

**Issue by juscamarena** [OpenBazaar/OpenBazaar-Client#1286]
Brief Description: 

Operating System (OS and version): Windows 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.1
Hardware: Dell laptop

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Tried one purchase, other reports on slack. 3 confirms in.

Steps to reproduce:
1. Buy item
2. send money
3. no profit

Observed Behavior:
The link to the payment address shows the correct amount sent and confirmations, but nothing on the client. Still shows as  "Purchasing (Payment 

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
This usually just means the libbitcoin servers are behind, after a while if you check the Transactions section your payment will go through.
