### ISSUE TITLE
1.1.1 completely fails for some

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1287]
On the @helpdesk several people are complaining that 1.1.1 is a complete failure for them (compared to 1.1.0). At least one guy is on windows 7 64 bit.

**Comment by jjeffryes** [comment]
Can you provide more details?

**Comment by JustinDrake** [comment]
Not really. I didn't dare try myself. See others with the same issue here: https://www.reddit.com/r/OpenBazaar/comments/4dpncl/unable_to_connect_to_your_server/

**Comment by jjeffryes** [comment]
The client has been updated to 1.1.2.
