### ISSUE TITLE
1.1.2: Mac OS recommends moving to trash

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1288]
See screenshot. I can't run 1.1.2

![screen shot 2016-04-07 at 17 08 55](https://cloud.githubusercontent.com/assets/731743/14358102/7f303832-fce3-11e5-9d10-242ed3e278c5.png)

**Comment by hoffmabc** [comment]
is the checksum ok on the file?

**Comment by JustinDrake** [comment]
How can I check that? What's the command?

**Comment by M45t3rJC** [comment]
I am getting the same error...

**Comment by hoffmabc** [comment]
Did you try the s3 link?

**Comment by M45t3rJC** [comment]
what/ where is s3 link???
I used the installer from OpenBazaar.org

**Comment by JustinDrake** [comment]
@hoffmabc What does `s3` mean? Where is the `s3` link?

**Comment by TheButterZone** [comment]
Redownload it, the code has been resigned properly to comply with OSX's requirements and I didn't see any more errors like this, nor security warnings.

**Comment by hoffmabc** [comment]
The new binaries are not giving this issue any longer thanks.
