### ISSUE TITLE
Can't type polish letters 'ę' (Alt + E) and 'ł' (Alt + L) beacuse of shortcuts

### ISSUE THREAD

**Issue by Libter** [OpenBazaar/OpenBazaar-Client#1289]
OpenBazaar version: 1.1.2
Reproducible: Always

Just change shortcuts letters in js/config.js or replace Alt with Ctrl in shortcuts.

**Comment by jjeffryes** [comment]
@programmerpeter the shortcuts currently use Ctrl. They shouldn't affect Alt and another key at all.

**Comment by Libter** [comment]
I reinstalled OpenBazaar. Unfortunately Alt shortcuts still works, Ctrl shortcuts works too.

There is no reference for altKey in js/main.js, so I have no idea why this issue happens.

**Comment by jjeffryes** [comment]
I can't duplicate this, on my computer the alt key doesn't trigger shortcuts. 

Can anyone else with a non-English keyboard replicate this?

**Comment by Libter** [comment]
Fixed: https://github.com/OpenBazaar/OpenBazaar-Client/pull/1298/commits/3a6652e1d5e0a9bf82870c36f63aefa98a6190b1

When alt key is pressed - e.ctrlKey and e.altKey is true.
