### ISSUE TITLE
Enhancement to main screen browsing experience. 

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#129]
This has been brought up a few times and I wanted to suggest an idea on how to resolve the problem.

**Problem:** Clicking an item on the homepage takes you to the contract detail screen on the vendor's page and then clicking back to home refreshes the entire list of items. Once the items reload again, the ordering of the items no longer matches the prior order, which makes the user have to dig through the same items multiple times and having to wait for it to reload feels unnecessary. This doesn't make for a great browsing experience, in fact it's pretty bad.

**Solution:** Let's identify when the user is casually checking out items; toggling back and forth between home and contract detail pages. If they are casually browsing, do not rebuild the list, instead cache it. We can safely append new items to the bottom of the list (lazy load style), but let's not blow away what has already been loaded.

At some point (let's say 30 minutes of inactivity), delete the cache and fetch from the network. Fetching should also happen on launch of the client and clicking reload while on the main screen could also destroy the cache and fetch from the network.

The only negative I can think of is nodes may go offline while they're still displaying in your cached list. I'd imagine this would only happen on a small percentages of clicks though since the cache doesn't live very long.

Open to ideas on how to make this even better.

**Comment by drwasho** [comment]
I like Wolf's proposal; it should enhance the UX.

**Comment by morebrownies** [comment]
https://38.media.tumblr.com/c26b20d3523d58572c00a59fabfc6650/tumblr_mtzmeqC16Z1qcga5ro1_500.gif
