### ISSUE TITLE
Time Zones still not translated

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1292]
Time Zones on General Settings are still not translatable (don't have strings).

OB v1.1.2

**Comment by pryds** [comment]
I believe this is a duplicate of issue #1179.

**Comment by Libter** [comment]
This issue has been fixed in 3bdc86e781e48c53e4a1ec866c257e6089439f1b.

**Comment by jjeffryes** [comment]
@programmerpeter is correct, I missed this issue when merging that code.
