### ISSUE TITLE
User cannot erase avatar image

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1296]
After user selects an avatar, the only option available on settings is to upload a new avatar. He can't choose not to use an avatar (can't use default avatar). 

![avatar](https://cloud.githubusercontent.com/assets/10789865/14371672/5decab56-fd10-11e5-8f81-b772d4b8cf52.png)

**Comment by morebrownies** [comment]
I just checked Github, FB and Twitter and none of these services offer a way to go back to the default avatar. People can always override the avatar they currently have by selecting a new one, but going back to default seems unnecessary.
