### ISSUE TITLE
cannot connect to server

### ISSUE THREAD

**Issue by BugsBunE** [OpenBazaar/OpenBazaar-Client#1300]
Brief Description: failing to connect to server

Operating System (OS and version):  win 7 x64
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware:  OpenBazaar-1.1.2_Setup_x64.exe

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. load client on windows 7, no vmware
2. try to connect
3. fails and i retry to get same failure

Observed Behavior:
previous version worked but required multiple restarts throughout the day

**Comment by drogongod** [comment]
Having the exact Same issue with windows 10 64  tried full uninstall. I upgraded to OpenBazaar-1.1.2_Setup_x64.exe and it stopped working tried uninstall and OpenBazaar-1.1.2_Setup_x32.exe no good . keep getting cannot connect to server . Ran as administrator.

**Comment by jjeffryes** [comment]
If you have just installed, the best way to resolve this is to join the #installation-issues Slack channel. There are so many possible variables with installation on an individual computer that it's unlikely there is a single issue that is causing all installation problems. 

http://slack.openbazaar.org/

If this is an existing installation, go through the following steps:
1. Try these instructions: https://openbazaar.zendesk.com/hc/en-us/articles/208277053
2. If you're still have problems, keep the username and password changes you made on the ob.cfg file.
3. Find the location of your database folder
   - Windows: `C:\Users\[Username]\AppData\Roaming\openbazaar`
   - OSX: `~/Library/Application Support/OpenBazaar`
   - Linux: `~/.openbazaar`
4. use a tool like http://sqlitebrowser.org/ to open the database. Find the settings table, and look for the username and password. If they are not the same as the ones you put in the config file, copy them from the database, and put them in the Server Configuration modal in the OB client, and click Save Changes.
5. If nothing else works, delete your database to start over. This will erase all of your data, only do this as a last resort.
6. Restart OpenBazaar
   - You'll most likely be taken to the 'Server Configuation' page again
   - Type in the username and password that you set in the ob.cfg file
   - Click 'Save Changes'

​_REMEMBER_​
- Be patient! 
  - If your node is starting for the first time, it will take at least 30 seconds before a GUID is generated. 
- Make sure SSL is turned off unless you are using a remote server with SSL

**Comment by Amiga500** [comment]
I have the same issue.. and i didn't resolved following these steps.. OB 1.1.2 with windows 7 64

**Comment by BugsBunE** [comment]
https://www.reddit.com/r/OpenBazaar/comments/4e19dt/heres_a_fix_for_unable_to_connect_to_server/

downloading openssl fixed the connection issues on this version
also i re-added the new version into the windows firewall

**Comment by Amiga500** [comment]
Thanks a lot.. it works :)

2016-04-09 19:56 GMT+02:00 BugsBunE notifications@github.com:

**Comment by jjeffryes** [comment]
More steps that may solve connection and other issues:

Install/update OpenSSL and other libraries that OpenBazaar uses:

Windows: 
https://slproweb.com/download/Win64OpenSSL-1_0_2e.exe

Macintosh:
- Install Xcode command line tools
- Open the terminal and type: $ xcode-select --install
- Install homebrew
- $ ruby -e "$curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
- $ brew update
- $ brew doctor
- $ brew install openssl
- $ brew install libffi
- $ brew install python

More information on manual installs can be found here https://slack-files.com/T02FPGBKB-F0KJU1CLX-cbbcf8a02c

**Comment by nimchak** [comment]
The Link Jjeffryes provided is dead now (old version).  Here is a newer version that did work for me.
https://slproweb.com/download/Win64OpenSSL-1_0_2g.exe

This really should be fixed in an immediate update.  specially since the client/server update themselves automatically.  I logged into my workstation today to find out my server has stopped working.

**Comment by hoffmabc** [comment]
Latest installer should resolve this now.
