### ISSUE TITLE
Unfilitered Discover page caches old vendors, no new vendors.

### ISSUE THREAD

**Issue by toxicwind** [OpenBazaar/OpenBazaar-Client#1307]
Brief Description: 
Discover page caches old vendors, no new vendors.
No new vendors appear even after restart/hitting discover again, but new vendors are findable with direct search.

Operating System (OS and version): 
Windows 10 
OpenBazaar version 1.1.2

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Open Client
2. Hit Discover Button **This is definately with the filter off
1st load: http://i.imgur.com/FruzlYO.png
hit discover, same items in different order, just slightly down the page, no new items or vendors at all:
http://i.imgur.com/fCDBtoR.png 
3. Scroll to bottom of listings, the list will just stop. http://i.imgur.com/ZlWs1H7.png

Observed Behavior:
Same stores, sometimes different order, no new vendor connections. Can't actually "discover" any new stores as there are no new vendors.

Expected Behavior:
New randomized list of items from vendors that have been found from newly queried node list.
It seems like the node list is just reading the cached list and giving back those.

**Comment by hoffmabc** [comment]
So one thing to understand is that the listings you see are a randomized assortment of listings from nodes in your "neighborhood". If you don't know how Kademlia works, essentially you have a routing table with a subset of all nodes in it that you are connected to. This could be why you only see some of the same types of listings over and over. Also you may have limited connectivity to all of the network (I'm not sure your case). This is an extremely basic way of discovering on the network, but I don't believe this is necessarily a bug. What makes you say they're from the cached list? Do you have some data to back that up? Not accusing, just would like to see your evidence of that.

**Comment by jjeffryes** [comment]
We haven't been able to reproduce this, I'm going to close it.
