### ISSUE TITLE
No response from the server

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1309]
Just installed 1.1.2, see screenshot:

![screen shot 2016-04-09 at 17 15 19](https://cloud.githubusercontent.com/assets/731743/14404800/bc14839a-fe76-11e5-8453-0faa3820200c.png)

**Comment by hoffmabc** [comment]
This is related to the CPU usage issue I believe.

**Comment by jjeffryes** [comment]
Server connection problems are consolidated in #1300
