### ISSUE TITLE
Report from @helpdesk

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#1310]
"I just wanted to report a bug. Whenever I press CMD+W to close the window of openbazaar in OSX the app crashes. Please fix it. Thanks."

**Comment by morebrownies** [comment]
Confirmed

Here's a screenshot of the crash log

![screenshot 2016-04-11 08 27 42](https://cloud.githubusercontent.com/assets/13066886/14432508/5467f5de-ffbf-11e5-8cc0-bed2706cf6e4.png)

**Comment by hoffmabc** [comment]
Will fix. Thanks.

**Comment by jjeffryes** [comment]
This was fixed.
