### ISSUE TITLE
Graphic Acceleration Artifacts

### ISSUE THREAD

**Issue by nerdy-sam** [OpenBazaar/OpenBazaar-Client#1311]
Brief Description: Black boxes cover most of the client with this in the log... (over and over)
[77278:0409/162705:ERROR:gles2_cmd_decoder.cc(7430)] [.Compositor-0x7fa2cbdba7f0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

Operating System (OS and version): OSX 10.11.3
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.2 from git commit 07a021c5eb23fd1dc7098a8e42b6f91768be4e80
Hardware: 16GB Ram intel processor and intel HD Graphics 3000 512 MB

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. npm start
2. 
3. 

Observed Behavior:
Flickering black boxes cover most of the client

Expected Behavior:
No flicering black boxes, but a properly rendered page

Additional info (links, images, etc go here):
![screen shot 2016-04-09 at 4 35 51 pm](https://cloud.githubusercontent.com/assets/1237892/14406569/40b8b50e-fe71-11e5-96fe-c0a260c70613.png)

**Comment by jjeffryes** [comment]
Does this happen every time you start the app, or only on certain pages?

**Comment by nerdy-sam** [comment]
Everytime I start the app, on every page, including settings... however, leaving it closed for a while and coming back to it... there are now no problems... might have just been my machine...

**Comment by jjeffryes** [comment]
We haven't been able to reproduce this, as far as I can tell it's an issue with chromium's rendering. Closing it unless it happens again.
