### ISSUE TITLE
Not possible to format text in "About" page

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Client#1312]
With the current client on OSX (commit 07a021c5eb23fd1dc7098a8e42b6f91768be4e80), it is not possible to format any of the text in the "about" field.

Formatting used to be possible with an earlier version of the client (by use of a pop-up menu) but that feature no longer exists. Though it says in the settings that basic HTML can be used, tags like H1 and H2 aren't recognized.

I would suggest allowing HTML header tags, as well as allowing basic markdown syntax (like "#"). As a note, the lack of section headers makes the indexed text on bazaarbay.org unreadable.

**Comment by jjeffryes** [comment]
This is not a bug, we deactivated the formatting because it was causing invalid JSON to be saved in some instances, which would make your profile unreadable.

Once we have corrected that, formatting will be allowed again.
