### ISSUE TITLE
Category Ordering

### ISSUE THREAD

**Issue by K-clarke** [OpenBazaar/OpenBazaar-Client#1313]
A sellers listings should be ordered alphabetically instead of in the order which they were created. This will help buyers find the category they are looking for faster, especially as sellers stores grow larger and the amount categories they have will increase.

![screenshot from 2016-04-09 22 18 01](https://cloud.githubusercontent.com/assets/4810448/14411876/ac01ca86-ff4c-11e5-85d5-d4f052867943.png)

**Comment by morebrownies** [comment]
+1 categories should sort alphabetically in the select menu

At some point in the future, we'll probably want to add different sorting options for the listings within a category (Order by date created, order alphabetically, order by most rated, order by highest rated, etc)
