### ISSUE TITLE
Enlarged images overlap the side bar

### ISSUE THREAD

**Issue by K-clarke** [OpenBazaar/OpenBazaar-Client#1314]
When an image of a item is enlarged it overlaps the side bar.

![screenshot from 2016-04-10 19 04 46](https://cloud.githubusercontent.com/assets/4810448/14411993/5413583c-ff4f-11e5-9063-a3e9395f268d.png)

![screenshot from 2016-04-10 19 04 37](https://cloud.githubusercontent.com/assets/4810448/14411994/5bbd85bc-ff4f-11e5-893d-d7b42672367e.png)

**Comment by morebrownies** [comment]
+1 confirmed 

It also happens when the chat panel is open.

**Comment by rmisio** [comment]
i got this one.
