### ISSUE TITLE
Setting up the client on a server and managing it from another machine

### ISSUE THREAD

**Issue by nimchak** [OpenBazaar/OpenBazaar-Client#1315]
Brief Description: 

Operating System (OS and version): Windows 2012 R2
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.2
Hardware: AWS

So I didn't want to have the client running always on my workstation and seeing how your listing do not stay up when you don't have the server/client running I decided to spin up an AWS server for it.  Here are the steps I took:
1) install client on the server (had to install open SSL (windows ) first to get it to actually come up.
2) copied appdata from my workstation where my store and listings were to the newly built server.
3) the client on the server started perfectly and my store was up.

My issue:
I want to connect to the server using my workstation to manage the store without having to log into the server.  How do I get the client on my workstation connect to the server?  I have seen the login page when there is connection problems but I don't know how I can force the connection settings to come up so I can specify the server location/username/password.

Thanks for the help.

**Comment by rmisio** [comment]
@nimchak this can be accessed by clicking the Change button in the Server Settings section of the Settings > Advanced page:

![image](https://cloud.githubusercontent.com/assets/794517/14437479/3ad3d96e-ffd6-11e5-8db8-15f152e2b90f.png)

![image](https://cloud.githubusercontent.com/assets/794517/14437492/4b13f64c-ffd6-11e5-9d91-4e3ddcb594d2.png)

**Comment by nimchak** [comment]
@rmisio Thank you for your response. Unfortunately from what I see that is not true.  The password you see listed under server settings are not visible.  So I can not use it on the workstation.

What am I missing?

**Comment by rmisio** [comment]
yes, to run the type of advanced set-up you are trying to run, you will need to specify your own custom username and password for your server. You do this in the ob.cfg file on the server. Make sure you also uncomment the username and pw lines (remove the leading hash). Also, be sure to restart the server after making the change.

![image](https://cloud.githubusercontent.com/assets/794517/14437684/4ccaddce-ffd7-11e5-88e8-7f269fcce474.png)

**Comment by nimchak** [comment]
:) I actually did specify username and password in that file already.  But I forgot to uncomment it.  Thanks I will try that tonight.
