### ISSUE TITLE
Listing title + avatar margin

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#132]
![image](https://cloud.githubusercontent.com/assets/3887694/10900332/243c8360-822a-11e5-99f6-b8c30220816f.png)

**Comment by gubatron** [comment]
![eye_twitch](https://cloud.githubusercontent.com/assets/163977/10900388/1e8f1a22-81ad-11e5-90a5-7004f832a935.gif)

**Comment by drwasho** [comment]
Kickass @jjeffryes
