### ISSUE TITLE
Redo the Shortcuts Again

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1325]
Some users are reporting shotcut collisions on Mac.

Redo the shortcuts to make sure:
- none collide with common shortcuts on Mac, Windows, or Linux
- none use number keys (non-english keyboards use the number keys for special characters)
- H is a Mac shortcut
- Y is expected to be redo

**Comment by mariodian** [comment]
There's only one collision with a **global** and **default** mac shortcut: cmd+h (hide window), we use it for "My Page". Everything else is an app-specific and we can't prevent that.
