### ISSUE TITLE
Show Listings in Unreadable Currency as Unavailable to Buy

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1332]
If a listing is set to a currency that doesn't currently return an exchange rate from btc_prices (due to the 3rd party APIs having issues), the client displays the price as NaN and the server cannot complete a purchase of that listing.

If the price is returned as NaN, show a message stating the item is temporarily unavailable, and disable the buy button.

**Comment by ulrichard** [comment]
Maybe related to this: CHF was available in an earlier version, but I cannot choose it in the current release.

**Comment by jjeffryes** [comment]
@ulrichard where are you seeing it as unavailable? I am able to select Swiss Francs as my currency normally when I try it in Settings.

**Comment by ulrichard** [comment]
Yes, it's available again.
And also the items that were listed with a NaN price show a numeric value again.
In the meantime I upgraded to 1.1.3

**Comment by jjeffryes** [comment]
@ulrichard sounds like upgrading fixed this for you. There was a bug in earlier versions of the code that caused currencies to fail to load.

I'm closing this issue, since we have changed the way we pull in currencies, and all currencies should always be available.
