### ISSUE TITLE
An incorrect reply was received from the server. The JSON data returned from the server was malformed

### ISSUE THREAD

**Issue by marcoBros** [OpenBazaar/OpenBazaar-Client#1335]
Brief Description: 
I modify product title for sale by adding html tag < h1 >. I got a message about JSON error after validate changes. I make changes again by removing html tag and validate. Now I cannot display my page without error, and cannot see my product for sale. The product is also not available in search.

Operating System (OS and version): Ubuntu 15
OpenBazaar client version : 1.1.2 

Reproducible : Always

Steps to reproduce:
1. Go on ob://@marcantoine

Observed Behavior:
Error message : "An incorrect reply was received from the server. The JSON data returned from the server was malformed"

Expected Behavior:
Shouldn't show error and should display the product for sale.

Additional info (links, images, etc go here):
![screenshot from 2016-04-12 19-54-18](https://cloud.githubusercontent.com/assets/1652041/14470182/5ba9e47c-00e8-11e6-8290-aa078eba182e.png)

**Comment by jjeffryes** [comment]
The data for your listing is somehow coming back as

`{
    "listings": [
        {
            "contract_hash": "33df5c5296b018d85a55adda36cb19e90ca82742", 
            "category": "domain name", 
            "nsfw": false, 
            "title": "&lt;h1&gt;openbazaar247.com<h2> domain name", 
            "thumbnail_hash": "fa604c874c736d25de8f5c82fb0e0fe6b983fcc7", 
            "price": 3.0, 
            "origin": "NA", 
            "currency_code": "BTC", 
            "ships_to": []
        }
    ]
}</h2>`

Which is invalid. We'll investigate why the server is returning data that way.

**Comment by jjeffryes** [comment]
This has been corrected on the server. Old data that is malformed may still be an issue, and might require editing your database directly or starting with a fresh database.

**Comment by marcoBros** [comment]
Yes, i used server API to remove the contract from his id.
I will try to reproduce this error if i get time

Thank you @jjeffryes

**Comment by marcoBros** [comment]
@jjeffryes ,
Okay i just reproduce this bug.

Steps : 
1. Create new product for sale
2. Fill all compulsory fields.
3. Save product.
4. Update product
5. Fill title field with : `<h1>Test<h2>`
6. Validate : You got an error message, but the contract has been updated.
7. Go on your home page : error message is displaying and product listing is not 

Maybe this error can appear by filling title field during the product creating and not only during updating.

How did you get my product listing ? I need to remove this contract (`ob://@marcantoine`)
`/api/v1/get_listings` provide an empty json object

**Comment by jjeffryes** [comment]
It looks like the title field isn't being sanitized. 

We're tracking this on the server at https://github.com/OpenBazaar/OpenBazaar-Server/issues/329

**Comment by rmisio** [comment]
This should be fixed, at least for the contracts endpoint. In the near future, the fix will be applied to all endpoint returning JSON to the client.

**Comment by jjeffryes** [comment]
This has been fixed.
