### ISSUE TITLE
Taler for payments in euros, etc.

### ISSUE THREAD

**Issue by burdges** [OpenBazaar/OpenBazaar-Client#1341]
Your FAQ expressed an interest in payment systems besides BTC.

[Taler](https://taler.net/) is an transaction system built on Chaum-style [RSA blind signatures](https://en.wikipedia.org/wiki/Blind_signature#Blind_RSA_signatures.5B2.5D:235).  It's therefore actually anonymous, assuming you mask your IP address, while BTC is at best only pseudonymous.  The wallet runs in the browser using WebExtensions.  See [demo](https://demo.taler.net/).   I've no idea if that's realistic to adopt to node.js and electron though.

A Taler exchange (mint) is expected to handle the real currency payments in euros, dollars, etc. using inexpensive electronic bank transfers, giving it extremely low fees.  Anyone could deploy an exchange that dealt in BTC, video game currencies, etc.  Anonymity and credit card dispute procedures would now play well together though.  ;)

**Comment by jjeffryes** [comment]
Thankyou for the suggestion. We'll keep an eye on Taler, but right now we don't have any plans to switch off of Bitcoin.
