### ISSUE TITLE
Something appears to be breaking the flexcol grid on the About tab

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1346]
It doesn't seem to happen on every about page, but it is definitely happening on @themes

<img width="1187" alt="screenshot 2016-04-13 09 07 27" src="https://cloud.githubusercontent.com/assets/13066886/14500497/3fc4767c-0157-11e6-8589-d84272dc2baf.png">

**Comment by hoffmabc** [comment]
Is this with which version of electron?

**Comment by morebrownies** [comment]
I'm on the latest version

**Comment by jjeffryes** [comment]
I've seen this crop up in a few places. I'll fix it.

**Comment by jjeffryes** [comment]
Apparently in the latest Chrome 66.66666666666666% + 33.33333333333333% is more than 100%, but 66.6% + 33.3% is not.

**Comment by morebrownies** [comment]
lol

**Comment by jjeffryes** [comment]
Actually, 66.6% + 33.3% is still more than 100%. They must have changed something with how flex-basis works.

**Comment by jjeffryes** [comment]
But it only happens sometimes. It might be something in the content making the column slightly too wide somehow.

**Comment by jjeffryes** [comment]
Somehow the guid is doing it, depending on which letters and numbers are in your guid in the right column.
