### ISSUE TITLE
Adding a new address requires non-applicable info

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#1348]
Brief Description: When adding a new address, the field State/Province/Region seems to be required. However, in Denmark (and most likely elsewhere, too), neither provinces, regions nor state (we have only one state) are ever used in postal addresses.

this piece of info is not part of a postal address. We have only one state (namely the whole country), and neither provinces nor regions are ever used in postal addresses.

Also, according to [these](https://hellowahab.wordpress.com/2011/05/24/list-of-countries-without-postal-codes/) [random](https://gist.github.com/kennwilson/3902548) [webpages](http://forum.geonames.org/gforum/posts/list/462.page), there are a lot of countries that don't use postal codes or zip codes in their addresses.

Additional info (links, images, etc go here):
![openbazaar-address](https://cloud.githubusercontent.com/assets/4420584/14505795/0561c188-01bb-11e6-8512-5798c2fe1316.png)

**Comment by jjeffryes** [comment]
This is part of the conversation in #1263
