### ISSUE TITLE
Client bricked when node is unreachable

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#135]
![image](https://cloud.githubusercontent.com/assets/3887694/10901775/6c122436-8240-11e5-93f1-77a440f0710a.png)

Esc or Ctrl+r doesn't get me out :/

**Comment by drwasho** [comment]
I think this got fixed in the latest bunch of commits. Will reopen if encountered again.

**Comment by jjeffryes** [comment]
Yes, I thought I had closed it in the PR.
