### ISSUE TITLE
Hardcoded "FOLLOWS YOU" on every user page

### ISSUE THREAD

**Issue by mariodian** [OpenBazaar/OpenBazaar-Client#1360]
There is a text saying "FOLLOWS YOU" in every user page. It's hardcoded to the template userPage.html

![screen shot 2016-04-14 at 6 47 20 pm](https://cloud.githubusercontent.com/assets/3636406/14525764/b0aebe9a-0271-11e6-865b-b17680c9ce46.png)

**Comment by jjeffryes** [comment]
Looks like a hide class was missing.

**Comment by mariodian** [comment]
I have the latest code and I still see it.

**Comment by jjeffryes** [comment]
That's strange. I'm on the latest master, and it's working correctly for me. 

Can you check js/templates/userPage.html, line 98, and make sure it is 
`
<div class="hide js-followsMe allCaps fontSize12 padding10">`

**Comment by mariodian** [comment]
Oh stupid me, I was on a different branch. Sorry, my bad.
