### ISSUE TITLE
Don't Launch Local Server if Connected to Remote

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1369]
When a client is connected to a remote server, if it was installed with the installer it still starts the local server, which is then unused and ads a "zombie" node to the network.

If the client is currently set to connect to a remote server, it should not start the local server when the app starts. This can be done by getting _serverConfig-1 from localStorage and checking to see if it starts with localHost.

**Comment by rmisio** [comment]
I'll look into it.

**Comment by rmisio** [comment]
This is still on my radar. I will get back to it once https://github.com/OpenBazaar/OpenBazaar-Client/pull/1453 is merged in since it directly affects this request.

**Comment by rmisio** [comment]
verified and merged.
