### ISSUE TITLE
CTRL-Y closes without saving

### ISSUE THREAD

**Issue by Giszmo** [OpenBazaar/OpenBazaar-Client#1375]
OB 1.1.3

Hitting CTRL-Y is not redo?

Observed Behavior:
When hitting CTRL-Y it jumps to Transactions->Sales

Expected Behavior:
It re-does stuff I just un-did using CTRL-Z

Additional info (links, images, etc go here):
It's kind of standard to have CTRL-Z to undo and CTRL-Y to re-do. Editing some complicated listing it's a pain to have it jump to Transactions->Sales out of nowhere, without asking if I want to save my changes.

**Comment by Dekker3D** [comment]
Ctrl-Y and ctrl-shift-Z have both been used for redo. But yes, ctrl-Y should not do something unexpected that forgets what you were just editing.

**Comment by Libter** [comment]
This issue propably duplicates #1325.
