### ISSUE TITLE
Link to Item in Order Summary doesn't load Item.

### ISSUE THREAD

**Issue by sgornick** [OpenBazaar/OpenBazaar-Client#1376]
At Sales -> Order Details -> Summary 
then click on the link for the item.  It appears it is trying to load the item, but it just spins, forever.

The status message in the center of the page is: "Connecting to listing [listing ID]"

Operating System: Linux Ubuntu 14.04
OpenBazaar version: v1.1.3

Reproducible: Always

Steps to reproduce:
1. Sales -> Order Details -> Summary 
2.Click on link to the item.

Observed Behavior:
"Connecting to listing [listing ID]"  with loading/spinner.   But nothing further.

Expected Behavior:
After spinning for a few seconds, the item would appear.

Additional info (links, images, etc go here):
This is for an item that I've made changes to after the order occurred.  Not sure how changes to an item impact post-sale inquiries.

**Comment by jjeffryes** [comment]
This was fixed.
