### ISSUE TITLE
selecting a chat should not follow links in the first message

### ISSUE THREAD

**Issue by Giszmo** [OpenBazaar/OpenBazaar-Client#1377]
If I click in the list of messages, I might click in the lower half of the box and if the sender sent me a link, OB opens that link in addition to selecting that chat.

Please disable links in the Messages list.

**Comment by hoffmabc** [comment]
Good catch.

**Comment by rmisio** [comment]
If I send a chat message with a link and then try to click that link from the chat head, it does not follow the link, it just opens up the chat conversation box at the bottom. If I click on the link within the chat conversation box, it does open the link in the browser. I believe that's the correct behavior.

Perhaps the bug has been fixed, or perhaps I'm completely misunderstanding it? Can anyone please confirm.

![image](https://cloud.githubusercontent.com/assets/794517/15161971/6396214a-16b5-11e6-86ab-449ea5cde6fc.png)

**Comment by jjeffryes** [comment]
It happens if they embed the link as <a href="link">link</a>, at least on my copy of master using Windows.

**Comment by rmisio** [comment]
hmm... pretty odd. Might be a Win only thing, because on my mac, that's what I did and it didn't follow the link.

**Comment by SamPatt** [comment]
@rmisio and @jjeffryes Cannot reproduce on Linux. Still an issue on other OS?

**Comment by jjeffryes** [comment]
I can't reproduce it on Windows.

**Comment by rmisio** [comment]
I couldn't on OSX. Looks like a Win issue.
