### ISSUE TITLE
Names of countries are still not translatable

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1384]
Names of countries ([countriesMd.js](https://github.com/OpenBazaar/OpenBazaar-Client/blob/master/js/models/countriesMd.js)) should be added to language files for translation.

**Comment by pryds** [comment]
This issue might be a duplicate of part of issue #1179.

**Comment by rmisio** [comment]
I'm working on this one.

**Comment by rmisio** [comment]
this is fixed.
