### ISSUE TITLE
"Add as moderator" botton om moderators' "About" tab

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#1385]
Brief Description: If you found a person with moderation enabled that you would like to add as a moderator, there doesn't seem to be any other way than load up the settings screen and hope that they will turn up there. I just tried that, and this particular person I found didn't turn up, so I was not able to add them.

Therefore, I propose the addition of a new button on a moderator's about page (or in a similar spot) that would add that person as a moderator on your store -- given you have enabled your store, and given this person has enabled the moderator setting, of course.

Maybe even the addition of an additional tab, next to "About", "Following" and "Follows" with moderating details, including fee, moderator-specific description text, and this button that would add them as a moderator for your store.

**Comment by Dekker3D** [comment]
https://github.com/OpenBazaar/OpenBazaar-Client/pull/1357 is me doing exactly that, about three days ago. Had some problems that needed to be fixed, currently waiting for it to be checked again. It will add an add/remove moderator button next to the follow/unfollow button, in the same conditions you specified.

The button still fails on moderators that don't show up in the list either, so this won't fix that. Others are probably working on this.

**Comment by pryds** [comment]
Very nice! Closing this issue, then.
