### ISSUE TITLE
qr code format

### ISSUE THREAD

**Issue by ulrichard** [OpenBazaar/OpenBazaar-Client#1392]
Brief Description: 
My case hardware wallet (choosecase.com) can't read the format of the qr code displayed by openbazaar

Operating System (OS and version): Ubuntu 15.10
OpenBazaar version (shown on `About OpenBazaar` page in menu):  1.1.3
Hardware: choosecase.com

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Buy something
2. Scan the qr code with a case hardware wallet
3. 

Observed Behavior:
Device can't read the qr code

Expected Behavior:
Device can make the payment

Additional info (links, images, etc go here):

The format used by openbazaar is:
bitcoin://3Jxxx?amount=0.1&label=text

While the case wallet can successfully read the format as used by electrum:
bitcoin:3Jxxx?amount=0.1&message=text

**Comment by jjeffryes** [comment]
The QR code is readable by the scanners we have access to, I'm not sure how we'd troubleshoot this short of getting a case hardware wallet.

@ulrichard can you check in settings/advanced in the client, to make sure you're not set to generate a testnet QR code?

**Comment by TheButterZone** [comment]
bitcoin://3Jxxx?amount=0.1&label=text doesn't meet [the URI standard](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki)?

**Comment by jjeffryes** [comment]
In what way do you think it doesn't meet the URI standard, @TheButterZone ?

**Comment by TheButterZone** [comment]
There are not supposed to be forward slashes, as shown in the link above.

**Comment by jjeffryes** [comment]
Good catch. The QR code in the transactions section when you look at an unpaid order doesn't have the //, we missed taking it out in the main purchase flow, and our QR scanners work regardless of the // being there or not.

I'll remove it.

**Comment by jjeffryes** [comment]
@ulrichard can you pull the latest client code and see if this issue still happens for you?

If you prefer to use the installer, this fix will be in the 1.1.4 release, once that happens please let us know if this issue is resolved.

**Comment by ulrichard** [comment]
I'm not so good with npm stuff. But I guess the 1.1.4 is just around the corner.

**Comment by jjeffryes** [comment]
Yes, it should be very soon.

**Comment by jjeffryes** [comment]
Any update, @ulrichard ? I'm going to assume this is complete, and close it. If you're still seeing the issue I'll reopen it.

**Comment by ulrichard** [comment]
Sorry, I was on holiday.
Yes, it works now flawlessly with the case wallet.
