### ISSUE TITLE
? Debian repository - install problems - seeking advice

### ISSUE THREAD

**Issue by EdNett** [OpenBazaar/OpenBazaar-Client#1395]
Hello,

I have been unable to get the client to install on debian jessie, and now also on wheezy. Could you please tell me:

1) Is this easier to install on ubuntu - if so, which version, please?

2) Is Debian jessie supported?

Is debian Wheezy supported?

4) Is there an ubuntu or Debian repository that we can add to the /etc/apt/sources.list file or list.d file to make this install easier?

5) Can you point me to a clear step-by-step example of how to install via the .deb file, please?

6) Could you post lmore info on how to make sure that the server and the client have the correct path info for the npm install - since npm isn't in any of the wheezy repositories that I can find - could you give a step-by-step guide to verifying and doing this, please?

I am trying to installl this on a vps and I am able to install the server, and when I get to the last command "npm start" there are a bunch of errors:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'start' ]
2 info using npm@3.8.6
3 info using node@v0.10.29
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle OpenBazaar@1.1.3~prestart: OpenBazaar@1.1.3
7 silly lifecycle OpenBazaar@1.1.3~prestart: no script for prestart, continuing
8 info lifecycle OpenBazaar@1.1.3~start: OpenBazaar@1.1.3
9 verbose lifecycle OpenBazaar@1.1.3~start: unsafe-perm in lifecycle true
10 verbose lifecycle OpenBazaar@1.1.3~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/OpenBazaar-Installer/OpenBazaar-Client/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
11 verbose lifecycle OpenBazaar@1.1.3~start: CWD: /var/OpenBazaar-Installer/OpenBazaar-Client
12 silly lifecycle OpenBazaar@1.1.3~start: Args: [ '-c', 'electron main.js' ]
13 info lifecycle OpenBazaar@1.1.3~start: Failed to exec start script
14 verbose stack Error: OpenBazaar@1.1.3 start: `electron main.js`
14 verbose stack spawn ENOENT
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:17:16)
14 verbose stack     at ChildProcess.emit (events.js:98:17)
14 verbose stack     at maybeClose (child_process.js:755:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
15 verbose pkgid OpenBazaar@1.1.3
16 verbose cwd /var/OpenBazaar-Installer/OpenBazaar-Client
17 error Linux 3.2.0-4-amd64
18 error argv "node" "/usr/bin/npm" "start"
19 error node v0.10.29
20 error npm  v3.8.6
21 error file sh
22 error code ELIFECYCLE
23 error errno ENOENT
24 error syscall spawn
25 error OpenBazaar@1.1.3 start: `electron main.js`
25 error spawn ENOENT
26 error Failed at the OpenBazaar@1.1.3 start script 'electron main.js'.
26 error Make sure you have the latest version of node.js and npm installed.
26 error If you do, this is most likely a problem with the OpenBazaar package,
26 error not with npm itself.
26 error Tell the author that this fails on your system:
26 error     electron main.js
26 error You can get information on how to open an issue for this project with:
26 error     npm bugs OpenBazaar
26 error Or if that isn't available, you can get their info via:
26 error     npm owner ls OpenBazaar
26 error There is likely additional logging output above.
27 verbose exit [ 1, true ]

Brief Description: 

Operating System (OS and version): 
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
The best place to troubleshoot installation issues is in the #installation-issues channel of our Slack. 

https://openbazaar-slackin-drwasho.herokuapp.com/

We currently only support Ubuntu 12 and 14, as well as Mac OSX and Windows 8.1 and above. Some users have gotten things working on various other OSes, but it usually takes some manual work.
