### ISSUE TITLE
Sellers editing listing settings on listing page

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1399]
Sellers should not see their own listings the same way as buyers do. Instead, they should be able to edit their listing while viewing it. Example:

![editinlisting](https://cloud.githubusercontent.com/assets/10789865/14662557/b1bf743a-068d-11e6-8f69-de9091ffe7b6.png)

**Comment by morebrownies** [comment]
I don't see a problem with having a distinct view mode and distinct edit mode (as we currently have it). If we essentially force the vendor into edit mode each time they visit one of their listings, how would they go about viewing what their customers see while they're shopping on their store?

**Comment by jjeffryes** [comment]
I agree with Mike, having a separate edit screen is standard, and in our case putting all of the edit controls into the normal view would make them more difficult to use.
