### ISSUE TITLE
Make Chats with Unread Messages Float to Top

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#1401]
As title suggests, if a chat conversation has unread messages it should float to the top of the list for increased visibility. This only is an issue for those with lots of previous conversations in their list where it might show a notification in the dock, but not be able to quickly see which conversation has unread messages.

**Comment by mariodian** [comment]
I'm not sure if it should go to the top, because you leave it unread for a reason. Whatever the reason is, the message is probably not important to you and that's why it shouldn't be extra visible.

If it's a new conversation, it already ends up at the top.

**Comment by mariodian** [comment]
I'm working on this.

**Comment by mariodian** [comment]
Sorry it takes so long to finish, I'm traveling now, I will get back to it in a week or so.
