### ISSUE TITLE
Change CMD + R hotkey to reload the current view instead of the entire application

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1402]
We'll then need to change Restart Application to another hot key (possibly CMD + SHIFT + R) or remove the hotkey all together.

**Comment by Libter** [comment]
Current shortcuts are good. F5 reloads current view and CMD + R restarts application.

**Comment by mariodian** [comment]
Nobody uses F5 on mac though and it's not exactly user friendly because you have to hit fn+F5.

**Comment by morebrownies** [comment]
Yeah CMD + R is much more user friendly

**Comment by jonasbits** [comment]
CMD + H to hide would also be nice ( CMD + M to minimize is working )

**Comment by morebrownies** [comment]
CMD + R still seems to reload the entire application

**Comment by jjeffryes** [comment]
Correct. I make CMD + T refresh the page, and kept CMD + R as-is. 

We don't want to add shift or alt, that causes problems for international keyboards, some of them use shift or alt to change the letters on the keyboard to special characters.

**Comment by morebrownies** [comment]
Hitting CMD + T to refresh isn't very intuitive. I'd also like to reserve CMD + T for opening a new tab (in the future). 

I don't think we need a hotkey to restart the entire app. I think we can just remove that hotkey and people can restart (when needed) via the user navigation.

**Comment by morebrownies** [comment]
<img width="296" alt="screenshot 2016-04-29 12 43 45" src="https://cloud.githubusercontent.com/assets/13066886/14927662/0ab5c19e-0e08-11e6-8422-2761e930041c.png">

Also adding "Refresh page" to the User nav seems unnecessary to me.

**Comment by jjeffryes** [comment]
The nav menu is where we show the keyboard shortcuts. How else will they know what keyboard shortcuts refresh and reload?

I use reload a lot, for development and testing, I think it should stay even if we don't draw the user's attention to it.

**Comment by morebrownies** [comment]
We can display it on hover of the reload button 

<img width="562" alt="screenshot 2016-04-29 12 50 23" src="https://cloud.githubusercontent.com/assets/13066886/14927807/fa0e01d4-0e08-11e6-981b-828dcc7f9440.png">
