### ISSUE TITLE
When I click "Pay for Order" and the QR fails to load, I'm stuck in a dead-end where I can't retry to "Pay for order"

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1408]
As the title says, I was trying to buy something from @openbazaar and the QR failed to load and I was pushed back into the Order Details step and I noticed I do not have the ability to click "Pay for Order" again. Notice the button in the modal is set to "Payment pending".

![screenshot 2016-04-20 09 25 57](https://cloud.githubusercontent.com/assets/13066886/14682361/25b6f84e-06da-11e6-9a74-47910c14ef48.png)

**Comment by jjeffryes** [comment]
When you say the QR code failed to load, what, exactly, happened? Did you get an error screen?

**Comment by morebrownies** [comment]
Yes. I didn't get a screenshot of the error, but it said something along the lines of the "Node can't be reached", which then pushed me back to the Order Details screen and left me stuck.

**Comment by morebrownies** [comment]
Actually, I just tried again and hit the error state. It seems to be happening a lot on the @openbazaar store

![screenshot 2016-04-20 11 43 31](https://cloud.githubusercontent.com/assets/13066886/14686352/27bcaa40-06ed-11e6-90c0-15893af5971f.png)

**Comment by hoffmabc** [comment]
I think this could be related to the store being so popular and not scaled up properly.
