### ISSUE TITLE
Need a mute button for sites that have audio

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Client#1418]
I am not sure how they are doing it, but some sites have audio associated with them. At a minimum, there should be a mute button in the client, or a preference setting that enables/disables audio. It might be better to simply not allow audio at all, given that there is no situation where this is acceptable behavior.

**Comment by JustinDrake** [comment]
Haha, could you provide an example vendor or listing?

**Comment by mariodian** [comment]
They embed youtube via iframe. Iframes will be blocked in #1416

**Comment by jjeffryes** [comment]
There was a bug that prevented the sanitization from catching some tags that shouldn't have been allowed, and some users figured out that let them put in iframes and embedded media.

That's been fixed, and any tags other than simple text formatting, images, and links will be removed in the next release.

**Comment by lunokhod** [comment]
Here's an example: 

ob://54cc90b781ba13cf3e7de3717bdc33d9a0acf3b6/store
