### ISSUE TITLE
Profile Pages and where @username is shown should ensure valid structure

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#142]
Make sure inputs only allow @username format and not arbitrary content. The next step would be to validate against Onename API as well. This will need to happen on incoming content as well to prevent identity spoofing.

![image](https://cloud.githubusercontent.com/assets/45482/10920990/242d1f1c-8241-11e5-9c9a-ae74c51212bc.png)

**Comment by drwasho** [comment]
Blockchain ID support should be its own issue.
