### ISSUE TITLE
shop not displaying any data

### ISSUE THREAD

**Issue by BugsBunE** [OpenBazaar/OpenBazaar-Client#1422]
Brief Description: : port forwarding was setup to make store accessible through a router.
a message gets sent to the shop and is successfully delivered instantly. not exactly sure why the store/shop data is missing

Operating System (OS and version):  win7 64x
OpenBazaar version (shown on `About OpenBazaar` page in menu):  1.1.3

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
always

Steps to reproduce:
1. start OB 
2. try to visit shop from another network (machine)
3. shop loads but with no data (about,follow,followers,store items)
4. updates have been made from v 1.1.1 > 1.1.3 without deleting old files

**Comment by jjeffryes** [comment]
This may be a problem with the other node you're trying to reach, or with your router setup. 

If you're seeing this problem with all other nodes (stores), post what's happening in the installation-issues channel in our Slack. 

https://openbazaar-slackin-drwasho.herokuapp.com/
