### ISSUE TITLE
If safely possible allow user-formated content on About section of Profile

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#143]
![image](https://cloud.githubusercontent.com/assets/45482/10921044/63c021a6-8241-11e5-926c-d3c16f6b6fc4.png)

**Comment by drwasho** [comment]
Markdown support would be awesome.

**Comment by drwasho** [comment]
This will be really important. It's not a `showstopper` issue, but it is a higher than low priority :smile:

I'd prefer markdown here, but if we just did `html` for the time being that would be ok too. In either case, having a minimized formatting guide would be something to put on your list @morebrownies

**Comment by drwasho** [comment]
Bumped up the priority on this... @jjeffryes can you please farm out to someone else.

**Comment by morebrownies** [comment]
I'll take a stab at this one later this week.

**Comment by jjeffryes** [comment]
Add the same html sanitizer used in chat to both the user page when it displays the about text, and to the settings where you enter new about text. That way they don't enter invalid text, and users are also protected from someone with their own client putting in malicious text.

**Comment by morebrownies** [comment]
Completed in misc4
