### ISSUE TITLE
Don't show 0 followers when loading the follower list

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1439]
See the screenshot for @openbazaar. Showing "0 followers" is wrong.

![screen shot 2016-04-23 at 20 17 46](https://cloud.githubusercontent.com/assets/731743/14763554/a24c6dcc-0990-11e6-9b4d-033272ff251c.png)

**Comment by jjeffryes** [comment]
This was resolved recently.
