### ISSUE TITLE
Delayed load of listings

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1443]
**Overview**
Listings fail to load when navigating from Home to Discover under certain conditions. Tested on the latest version of the client and server; Windows 10.

**Steps to replicate**
- Select 'Personalised' in the Discover page
- Click 'My Page'
- Click the 'Discover' icon

Most times the page will hang, failing to load listings.

**Comment by jjeffryes** [comment]
I can't replicate this on my Windows install. Has anyone else seen this issue?

**Comment by drwasho** [comment]
Seems to not be a problem anymore.
