### ISSUE TITLE
Show an indicator that items can be shipped to one of your addresses.

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1444]
## Overview

A visual indicator on listings to determine whether the item can or can't ship to your location.
## Requirements
- [ ] Items in Discover and Store page have a marking that they can be shipped to the user's location (or not)
- [ ] The match can be with the country of any of the user's saved addresses
## Implementation

@morebrownies will need to pick out an icon/graphic to show on the listing
@jjeffryes will wire it up on the front-end

**Comment by jjeffryes** [comment]
This has been completed.
