### ISSUE TITLE
Apply Rob's json sanitization fix to get listings, get moderators, etc.

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1445]
## Overview

Should harden the application against shenanigan use of the APIs.
## Requirements

@rmisio is already working on this
@jjeffryes to review

**Comment by jjeffryes** [comment]
Issue moved to [OpenBazaar/OpenBazaar-Server #374](https://github.com/OpenBazaar/OpenBazaar-Server/issues/374) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by jjeffryes** [comment]
I moved this to the server repo, since this is a server only task.
