### ISSUE TITLE
UI issue: overlay background gradient is covering side chat panel when an order modal is open

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1450]
This is preventing users to multi-task between general chat and an order discussion. 

![screenshot 2016-04-26 12 50 39](https://cloud.githubusercontent.com/assets/13066886/14832175/b2ffac5a-0bad-11e6-8b25-31754d3faaa5.png)

**Comment by rmisio** [comment]
this is fixed.
