### ISSUE TITLE
Blue buttons appear on transaction details loading screen

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1452]
- Operating System (OS and version): Ubuntu 14.04
- OpenBazaar version: 1.1.4
- Reproducible: Always 
- Steps to reproduce: Click on transaction details
- Observed Behavior: Blue buttons appear on top of the loading screen
- Expected Behavior: [~~Those buttons must not appear~~](https://github.com/OpenBazaar/OpenBazaar-Client/issues/1452#issuecomment-215212884) The buttons should use current color scheme

![](https://static.md/4b551d12a62cbe80dbeea6bd3b818180.png)

**Comment by morebrownies** [comment]
The buttons should use the theme color.

Also what does Load Index do? We've never used the term "Index" anywhere else in the app.

**Comment by jjeffryes** [comment]
This is not a bug, those buttons should appear. They are useful if you get stuck on the loading screen, which happens in rare cases, and requires restarting the app if you don't have these buttons.

The loadIndex button looks like it isn't loading a translated phrase. We can change it in the language file to "Go To Discover".

They should have the custom color classes added to them too.

On my TODO list is to add a timer so they only show up if you're on the loading screen for more than 3 seconds.

**Comment by ghost** [comment]
>  those buttons should appear. They are useful if you get stuck on the loading screen

:thumbsup:

**Comment by morebrownies** [comment]
Similar to #1449 we should not be blocking window controls or the main header. If this overlay didn't block the main header bar the standard Discover button would still be available and also the reload button. So maybe we can simplify this?

**Comment by jjeffryes** [comment]
That's a different reload button, it only resends the same address.
