### ISSUE TITLE
Display contract type in store

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#146]
Even though I have a physical, digital, and service contract in my store, they all look the same. I think we need to show these 3 different types in the listing view (for the homepage or store page) and when you open a listing and see the description.

**Comment by morebrownies** [comment]
I added this to the contract detail screen, should be merged at some point today. I'll need to figure out a spot to work it into the main screen.

**Comment by drwasho** [comment]
Awesome @morebrownies

**Comment by drwasho** [comment]
@morebrownies can you put this somewhere near the top of your list of things to think about? In the individual listing page we have that awesome icon, but we don't have anything on the 'Listings' page in Discovery. Should we even do it etc.

Should we create a new issue for showing differences in the Discover page.

**Comment by drwasho** [comment]
I'll create a separate issue for showing contract type in Listings.
