### ISSUE TITLE
"Follow" status is oftentimes incorrectly noted in the discover listings/pages

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Client#1464]
This is a problem that has existed for a long time:

When you click on discover, and sort by listings or pages, the user or item oftentimes has the incorrect follow status. This is easy verified by clicking on the user's page, where the follow status is correctly noted. 

This behavior is somewhat random. Sometimes if you click refresh, the follow status appears correctly. 

Client: OSX

**Comment by jjeffryes** [comment]
Issue moved to [OpenBazaar/OpenBazaar-Server #389](https://github.com/OpenBazaar/OpenBazaar-Server/issues/389) via [**ZenHub.io**](https://www.zenhub.io/)
