### ISSUE TITLE
"Add as moderator" and "Add moderators by GUID" both do not work

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Client#1469]
- When visiting a page and clicking on the button "Add as moderator", the moderator is not added to the list of moderators in the client settings.
- When manually entering the GUID of the moderator (or handle) into the field "Add moderators by GUID" and clicking save, the moderator does not appear in the list of approved moderators.

I am using the most up-to-date version of the server and client on OSX from github, and note that this problem has existed for some time now.

**Comment by Dekker3D** [comment]
I've experienced the same issue while creating that "Add as moderator" button. It seems that there are specific people for whom it does not work, and for most it does work. Can you tell us who you're trying to add as moderators?

**Comment by lunokhod** [comment]
You can try my account. I tried to do this from another account I'm running and it didn't work. 

51df06a21ea821b337c85388bdd786757818e7f0

**Comment by mariodian** [comment]
I tried to add you, the data was sent, server returned OK, but can't see you in my settings. It seems like an issue on the server/API side.

**Comment by lunokhod** [comment]
I am running the latest version of the server, so I'll open an issue there. Thanks for confirming the problem.

**Comment by lunokhod** [comment]
This problem mysteriously resolved itself, for the time being. I will re-open the issue if it reappears.

**Comment by danteweyl** [comment]
@lunokhod I have this problem too, and it's not solved.
Try adding me and see if it works: 403e140c2c74aab8bdbf5ea9a2ba426bb12a2fd5
Can you reopen this issue?
