### ISSUE TITLE
I can't join transifex translation team. Sent request 2 times, waited 2 days

### ISSUE THREAD

**Issue by Squirrel2020** [OpenBazaar/OpenBazaar-Client#1470]
Tried to join at https://www.transifex.com/ob1/openbazaar/ I can't translate on GitHub as well, my Russian proof-reading are being not included and lost so many times

Tried to login to Transifex from GitHub auth icon, as Squirrel2020

**Comment by jjeffryes** [comment]
We're at Consensus 2016 right now, I'll catch up with Transifex as soon as I'm back at a computer.

**Comment by Squirrel2020** [comment]
I am already translating the project at Transifex, thanks for approving, but it says that trial is expired, I afraid that all edits might get lost because of Transifex expiration (I am myself okay with GitHub, but a little bit tired of rejected translations). Concerning your comment saying "You don't have to do PR" (PR = proof-reading?).

I need access to proof-reading, because its unpleasant when I can't fix my errors (and I allow myself making a lots of errors at the 1st translation - because I know that I can't be perfect without seeing and comparing what is done to the interface - it takes some versions). Also when I get my translations rejected on a regular basis, I can't normally use OpenBazaar myself with buttons like these http://imgur.com/1riIzlg :)

I want to make perfect Russian right now, not because there is something special with Russian language, its because Russian is the gateway for 10 other unpopular languages from CIS-countries (I am in the process of building platform for voluntary translators for this unpopular 10 languages which would translate OB to millions of people from that poor countries which is my primary motivation)

**Comment by jjeffryes** [comment]
Ignore the message on Transifex about the trial being expired, it doesn't affect anything. 

You can proof-read without submitting a PR, can't you? Just change the code locally.

If you want to submit PRs, that's fine, as long as the same changes are made on Transifex. When Transifex gets out of sync that causes changes to be overwritten.

Regarding the button issue, we're aware of it, we haven't created a solution yet.

**Comment by Squirrel2020** [comment]
Regarding button issue it doesn't needs solution, it needs better proof-read (I will shorten it in Russian and I hope that all the other translators will do the same without losing the meaning of the buttons) Long words & buttons by itself are ugly, I believe they should have fixed size.

> You can proof-read without submitting a PR, can't you?

I don't really understand what PR means in this context.

Yes I can submit it on Transifex, but I don't understand what is "changing the code locally".

**Comment by jjeffryes** [comment]
PR = pull request, that's when you send your code to GitHub to be merged into the master branch.

Changing the code locally is when you change the code on your computer before you submit the Pull Request. You should be able to proof read it on your own computer.

Or do you mean you want other Russian readers to be able to proof read it?
