### ISSUE TITLE
No new order message notification

### ISSUE THREAD

**Issue by mariodian** [OpenBazaar/OpenBazaar-Client#1474]
Everytime I get a new message for orders, I don't see any notification about it.

Operating System (OS and version): latest OSX 
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.4 (from github)
Hardware: macbook pro 13" late 2011

Reproducible: Always

Steps to reproduce:
1. Create order
2. Send order message

Observed Behavior:
I hear the notification sound and can read the new message in order details, but can't see the notification in the notification menu. I can't see notification badges too.

Expected Behavior:
I should get a notification every time someone sends me an order message.

Additional info (links, images, etc go here):
![screen shot 2016-05-03 at 11 13 28 pm](https://cloud.githubusercontent.com/assets/3636406/14988252/ab16185c-1185-11e6-8df6-e3c3688c8314.png)

**Comment by jjeffryes** [comment]
This is being tracked in #372
