### ISSUE TITLE
Notification of Discussion taking place in Order Details

### ISSUE THREAD

**Issue by LiteBit** [OpenBazaar/OpenBazaar-Client#1475]
Brief Description: There is no notification of dialog happening within the Order Details box on either the Notifications or Messages. The only time I know a buyer is discussing something within each Order Detail box is by opening each order detail, going to the discussion tab and seeing if they've responded. 

With this being the only way to communicate with offline clients It'd be great to see notification counts in the Notification button when someone responds specific to an order.

**Comment by mariodian** [comment]
I've already addressed this issue yesterday #1474

It was working the supposed way but it's buggy now for some reason.

**Comment by LiteBit** [comment]
Ok. Sorry, i did a search but didnt see anything.

**Comment by jjeffryes** [comment]
This is being tracked in #372
