### ISSUE TITLE
Language Search

### ISSUE THREAD

**Issue by mpatc** [OpenBazaar/OpenBazaar-Client#1483]
Brief Description: Search for some languages that don't use the Roman alphabet do not show up in serach

Operating System (OS and version): Osx el capitan
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.4
Hardware: Macbook Pro Retina 13"

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Go to settings, after initialization in English 
2. Select the Languages drop down
3. Start typing. Doesn't find Chinese, Korean or Ukrainian, but can find Japanese

Observed Behavior: Doesn't find any language when one types in Ko, Ch, Uk,

Expected Behavior: It finds the language.

Additional info (links, images, etc go here):

**Comment by rmisio** [comment]
this is fixed.
