### ISSUE TITLE
Shipping is displaying for digital items and services

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#150]
<img width="623" alt="screenshot 2015-11-04 09 49 48" src="https://cloud.githubusercontent.com/assets/13066886/10943280/6b9fa26e-82d9-11e5-9d53-e38467fd3f2f.png">

**Comment by jjeffryes** [comment]
Processing time is a required field for all contracts. A digital product or a service can still have a processing time.
