### ISSUE TITLE
Important commit not included in tag

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1513]
[This](https://static.md/7db1ec3ba9989c40c58217b60a362f1e.png) commit https://github.com/OpenBazaar/OpenBazaar-Client/commit/01beedd1a9b1bc5ae20cd2f160816b44d132b449 is not included in v1.1.5 https://github.com/OpenBazaar/OpenBazaar-Client/blob/v1.1.5/package.json#L3 (see the old version)

**Comment by hoffmabc** [comment]
I'll be updating binaries but the only commit was a version tag bump which was included. Same source as tag.
