### ISSUE TITLE
Address settings: Do not require state/province/region field, and add additional lines for street

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Client#1514]
In the current client, I can not properly add my address.

First, in order to save the address, I am required to fill out all fields. However, where I live, it is not necessary to specify a "state/province/region". Leaving this blank gives me the error "Data could not be saved. Some fields are missing or incorrect."

Second, with my address, it is necessary to have an additional line that specifies things like the apartment number, and for deliveries, the code for entering the building. In its present form, this can only be specified by commas within the street field.

**Comment by jjeffryes** [comment]
Issues with the flexibility of addresses are being tracked under #1263

**Comment by jjeffryes** [comment]
We will be revising the address system in the near future, and will include the kind of flexibility you mentioned.
