### ISSUE TITLE
Server Maintence Windows loose sync.

### ISSUE THREAD

**Issue by Git909Monk** [OpenBazaar/OpenBazaar-Client#1516]
Brief Description:
When switching/editing the server list the window will sometimes not redisplay the edit server settings part. Instead the server selection windows is displayed at the bottom. See attached.

Operating System (OS and version): Ubuntu  16.04
OpenBazaar version (shown on `About OpenBazaar` page in menu):  1.1.5
Hardware:  virtualbox

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Open server configurations
2. Switch between various servers, randomly selecting edit.
3. Get the situation in the screencap

Observed Behavior:
Expected Behavior:
Additional info (links, images, etc go here):
Attached screen shot.
![client-servermaintenance-bug](https://cloud.githubusercontent.com/assets/17788096/15224227/245f5c84-1846-11e6-907f-fe09ae918e89.png)

**Comment by jjeffryes** [comment]
@rmisio can you take a look at this?

**Comment by rmisio** [comment]
no doubt.

**Comment by jjeffryes** [comment]
This has been fixed.
