### ISSUE TITLE
What causes the spinner to display each time I view one of my contracts?

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#152]
Isn't this data already local? Could it be served up instantly? Seems like it takes a few seconds to display each one of contracts every time I view it and I wonder if this is necessary.

<img width="456" alt="screenshot 2015-11-04 09 52 28" src="https://cloud.githubusercontent.com/assets/13066886/10943374/c5e4fb0c-82d9-11e5-8200-1fa9726bb134.png">

**Comment by jjeffryes** [comment]
Pulling data from the local server isn't instant.

**Comment by morebrownies** [comment]
Could caching help? The experience just feels a bit off. I first see a giant spinner that overtakes the entire screen and then the smaller spinner displays and it takes a few seconds to render. 

Clicking followers or following on my page loads instantly, wondering if it could work the same for contracts.

**Comment by jjeffryes** [comment]
The followers, following, about and store all load when the page loads, since each of those is a single call to the server. Individual contracts don't load until someone clicks on one.

If a store had a lot of contracts, loading all of them when the page loads could take a while, since each one is a separate call to the server, especially if you're looking at someone else's store.

**Comment by cpacia** [comment]
I would agree with Mike, I feel like spinners should only show if it's going to take a while. 1 or 2 seconds to load something doesn't seem like the place to use a spinner.

**Comment by jjeffryes** [comment]
How do you tell how long it's going to take before you show the spinner?

We could delay showing the spinner, but it would seem weird to show nothing, wait, and then show the spinner.

**Comment by morebrownies** [comment]
I think a spinner should still display if it's fetching content, but seeing two different types of spinners and having to wait to load something that I looked at a few seconds ago seems like there is some room for optimization.

**Comment by drwasho** [comment]
Status @morebrownies ?

**Comment by drwasho** [comment]
Just gonna say this is fixed.
