### ISSUE TITLE
Server set up Window seems supersized

### ISSUE THREAD

**Issue by Git909Monk** [OpenBazaar/OpenBazaar-Client#1525]
Brief Description:  The server set up window seems larger than normal. This causes issues with not being able to see the Save button at the bottom since one can not 'scroll' to them.

Operating System (OS and version):  Ubuntu 16.04
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware:  VirtualBox

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce):  Always

Steps to reproduce:
1. Start the client in a 800x600 window
2. cringe
3. ctrl-w

Observed Behavior:
I haven't compared the size to the window once initial set up is complete but it seems larger.
Button is off window, can't scroll to it.

Expected Behavior:
I need my button!

Additional info (links, images, etc go here):
See below.

![supersizedserverconfig](https://cloud.githubusercontent.com/assets/17788096/15256076/c4830e00-190d-11e6-9c51-86daa05391b3.png)

**Comment by rmisio** [comment]
The minimum size of our app is 1024 X 700, so it's not going to work well if you're limited to 800 X 600. Can you configure your VirtualBox so that the window can be enlarged?

FWIW, the server set-up modal is the same size it's always been and does fit within the app's standard size.

**Comment by Git909Monk** [comment]
I had just noticed it seemed bigger, probably me. Thanks for the size info. I was looking in to a kiosk environment. But there is kinda a lot of padding in that window you must admit...

**Comment by jjeffryes** [comment]
I don't think we're going to reduce the minimum size of the app in version 1, we'll probably add a more responsive design for v2.
