### ISSUE TITLE
Weird black state achieved through steps.

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#1528]
![screen shot 2016-05-13 at 21 14 45](https://cloud.githubusercontent.com/assets/4035854/15260638/d745510a-194f-11e6-8204-fdcd4fd54d5c.png)

To get it like this, start a server that has never been set up using a client. Visit that server's guid with your node. Then shut down your node's server. Now you are in this state.

**Comment by jjeffryes** [comment]
Do you have an example guid of a server that has never been set up using a client?

**Comment by dsmurrell** [comment]
try this guid: 035975a346b17666a09c08b8972453fd3e64b85a

please let me know when you are done with it... I'm using it for testing something and I need to set it up again (I just recreated it) for it to work with my testing.

practically, I'm not sure if you can get hold of guids from nodes that are never set up... I print out mine so I can visit it. Is it available through discover or hidden if it's not set up? maybe this is a non-problem.

**Comment by jjeffryes** [comment]
I'm done with it.

It looks like new nodes are getting all their colors assigned as 0 instead of the defaults.

**Comment by jjeffryes** [comment]
Issue moved to [OpenBazaar/OpenBazaar-Server #402](https://github.com/OpenBazaar/OpenBazaar-Server/issues/402) via [**ZenHub.io**](https://www.zenhub.io/)
