### ISSUE TITLE
Customize Profile from Menu does not go to the feature

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#153]
Self-explanatory.

**Comment by jjeffryes** [comment]
Do we still want this in the menu? Or should you just go to your page and then click the customize button?

**Comment by morebrownies** [comment]
Having it in two places is better than one

**Comment by drwasho** [comment]
![image](https://cloud.githubusercontent.com/assets/3887694/10953824/cb49d9d4-8395-11e5-8404-caef44354de8.png)

Color customization isn't saving either.

**Comment by drwasho** [comment]
My issue is long resolved. Original issue is still outstanding. Ping @jjeffryes 

Labeled this as `showstopper` as we really can't have an option that goes nowhere. Personally I'm happy to either delete it from the menu, as I think it's only something we should see in the store page, but that's just like my opinion man...

**Comment by morebrownies** [comment]
@jjeffryes fixed this.
