### ISSUE TITLE
Translation of currencies has too many duplicated strings

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1530]
This is a problem about #1503

There should not be duplicated translation strings for the currencies that are used in more than one country (like United States Dolar or Euro).

**Comment by rmisio** [comment]
yeah, good call. We could probably just break the currencies out into a separate object within the translation files. The mapping between a country and its currency is done outside of the translation files, in countriesMd.js.

**Comment by ghost** [comment]
Yes, that would be the best approach.

**Comment by jjeffryes** [comment]
Agreed.

**Comment by rmisio** [comment]
this is fixed.
