### ISSUE TITLE
Hover over Close displays a message that is not clear

### ISSUE THREAD

**Issue by sgornick** [OpenBazaar/OpenBazaar-Client#1534]
When I hover over the red X to close, a hover message reads: ""Close (Your page will go offline)".

But my page stays accessible by others even if I close the client.   Is this message wrong?   Is that describing that "my page" About page will go offline (where other's can't retrieve it?)   Because that's not happening.

If instead this is just suppose to mean that my client will close, and I'll no longer know about new messages, orders, etc., ... then that message is misleading at best.  My page doesn't go offline, but the OpenBazaar client will close

OpenBazaar-Client v1.1.5 
Reproducible: Always

Steps to reproduce:
1. Hover mouse over the red X to close,

Observed Behavior:
Hover message displayed: "Close (Your page will go offline)" 
My About page and store is still accessible by others.

Expected Behavior:
Hover message displayed: "Close (OpenBazaar client will end)"  [Or something more clear.]

**Comment by jjeffryes** [comment]
Did you install using the installer, or through github?

For users that installed with the installer, their node does go offline when they close the client.

**Comment by sgornick** [comment]
> For users that installed with the installer, their node does go offline when they close the client.

Oh, I didn't know that. 

So the client installed using the installer shuts down the server when the client is closed?  So this is something that the client is able to know (and can provide a hover that is message consistent with the subsequent behavior).

[Edit: And to address your question, I installed both the client and server independently, using the tarball, for Linux.]

**Comment by jjeffryes** [comment]
The client doesn't know if it was installed with the installer or not. But for the majority of users, that will be the case.

**Comment by rmisio** [comment]
It's not super well-known, but we do actually have that info from main.js:

```
if(fs.existsSync(__dirname + path.sep + ".." + path.sep + "OpenBazaar-Server" + path.sep + daemon)) {
  global.launched_from_installer = launched_from_installer = true;
}
```

So... it would be relatively simple to customize the close message.

**Comment by jjeffryes** [comment]
This was completed
