### ISSUE TITLE
In Discover, add a button to go back to the top of the page easily.

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1536]
**Description**

Scrolling for a while leaves you pretty far down the page and requires a lot of scrolling to get back to the top. We should make it easier for the user by conditionally displaying a "Back to top" button when they scroll past a certain point.

**Requirements**
- [ ] Display a back to top button after the user scrolls beyond the default viewport. (#1)
- [ ] If the user scrolls back to the top or clicks "Back to top" hide the "Back to top" button. (#2)
- [ ] Also put button on store page.
- [ ] Only show button after the user scrolls far enough the top controls aren't visible (roughly one flick of the scroll wheel).
- [ ] Cool fade in effect.

**Comment by rmisio** [comment]
i got this one.
