### ISSUE TITLE
Notifications for chat messages in Order Details - Discussion tabs

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1538]
## Overview

**Messages sent via the Discussion tab in the `Order Details` of an order do not show a message notification either in the notification tray, or on the order page.**
## Prototype

https://invis.io/WD72RPU5U#/153344523_Openbazaar-Transaction-Notifications-Discover
## Requirements
- [x] As a buyer or seller, when a new transaction Discussion message comes in, I should receive a notification in the notification tray. **(1)**
- [x] As a buyer or seller, when a new Discussion message comes in, I should see an indicator next to the appropriate order in the Transaction section. **(2)**
- [x] Should see an indicator next to the Discussion tab in the Order Modal. **(3)**
- [x] As a buyer or seller, when I view the notification tray, the New discussion notification should be marked as read. **(4)**
- [x] As a buyer or seller, when I open the Order Modal and click the Discussion tab, the indicator in **(2)** and **(3)** should go away. **(5)**
- [x] As a buyer or seller, when a new Discussion message comes in, the order line item in my transaction list should display at the top of the list. (sort by orders that need my attention) **(6)**

![0](https://trello-attachments.s3.amazonaws.com/5714881c94c235e9bc4cb591/2400x1442/1c04b847a4c67f620ea11168c77b55ff/openbazaar-transaction-notifications%402x.png)

Lots of coordination by @cpacia and @jjeffryes 

Server PR for this issue: https://github.com/OpenBazaar/OpenBazaar-Server/pull/378

Related Server Issue: https://github.com/OpenBazaar/OpenBazaar-Server/issues/372

**Comment by ghost** [comment]
:+1: 

A vendor wrote me a few days messages in order, I received notifications in main chat but there were no new messages, I thought there was a bug with notifications, then he wrote me in main chat to look in order chat.
