### ISSUE TITLE
Chat window menu is always open

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1540]
![chat window](https://cloud.githubusercontent.com/assets/10789865/15345122/ca240558-1c82-11e6-9f92-95293c0469b8.png)

Chat window menu is always open, even when user clicks outside of it, for instance, on text input "Enter message...". It is covering chat messages. The only way to close it is by clicking on the menu button again.

OB 1.1.5 w7 64bits

**Comment by rmisio** [comment]
I've got this one.

**Comment by jjeffryes** [comment]
This was fixed.
