### ISSUE TITLE
Disable drag and drop on avatar

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1559]
Some avatar (on chat and order details windows) have drag and drop enabled. When dragged, they show, for instance, a link like the following:

_file:///C:\Users\User\AppData\Local\OpenBazaar\app-1.1.5\resources\app.asar\index.html - userPage/a06aa22a38f0e62221ab74464c311bd88305f88c/store_

This link is useless outside the software and should be disabled.

OB v1.1.5 win 7 64 bits

**Comment by mariodian** [comment]
I'll fix it
