### ISSUE TITLE
Chat bugs

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1563]
Latest client code on Windows. Bugs observed after receiving a normal chat message from another node.

**Part 1**
![image](https://cloud.githubusercontent.com/assets/3887694/15462559/d8a0a2c0-2106-11e6-8b67-3beb1a673a2f.png)

**Part 2**
![image](https://cloud.githubusercontent.com/assets/3887694/15462573/f2416e08-2106-11e6-9352-5574239aebfd.png)

**Comment by jjeffryes** [comment]
I can't replicate these issues.

**Comment by drwasho** [comment]
Fixed ages ago.
