### ISSUE TITLE
The title bar text should inherit the text color of the theme

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1564]
Currently it's always white, which makes it invisible or very difficult to read in some cases. I'm referring to the "OpenBazaar — @vintagefashion" text.

<img width="1201" alt="screenshot 2016-05-23 06 55 57" src="https://cloud.githubusercontent.com/assets/13066886/15475553/8848166a-20bf-11e6-80ff-5efc484b60d7.png">

**Comment by mariodian** [comment]
I'll fix it
