### ISSUE TITLE
Notification badge gets cut off

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1565]
<img width="86" alt="screenshot 2016-05-23 08 24 19" src="https://cloud.githubusercontent.com/assets/13066886/15475611/c9090bd2-20bf-11e6-8af0-78d7cb0dde73.png">

**Comment by mariodian** [comment]
I'll fix it

**Comment by mariodian** [comment]
There's a problem with how #appBar and #pageNav are positioned and the way notifications and the menu get hidden. You can't simply lower the z-index for #appBar:

![screen shot 2016-05-24 at 11 11 56 am](https://cloud.githubusercontent.com/assets/3636406/15491329/ed4b936a-21a1-11e6-92e6-c24ae088ed9f.png)

I don't feel like rewriting behavior of .popMenu-notifications and .popMenu-navBar, so I came up with the following solution.

`#pageNav { clip: rect(0px 5000px 5000px 0px); }` will make sure hidden notifications and the menu isn't visible from top. It acts in a similar way as `overflow: hidden`, but in this particular case hides the overflow only from top.

@jjeffryes @rmisio what do you think?

**Comment by rmisio** [comment]
Wouldn't that cut off the badge too?

I think the problem is that the top padding was removed from `#pageNav .navBar.bar`. If 1px is put back in, the badge is no longer cut off.

**Comment by mariodian** [comment]
@rmisio oh of course, you're right. I was focusing on hiding notifications too much and totally ignored the badge.

Adding `padding-top: 1px` makes notifications and the menu visible from the top. However changing height of .bar to 51px (without the padding) fixes it. Not sure if we want to add the extra height though? @morebrownies

**Comment by rmisio** [comment]
Changing the height is fine, but then I think you'd have to adjust (by a pixel) all the modal and container positions that are in relation to the nav bar.

Padding doesn't seem to affect the height, so it would save you having to do those updates. But, up to you.

**Comment by morebrownies** [comment]
If we need to add extra height to get the badge to not be cut off then that is completely fine with me. We just want to avoid the header becoming overly bulky, which doesn't sound like it will be the case.

**Comment by mariodian** [comment]
#1575 also fixes this issue

![screen shot 2016-05-25 at 1 57 29 pm](https://cloud.githubusercontent.com/assets/3636406/15529542/b80466c0-2280-11e6-8c80-bfa4221a65c2.png)

**Comment by jjeffryes** [comment]
This seems too tight to me, I think Mike's original suggestion of 7px, or 8px to match the space between the edge of the window and the left-most and right-most buttons would be better.

**Comment by jjeffryes** [comment]
@morebrownies what do you think?

**Comment by morebrownies** [comment]
I'll take a look in a bit, trying to wrap something up.
