### ISSUE TITLE
Too much spacing underneath the header controls

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1566]
Currently there is 14px of vertical spacing underneath the header controls and address bar. This can likely be cut in half to 7px or even 5px to free up more vertical space.

<img width="668" alt="screenshot 2016-05-23 08 26 52" src="https://cloud.githubusercontent.com/assets/13066886/15475722/4d6b2432-20c0-11e6-85df-7621e63bbba6.png">

**Comment by mariodian** [comment]
I'll fix it

**Comment by rmisio** [comment]
@mariodian please keep in mind that if we are shortening that nav bar, a bunch of things that are positioned in relation to it will need to be adjusted. Currently, these things are positioned with a top of 78px, so if you search for '78px', you'll find them. Basically, anything with that value that is related to modals, as well as #obContainer and #sideBar should be adjusted.

**Comment by mariodian** [comment]
@rmisio yeah I know, that's why I brought up the "sass issue" on the slack. Thanks.
