### ISSUE TITLE
There's a bar displaying in the bottom of the cover photo section on a user page

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1567]
The cover photo should be sitting flush against the tab bar.

<img width="1043" alt="screenshot 2016-05-23 08 29 24" src="https://cloud.githubusercontent.com/assets/13066886/15475804/b69edc64-20c0-11e6-8e7f-43609ae5abcb.png">

**Comment by mariodian** [comment]
I'll fix it
