### ISSUE TITLE
Address Bar Autocomplete

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1569]
- keep a record in localstorage of tags and handles the user has visited.
- when a user is entered text in the address bar, show autocomplete suggestions based on the saved tags and handles. 
- while the autocomplete tray is visible, the rest of the window should be covered in an overlay. Only the autocomplete tray, navbar, and title bar should accept user interaction.
- the down arrow should highlight the first suggestion in the autocomplete tray. After that, the up and down arrows should change the selected suggestion. When the first (top) suggestion is highlighted, the up arrow key should return focus to the address bar
- the enter key should replace the address bar text with the suggestion if a suggestion is highlighted when the enter key even occurs
- only show the autocomplete tray when suggestions are found

An existing library can be used, if one can be found that meets the requirements, such as https://goodies.pixabay.com/javascript/auto-complete/demo.html

Any external library used must have the MIT Open Source license, or be compatible with it.

![image](https://cloud.githubusercontent.com/assets/1584275/15476408/bf5d1ff2-20dc-11e6-98fa-3ec60401b960.png)

![image](https://cloud.githubusercontent.com/assets/1584275/15476420/c84ae93c-20dc-11e6-9f98-c0ccd59ce281.png)

**Comment by mariodian** [comment]
I'll take it if no one is working on it?

**Comment by morebrownies** [comment]
It's all yours @mariodian 👍

**Comment by mariodian** [comment]
Please review my PR.

**Comment by jjeffryes** [comment]
This was completed.
