### ISSUE TITLE
Cache Views in DOM

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1570]
- when the Discover and UserPage views are navigated away from, instead of removing the views, keep them in memory for a limited time
- a method of saving UserPage views by ID will need to be added, so more than one can be held in memory
- if the Discover or UserPage view is loaded again, and the limited time has not expired, show the existing view instead of loading data and re-rendering it (for the UserPage, only if the ID is the same)
- this is an experimental issue, it should be prototyped first to see if this approach is feasible

**Comment by rmisio** [comment]
i'm on it.
