### ISSUE TITLE
Manually Backup Database

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1574]
- the settings/advanced section should have a button to backup the database
- when the button is pressed, a password field should be shown. This password is used to encrypt the database. It will be sent to the backup API.
- when the backup API call returns with the backup file, a file save dialog should appear, so the user can save the database to whatever location they want to
- the server will be saving the backup in a standard location, and then giving a link to that file to the client, so it can be saved somewhere else (the server may be remote or not have write access to that location, which requires the client to pass the file to the new location)
- the backup file will have a timestamp on the filename, set by the server
- it would be ideal to pre-set the save path to the last saved location, investigate if that can be done with the OS save file system.

Related Server Issue: https://github.com/OpenBazaar/OpenBazaar-Server/issues/417

**Comment by rmisio** [comment]
@morebrownies Is a design coming for this?

**Comment by jjeffryes** [comment]
We've decided not to add this feature.
