### ISSUE TITLE
Make Pre-Commit Hooks for ES-Lint Work for All Envirionments

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1578]
Edit: Apparently the hooks do fire on commit for some environments. Find out why, and fix the issues preventing them from working in some cases.

**Comment by hoffmabc** [comment]
Now to just abide by them and not just -n through them.

**Comment by jjeffryes** [comment]
Edit: Apparently the hooks do fire on commit for some environments. Find out why, and fix the issues preventing them from working in some cases.

**Comment by jjeffryes** [comment]
This was completed, pre-commit hooks for es-lint are working, and the full set of es-lint rules have been added.
