### ISSUE TITLE
Reject Poorly Formatted Messages

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1580]
When websocket nofications and messages are received, if they don't have the expected format don't show them.

**Comment by rmisio** [comment]
Why bubble gum patch this? If the server is sending poorly formed notifications, the bug should be on the server. (I think there's too many such instances in the client where we are doing such things.)

**Comment by jjeffryes** [comment]
We think some messages may be coming in from out of date or customized nodes with bad formatting.

@cpacia can this be handled on the server? I filed this issue when Wash and I were talking about the bug he saw so I wouldn't forget it, I can move it to the server repo.

**Comment by jjeffryes** [comment]
I haven't been able to reproduce this, and as far as I can tell, only the expected data is shown. How @drwasho saw this bug is a mystery.

**Comment by rmisio** [comment]
Mysterious things happen down under...
