### ISSUE TITLE
Add "Size" variable for product listings

### ISSUE THREAD

**Issue by LiteBit** [OpenBazaar/OpenBazaar-Client#1592]
Brief Description: Add a "Size" variable in the /Listing dialog when creating new product listings. Can be a text box where user can enter any size related word/s for the product. 

Examples: 
- 8oz Honey could have "8oz" in the size box
- small shirt could have "small" in the size box

From a coding perspective I imagine the same lines of code used for the SKU variable could be copied. 

Additional info (links, images, etc go here):
![capture](https://cloud.githubusercontent.com/assets/6236019/15596109/a6910a0c-2392-11e6-831b-a25ad9a12c75.JPG)

**Comment by jjeffryes** [comment]
How does size apply to listings that don't have a size, or to digital or service listings?

**Comment by LiteBit** [comment]
Size doesnt matter with some items, just like SKU. I think having 'optional' is appropriate and vendors can use as needed. 

Would be helpful for any perishable (food) item, any clothing item, accesories, electronics,

**Comment by jjeffryes** [comment]
SKU is a stock tracking field, which can be used for any listing, and is a requirement for larger sellers. 

I don't think we want to add a field to all contracts that can only be useful for some of them. Size could be easily described in the description field, which is where non-universal data should go. 

We do have an options feature that hasn't been implemented fully yet, that would allow each listing to have options that can be picked at the time of purchase, that's where things like size would go if a listing had more than one size. 

I'm going to close this issue and the related PRs. Thank you for the work you did, if you're interested in adding new features, look for issues that have been labeled as bugs or enhancements, those have been reviewed and fit with our current roadmap. Or anything labeled "Help Wanted." And don't hesitate to ask questions before working on something, here or in our Slack channel.
