### ISSUE TITLE
Inconsistency in listing capitalization of title

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#160]
On the store page (`not working`):

![image](https://cloud.githubusercontent.com/assets/3887694/10958612/d889f888-83bb-11e5-9b42-87d6d29efb99.png)

When you open a listing (`working`):

![image](https://cloud.githubusercontent.com/assets/3887694/10958605/bd6239c6-83bb-11e5-9a50-b27b6b9143cb.png)

**Comment by jjeffryes** [comment]
The data is saved exactly how you typed it. @morebrownies put in a CSS class that forces the capitalization to be like that. 

My suggestion is we should follow whatever capitalization the user put in, otherwise it looks like a bug.

**Comment by SamPatt** [comment]
Yes you definitely need that. ALL CAPS listings would be annoying but not as annoying as not being able to capitalize words that genuinely need it.

**Comment by morebrownies** [comment]
I wonder if the inconsistency is actually appropriate here? We could display the title exactly as entered on the contract detail page, but in discovery opt on the side of avoiding all caps listings from taking over. I don't have a strong opinion, more so just a thought.

**Comment by SamPatt** [comment]
I think people's listings should display in discovery as they display in their store, at least as much as possible.

**Comment by morebrownies** [comment]
Ok, works for me. If it starts to get out of control with all caps listings everywhere, we may want to find a way to normalize it in the future. Hopefully that isn't the case though.

**Comment by drwasho** [comment]
This hasn't been fixed yet; ping @morebrownies

**Comment by morebrownies** [comment]
Fix coming in my next branch

**Comment by morebrownies** [comment]
Fixed in #400

**Comment by morebrownies** [comment]
@drwasho please confirm this is fixed

**Comment by drwasho** [comment]
Fixed.
