### ISSUE TITLE
Header issue

### ISSUE THREAD

**Issue by mariodian** [OpenBazaar/OpenBazaar-Client#1620]
If you have visual effects disabled you get the slim header in the way. 

![screen shot 2016-05-28 at 1 47 26 pm](https://cloud.githubusercontent.com/assets/3636406/15625495/e80972b4-24da-11e6-846f-345a10fc57ad.png)

If you scroll down the header shows correctly. However if you scroll down with visual effects enabled you can see a little "blink" of the header above the app bar.

OSX, the latest pull (ff061f3), but I've spotted the issue earlier. Not sure which commit though.

Seems like my changes in #1575 got merged and then removed somehow.

**Comment by jjeffryes** [comment]
This was corrected in Master.

**Comment by mariodian** [comment]
@jjeffryes I don't think so. This is a screenshot from the freshly cloned repo:

![screen shot 2016-06-02 at 12 58 35 pm](https://cloud.githubusercontent.com/assets/3636406/15734399/e16c08b4-28c1-11e6-971e-ecaf6edc84e0.png)

**Comment by jjeffryes** [comment]
Here's the same screenshot on the current master:

![image](https://cloud.githubusercontent.com/assets/1584275/15748356/90ef1daa-28ac-11e6-94b9-b4724df8f45d.png)

**Comment by mariodian** [comment]
@jjeffryes you need to **disable visual effects** as mentioned in OP.

**Comment by jjeffryes** [comment]
Ah, ok. I'll fix it in my next PR.

**Comment by rmisio** [comment]
There's also a related issue where the app cannot be dragged by the app-bar when on the the user page, unless you're scrolled to the top. Haven't dug too deep into it, but it seems that even when the image is not visually covering the app-bar, it's still preventing it from being draggable.

**Comment by jjeffryes** [comment]
@rmisio that was something different, the modalHolder div had a no-drag property on it, and under the new structure it scrolls with the page when it's not visible.

It's fixed in https://github.com/OpenBazaar/OpenBazaar-Client/commit/33f75d56c58d5593804558be5273b50ad178bc3d

**Comment by mariodian** [comment]
Seems to be fixed, but the header's height is still too big (and it shouldn't be according to this issue #1566 which was fixed later, got merged and then removed somehow).
