### ISSUE TITLE
Error with required fields when creating a listing

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1622]
When creating a listing with all fields blank, only tags and description field are marked in red. Error message informs that only Tags field is required:

_Data could not be saved:_ 
_Some fields are missing or incorrect._
_\- Tags_

![check required](https://cloud.githubusercontent.com/assets/10789865/15629727/16539494-24f7-11e6-912e-fcec0cf930c3.png)

Then, if user fills tags field, error message informs other required fields, that now are marked in red:

_\- Title_
_\- Price_
_\- Description_
_\- Processing Time_

![check required2](https://cloud.githubusercontent.com/assets/10789865/15629738/441f40a8-24f7-11e6-8a5f-c305d282c778.png)

And if those fields are filled, then, error message informs the last required field, that now is NOT marked in red:

_\- images_

Other problem:
If left blank, "Ships To" field display on error message as "undefined".

**Expected Behavior:**
All required fields should be marked in red (including Images/Photos field) and error message should include all missing required fields at once, and on the correct order of appearance. "images" item on error message should be renamed to "Photos":

_Data could not be saved:_ 
_Some fields are missing or incorrect._

_\- Title_
_\- Price_
_\- Description_
_\- Processing Time_
_\- Ships To_
_\- Photos_
_\- Tags_

Operating System (OS and version): Win7 64 bits
OpenBazaar version: 1.1.5
Reproducible: Always

**Comment by ghost** [comment]
Another fix needed: on the "Photos" section, the message "_No photos added_" should appear below (and not under) the white circle with plus (+).

**Comment by ghost** [comment]
Another fix with the marking in red: all required items are marked only on the fields to be filled, except the "Tags" which is marked on the title (Tags) AND the field (place where user writes his tags). You can see this on the first screenshot.

**Comment by rmisio** [comment]
i got this one.
