### ISSUE TITLE
Search bar message issues

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1626]
![search bar message](https://cloud.githubusercontent.com/assets/10789865/15630219/99fc2464-2506-11e6-9e37-62c0db3f81a7.png)

Problem 1:
If currently number of loaded pages is the same as total number of followers or following, search bar message should be just "Search for a name".

Problem 2:
The message "Search for a name in your currently loaded followers (scroll to load more)." is being used both on "Following" and "Followers" tabs. I would suggest changing to: "Search for a name in your currently loaded pages (scroll to load more)".

**Comment by mariodian** [comment]
Fixed
