### ISSUE TITLE
Tooltip text runoff

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1630]
![image](https://cloud.githubusercontent.com/assets/3887694/15658643/3f2dacd0-2702-11e6-8ce2-5b3231ad932c.png)

**Comment by ghost** [comment]
This is a duplication of #1181

**Comment by drwasho** [comment]
@jjeffryes closing this issue as it's a duplicate. Thanks @rhcastilhos

**Comment by jjeffryes** [comment]
This is a separate issue from #1181, it was introduced when we removed the truncation from tooltips recently.

**Comment by jjeffryes** [comment]
I can't reproduce this, @drwasho can you make sure you're on the latest master and check again?
