### ISSUE TITLE
Styles incorrect and text not displaying clearly

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1636]
**Brief Description:** Styles incorrect and text not displaying clearly

**Operating System:** OSX 10.10.5 (14F1021)

**OpenBazaar version:** 57ab66bc3ca65c3b1ad69f806b241953a3a06c11

**Reproducible:** Always

**Steps to reproduce:**
1. Checkout master (or 57ab66bc3ca65c3b1ad69f806b241953a3a06c11 or after)
2. Start Client; notice styles are wrong
3. Open an order modal; notice text is wrong

**Screenshot:** http://content.screencast.com/users/TylerBSmith/folders/Jing/media/626e906f-866b-4896-8504-cfef3d2d2506/00000472.png

Normally the theme is a beautiful green palette not red/blue

I've determined the commit introducing the issue is 57ab66bc3ca65c3b1ad69f806b241953a3a06c11

**Comment by jjeffryes** [comment]
Thank you for catching this. It's been fixed in fe8c43f.
