### ISSUE TITLE
Add default expiration time to Create Listing page

### ISSUE THREAD

**Issue by unsystemizer** [OpenBazaar/OpenBazaar-Client#164]
If I pick (say) Dec 31, 2015 as my expiration date, the time could be set to 00:00 or 23:59.

Right now it's `--:--` so although I don't care what's in there as long as I don't have to enter anything, it is not possible to use `--:--`. If that was set to anything acceptable to the validator, it'd save time.

**Comment by drwasho** [comment]
For the love of God yes.

**Comment by drwasho** [comment]
Nice work.
