### ISSUE TITLE
It would be nice to be able to reorder the listings.

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#1642]
Maybe in a similar way to how you reorder images for listings.

I even tried to do this myself by looking into the database of the server but it's stored as a binary blob :( 

![screen shot 2016-06-02 at 11 38 47](https://cloud.githubusercontent.com/assets/4035854/15742424/b8f391f0-28b6-11e6-998e-c9895d257b8a.png)

Not much I can do there. 0 options. 

Do I have to delete all of them and start again if I want to reorder?

**Comment by morebrownies** [comment]
Agreed. More sorting flexibility is definitely needed.

**Comment by mariodian** [comment]
> Do I have to delete all of them and start again if I want to reorder?

The latest saved listing ends up at the end of the list. So you can just ctrl+s each listing in desired order for now.

When the feature mentioned in the OP is available, auto re-ordering on a listing update should be disabled.

**Comment by dsmurrell** [comment]
Ah thanks Mario... I can use this hack for now.

**Comment by jjeffryes** [comment]
The Pinned functionality in #1783 addresses this issue.
