### ISSUE TITLE
No word wrap in review text

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1656]
Review text doesn't wrap words correctly.

OB v1.1.5

![review2](https://cloud.githubusercontent.com/assets/10789865/15801651/509d9d2c-2a72-11e6-8a11-32838c0e1daf.png)

**Comment by lunokhod** [comment]
I confirm that this is an issue on OSX and that this is very important. Consider the difference in meaning between these two:

```
determining
```

and

```
deter
mining
```
