### ISSUE TITLE
Client opens between two monitors in Linux

### ISSUE THREAD

**Issue by Krisseck** [OpenBazaar/OpenBazaar-Client#1664]
Brief Description: When the client starts, it opens up between the two monitors in Linux.

Operating System (OS and version): Elementary OS Freya
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.6 
Hardware: Thinkpad E540

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Have Linux OS
2. Have atleast two monitors
3. Open OpenBazaar Client

Observed Behavior:
The client opens half in first monitor and half in second.

Expected Behavior:
Client opens centered on the first monitor.

Additional info (links, images, etc go here):
![screenshot from 2016-06-07 10 10 13](https://cloud.githubusercontent.com/assets/471887/15848898/2c4e19ba-2c98-11e6-8ceb-a5972d2ec510.png)

EDIT: Still present in 1.1.6

**Comment by hoffmabc** [comment]
This may be an electron issue. I think it just launches in the center of the whole display no matter what so it must not be smart enough to pick one display over the other. Will have to take a look.

**Comment by Krisseck** [comment]
Yeah, looks like it's rather an issue on Electron. I created an issue there, I'll close this :)
