### ISSUE TITLE
No sales visible in my transactions tab - list.min.js: 1 Uncaught Error

### ISSUE THREAD

**Issue by Timbo925** [OpenBazaar/OpenBazaar-Client#1667]
Brief Description: No sales visible in my transactions tab

Operating System (OS and version): VPS with latest pull, 1.1.6 clients on windows and mac
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Open sales tab

Observed Behavior: No sales are shown, only 

Expected Behavior: Show sales

Additional info (links, images, etc go here):
I updated today both on my mac and windows machine to version 1.1.6. Now it seems like I cant see my sales anymore. Going through the API works still fine to it doesn't seem like a server problem.

If I look in console on the client I get the following error: 
`list.min.js:1 Uncaught Error: The list need to have at list one item on init otherwise you'll have to add a template`

Also no call isn bing made to 'get_sales' while i do see `get_purchases` being called. Seems like the client is crashing at this point.

**Comment by Timbo925** [comment]
Rolling back to 1.1.5 on mac solved the issue and I can see everything again.

**Comment by hoffmabc** [comment]
@jjeffryes please check this one out.

**Comment by jjeffryes** [comment]
@Timbo925 can you post a screenshot of your transactions page with the sales tab active?

Also look at the button right below the tab labeled "Hide Unfunded". If it has a number in it, you have sales that have not been funded, which are now hidden by default. You can click that button to show them.

**Comment by Timbo925** [comment]
@jjeffryes Here you go http://imgur.com/a/bkMzF

The one showing the listings is on 1.1.5 OSX, without 1.1.6. and I have different stages between them if that maters (not funded/funded/shipped/completed/disputed/dispute closed) Seems like due to the error not all the api calls are being made.

**Comment by jjeffryes** [comment]
That error with List.js doesn't block any other code, I'm pretty sure it can't be causing this.

Can you post your server error log? If there is a server issue with the get_purchases call, it will block the get_sales call.

**Comment by jjeffryes** [comment]
One other thing, if you can give us the results of the get_purchases call, that might be useful too.

**Comment by Timbo925** [comment]
Ok this is weird. It didn't work so I decided to test the API call directly using postman (which worked). Then going back to the application it suddenly worked and my listings are showing. Guessing I forced something to change using postman to login and do the call. Can't seem to reproduce the problem now.

Using the API directly and in terminal form the client I get this:

```
[{
    "status": 0,
    "vendor": "@vintagefashion",
    "description": "Vintage-style basecall cap.<p><b>Item specifics</b></p><ul><li>Item Type:  Baseball Caps  </li><li>Pattern Type:  Patchwork  </li><li>Department Name:  Adult  </li><li>Brand Name:  Fun  </li><li>Style:  Casual  </li><li>Gender:  Unisex  </li><li>Material:  Cotton  </li><li>Strap Type:  Adjustable  </li><li>Hat Size:  One Size  </li><li>Model Number:  Fun</li></ul>",
    "title": "New Unisex Cotton Motocycle Cap",
    "order_id": "841cd431e41290db554198ac5c12dcc9d5e19165",
    "timestamp": 1461501544.71127,
    "btc_total": 0.0175589,
    "contract_type": "physical good",
    "thumbnail_hash": "ce650ffd635dfbbbc653627553ce63392cf161c4",
    "unread": 0
}]
```

**Comment by jjeffryes** [comment]
@Timbo925 Occasionally the get_purchases or get_sales call hangs or takes a very long time to resolve, my guess is that's what happened here. 

Usually hitting Cmd + F to reload the app will clear it up. 

If you see this again, check the get_purchases call to see if it's resolving, and let us know what the results are.

**Comment by Timbo925** [comment]
Ok thank you will do if it happens again.
