### ISSUE TITLE
Chat message being considered a required field

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1675]
Chat message is not a required field and should not be marked in red if nothing is typed.

It is now being marked in red even if user doesn't click on send message (i.e. clicks on chat text).

![chat message input](https://cloud.githubusercontent.com/assets/10789865/15879951/1ec033f2-2cff-11e6-89ee-034fd70b39e8.png)

**Comment by morebrownies** [comment]
+1
