### ISSUE TITLE
Allow item prices to be lower than 0.002 BTC

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1686]
Each bitcoin transaction has fees that must be covered, requiring a minimum value for each transaction.

Current minimum value of a transaction is being guaranteed by seller by setting a minimum item price, which is now 0.002 BTC (1.16 USD) per item.

A better approach should be allowing sellers to define item prices as low as possible, like 0.01 USD (0.0000172 BTC), and to require buyer to guarantee a minimum value of a transaction. For instance, if a buyer wants an item costing 0.01 USD, the following message should appear to him "_You must buy at least 116 units of this item to ensure Bitcoin transaction costs_".

This way vendors can be extremely precise on their prices. Example: translators setting prices per single word or single character, musicians/artists/teachers setting prices per second of time.

**Comment by jjeffryes** [comment]
This was resolved, the minimum price is now set to the lowest that still clears quickly for a transaction of average size. see #1693 for more discussion on future solutions.
