### ISSUE TITLE
Shipping address not clear enough

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1687]
I have bought an item on OpenBazaar, and the seller writes:

![screen shot 2016-06-09 at 17 49 00](https://cloud.githubusercontent.com/assets/731743/15938319/99326dd2-2e6a-11e6-8978-a2ba7499fc06.png)

**Comment by LiteBit** [comment]
Has the payment been paid in full? I think shipping info is withheld from viewing until payment has been completed. That may be what they are referring to.

**Comment by JustinDrake** [comment]
Paid in full

**Comment by jjeffryes** [comment]
Can you get a screen shot of the shipping tab for the transaction from the seller? We don't have much to go on.
