### ISSUE TITLE
Discover page elements keep language

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1689]
![language change2](https://cloud.githubusercontent.com/assets/10789865/15951522/742a19de-2e8f-11e6-8e9e-bce4229e86ef.png)

To reproduce: Change language on settings, and return to Discover page. Elements keep previous language.

OB 1.1.6

**Comment by jjeffryes** [comment]
@rmisio is this an issue with caching?

**Comment by rmisio** [comment]
@jjeffryes it is a caching issue. I have a couple of language issues that I've been meaning to discuss with you that would affect how to go about handling this. I'll defer fixing this bug until then.
