### ISSUE TITLE
No umlauts in the title of an article possible

### ISSUE THREAD

**Issue by Gitju** [OpenBazaar/OpenBazaar-Client#1690]
Brief Description: 

Operating System (OS and version): GNU/Linux Debian 8.3
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.6 
Hardware: Yes ;)

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Create a new article
2. Choose a title like **Kühlschrank**
3. Try to save the article

Observed Behavior:
Error message that the article could not be saved.

Expected Behavior:
Article would be saved.

Additional info (links, images, etc go here):
If I subsiture **ü** with **ue** in the title it works so the reason are umlauts in the title.

**Comment by jjeffryes** [comment]
This is probably the same issue as https://github.com/OpenBazaar/OpenBazaar-Server/issues/434

The title field needs to be updated on the server to handle special characters.

Pinging @cpacia

**Comment by jjeffryes** [comment]
I'm closing this in the client repo, as this is a server issue.
