### ISSUE TITLE
Inconsistent behavior on count of unread messages in Order's discussion

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1691]
Discussion button's count of unread messages is inconsistent. If you restart the software and go to Transactions page again, sometimes it adds the number of unread messages to the previous number of unread messages.

On example below I had 3 unread messages, it was showing 1, and after restarting software, it started showing 4 unread messages. 

![discussion count2](https://cloud.githubusercontent.com/assets/10789865/15953073/10343960-2e9d-11e6-8c00-cf59b2619048.png)

Other times I got the correct number (3).
Other times you read the messages, close and open the software again, and the (3) unread messages sign is back again.

OB 1.1.6

**Comment by jjeffryes** [comment]
Issue moved to [OpenBazaar/OpenBazaar-Server #437](https://github.com/OpenBazaar/OpenBazaar-Server/issues/437) via [**ZenHub.io**](https://www.zenhub.io/)
