### ISSUE TITLE
The minimum price logic when creating/editing a listing seems to be over estimating the minimum price

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1693]
Currently it's saying I can't list an item for less than $1.16. The current bitcoin fees are probably around 5 cents right now so I'm not sure where $1.16 is coming from. Seems like there is a bug in the logic.

<img width="545" alt="screenshot 2016-06-10 08 14 27" src="https://cloud.githubusercontent.com/assets/13066886/15969124/68305248-2ee3-11e6-9006-e42546dfe935.png">

**Comment by jjeffryes** [comment]
It's not a bug, we decided to set it to 0.002BTC to make sure the transaction goes through.

**Comment by jjeffryes** [comment]
The issue is we have to set it to some arbitrary amount, since we don't have a way of dynamically detecting what the lower limit should be, so we'll have to continuously update this as prices and the network change. 

It'd be nice to have a better way to handle it.

**Comment by morebrownies** [comment]
We may want to go back to the drawing board on this one and consider alternative approaches. The main problem is I can't update my listings without raising the price.

**Comment by jjeffryes** [comment]
The theory is if your prices are in fiat, and the BTC to fiat exchange rate goes up, you need to raise the prices or when people try to buy your products the transaction will fail or never resolve (or take a very long time to resolve). We set the minimum higher than the actual point at which they fail to provide a little buffer against price fluctuations.

There's a ticket to make listings in fiat prices that are below the minimum price unbuyable, to prevent people from getting purchases stuck in limbo.

We should also have a way to notify the vendor if their listings drop below the minimum price, so they can update them.

If we take out the minimum, then we'd need a better way to deal with listings with prices that are too low.

**Comment by jjeffryes** [comment]
Let's consider using a service like https://bitcoinfees.21.co/api to get a constantly updated number, and base it off of a transaction size of 400 bytes.

For now I'll move the minimums by a decimal place, it was probably a typo when we set it up.

**Comment by mariodian** [comment]
Maybe it's a good idea to follow the reference bitcoin client 

https://github.com/bitcoin/bitcoin/blob/28ad4d9fc2be102786a8c6c32ebecb466b2a03dd/src/primitives/transaction.h#L161

**Comment by jjeffryes** [comment]
This has been fixed. In the future we may set the minimum price dynamically.
