### ISSUE TITLE
Merge in Esperanto translation

### ISSUE THREAD

**Issue by LaPingvino** [OpenBazaar/OpenBazaar-Client#1696]
The Esperanto translation in Transifex is at 71%, no really important things are untranslated. I will of course keep on translating, but it would be really nice to have the version as is included (also as it's further translated than some other languages...).

**Comment by jjeffryes** [comment]
We'll add it in the next release. 

Generally we add languages at 80%, but as new phrases get added the percentages change, so some of the languages that used to be near 100% are now much lower because they haven't been updated recently.

**Comment by LaPingvino** [comment]
Should be completely mergeable now: it's at 100%. Thanks!

**Comment by jjeffryes** [comment]
Esperanto has been added.
