### ISSUE TITLE
Bitcoin labels don't always show all digits of price

### ISSUE THREAD

**Issue by LaPingvino** [OpenBazaar/OpenBazaar-Client#1698]
Brief Description: When making a payment not using the link (because the system doesn't support that for example) the amount shown can be slightly off because some digits of the bitcoin price get cut of, thus making the payment not go through

Operating System (OS and version): Linux x64 (Ubuntu chroot on ChromeOS)
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.6
Hardware: Chromebook Pixel 1st gen

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Sometimes (I had the same thing in BazaarHound, so I suspect it's a server and/or js floating point issue)

Steps to reproduce:
1. Have a product with a price using all parts after the decimal point
2. Try to pay it
3. Copy the price to pay from the payment message

Observed Behavior:
Payment doesn't go through because it's not exactly right

Expected Behavior:
Payment is exactly right

Additional info (links, images, etc go here):
Maybe using ints with a point only added for display solves this

**Comment by jjeffryes** [comment]
@LaPingvino can you pull the lastest version of the client from Github, and see if that solves the issue?

Or post the OpenBazaar link to an affected listing?

**Comment by jjeffryes** [comment]
This has been fixed.
