### ISSUE TITLE
'Cancel' button doesn't work in Customizations

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#170]

**Comment by jjeffryes** [comment]
Can you explain when the cancel button doesn't work?

I am trying it in master right now, and I can't reproduce this issue.

**Comment by drwasho** [comment]
Hmm... couldn't reproduce it either. But I did run into this bug along the way (it's a YouTube video, click the image):

[![customization bugs](http://img.youtube.com/vi/yjq9tVr9oLA/0.jpg)](http://www.youtube.com/watch?v=yjq9tVr9oLA)
