### ISSUE TITLE
Minus 1 notifications

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#1700]
![screen shot 2016-06-16 at 00 18 57](https://cloud.githubusercontent.com/assets/4035854/16100710/2534a236-3358-11e6-9041-c790c67401f9.png)

Not sure how this happened... was chatting in the contract discussion.

**Comment by tmmunro** [comment]
I also just got the -1 ... running 1.6 client connected to VPS from master pull
