### ISSUE TITLE
Word wrap breaks individual words in chat and in contract discussion chat.

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#1701]
This looks pretty bad. Not sure if intentional.

**Comment by jjeffryes** [comment]
This should have been fixed in commit 5a389e3, are you still seeing it in master?

**Comment by dsmurrell** [comment]
Is that commit before 1.1.6? I'm using the client from the installer.

**Comment by jjeffryes** [comment]
No, it's only in the master branch, it was committed last night.

**Comment by dsmurrell** [comment]
Oh ok, no problem then. We can close this.
