### ISSUE TITLE
I need an easy way to clear the "Ship to" input when creating/editing a listing 

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1702]
<img width="531" alt="screenshot 2016-06-15 17 27 29" src="https://cloud.githubusercontent.com/assets/13066886/16101809/77ec9be4-331e-11e6-94c9-587a8afa905a.png">

If you accidentally select Shipping Region "All countries", you'll manually have to remove each country one by one from the Ship to field. Having a way to "clear" the input would be a life saver.

Oh and the X isn't displaying for each country in the Ship to field.

**Comment by mariodian** [comment]
Can you please add a design for this use case? I'll get this one.
