### ISSUE TITLE
Third party search engines API

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1703]
As I understand the OpenBazaar team wants an API for third-party search engines to allow for fast searches from the OB client. This is in the "3-12 months" category in [the roadmap](https://medium.com/@therealopenbazaar/openbazaar-roadmap-46b9e774f319#.th37jnt8u).

The [Duo Search OpenBazaar search engine](https://duosear.ch) is keen to become a third-party search engine to provide our ultra-fast search experience directly to the OpenBazaar client.

To start the discussion, I am going to suggest sticking with an existing industry standard, namely [OpenSearch 1.1](http://www.opensearch.org/Specifications/OpenSearch/1.1). We already use OpenSearch for people to search within Duo Search directly from the Chrome omnibar:

> https://duosear.ch/opensearch.xml

```
<?xml version="1.0" encoding="UTF-8" ?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>Duo Search</ShortName>
  <Description>Search OpenBazaar</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image width="16" height="16" type="image/x-icon">https://duosear.ch/img/180x180.png</Image>
  <Url type="text/html" method="get" template="https://duosear.ch/?q={searchTerms}"></Url>
</OpenSearchDescription>
```

The `searchTerms` can easily accommodate the Twitter semantics `@username` and `#tag`, and maybe custom filters such as `$category:food`, `$origin:France`, `$freeShipping:true`, etc.

Thoughts? cc @hoffmabc @cpacia @drwasho

**Comment by hoffmabc** [comment]
Haven't given a ton of thought on this yet, but I think OpenSearch is reasonable to me. Especially since you are already using it for the duosearch product and the rest of us who will be building endpoints (OB1, bazaarbay, etc) haven't currently built out any alternative.

**Comment by JustinDrake** [comment]
We're using OpenSearch is a minor fashion; very open to other suggestions.

**Comment by jjeffryes** [comment]
This will be a feature in v2, we're not planning to add it to v1 (this repo).

**Comment by JustinDrake** [comment]
@jjeffryes Are you going to open a corresponding issue for the appropriate repo?

**Comment by jjeffryes** [comment]
We don't need an issue on the v2 repo, this is baked into the roadmap.

**Comment by JustinDrake** [comment]
This thread is a discussion about API design. It's a two-way thing that can happen on GitHub.
