### ISSUE TITLE
Store Color Costomization not propperly saved in settings

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1720]
@SimonBelmond commented on [Thu Jun 23 2016](https://github.com/OpenBazaar/OpenBazaar-Server/issues/445)

Brief Description: 

Operating System (OS and version): Ubuntu 14.04
OpenBazaar version: 1.1.6.deb
Hardware: 4gb ram, HP mini desktop (sorry for crappy description)

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Create a new store
2. Costomize the colors and image of your page and press save
3. Got to settings and change anything (not image or colors) and hit save

Observed Behavior:

Colors change back to default theme.

Expected Behavior:

Colors are saved in settings too

My Workaround:

Write down RGB codes and enter them in the settings page and hit save. This way they are in fact saved.

Additional info (links, images, etc go here): The bug is not 100% reproducible for the image but for the colors.

**Comment by jjeffryes** [comment]
This occurs when the Settings view is loaded, and then values that affect the Settings view are changed (such as becoming a store using the store wizard, or changing the page colors).

When Settings is navigated to again, the cached values are used, instead of the new values.

Reloading the Settings page with control f loads the correct values.

**Comment by jjeffryes** [comment]
Disabling caching also fixes this. 

@rmisio do you want to take a look at this?

The user page clears it's cache when the data is changed in Settings, can that work the other way too?

**Comment by SimonBelmond** [comment]
If you need any help, logs or anything from me let me know. Mad another clarification comment here after the issue was closed: https://github.com/OpenBazaar/OpenBazaar-Server/issues/445

"Glad you could reproduce it. Initial color change was on my page not in settings. colors were showing correctly until I went and changed something else in the settings and hit save. then the settings were overwritten back to initial theme."

**Comment by jjeffryes** [comment]
@SimonBelmond if you can pull the latest copy of master, this issue should be resolved now. If you're using the installer, we're wrapping up the next release and it should be available soon once we've tested everything.

Thank you for alerting us to this, it was very helpful.
