### ISSUE TITLE
Add as moderator option does not work reliably, moderator page and GUID entry in settings affected.

### ISSUE THREAD

**Issue by SimonBelmond** [OpenBazaar/OpenBazaar-Client#1726]
Operating System (OS and version): Ubuntu 14.04
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.6.deb file

Hardware: HP 4gb ram mini pc

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Sporadic, two users have reported the issue affecting a total of two moderators.

Preconditions:
Both mods online and have moderation enabled.

Steps to reproduce:

1a. On moderator page, press "add as moderator" button.

1b, Go to settings and paste the GUID of the moderator, press save and wait untill confirmed saved.

Observed Behavior:

a. Button changes color lightly as being selected and turns into the little clock and stays there. UI does not update to "following" and stays on the clock. Manual updated of page shows the option "add as moderator" but pressing the button again, which now make the button go to the selected color and stays on "add as moderator"

b. Moderator does not show in selected. page update also shows nothing else.

Expected Behavior:

a. Button changes to "Following"

b. moderator is shown in settings.

**Comment by ghost** [comment]
I confirm this bug, my node can not get chosen as moderator by 2 other nodes and I can not add a new moderator by clicking the button or by manually adding the GUID, but by choosing from the moderator list.

**Comment by jjeffryes** [comment]
Can you paste the addresses to your nodes?

So far I have been unable to replicate this issue. It may be specific to your nodes or your server setup.

**Comment by hoffmabc** [comment]
I'm seeing this as well. I can't add ob://@JustinTime/about as a moderator

**Comment by hoffmabc** [comment]
API returns success:true but it is not added to the list of moderators.

**Comment by jjeffryes** [comment]
I'm able to add justintime as a moderator normally. 

You're sure you're on the latest master for the server and client?

**Comment by ghost** [comment]
I am on the latest server and client and I can't, as said, add a moderator (only by selecting from the list) or get added by others.

**Comment by jjeffryes** [comment]
I can confirm that it's not possible to add c485bd9861dd2e9f896c21bae5af868abca55eff
 (@tyggrr) as a moderator. 

The guid is sent correctly to the API, but the server doesn't add it, and the GET call to settings doesn't have that user as a new moderator.

Other guids work normally.

This appears to be a server issue, I'm moving it to that repo.

**Comment by jjeffryes** [comment]
Issue moved to [OpenBazaar/OpenBazaar-Server #448](https://github.com/OpenBazaar/OpenBazaar-Server/issues/448) via [**ZenHub**](https://www.zenhub.com/)
