### ISSUE TITLE
Chat alert icon at -3 and no messages marked in organge -->Screenshot

### ISSUE THREAD

**Issue by SimonBelmond** [OpenBazaar/OpenBazaar-Client#1730]
Operating System (OS and version): Ubuntu 14.04
OpenBazaar version (shown on About OpenBazaar page in menu): 1.1.6.deb file

Hardware: HP 4gb ram mini pc

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Sporadic, two users have reported the issue affecting a total of two moderators.

Preconditions:
Local client and server on the same machine, running connected to the world.

Steps to reproduce:
1. Don't know sorry, has been strange with that icon lateley. Also before and after restart.

Observed Behavior:

See screenshot. Basically had that simbol orange a lot although no messages were unread. On a closer look i think it is whowing -3. Normally I think new messages are indicated with an organe mark to the left. See arrow.

Expected Behavior:

No alerts when no new messages. Sidenote, configurable smtp for received chat messages would be awesome.

Screenshot: [http://imgur.com/v6sFIUI](http://imgur.com/v6sFIUI)

**Comment by jjeffryes** [comment]
The -3 icon you're seeing is for the Notifications, which appear if you click the bell icon.

The negative number issue has been fixed in release 1.1.7.

**Comment by SimonBelmond** [comment]
OK, sorry. Didn't know that you close issue before releases. Looked for a similar issue in open issues.

**Comment by jjeffryes** [comment]
No worries. We close the issues as soon as they've been fixed in the master branch. I know that's sometimes confusing.
