### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by ulrichard** [OpenBazaar/OpenBazaar-Client#1733]
Brief Description: Placeholders are displayed where I woule expect translated text.

Operating System (OS and version): Trisquel Belenos / Ubuntu 16.04
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.7
Hardware: Lenovo X60 libreboot

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Was fine with 1.1.5 and earlier versions. With newer versions always reproducible.

Additional info (links, images, etc go here):
http://ipfs.io/ipfs/QmTMct91hbg4XEgbasHjzy54p2BXAT8kSSjpLNy6ZaXcvt
http://ipfs.io/ipfs/QmemSUgzUdms3y4BaScjK7J6Mza26np1ooJLGxLXcBFGvU

**Comment by jjeffryes** [comment]
If you go to settings and pick a language, do the placeholders change to normal words?

**Comment by ulrichard** [comment]
That's the first thing I tried. Didn't help.

**Comment by jjeffryes** [comment]
Does this happen with every language you select in settings, or only certain languages?

**Comment by ulrichard** [comment]
The following workflow fixed the labels:
- select German
- save and restart
- select English again
- save and restart

The difference before was that I didn't save and restart wit the other language before switching back to English.

Still, it would be good if the upgrade wouldn't cause this behavior.

**Comment by rmisio** [comment]
Actually, we are now requiring the user to re-start in order for a lang change to fully take effect:

https://github.com/OpenBazaar/OpenBazaar-Client/commit/b171cc7c558cfd850ae3c217867f78f4ccbb70ef

![image](https://cloud.githubusercontent.com/assets/794517/16569453/76cb5bde-41eb-11e6-8cb2-61ebed4e0962.png)

I think this happened after the last release. Should be in the next release.

**Comment by ulrichard** [comment]
But I restarted many times after the upgrade, and the labels remained broken. Only switching back and forth fixed it.
Could it be that the upgrade resets the language, and an explicit language initialization is required?

**Comment by jjeffryes** [comment]
This may have been closed by #1739, we haven't been able to duplicate it yet so it's hard to be sure.
