### ISSUE TITLE
Can't put accent in title

### ISSUE THREAD

**Issue by qsypoq** [OpenBazaar/OpenBazaar-Client#1738]
Brief Description: 
If you try to create a product with a accent in the name you will not be able to save it, it will show a error saying "impossible to save data"

Operating System (OS and version): Archlinux
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.7

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Create a product
2. Put a "é" in the title
3. Try to save it

**Comment by jjeffryes** [comment]
This is being tracked on the server repo here: 
https://github.com/OpenBazaar/OpenBazaar-Server/issues/434

**Comment by jjeffryes** [comment]
I'm closing this in the client repo, as this is a server issue.
