### ISSUE TITLE
Selecting 'Create Listing' from the Menu -> No 'save changes' button

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#174]
**Bug:**
1. Select 'Create Listing' from the menu
2. The two buttons are 'Create Listing' and 'Customize'.. there is no 'Save Changes'.
3. Whatever you fill in is lost because the listing can't be saved.

![image](https://cloud.githubusercontent.com/assets/3887694/10984629/657423f4-8466-11e5-8c6d-cbe318481edc.png)

**Comment by jjeffryes** [comment]
I haven't been able to duplicate this.

**Comment by drwasho** [comment]
It's reproducible for me.

**Comment by jjeffryes** [comment]
What operating system are you on?

**Comment by drwasho** [comment]
The 10th version of Windows.

**Comment by jjeffryes** [comment]
Are you still seeing this issue? Has anyone else been able to reproduce it?

**Comment by drwasho** [comment]
All fixed.
