### ISSUE TITLE
Stores with more listings take longer for home page to load

### ISSUE THREAD

**Issue by sgornick** [OpenBazaar/OpenBazaar-Client#1742]
It takes an unacceptably long time for the "home page" of a store with more than just a few dozen items to load.  

Stores are adding listings and as the number of listings grows that makes their "home pages" unusable.

Top stores (by listing count) can be seen here: https://duosear.ch/stores

Reproducible: Always

Steps to reproduce:
1. any of the following:
 ob://ce77c1aa83e4e639761f4d5c9c63c8dd47a479f9/store
ob://@crypto_collectibles/store
ob://f1ff5c21ca953c6078299df23aa0874b8df7f19f/store

Observed Behavior:
A "spinner"/loading icon will be shown and then there is a delay along the lines of 15 to 30 seconds, or longer sometimes. 

Expected Behavior:
Responsive enough where the first listings start being displayed within some number of seconds that is less than 15 or 30.

Additional info (links, images, etc go here):
Issue #375 is closed, but it might be related.

**Comment by sgornick** [comment]
Left as-is, this will place an upper limit on the number of listings a single store should add.    I described this to a merchant wanting to do a mass import here: 

https://www.reddit.com/r/OpenBazaar/comments/4r6sz3/what_are_the_current_ways_to_mass_import_listings/d4z59th  

Someone saw that and felt it made good fodder for /r/buttcoin: https://np.reddit.com/r/Buttcoin/comments/4rchgl/openbuttzar_soon_to_put_amazon_and_ebay_out_of/ )

**Comment by jjeffryes** [comment]
Lazy loading of the listings is on our roadmap, but has not been implemented yet.

**Comment by jjeffryes** [comment]
To clarify, do you mean it takes a long time for all of the images for the listings to load, or does the entire page take a long time?

Displaying the listings for crypto_collectables took 6.3 seconds when I tested it, but loading all of the images took a while after that, and some of them failed to load.

**Comment by sgornick** [comment]
> Displaying the listings for crypto_collectables took 6.3 seconds when I tested it,

Right.  But it accesses all items in the store, so if it had 1,200 items instead of 600 items, your load time would have been ~12.6 seconds.    Or for 2,400 items, ~25.2 seconds.     So the point is, current approach imposes a significant delay as the store size (listing count) increases. 

As you described it, lazy loading would fix that. 

> To clarify, do you mean it takes a long time for all of the images for
> the listings to load, or does the entire page take a long time?

Here's a timeline from loading ob://@crypto_collectibles/store right now:

0s: Says "Connecting to @crypto_collectibles"
2s: Shows store's cover photo loaded "Store [...]" item count was blank and Follow button not showing yet.  Spinning/Loading icon.
14s: Follow button displayed
16s: Store listing count now populated, 601 items.   The gray image background for the first three listings rendered.  , but no actual images yet.
17s: Images for the first three listings now show.

I just noticed that when I scroll down for the next three listings, they don't show at all -- just the gray image background.   This corresponds with your report that some images fail to load.    With another large store, ob://f1ff5c21ca953c6078299df23aa0874b8df7f19f/store after the long delay I do see all the images (at least the first 50 or so) so the probably is no need to open an issue ticket for the problem of images not showing up on @crypto_collectibles.

I guess we wait for lazy loading to be implemented, and use DuoSear.ch in the meantime to browse listings on these larger stores.

**Comment by jjeffryes** [comment]
Lazy rendering and other optimizations for the store tab were added in #1789
