### ISSUE TITLE
vendorAvatarURL does not get cleared if switching to server with no store

### ISSUE THREAD

**Issue by pinheadmz** [OpenBazaar/OpenBazaar-Client#1748]
Brief Description: 
1) connect to remote OB server and create store with avatar images
2) disconnect from remote, and connect to default (local)
3) make purchase from someone else online
4) contract details for purchase indicate an vendorAvatarURL at the IP address of the remote server! 

buyerAvatarURL value is correct (localhost...)

Operating System (OS and version): 
OSX 10.10.5

OpenBazaar version (shown on `About OpenBazaar` page in menu): 
1.1.7

**Comment by jjeffryes** [comment]
I haven't been able to reproduce this issue. I'm going to close it unless we see it again.
