### ISSUE TITLE
typo: errorMessaes

### ISSUE THREAD

**Issue by jazy510** [OpenBazaar/OpenBazaar-Client#1750]
Brief Description: I found 3 instances of this typo, see here: https://github.com/OpenBazaar/OpenBazaar-Client/search?utf8=%E2%9C%93&q=errorMessaes

Operating System (OS and version): OSX 
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.7
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Go to setting page (cmd-G)
2. attempt to add in an address and save it
3. error message displays titled: "Data could not be saved.  errorMessaes.missingError"

Observed Behavior:
errorMessaes.missingError

Expected Behavior:
errorMessages.missingError

Additional info (links, images, etc go here):
https://github.com/OpenBazaar/OpenBazaar-Client/search?utf8=%E2%9C%93&q=errorMessaes

**Comment by jjeffryes** [comment]
Great catch, thank you.
