### ISSUE TITLE
Shipping costs errors

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#1752]
**Problem:**
- Domestic shipping costs are being displayed but under the header of 'Worldwide'
- International shipping costs are not showing at all

This problem is found in the official release and the latest version of the client. Example listing can be found here: ob://@cmosthestore/listing/19f3c365012b0bba36add322681cc02ac648a89f

![image](https://cloud.githubusercontent.com/assets/3887694/16759362/d49cb644-4859-11e6-931e-6e888f41f4a8.png)

**Comment by jjeffryes** [comment]
Good catch.
