### ISSUE TITLE
Set test item to lowest possible cost. Couldn't buy it.

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#1756]
Price was set at 0.0002BTC

Got this message when trying to buy it:

![screen shot 2016-07-21 at 13 39 46](https://cloud.githubusercontent.com/assets/4035854/17023002/00c70f9e-4f49-11e6-8b7e-10b27e69f8bd.png)

**Comment by jjeffryes** [comment]
Closed in #1758
