### ISSUE TITLE
I suggest that the client load the server's homepage after a switch of configuration.

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#1757]
Loading the last guid is very confusing when you switch between configurations. 

I suggest that the client drop its memory of who it was last trying to access from the last server you connected to and show the home page of the server you have just connected to.

This would also fix https://github.com/OpenBazaar/OpenBazaar-Client/issues/1719

**Comment by jjeffryes** [comment]
This was closed by #1784
