### ISSUE TITLE
"Settings" can't be displayed

### ISSUE THREAD

**Issue by unsystemizer** [OpenBazaar/OpenBazaar-Client#176]
Upgraded to Server and Client with commits from Nov 6, now in client Web UI "Settings" doesn't show up (Admin Panel, for example, does).
When I click on "Settings" it seems the code hits `fadeOut hide` and stops there.
It worked with Client/Server source from 2 days ago.

**Comment by jjeffryes** [comment]
The code for settings hasn't been committed yet, Hauxir is finishing it.

**Comment by jjeffryes** [comment]
For more clarity, what do you mean by settings worked two days ago? Clicking on settings shouldn't have done anything.

**Comment by unsystemizer** [comment]
I thought Settings was working and I'm pretty sure more buttons were working than with the updated code. But now my OB Server can't start ("Finding NAT Type...") either, so I can't see any more what else does not work. 
Okay let's leave this closed.
