### ISSUE TITLE
ERROR: electron main.js  while loading shared libraries: cannot open shared file: no such file or directory

### ISSUE THREAD

**Issue by uzair90** [OpenBazaar/OpenBazaar-Client#1764]
I am trying to install OpenBazaar-Client on ubuntu machine everything went fine except npm start.

Operating System (OS and version): Ubuntu

This is the error shown in the terminal.
`
root@anything:~/OpenBazaar-Client# npm start

> OpenBazaar@1.1.8 start /root/OpenBazaar-Client
> electron main.js

/root/OpenBazaar-Client/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! OpenBazaar@1.1.8 start: `electron main.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the OpenBazaar@1.1.8 start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the OpenBazaar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs OpenBazaar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls OpenBazaar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/OpenBazaar-Client/npm-debug.log
`

**Comment by jjeffryes** [comment]
As a first step, try running "npm install" again a few times to make sure all the dependencies are installed.

Sometimes it takes a few times to catch all the sub-dependencies.

**Comment by uzair90** [comment]
Ran npm install 10 times nothing worked gives the same error. Is there anything wrong with the version of electron-prebuilt?

**Comment by jjeffryes** [comment]
The version of electron-prebuilt it's using should be fine, you can try changing it to a more recent version, we haven't tested that though.

**Comment by uzair90** [comment]
Manually installed all the dependencies which are shown in the error but still having the same error.
`root@anything:~/OpenBazaar-Client# npm start

> OpenBazaar@1.1.8 start /root/OpenBazaar-Client
> electron main.js

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! OpenBazaar@1.1.8 start: `electron main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the OpenBazaar@1.1.8 start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the OpenBazaar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs OpenBazaar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls OpenBazaar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/OpenBazaar-Client/npm-debug.log
`

**Comment by rmisio** [comment]
can you try to delete your node_modules folder and then do a `npm cache clean` and then re-do the `npm install`?

**Comment by uzair90** [comment]
Still same @rmisio

**Comment by rebroad** [comment]
I also have this exact same error. Running Ubuntu 16.04.1 LTS

using npm@3.5.2
using node@v4.2.6

silly lifecycle OpenBazaar@1.1.8~start: Args: [ '-c', 'electron main.js' ]
silly lifecycle OpenBazaar@1.1.8~start: Returned: code: 1  signal: null
info lifecycle OpenBazaar@1.1.8~start: Failed to exec start script
verbose stack Error: OpenBazaar@1.1.8 start: `electron main.js`
verbose stack Exit status 1
verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
verbose stack     at emitTwo (events.js:87:13)
verbose stack     at EventEmitter.emit (events.js:172:7)
verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
verbose stack     at emitTwo (events.js:87:13)
verbose stack     at ChildProcess.emit (events.js:172:7)
verbose stack     at maybeClose (internal/child_process.js:821:16)
verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by onics** [comment]
Same issues here on Arch linux. Appears to be an issue with the way modules are being loaded in main.js

Electron requires importing the modules in one of two forms:

```
require ('electron').app;
```

or

```
const {app} = require ('electron');
```

When I tried to switch to importing all of the Electron modules over to one of these methods, it broke a lot of stuff with naming. Eventually got the client to launch, but it is not loading the template correctly. Most likely due to some change in methods and modules in the Electron library.

Full disclosure: I am not a Node developer, so definitely open and grateful for any help/advice.

**Comment by ghost** [comment]
I get the following error message while starting the OpenBazaar client with `npm start`:

```
/home/fturco/software/openbazaar-client/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

Is GTK+ required in order to run OpenBazaar? On my systems I only install Qt applications...

**Comment by hoffmabc** [comment]
I believe gtk is required for Electron which we use. Is this a manual install @fturco ?

**Comment by ghost** [comment]
Yes, I manually installed everything from git.

Edit: https://electron.atom.io/docs/development/build-instructions-linux/ (yes, Electron requires GTK+ 2.x)

**Comment by hoffmabc** [comment]
And you're building the latest Electron? It seemed like this was a problem at one point but got resolved in a later version.

**Comment by ghost** [comment]
electron@1.6.10, according to `npm list`.

**Comment by ramses0** [comment]
Just had this issue on windows 10 / WSL-ubuntu. 

```
rames@Red-Slash:~/Git/electron-quick-start$ yarn install
yarn install v1.2.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.18s.
rames@Red-Slash:~/Git/electron-quick-start$ yarn run start
yarn run v1.2.1
$ electron .
/home/rames/Git/electron-quick-start/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Yangfan2016** [comment]
@ramses0  How to do can run electron  on windows 10 /wsl-ubuntu ^_^

**Comment by jjeffryes** [comment]
@Yangfan2016 this repo is no longer being maintained. Please use https://github.com/OpenBazaar/openbazaar-desktop
