### ISSUE TITLE
Endless loop in the window for the generation of the OpenBazaar ID

### ISSUE THREAD

**Issue by krosav** [OpenBazaar/OpenBazaar-Client#1767]
Brief Description: I am hung at the personal keys and OpenBazaar id generation

Operating System (OS and version): Windows 10 
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.7
Hardware: Desktop

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Installing the OpenBazaar 1.1.7 for Windows 64 bits
2. The connection to the server works, i answer all questions, i accept the disclaimer
3. After that, i get to the moment when it tries to generate the personal keys and OpenBazaar Id, and then it stays forever in this window.

Observed Behavior: Here is what i have in the window:

Hang tight for a few...

Your personal keys and OpenBazaar ID are generating and should only take about 30 seconds to finish.  You'll be automatically connected to the network once the process is finished, so please hang tight.

Looking for something to do in the meantime? Read the OpenBazaar blog.

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
@faffner if you turn off the app, and start it again, does it take you through the onboarding process where you set up you language, country, etc. again?

If you press "control shift I" while one the "Hang tight for a few..." screen , to bring up the web developer panel, and look at the console tab, do you see any errors?

**Comment by krosav** [comment]
@jjeffryes  yes, it took me each time through the onboarding process - language, country, etc. up to the disclaimer.

And i did it several times, and i did not think of pressing "ctrl shift I", which is unfortunate, because i just did it again, and this time it worked !!! My OpenBazaar ID got generated.

So i will close this issue, hoping that once the ID has been generated, the problem will not happen again. I am sorry to not be able to provide you with more information about this problem.

Let me know if you would like me to perform some other verifications.
