### ISSUE TITLE
High DPi (4k) not supported

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1770]
Brief Description: 

Operating System (OS and version): Ubuntu 16.04 x64 
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.7
Hardware: Dell XPS 15 9550

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Start OpenBazzar

Observed Behavior: Everything is too small

Expected Behavior: The UI must adapt to scaling factor set in Ubuntu Settings.

Additional info (links, images, etc go here):

![screenshot from 2016-09-05 16-33-45](https://cloud.githubusercontent.com/assets/1475489/18249522/7c67bda8-7387-11e6-99d4-9dea5eb72c23.png)

**Comment by rmisio** [comment]
Thanks for reporting this issue.

Some responsiveness is on the roadmap for v2. For example, in v2 the plan is for the grid of listings to be expandable to the full width of the window.

At this time, we don't have any plans to retro-fit v1 with this functionality.

**Comment by stevenroose** [comment]
Why was this closed? It's still an issue... The text and buttons are crazy small on my machine..

**Comment by ghost** [comment]
@stevenroose Because v1 will not receive major updates, all the effort is done for [v2](https://github.com/OpenBazaar/openbazaar-desktop) (this should be fixed in v2)

**Comment by stevenroose** [comment]
Oh, v2 has a separate repo. That makes it clear :) Thanks!

**Comment by heyakyra** [comment]
Looks like https://github.com/OpenBazaar/openbazaar-desktop/issues/435 added support

But out of the box things could still use improvement: https://github.com/OpenBazaar/openbazaar-desktop/issues/1612
