### ISSUE TITLE
Shipping information on client is wrong/confusing

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#1776]
Listing in question: ob://@crypto_collectibles/listing/ab332c6efa31fb940a6fa96830598334549dddcc

Shipping info given through client:
![screen shot 2016-09-15 at 14 06 11](https://cloud.githubusercontent.com/assets/4035854/18550851/ca9a10e8-7b4d-11e6-8c46-de84a7ee1f84.png)

duosear.ch info on shipping:
![screen shot 2016-09-15 at 14 08 16](https://cloud.githubusercontent.com/assets/4035854/18550878/e74aecf8-7b4d-11e6-8eac-fd78f8478604.png)

I can't make any sense of the shipping info given back to me by the client. Is something wrong here?

**Comment by jjeffryes** [comment]
What's confusing about it?

It ships worldwide (ALL), from the United States, for free.

Are you using an old client? The current version in Master shows both local and international shipping info when the shipping_regions is set to ALL.

The current version looks like this:

![image](https://cloud.githubusercontent.com/assets/1584275/18558252/671b1b64-7b40-11e6-8e9c-cd7c10eb6f9c.png)

**Comment by dsmurrell** [comment]
Using the latest release. Do you not want any bug reports on the latest release? Should we always use the latest master for bug reports?

Domestic says '7-14 Business days'. International says 'varies'... this is not shown anywhere.

When you look at the first image in my post, it looks like the shipping time to worldwide is 7-14 Business days. Is the info we have on shipping incorrect for this listing?

**Comment by jjeffryes** [comment]
We have a new release that was held up, so things are a little weird, but this has been fixed just not released yet.

**Comment by dsmurrell** [comment]
Ok, will test on master. Sorry for the distraction :)

**Comment by jjeffryes** [comment]
This was fixed in release 1.1.8, I am closing this issue.
