### ISSUE TITLE
NSFW warning displaying on each store for new users 

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1793]
I just spun up a new node and went to the @openbazaar store and was hit with this warning

<img width="1200" alt="screenshot 2016-10-05 08 24 57" src="https://cloud.githubusercontent.com/assets/13066886/19119661/53bb16ce-8ad5-11e6-87a2-d301dfbce241.png">

**Comment by jjeffryes** [comment]
Are you on the latest master? I think this is a bug that was fixed recently.

**Comment by morebrownies** [comment]
I just pulled and don't see it happening anymore.
