### ISSUE TITLE
How will Client code be updated for users?

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#181]
Brian mentioned that as an Electron app there might be the option for pushing updates automatically. Opening this up for discussion.

**Comment by gubatron** [comment]
I recommend Bittorrent. Saves us about $10k in bandwidth costs every month, and we have a 20mb installer, I think yours will be considerably larger, which would probably cost you +$100k/monthly in bw costs if you get growth.

**Comment by SamiLehtinen** [comment]
You could also publish chunked updates using OpenBazaars own Object Storage and Merkle tree and for users who aren't using BitTorrent, you could host the files on some really bandwidth cost efficient hosting. I don't want to put any 'adverts' here so I'll give the info personally if required.

**Comment by drwasho** [comment]
Work on this is currently underway by @hoffmabc , please close when ready.

**Comment by drwasho** [comment]
All done!

**Comment by ac225519** [comment]
How can I force a update to test it ?

**Comment by gubatron** [comment]
where is it downloading the updates from? I'm thinking about central point of failure, security and costs.

is there any checksum done before starting an update?

**Comment by hoffmabc** [comment]
The only way to force an update is to post a new release to GitHub. Next the Squirrel (nuts) server running at updates.openbazaar.org will monitor that and when you start your app it will ping the nuts server seeing if an update is available. If you comply within the OpenBazaar app it will download, install and restart the application. It's exactly how Spotify does it. All releases must be signed and I am the one who signs releases today.

**Comment by drwasho** [comment]
![image](https://media.giphy.com/media/veL6DyCLYL3Fu/giphy.gif)

**Comment by gubatron** [comment]
Awesome! Signed and all.
Is it served off-of a CDN?

**Comment by hoffmabc** [comment]
GitHub uses AWS

**Comment by gubatron** [comment]
sweet, let's see how long until they come'a knocking.

I got confused with the updates.openbazaar.org, I suppose that only points metadata about a new update with URLs on github.

Where can I find this in the code? tried looking for a related commit message on the 3 repos but didn't find anything mentioning it, also on this repo didn't find any file with _update_ in its name. I'm rusty.

**Comment by gubatron** [comment]
FYI, so you don't plan on relying this for too long, I think they'll come knocking soon,

"If your bandwidth usage significantly exceeds the average bandwidth usage (as determined solely by GitHub) of other GitHub customers, we reserve the right to immediately disable your account or throttle your file hosting until you can reduce your bandwidth consumption."
https://help.github.com/articles/github-terms-of-service/

Might not want to abuse the service and get the account shutdown.

**Comment by SamPatt** [comment]
@gubatron If only there was a way to distribute files that wasn't dependent on a central location!

Do you have a recommendation on a simple way to automatically torrent these installers?

**Comment by gubatron** [comment]
the initial one, I already have a version of jlibtorrent for JS that might be good enough for this. I've to see if I have binary builds for all the OSes.

**Comment by gubatron** [comment]
Here's sample code on JS on how to download a .torrent
https://github.com/frostwire/frostwire-jlibtorrent/blob/master/node/download_torrent_test.js

It's a JS wrapper to the all powerful libtorrent.

I'd love to help with this on my free time, would love to have OpenBazaar using this library.

**Comment by ac225519** [comment]
> Do you have a recommendation on a simple way to automatically torrent these installers?

I have a recommendation, at least how to torrent the best way.
A statically linked aria2 binary is the best way to multi-platform torrent / http(s) / (S)FTP.
All protocols concurrent at the same time from multiple sources. Beat that.
For Linux/Unix, OSX/iOS, Windows, Android.
https://aria2.github.io/

**Comment by gubatron** [comment]
the best way?
last time I heard libtorrent moves easily 30% of all internet traffic, over 10mm DHT node count at all times...

**Comment by hoffmabc** [comment]
Ok guys take it easy you can have your nerd fight on Twitter where all the mud slinging occurs

**Comment by ac225519** [comment]
Hahaha,
A "quantity" argument is so low, its not even in the [hierarchy of disagreement](https://en.wikipedia.org/wiki/Paul_Graham_%28computer_programmer%29#Graham.27s_hierarchy_of_disagreement)

**Comment by gubatron** [comment]
ha. Well you made me curious, I took a look, but I was very disappointed by what I saw in the github repo, it also has way too many features unnecessary for what's needed, just a torrent download with the lightest, heavily battle tested and optimized bittorrent library there is.  :)
