### ISSUE TITLE
Can't edit "Short Description" without deleting all existing text.

### ISSUE THREAD

**Issue by stamfordpark** [OpenBazaar/OpenBazaar-Client#1814]
Brief Description: The only way to edit the store short description is to completely delete all existing text which takes you back to the prompt you get when you first set up your openbazaar before you click "become a store" see pics

Operating System (OS and version): OS X Sierra 10.12.1
OpenBazaar version (shown on `About OpenBazaar` page in menu): v1.1.8
Hardware: iMac (27-inch, Late 2013)

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): always

Steps to reproduce:
1. open settings, click page
2. under short description, you can delete text but you cannot enter text until all text is deleted.
3. enter new text and click save

Observed Behavior:

Expected Behavior: should be able to make small corrections

Additional info (links, images, etc go here):
![short description 1](https://cloud.githubusercontent.com/assets/23071096/19749998/5a0f38aa-9c39-11e6-816c-b65e7089284e.jpg)
![short description 2](https://cloud.githubusercontent.com/assets/23071096/19750004/61882290-9c39-11e6-985e-5f37e274cf12.jpg)

**Comment by jjeffryes** [comment]
Are you trying to enter more than the limit of 160 characters in the short description? I'm not able to reproduce a bug with not being able to enter new text, but it does look like you may have hit the character limit in your short description.

The description in the become a store dialog is the about text, we should make that more clear.

**Comment by stamfordpark** [comment]
Hi jjeffreys, absolutely correct, didn't realise I'd gone over 160 chars and openbazaar let me and accepted and published it, there needs to be a limiter built in and I agree, it should be labelled store description or not appear at all until you click" become a store".

**Comment by stamfordpark** [comment]
sorry hit the wrong button, this is a classic case of stupid non-intuitive design.
