### ISSUE TITLE
New features (pinned, hidden, max quantity) not working

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1818]
Brief Description: 
When editing or creating a new listing, when Max Quantity is set to a number and Pinned/Hidden listing are selected to "Yes", those configurations are not saved when Save Changes button is clicked. However all other configurations on edit listing page are normally set. The next time I open the listing they are at default again (Blank, No, No).
Operating System:  Win7 64 bits
OpenBazaar version: 1.1.8
Reproducible: Always

**Comment by jjeffryes** [comment]
It sounds like you may have an out of date server. Are you using a local server that was installed by the installer, or a server you set up manually?

**Comment by ghost** [comment]
I'm using v1.1.8 (Client + Server) installed through installer. I'm also having the same error with new features when connecting my v.1.1.8 client to a node on Digital Ocean (created using Deploy). I've never installed "Client Only" version.

**Comment by jjeffryes** [comment]
I have confirmed that the installed version of the client and server in 1.1.8 have this issue, but the code in master does not.

**Comment by jjeffryes** [comment]
We've found the source of the bug, and will be issuing a fix soon.

**Comment by jjeffryes** [comment]
In the meantime, manually updating your server through git, or installing a new one from git, will fix this.

**Comment by jjeffryes** [comment]
This has been fixed in the master branch of the server.
