### ISSUE TITLE
How will users remove themselves as stores, and will their stores still be viewable?

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#183]
Vendors need to be able to make themselves non-vendors. If this happens, will other users be able to still view their store and any remaining listings?

This is in the Client repo but ideally this type of decision would be made at the server level.

**Comment by unsystemizer** [comment]
In my opinion if someone has a listing, he's a store. If someone doesn't want to be a store, he can unlist his stuff and then stop being a store (if he doesn't plan to sell anything in the near future).
Then the question becomes is there a need for stealth listings (stealth stores).

**Comment by hoffmabc** [comment]
I think people may put a lot of time and effort into their stores management and creating listings. Also what if they're preparing to bring out a bunch of new stuff and don't want to expose it until later. I think there are a bunch of use cases where people may want to "hide" their listings from the general network for a time.

**Comment by unsystemizer** [comment]
Pre-launch preparations make sense. I thought a listing is a published offer and that the question is about those.
To me it seems it would be more practical to add another field to product listing (ex: `valid_from`) and not have the listing published until chosen time and date, than to have only one way to disable a listing (to un-store yourself, which isn't very granular and disables all listings).
Speaking of scenarios, if you run out of stocks, you need to be able to un-list the item (alternatively, you may need to put a note you're taking orders but modify delivery time to account for delays?), so unless there's a better way store owners would need a way to unlist items at will. I wonder whether that can create a high frequency trading type of thing where one flips the switch on and off to basically spam the market with a low priced offering that can never be bought.

**Comment by jjeffryes** [comment]
I think there are scenarios where it makes sense to mark an item as "Not For Sale" without deleting it. It would be simpler, and a better experience, if the item was still visible, just marked as not for sale and the buy button was disabled.

@cpacia could contracts have an Active boolean attribute? Then you could just set that when creating or editing the product, and the client would disable buying if it was set to false. The server could check the same attribute when a purchase call was made, so someone couldn't try to buy inactive products with a branched client. 

I think that would be the easiest way to do this from a UX and development standpoint.

**Comment by cpacia** [comment]
Not without changing the contract hash. I could maybe put a boolean in the metadata but if the user goes straight to the product then it wouldn't show. 

I feel like this is not something we should be stressing over for version one. Simply setting vendor=False and not showing listings for a node with vendor=False is probably good enough.

**Comment by hoffmabc** [comment]
We can make a strong inventory management push for next release

**Comment by morebrownies** [comment]
I agree that toggling your store on/off should be good enough for the initial release. We can add the toggle to the settings page for now.

On = My store is visible to everyone and my items display in search.

Off = My store is not visible to me or others, plus all my items are pulled from search. If someone has a direct url to one of my items, display "This listing no longer exists". 

Moving forward, we'll need to consider additional visibility options, but I agree they can wait until later.

**Comment by drwasho** [comment]
I mostly agree with @morebrownies 

If Alice selects 'Off', their profile/social data is still accessible to other nodes but not their Vendor-related data like listings (they would remain private). So Alice's node would not serve that data when the `get_listings` call is made AND the WS `get_vendors` call would not show Alice as a Vendor. Also looking for specific contracts won't work either.

**Comment by lcipciriuc** [comment]
tell me if i am right thinking that 
1. once i am a Follower, my client stores the information about the Followed store, and i can browse it while the Followed is off-line?
2. once changes are made in the store Followed, a popup window will appear in my client, informing me about the changes occurred in that respective Followed store - say prices have changed, new arrivals, etc

**Comment by jjeffryes** [comment]
Currently, no information about other stores is stored on the client or the server. If a store is off-line, you can't look at its information. 

Notifications about changes to a store you follow may appear in your notifications section.

**Comment by lcipciriuc** [comment]
jjefreyes
in that case i have to have the option to run a 'long' search, so to call it, that my client will search for the word 'honey' like for 48 hours or so to ping the whole net to give me back all the traders who offer honey. or, the seller needs to leave his client running non-stop, so that everybody can have access to it around the clock. i presume, if a seller is a small guy, who is using computer for 2 hours in 3 days, there are very little chance he will sell his goods in a quick manner.

**Comment by jjeffryes** [comment]
@lcipciriuc we're working on solutions for that, I recommend discussing it in the slack general channel instead of on this github issue.

**Comment by drwasho** [comment]
Update on this issue.

If you deselect yourself as a Vendor in the admin panel: 
- Users can still visit your node if they know your GUID, but
- Users cannot see the `Store` page when they visit your node
- Users can still see your node in the `Pages` tab (irrespective of whether you're following them or not)
- Users **still see your listings** on the `Discovery` tab

**Comment by jjeffryes** [comment]
Listings appearing in the discovery tab if the seller isn't a vendor would be a backend bug, I believe it's supposed to only show vendor items.

**Comment by hoffmabc** [comment]
Can we get an update on this @jjeffryes ?

**Comment by jjeffryes** [comment]
This was completed a while ago. In Settings/Store, changing your store to inactive hides it without deleting anything.
