### ISSUE TITLE
Remove RushWallet from BuyWizard

### ISSUE THREAD

**Issue by sgornick** [OpenBazaar/OpenBazaar-Client#1843]
Brief Description: RushWallet is closing, remove from OpenBazaar BuyWizard

Additional info (links, images, etc go here): 

"Rushwallet.com  & http://Ethereumwallet.com  will be discontinued in the coming weeks. Please transfer your funds out soon!"
https://twitter.com/DECENTRALca/status/802208461236928512

https://github.com/OpenBazaar/OpenBazaar-Client/blob/386f3753432a707d5a229298f2ddfc022807eaf0/js/templates/buyWizard.html#L140

**Comment by hoffmabc** [comment]
Thanks! Pinging @joshj

**Comment by jjeffryes** [comment]
We'll take it out, thanks.
