### ISSUE TITLE
Add indicator ShapeShift is Available

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#1846]
In the purchase flow, add an indication that shapeshift is available early in the flow.

**Comment by hoffmabc** [comment]
Something like this next to the Bitcoin accepted might be fine.

![image](https://cloud.githubusercontent.com/assets/45482/21126420/029c6eb2-c0ba-11e6-9c15-fd2e951bcab5.png)
