### ISSUE TITLE
Private/hidden listings

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#187]
This is related to #183 but there is a use-case for supporting private/hidden listings.

The rationale is that I want to create a listing on my store (or even while not having an official store) that is only accessible to anyone or a specific user **provided** they have the correct contract hash (ID).

This would also mean that private listings would have their keywords disabled in order to prevent public discovery.

**Comment by SamPatt** [comment]
This is definitely a desirable feature. The contracting system lends itself well to invoicing, so you could craft an invoice as an item and then send the link along, but this wouldn't work if it's publicly listed.

Lots of use cases for this. If it's easy to implement it should be a v1 goal.

**Comment by SamPatt** [comment]
Updating with some more thoughts:

Right now you can either display an item or delete an item, with nothing in between, but that's going to be a major problem for someone who runs out of stock temporarily.

@morebrownies suggests:

> Listings need some type of status field so that vendors can set them to `active` `Out of stock` or `inactive`
> 
> They’ll need this for adding new items to their store too. They may want to preload listings and activate all of them on the same day when they’re ready.
> 
> [If someone lists as out of stock ] we could hide the buy buttton and display out of stock instead

**Comment by Kirvx** [comment]
Private/hidden listings/stores is definitely a good idea and should even be a requirement for many people when they start the creation of a store.
