### ISSUE TITLE
Little Snitch 4 (warn mode) not compatible with OpenBazaar search

### ISSUE THREAD

**Issue by Kadrian** [OpenBazaar/OpenBazaar-Client#1871]
**Brief Description**
OpenBazaar not usable together with Little Snitch 4. https://www.obdev.at/products/littlesnitch

Little Snitch in Warn mode monitors network traffic and allows you to allow / reject an outgoing connection to any IP you haven't been connected to before.

**Operating System**: OS X High Sierra 10.13.1
**OpenBazaar version**: 2.0.17
**Hardware**: Macbook Pro

**Reproducible**: Always

**Steps to reproduce**
1. Install OpenBazaar 2
2. Install and start Little Snitch 4 in "Warn" mode (asks about new connections)
3. Install and start OpenBazaar 2
4. Allow all (around 10) outgoing connections individually. That allows you to see your OpenBazaar profile (stable state until here)
5. Use the address bar in OpenBazaar to search for any term (hit enter)
6. See LittleSnitch using lots of CPU and blocking OpenBazaar from continuing. This state goes on (after all I could observe) forever.

**Observed Behavior**
Little Snitch uses plenty of CPU and stops OpenBazaar from working. The only way around it is to stop the network filter in little snitch (basically let everything through), quit OpenBazaar, re-start the network filter.

I suspect this is due to the decentralized nature of OpenBazaar during search, when it opens lots of outgoing connections to lots of different IP addresses.

I'm curious: Is that what's happening – and is that the desired behavior? How many connections are opened at the same time?

**Expected Behavior**
Little Snitch continues to work and asks me to allow one connection after the other.

**Comment by ghost** [comment]
When you first perform a search in OB it prompts you to select a default search provider. Does this issue occur before or after that happens?

**Comment by Kadrian** [comment]
After. I've seen that prompt for a default search provider before everything went infinite-looping

**Comment by jjeffryes** [comment]
This is the repo for the v1 client, can you file this issue in the https://github.com/OpenBazaar/openbazaar-desktop repo?

I know the names are confusing.

**Comment by Kadrian** [comment]
Alright. Re-opened: https://github.com/OpenBazaar/openbazaar-desktop/issues/1117

**Comment by jjeffryes** [comment]
Thank you.
