### ISSUE TITLE
Automatic Cross-Verification of Authentic Physical Addresses

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1872]
This suggestion request relates directly to how the OpenBazaar client handles physical address additions. This is related to the address book section of the client. 

Operating System (OS and version): Windows 10 Pro
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: client 2.0.22, server 0.10.1

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always.

The address book needs the ability to cross-reference and check an external source/database that will automatically compare and verify authentic physical mailing addresses. With the current format, you can input any address and the client will pick it up as valid. This should not be acceptable as it will only cause problems for the opposite end of the spectrum buyer or seller.

If a similar address exists to the one that was input, then a suggestion should appear with the valid address and give the user an option to change it.

If the address does not exist from the linked source/database, an error should pop up informing the user.

Benefits
This should be implemented for the following reasons:

- This will remove complications with sellers not knowing where to ship, or with potential scammers using fake addresses.

- This will remove the ability for human error. If an address is validated and verified from the referenced source point and accepted by the user, the package will not mistakenly wind at to a non-existent or incorrect location.

- This will boost the overall professionalism of the platform, now having the same ability that huge marketplaces like eBay, Amazon, and Newegg already use.

**Comment by jjeffryes** [comment]
Thanks for the suggestion. We've considered something like this in the past, and had Google Maps integration for addresses in v1 (this is the v1 repo, BTW, openbazaar-desktop is the v2 repo, which we know is confusing).

The feedback we've gotten is address verification is a significant privacy concern for many users. We haven't found a good way to do it that doesn't require integration with an outside API. 

This is still on our radar, if we can find a method of address verification that doesn't cause privacy issues we'll integrate it in the future.
