### ISSUE TITLE
Provide an AppImage for Linux

### ISSUE THREAD

**Issue by Tvax** [OpenBazaar/OpenBazaar-Client#1873]
Providing an [AppImage](http://appimage.org/) for distributing application has, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

In other terms, you wouldn't need to make a version for each Linux distributions, and it would be easier to launch. I think that, this is the kind of time-saving tool that you guys need!

LibreOffice, Krita and other projects already use it, see the full list here: https://appimage.github.io/apps/

**Comment by jjeffryes** [comment]
This repo is depreciated, did you mean to open this issue in OpenBazaar-Desktop?

@hoffmabc can answer questions about how he handle releases.

**Comment by Tvax** [comment]
Yeah wrong repo, my bad
