### ISSUE TITLE
Affiliate Programme / Decentral Marketing Incentives

### ISSUE THREAD

**Issue by timschloe** [OpenBazaar/OpenBazaar-Client#1874]
I'm trying to run a social-graph based marketing campaign.

Amazon offers an "Affiliate" program, where influencers who promote my book get 10% when purchases are made via a specific link to the shop. I need the same thing for Open Baazar.

**Comment by jjeffryes** [comment]
Thank you for the suggestion.  We have no immediate plans to add an affiliate feature, but we have discussed it in the past, and may add something like that eventually.

For future issues, it's best to use the desktop repo. That's the repo for the v2 reference client, this repo is for the v1 client which is no longer being developed.
