### ISSUE TITLE
UX: only show download latest if there is a newer version

### ISSUE THREAD

**Issue by ligi** [OpenBazaar/OpenBazaar-Client#1875]
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.2.4

This button let me believe that there is a new version - but I am already running the latest version.

![selection_124](https://user-images.githubusercontent.com/111600/44357426-4dba7780-a4b2-11e8-9e10-25c10686e21c.png)

Perhaps only show this button if there is a new version.

**Comment by jjeffryes** [comment]
@ligi can you re-create this issue in the repo for the desktop client?

This repo is for the v1 client, which we no longer support.

https://github.com/OpenBazaar/openbazaar-desktop
