### ISSUE TITLE
Following/Followers Avatar not updating

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#188]
Old avatars are being used when looking at nodes in the following/followers tabs.

**Comment by jjeffryes** [comment]
Can you tell if the problem is it's loading the wrong image hash and guid, or if the image hash and guid results in the wrong image?

**Comment by drwasho** [comment]
![image](https://cloud.githubusercontent.com/assets/3887694/11025109/fbad61a4-86e2-11e5-921d-10aeb2917859.png)

**Comment by jjeffryes** [comment]
Which ones are the old ones?

The avatars that have 404 errors should be showing the default avatar, which is that abstract blob thing.

**Comment by drwasho** [comment]
Sam's avatar, which belongs to a node that no longer exists after he blew away his database.

**Comment by drwasho** [comment]
Brian's node... of course :P

**Comment by hoffmabc** [comment]
That's how I roll

**Comment by cpacia** [comment]
It won't update the avatar. That would require querying everyone follower every time.

**Comment by drwasho** [comment]
Don't we have the latest avatar in cache?

**Comment by hoffmabc** [comment]
You still would have to do a profile call to see what is the latest avatar then check the cache.

**Comment by drwasho** [comment]
So we don't have a place in the database for the last known avatar hash for users in our followers/following tab?

**Comment by cpacia** [comment]
No.

**Comment by drwasho** [comment]
Ok... so are we saying we're ok with this bug? What's the solution here?

**Comment by hoffmabc** [comment]
I think for now yes

**Comment by hoffmabc** [comment]
We could push it to the DHT at a small icon size right?

**Comment by cpacia** [comment]
That's a bad idea. There isn't any way to get an updated image without querying everyone. If you unfollow and refollow it will update it, but that's it.

The follow data is signed so it can't be faked by node serving it. You can't just update it without another signature on the follow object.

**Comment by hoffmabc** [comment]
But why is an avatar part of signed data it doesn't make much sense. I guess if they used blockchain id could mitigate this.

**Comment by cpacia** [comment]
I signed it so that people don't put up fake avatars for other people. Like imagine you use some porn image for one of your competitors to try to deter people from going there.

**Comment by drwasho** [comment]
I think for the time being we'll just have to live with this.
