### ISSUE TITLE
Set server location

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#191]
I put the wrong address for my server location in the client and it had to go through 10 attempts before resetting to the default settings. It would be great if there was a button next to 'Close Application' that would reset to the default settings straight away.

**Comment by jjeffryes** [comment]
Recommended Solution: duplicate the button at the bottom in index.html, change the text to "Use Default Values", and trigger the same code as what happens when reloadProfile's loadProfileCount is over 10.
