### ISSUE TITLE
Scroll/small icon broken

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Client#200]
![image](https://cloud.githubusercontent.com/assets/4504708/11128731/a3682d6c-8949-11e5-9f9c-313500b3cbef.png)

Doesn't use the profile image when minimizing the avatar on scroll, then proceeds to scroll past it instead of stopping on it like it used to.

**Comment by jjeffryes** [comment]
Maybe I spoke too soon about that being a smooth merge this time...

**Comment by cpacia** [comment]
This was broken before the merge. Wasn't sure if you were aware of it.

**Comment by jjeffryes** [comment]
I was not.

**Comment by morebrownies** [comment]
Yeah it happened after the zindex changes so likely just a CSS issue
