### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by z3ntu** [OpenBazaar/OpenBazaar-Client#202]
![openbazaar_006](https://cloud.githubusercontent.com/assets/3768500/11130579/0e03877a-8986-11e5-8c79-f5ffa97db8c5.png)
I actually don't know why this error occurs...

**Comment by jjeffryes** [comment]
This can happen if you have an out of date version of the server. Try updating to the latest server and client, and deleting your database.

**Comment by z3ntu** [comment]
How do you "delete your database"? Client & Server should be updated.

**Comment by jjeffryes** [comment]
Find your OpenBazaar folder, and delete the OB-Testnet.db file. After that, the next time you start the server it should generate a new guid.

**Comment by z3ntu** [comment]
Worked, thank you. Still very weird that the client shows an SyntaxError in the HTML file... :smiley:

**Comment by jjeffryes** [comment]
It's not really in the HTML file, it happens when the main js file, which is loaded by index.html, has a problem with the data returned on the very first contact with the server.
