### ISSUE TITLE
Settings -> Currency Selection Issues

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#203]
1. Bitcoin is not in the drop-down list
2. Strange repeat when a search is done

![image](https://cloud.githubusercontent.com/assets/3887694/11132626/a121b5d0-89dc-11e5-9a4b-ff51f89569ea.png)

**Comment by drwasho** [comment]
The second problem is due to multiple copies of a currency code in the drop-down list.

**Comment by jjeffryes** [comment]
The currency list is pulled from the currencies in the country list, it needs to be de-duped before being added to the model, that must not have been done here.

**Comment by z3ntu** [comment]
This is fixed?

**Comment by jjeffryes** [comment]
This was resolved.
