### ISSUE TITLE
Homepage - Follow button

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#204]
1. Following a store from the homepage shouldn't navigate you to that node's store.... where you have to press the follow button there in order to _actually_ follow the store. 
2. When the user presses the follow button, you should immediately start following that node.
3. In the Pages tab, people you're already following shouldn't have a 'Follow' button, but an 'Unfollow' button.

I figure we're working towards this, but I'll keep it here on record.

**Comment by morebrownies** [comment]
100% agree on all points

**Comment by morebrownies** [comment]
@djbooth007 here's another good one to work on

**Comment by drwasho** [comment]
Here comes @jjeffryes kicking ass and taking names... done.
