### ISSUE TITLE
Listing - Select expiry date

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#205]
![image](https://cloud.githubusercontent.com/assets/3887694/11134500/ec334ce4-89e8-11e5-80e8-18555bcbca73.png)

I have to click the arrow (within the red square); all the space around the icon isn't selectable. It would be a great UX improvement if I could click anywhere in that square to toggle the calendar.

**Comment by morebrownies** [comment]
Difficult to do exactly what you're asking for since the arrow is a part of the input, however I did manage to make the click area larger, which should help.
