### ISSUE TITLE
Homepage - Search bar is active when tab selected

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#206]
![image](https://cloud.githubusercontent.com/assets/3887694/11134564/815fc360-89e9-11e5-9d32-09b53929bd99.png)

From a UX perspective, it distracts the user from the listing grid below.

**Comment by morebrownies** [comment]
I think it's helpful to auto focus the input so that he user doesn't have to manually do it. However, I think what you're pointing out is the focus state of an input is too bold. I'm toning it down and will push up a fix soon.
