### ISSUE TITLE
Avatar quality is too low after compression 

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#208]
We're probably going to want to double the quality on avatars, mine looks pretty bad.

<img width="118" alt="screenshot 2015-11-13 09 36 56" src="https://cloud.githubusercontent.com/assets/13066886/11151836/dbe25f4a-89f4-11e5-9630-061f20a44919.png">

**Comment by hoffmabc** [comment]
you like an old man, the Godfather.

**Comment by jjeffryes** [comment]
What does quality mean? Currently the jpeg quality is 75%, which is pretty light compression. 

We could increase the pixel size, right now it's at the size of the thumbnail, I could double it.

**Comment by morebrownies** [comment]
I'm not sure what needs to be adjusted in the code, I'm mostly just pointing out that they visually don't look great.
