### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#215]
Add a tooltip system with the following features:
- an element with a tooltip class can be added to a button or link (preferably inside, as a sibling might work too). 
- the tooltip element is hidden by default (either display: none or set to 0 height and width)
- on hover, the tooltip is shown

**Comment by jjeffryes** [comment]
Recommended solution (very basic, needs to look nicer than this):

<div class="tooltip" data-tooltip="text of tooltip">This has a tooltip</div>

.tooltip {
position: relative;
}

.tooltip:hover:before{
content: attr(data-tooltip);
position: absolute;
bottom: 10px;
display: block;
background: #ddd;
padding: 20px;
}

**Comment by morebrownies** [comment]
I'll take this one.

**Comment by morebrownies** [comment]
Added tooltips
