### ISSUE TITLE
git pre-commit hook tasks (valiquire and linting) failing

### ISSUE THREAD

**Issue by mattosborn** [OpenBazaar/OpenBazaar-Client#221]
Both failing on a clean checkout. Output below. Is this a known issue or a broken environment?
## Valiquire

[Error: Inside "/home/matt/work/OpenBazaar-Client/js/views/adminPanelVw.js"
Cannot resolve "remote" because:
Cannot find module 'remote']
[Error: Inside "/home/matt/work/OpenBazaar-Client/js/views/pageNavVw.js"
Cannot resolve "remote" because:
Cannot find module 'remote']
[Error: Inside "/home/matt/work/OpenBazaar-Client/js/views/userPageVw.js"
Cannot resolve "shell" because:
Cannot find module 'shell']
[3] require statements couldn't be resolved!
Not OK!
## Linter

✖ 1117 problems (944 errors, 173 warnings)

**Comment by jjeffryes** [comment]
This was fixed in #225
