### ISSUE TITLE
Pre-select user language in onboarding and move line item to the top of the list

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#229]
In Javascript, we can get the user's language with the following command **window.navigator.language**, which would output something similar to *_"en-US"_. 

It has been reported that **window.navigator.language** is not 100% accurate so I don't recommend we by pass the language step, but instead we can use **window.navigator.language** to autoselect the language that is likely true and move it to the top of the list. The user more so has to confirm the pre-selected option instead of digging though the list to find their language then.

I believe only one thing needs to be added to the code to get this working.

Compare **window.navigator.language** to the options on the language onboarding step. If one matches, select it and move it to the top of the list. There likely needs to be some type of mapping logic put in place as well, e.g. 

```var language = window.navigator.language;

if language === "en-US" {
  $('#sp').attr('checked', true); 
  $('.js-homeModal-languageList').prepend($('.rowItem[data-code="sp"]').parent());
}else if(...```

This introduces some light maintenance as we add new languages, but it seems worth it. 

@jjeffryes please add any thoughts you may have to this.

**Comment by jjeffryes** [comment]
This should be fairly easy to do, and would work well with how the language model already works.

**Comment by jjeffryes** [comment]
Though I should point out it will only work for languages we have already added to the client.

**Comment by morebrownies** [comment]
@djbooth007

**Comment by morebrownies** [comment]
Completed
