### ISSUE TITLE
Pre-select user's country in onboarding and move line item to the top of the list

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#230]
Similar to #229 (see detailed instructions there), I believe we can get the user's country code from **window.navigator.language**. Now we probably don't want to try to map every single country since it's a lot of tedious work, but instead we could start simple by mapping the ten most populated countries to ensure that the majority of users have an easy onboarding experience.

**Comment by jjeffryes** [comment]
As we add languages, we could probably add an assumed country.

**Comment by morebrownies** [comment]
@djbooth007

**Comment by drwasho** [comment]
Where are we on this @morebrownies

**Comment by morebrownies** [comment]
I was hoping someone in the community could help with these smaller enhancements. They're definitely low priority, but would make onboarding a bit more seamless.  Not required for launch.

**Comment by morebrownies** [comment]
Completed

**Comment by jjeffryes** [comment]
The preselect for country isn't ready yet, just the scroll part.

**Comment by drwasho** [comment]
Ready to close @jjeffryes ?

**Comment by jjeffryes** [comment]
I don't think we're doing this in v1, we'll need to do a IP lookup against a database of IPs use an online geolocation service.

We can't do it the same way we do with language, since some languages are used in multiple countries.

**Comment by jjeffryes** [comment]
Since this is a very minor feature, and the solution is both complex and may cause privacy concerns, I'm going to close this.
