### ISSUE TITLE
Pre-select user's currency in onboarding and move line item to the top of the list

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#231]
Once the user selects their country (see #230), we should have a good idea of what their currency is. 

Trying to maintain a mapping of every country to currency is a lot of tedious work, but we could start by mapping the ten most populated countries to ensure that the majority of users have an easy onboarding experience. 

For example:
```If country === "US" 
    auto select US Dollars and move to the top of the list
   else if country === "China"
    auto select Yuan and move to the top of the list

```
```

**Comment by jjeffryes** [comment]
We actually already have all of the countries and currencies mapped to each other in the countriesMd.js file. It should be relatively easy to make selecting a country also select the default currency for that country.

**Comment by morebrownies** [comment]
Completed

**Comment by jjeffryes** [comment]
Pre-selecting the user currency isn't ready yet, just the part that scrolls to the currency that is selected.

**Comment by morebrownies** [comment]
My bad.

**Comment by SamPatt** [comment]
@jjeffryes Can this be closed?

**Comment by jjeffryes** [comment]
I think we can close this. There is no good way to pre-select a currency, and I feel like there's a good chance the results would be inaccurate in any case.
