### ISSUE TITLE
Pre-select user's timezone in onboarding and move line item to the top of the list

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#232]
Similar to #229  (see detailed instructions there), I believe we can get the user's time zone from **new Date().getTimezoneOffset()**, do some comparisons against GMT and preselect the user's timezone and move it to the top of the list.

Here's a helpful blog post for more information:
http://www.onlineaspect.com/2007/06/08/auto-detect-a-time-zone-with-javascript/

Edit, this seems to be more relevant:
https://bitbucket.org/pellepim/jstimezonedetect

**Comment by zhuol** [comment]
I can help on this recently.

**Comment by zhuol** [comment]
Actually which part we should show timezone? Can you point me to the right place?

**Comment by jjeffryes** [comment]
The onboarding code is in pageNavVw.js and pageNav.html. To see the onboarding modal, go to the Admin Panel using the upper right corner menu, and click the Clear Local Storage button. That will cause the onboarding to start again.

**Comment by zhuol** [comment]
cool, I will check it.

**Comment by zhuol** [comment]
So I am gonna add a timezoneListVw.js, and put timezone detection logic there which will be used in render method of  pageNavVm.js, right?

**Comment by jjeffryes** [comment]
You can either leave the timezones hard coded (which is ok, because timezones are very unlikely to change), or you can build them the same way they are in settingsVw.js.

The logic for pre-selecting the user's timezone should happen in pageNavVw.js, in the accordionReady function.

**Comment by zhuol** [comment]
I find another issue, that the timezone we selected if not really kept.
After onboarding, if we go to settings page to check what we just selected, we can see that the timezone is not the one we picked.

**Comment by zhuol** [comment]
Here is what I am going to fix the issue for pre-select timezone:
      // pre-select timezone
      var offset = new Date().getTimezoneOffset();
      offset = '(GMT ' + (offset<0? '+':'-')+parseInt(Math.abs(offset/60)) + ':00)';
      $("[id*='"+offset+"']").prop('checked', true);

**Comment by jjeffryes** [comment]
@zhuol do you want to tackle the other part of this issue next? 

After changing the state of the user's timezone to checked, it would be ideal to scroll the js-homeModal-timeZoneList ul element so the checked timezone is at the top of the scroll area.

**Comment by zhuol** [comment]
Sure thing, I'd like to handle that as well.

**Comment by zhuol** [comment]
So it will be preferred to scroll the li inside ul instead of just putting the selected one to the top, right?

**Comment by jjeffryes** [comment]
Yes. I think that's better than changing the order of the timezones, and it achieves the same effect.

**Comment by zhuol** [comment]
Definitely, 've made the change using scrolling logic.
