### ISSUE TITLE
Question: should the chat sidebar be scrollable while minimized?

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#252]
![image](https://cloud.githubusercontent.com/assets/3887694/11551579/39be1754-99c6-11e5-9235-0c2d37b9ef87.png)

I have more chat bubbles that go down the page that I can't access. Obviously I can get them if I click a random bubble to expand the sidebar... but I'm wondering whether it can/should be scrollable? The only con is that have two scrollable elements so close to each other will get annoying.

**Comment by morebrownies** [comment]
Yes doesn't hurt to make it scrollable. I'll add this to the branch I'm
working on.

**Comment by drwasho** [comment]
Completed.
