### ISSUE TITLE
Increase Quiet Zone around QR Code in buy flow.

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#253]
The Quiet zone should be at least 4 times the width of the black squares in the QR code. 

Increase the padding around the QR code to see if this improves the ability of phones to read the code. 

This may also allow the code to be smaller.

**Comment by jjeffryes** [comment]
Also, the padding should be forced to be white, instead of picking up the custom user colors.

**Comment by hoffmabc** [comment]
I think 1x should be fine if the design necessitates. We can test.
