### ISSUE TITLE
Avatars in Followers/Following Tabs Don't Do Anything

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#254]
![screen shot 2015-12-03 at 10 14 48 am](https://cloud.githubusercontent.com/assets/45482/11566302/cbaaa8b0-99af-11e5-9644-0ccef477ac9e.png)

Clicking the avatar should go to a user's profile.
Follow should follow them.

**Comment by morebrownies** [comment]
I fixed the avatar issues on one of my branches, should be integrated soon. 

@jjeffryes is going to have to get the follow/unfollow buttons working there since that is over my head.

**Comment by morebrownies** [comment]
Or @hoffmabc you could take a stab at it too.  If you're already following the user, it should display unfollow. I believe @drwasho had a bug open for this too.

**Comment by drwasho** [comment]
Fixed.
