### ISSUE TITLE
Shipping and Return Tabs Content Issues

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#255]
Shipping  & Returns tab is showing: Ships From: UNITED_STATES. I think this is a translation issue maybe?

EstimatedDelivery no space.

![image](https://cloud.githubusercontent.com/assets/45482/11566343/f5856cec-99af-11e5-95c1-8a0643738b2d.png)

**Comment by drwasho** [comment]
Fixed by @morebrownies
