### ISSUE TITLE
Payment Type Moderators List Styling Issues

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#256]
Formatting of Payment Type moderators is kind of ugly and on Windows it wraps around and looks bad.

![image](https://cloud.githubusercontent.com/assets/45482/11566357/02b76a5a-99b0-11e5-8dee-0e92e93f57cb.png)

**Comment by drwasho** [comment]
Still an issue, and there is some inconsistency between onboarding and settings when showing data about Moderators.

![image](https://cloud.githubusercontent.com/assets/3887694/11731973/699c7ff8-9feb-11e5-9243-5e029e236c6a.png)

**Comment by drwasho** [comment]
Update on this @morebrownies ?

**Comment by morebrownies** [comment]
I'll take a spin back through the store creation process in a few days. I know there's another detail or two to polish up there as well.

**Comment by jjeffryes** [comment]
I just fixed the issue where the text is on a separate line from the thumbnail, it'll be in the PR for the branch that works with Chris's changes to the server's handling of moderators.
