### ISSUE TITLE
Direct Payment Description Bad Grammar

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#257]
Direct option description says "Send fund directly to" which is horrible grammar.

![image](https://cloud.githubusercontent.com/assets/45482/11566389/1e630e8a-99b0-11e5-8935-55c5a5413ad7.png)

**Comment by morebrownies** [comment]
@SamPatt want to help with the language here?

**Comment by SamPatt** [comment]
Sure thing.

**Comment by SamPatt** [comment]
#265 should fix this.
