### ISSUE TITLE
Order Details Screen Issues

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#258]
What is going on with that up or down UI control? They're non-functional and look odd.

Also Avatars get stretched with long addresses.

![image](https://cloud.githubusercontent.com/assets/45482/11566402/2d75d042-99b0-11e5-88d7-4d229497cea9.png)

**Comment by jjeffryes** [comment]
I don't see the arrows being flipped on my branch. There's some slightly exotic chrome css going on there, is it possible this is an OSX issue?

**Comment by hoffmabc** [comment]
Do others see it? @morebrownies ?

**Comment by morebrownies** [comment]
I haven't looked at checkout yet. I'm planning on starting on that Monday.
