### ISSUE TITLE
Scroll bar too narrow for ubuntu

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Client#266]
When you try to move the mouse over to the scroll bar it changes to the 'resize window' mouse because the scroll bar is too close to the edge.

**Comment by morebrownies** [comment]
Can you include a screenshot Chris? Will be easier to diagnose if I can see
what's going on.

**Comment by cpacia** [comment]
Print screen doesn't show the mouse. Basically it changes over to the 'resize window' mouse as soon as I move it over the scroll bar.

**Comment by drwasho** [comment]
Ping @cpacia and @morebrownies ... is this still an issue?

**Comment by SamPatt** [comment]
Yes.

**Comment by morebrownies** [comment]
I'll have this fixed in my branch early next week.

**Comment by morebrownies** [comment]
Fixed in #400

**Comment by morebrownies** [comment]
@cpacia is this good in Ubuntu now?

**Comment by morebrownies** [comment]
I'm closing for now.
