### ISSUE TITLE
Hover over user information in UI to access Block function

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#272]
This would be coupled with the server-side block API call.

**Comment by morebrownies** [comment]
I'll build in the ui elements this upcoming week and then someone can trail behind me and wire them up to the API.

**Comment by morebrownies** [comment]
The design elements are ready, needs to be wired to the API now.

**Comment by SamPatt** [comment]
Congrats on this @morebrownies @jjeffryes and @rmisio. I'm closing.

**Comment by morebrownies** [comment]
:fireworks:
