### ISSUE TITLE
Grey Theme seems jacked up

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#288]
What's up with the grey theme?

![image](https://cloud.githubusercontent.com/assets/45482/11618995/513e38e4-9c70-11e5-8ae1-c1dc383d5f0d.png)

**Comment by jjeffryes** [comment]
How did you get this result? I don't see it when I set any of the grey schemes in settings. Was it through onboarding?

**Comment by hoffmabc** [comment]
Onboarding.
