### ISSUE TITLE
User Menu not accurate

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#289]
I'm a store and I still see Become a Store and Customize Page does not work.

![image](https://cloud.githubusercontent.com/assets/45482/11619005/6d2e9760-9c70-11e5-9561-cff38cd3897b.png)

**Comment by SamPatt** [comment]
Can confirm both.

**Comment by drwasho** [comment]
- Customize page referenced in #153 
- Become a store is still an outstanding issue

**Comment by morebrownies** [comment]
@jjeffryes I took a look into the issue with the `Become a Store` link displaying even after you've become a store and when I output `<%- JSON.stringify(ob) %>` it didn't seem we have access to the vendor boolean here.

**Comment by jjeffryes** [comment]
It's probably looking in the wrong place, that code is fairly old, it needs to be updated.
