### ISSUE TITLE
Implement Force-Quit handler

### ISSUE THREAD

**Issue by gubatron** [OpenBazaar/OpenBazaar-Client#290]
<img width="420" alt="screen shot 2015-12-07 at 3 13 51 am" src="https://cloud.githubusercontent.com/assets/163977/11622097/a2ab5480-9c90-11e5-9680-dfcdfa17114f.png">

If someone tells me what should be done when force quitting I think I can take a stab at this one, it's annoying the hell out of me.

**Comment by gubatron** [comment]
should it invoke some RPC comand on the OpenBazaar-Server? like shutdown or something?

**Comment by hoffmabc** [comment]
I think the problem is its backward. It was supposed to prevent the shutdown code from occurring if the OS restarted or shut down.

**Comment by hoffmabc** [comment]
Did you git pull though it shouldn't show the alert anymore but just hang at command prompt. Either way not working completely.

**Comment by drwasho** [comment]
Fixed.
