### ISSUE TITLE
Loading Window flashes when saving settings.

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#295]
The loading window briefly flashes when saving settings. This may be a dupe but couldn't find it.

**Comment by jjeffryes** [comment]
This is a general issue with any time we take the shortcut of reloading the whole app to apply changes. That's done any time we need a view to run it's initialize function before re-rendering.

I'll take a look, I think I've updated things to where that isn't needed any more on pageNav and settings.

**Comment by jjeffryes** [comment]
Closed in #298
