### ISSUE TITLE
Suggestion: add Blockchain ID handle to chat (if they have one)

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#303]
![image](https://cloud.githubusercontent.com/assets/3887694/11643696/7687b5f4-9d91-11e5-8225-64b8597ab5dc.png)

Right now we can identity **who** we're talking to based on their avatar and GUID. I suggest we add the node's Name as the most prominent text identifier, with GUID minimized beneath it (or something like that).

Obviously a more permanent and memorable identifier would be better, from say Blockchain ID, but until that is fully integrated - or for users who choose not to register a BID - the Name should be a big help.

_Edit:_
- Changed the title of the issue from `name` to `handle`
- Replace the GUID with the Blockchain ID `handle`, which will prevent collisions and thus impersonator attacks
- Added here to we remember to do this when Blockchain ID is integrated prior to v1

**Comment by cpacia** [comment]
I think it should just be the handle. That is the only real thing that identify's you. Anyone can enter a name and avatar to impersonate you.

**Comment by SamPatt** [comment]
Are we concerned about this leading to simple impersonation attempts? With GUID at least they're need to take some effort to check.

**Comment by drwasho** [comment]
- @cpacia In principle I agree, but at the moment handles a user-generated and not registered via Blockchain ID so they're no different to Names. We shouldn't use handles at all until we can prevent collisions.
- @SamPatt That's why I suggest we keep the GUID

**Comment by cpacia** [comment]
Blockchain id will work at launch. I don't see why we would change it just for time up to launch then change it back.

**Comment by drwasho** [comment]
> Blockchain id will work at launch

Ok, if that's the case then we'll do that. Editing the issue to reflect that.

**Comment by drwasho** [comment]
Changing this to a stretch goal. We can launch the v1 test without this feature and try and incorporate it before going live on mainnet.

**Comment by jjeffryes** [comment]
I've filed an issue on the server side, get_chat_conversations doesn't return a value for avatar_hash and doesn't return handle at all, we'll need that for this feature.

**Comment by drwasho** [comment]
Working. Spectacular work @rmisio
