### ISSUE TITLE
Default avatar image missing in chat for users

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#304]
For users who haven't set an avatar image, we're not seeing the default image in the chat pane: 

![image](https://cloud.githubusercontent.com/assets/3887694/11643792/0b76466c-9d92-11e5-9d27-c044428c8104.png)

**Comment by jjeffryes** [comment]
Either I can't reproduce this, or I'm not understanding the description. I'm seeing the default image normally in the chat pane for users with no avatar.

![image](https://cloud.githubusercontent.com/assets/1584275/11647030/96fc569c-9d31-11e5-8ab5-8d9617262fd3.png)
