### ISSUE TITLE
Header image errors

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#307]
![image](https://cloud.githubusercontent.com/assets/3887694/11644331/c0dcc086-9d96-11e5-8144-0c69e83c7800.png)

This bug is triggered immediately after 'Following' or 'Unfollowing' someone and scrolling. Also, Following/Unfollowing takes 3 seconds to register in the DOM.

Edit: scrolling all the way down and then up fixes the rendering problem, but if you press 'follow/unfollow' and slowly scroll down you'll see the bug clearly.

**Comment by drwasho** [comment]
Related: when the 'Follow/Unfollow' button is pressed, the listing disappears and reappears.

**Comment by drwasho** [comment]
Same thing happens when I press 'My Page' and scroll.

**Comment by SamPatt** [comment]
Cannot replicate on Ubuntu.

**Comment by jjeffryes** [comment]
I can't replicate this on Windows either.

**Comment by drwasho** [comment]
I love these types of bugs...

**Comment by drwasho** [comment]
Video evidence: https://www.youtube.com/watch?v=O7xU3le-xEQ

**Comment by jjeffryes** [comment]
Looks like a z-index problem of some sort. I think there were some changes to z-indexes in the recent merges.

**Comment by morebrownies** [comment]
I have the same issue on Mac. I cleaned up the zindex issue on one of my branches (scrolling had been broken for weeks), but seems like it broke again on the merge.

**Comment by jjeffryes** [comment]
I can't figure out why I'm not seeing it on my machine, on the latest copy of master. Z-index issues shouldn't be platform-specific, and @drwasho is on Windows like I am.

**Comment by drwasho** [comment]
These seem to be fixed now. Well done whoever did that.
