### ISSUE TITLE
Outgoing chat messages fail with separate server/client config

### ISSUE THREAD

**Issue by djbooth007** [OpenBazaar/OpenBazaar-Client#326]
I have a Digital Ocean VPS droplet running the server and a separate virtual machine running the client off my laptop. Both server and client are Ubuntu 14.04 updated to latest git.

I can receive incoming chat messages. Server debug.log entry:
2015-12-09 17:15:20-0500 [MarketProtocol] [INFO] received a message from [redacted]

I **cannot** send any outgoing messages. There are no errors in server file debug.log

When sending a message, my response does not display in the chat window.

EDIT for more info:

From Developer Tools > Console, these two entries occur when trying to send:

/home/ubuntu/OpenBazaar-Client/js/views/chatAppVw.js:189 none found

/home/ubuntu/OpenBazaar-Client/node_modules/jquery/dist/jquery.js:5221 
GET http://159.203.91.0:18469/api/v1/get_image?hash=null&guid=10efd4f3f7903849795f8a22c3dc2d2f17e1793f 404 (Not Found)

**Comment by drwasho** [comment]
Ok the second error is because of the nodes you were talking to is not online and their avatar image was a default one (most likely). It's more or less a harmless bug.

First issue is resolved :D

**Comment by djbooth007** [comment]
Issue appears to be resolved with either recent changes (when running 'git pull') or when installing newer version of txaio:
pip install txaio==1.1.0
