### ISSUE TITLE
Grey out 'Buy Now' button when viewing your own contracts

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#329]
As the title describes.

**Comment by jjeffryes** [comment]
Recommended solution: when the user is looking at their own products, add the disabled class to the buy button. This should be done using only the template.

**Comment by morebrownies** [comment]
@drwasho How strongly do you feel about this task? The server rejects the sale downstream anyways. 

It's also helpful to see what the checkout process looks like on my store. If we disable the button completely, I could never see what it looks like.

**Comment by drwasho** [comment]
Hmm.... good point. Happy to keep it for now in that case.
