### ISSUE TITLE
Using Tab key in "Become a Store" or onboarding sections causes error

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#334]
If you are on the "Description" section in the Become a Store section and hit the Tab key, it will display this:

![image](https://cloud.githubusercontent.com/assets/6955773/11723094/65309f14-9f3a-11e5-85d4-aa5567ba66e6.png)

Tab also causes similar errors in the onboarding process.

**Comment by drwasho** [comment]
Can confirm this bug... it's been here for a while.

**Comment by drwasho** [comment]
This is still a big problem that needs to be solved sooner rather than later.
