### ISSUE TITLE
Notify user when libbitcoin server is down

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Client#336]
I updated the check_for_payment api call to return 

```
{"success": False, "reason": "libbitcoin server offline"}
```

when the libbitcoin server is down. We should probably put an error message in that top part of the order model telling them that the server is down, their coins aren't lost and the transaction will show when the server comes back online. Also point them to the settings if they want to change their libbitcoin server.

**Comment by jjeffryes** [comment]
Recommended solution:  inside js-buyWizardHero add a new section that is initially hidden with the hide class. When the offline message is received, show the hidden section with the offline message and a button with a link to #settings/advanced.

**Comment by drwasho** [comment]
Nice work @cpacia

**Comment by drwasho** [comment]
This is quite important as users will be confused as to why their transactions aren't being processed.

**Comment by drwasho** [comment]
Updated @jjeffryes ?

**Comment by jjeffryes** [comment]
@drwasho this hasn't been added yet

**Comment by drwasho** [comment]
Done and dusted.
