### ISSUE TITLE
Fix message after purchase

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#338]
After purchase a user will see this text below the order summary.

With the GUID is looks poorly formatted; the GUID should probably be on it's own line.

It should also say how many days processing will take "The expected processing time for this order is X _days_."

![image](https://cloud.githubusercontent.com/assets/6955773/11724972/26f87824-9f45-11e5-949a-29c8b9bf0142.png)

**Comment by jjeffryes** [comment]
The processing time field in the item edit is open ended, you could put "2 days", "20 hours", or "a ham sandwich" in that field, so in this interface we just dump in whatever was stored there. 

If we want to make sure it is some kind of time unit, we should change the item edit field to force time units.

**Comment by SamPatt** [comment]
Ahh didn't realize that. In that case I suggest we change the sample text in that field from "1-2 Business days" to "Time needed to process the order" or something similar.

**Comment by SamPatt** [comment]
I'll try to take care of this one myself.
