### ISSUE TITLE
Chat: remove conversations on sidebar

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#342]
Could we have a button that clears conversations on the sidebar? Aside from being a nice feature, nodes will come and go and eventually we won't be able to pull their avatars, leading to this situation:

![image](https://cloud.githubusercontent.com/assets/3887694/11732237/e246a63e-9fed-11e5-867e-ecf08adcc394.png)

**Comment by morebrownies** [comment]
Do we have an API for clearing out all of the messages in a conversation? If so I can add a line item for "Clear conversation" to the new menu I just added to the conversation window. 

<img width="253" alt="screenshot 2016-01-15 16 20 44" src="https://cloud.githubusercontent.com/assets/13066886/12366928/fc3108ce-bba3-11e5-9a48-41ffa0045974.png">

**Comment by drwasho** [comment]
Paging @cpacia and @jjeffryes

**Comment by jjeffryes** [comment]
We would need an API for this. How do we want it to work?
1. Never show the conversation again to the user (either delete it from their database, or mark it "do not show" in the database).
2. Don't show conversations past a certain age. This option should include a button to show older conversations.

**Comment by hoffmabc** [comment]
I thought we had a delete messages API already...

**Comment by jjeffryes** [comment]
We have mark as read, I don't think we have delete.

**Comment by drwasho** [comment]
Can't this be a front end trick? Ideally I'd like to keep the message history, but clear the conversations from the client.

**Comment by jjeffryes** [comment]
If we just want to hide notifications older than X, we can do that in the client. We'll just have to decide what X is, and add a button to show older notifications, possibly with paging or some other way to manage it when there are hundreds of old notifications.

**Comment by drwasho** [comment]
@jjeffryes I noticed that when a user is blocked then their chat conversation disappears. What I'm really after from this issue is the ability to remove a conversation without blocking them. The option can appear here:

![image](https://cloud.githubusercontent.com/assets/3887694/12705640/273a3a2a-c8c1-11e5-92a8-777b1b6df1c8.png)

Maybe this is something for @rmisio ?

**Comment by jjeffryes** [comment]
The trick here is if you want to mark a specific conversation as hidden, we need to save something on the server so the client knows which conversations to hide. Currently there's no api for that. 

If we only want to hide conversations based on date (ie: older than X days) we can do that just on the client.

**Comment by drwasho** [comment]
Could you hide the conversation according to the chat's subject line?

**Comment by jjeffryes** [comment]
We could hide them based on anything we want, but they would reappear the next time you started the client unless we save that data somewhere. 

We could save it to localstorage, but that means it would only work on that client, not on other clients using the same server.

**Comment by drwasho** [comment]
> We could save it to localstorage, but that means it would only work on that client, not on other clients using the same server.

I could live with that :P

**Comment by rmisio** [comment]
@drwasho @jjeffryes Doing this via localstorage is, at best, a band-aid solution. I've created a server side issue for this (which we could prioritize appropriately), which would allow us to implement a much more robust solution.

https://github.com/OpenBazaar/OpenBazaar-Server/issues/265

**Comment by jjeffryes** [comment]
There's actually a new api for deleting conversations we can use now.

**Comment by rmisio** [comment]
@morebrownies I've broken out the "Clear conversation" function into a separate issue, since that is a different thing than removing a conversation from the side bar.
https://github.com/OpenBazaar/OpenBazaar-Client/issues/971

**Comment by rmisio** [comment]
@jjeffryes No, that is something different. That allows us to delete all the messages from a conversation. Removing a conversation from the sidebar would just remove the convo (and the chat head) from the UI, but upon the next message it would come back and the message history would be in tact. That's how most of the chat apps I've used work.

**Comment by jjeffryes** [comment]
@cpacia does the delete conversation api keep the old messages, or does it completely remove them?

**Comment by jjeffryes** [comment]
This has been done.
