### ISSUE TITLE
Chat scrollbars

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#344]
One area where the new scrollbars aren't showing: 

![image](https://cloud.githubusercontent.com/assets/3887694/11732620/ac72406e-9ff1-11e5-893c-14b238a1490c.png)

**Comment by morebrownies** [comment]
Need to fix the font in that textarea too. I'll fix next week.

**Comment by morebrownies** [comment]
Fixed in #400
