### ISSUE TITLE
Visual clarity when seller does not ship to buyer country

### ISSUE THREAD

**Issue by djbooth007** [OpenBazaar/OpenBazaar-Client#345]
![ob-buy](https://cloud.githubusercontent.com/assets/16231886/11732690/bb7ce59c-9ffa-11e5-9b52-f6d7ee42ee18.jpg)

'Greyed' out theme color hides information the buyer should see clearly when seller wont ship to their country.

'buyFlow.DoesNotShipHere' to be replaced with (suggestion) red X and also in the top header:

(bold, larger font size) **Vendor does not ship to your address.**
This vendor ships to these countries
United States of America (The)

**Comment by jjeffryes** [comment]
That should actually say something along those lines, it saying buyFlow.DoesNotShipHere is a bug in the language file.
