### ISSUE TITLE
Editing contract weirdness

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#347]
![image](https://cloud.githubusercontent.com/assets/3887694/11733000/65146a18-9ff5-11e5-9aad-b54d697c0d55.png)

I haven't been able to isolate the cause of the issue yet.

**Comment by morebrownies** [comment]
Haven't run into this one yet. Let us know if you figure out how to replicate it.

**Comment by drwasho** [comment]
Seems to be fixed.
