### ISSUE TITLE
Worldwide shipping

### ISSUE THREAD

**Issue by djbooth007** [OpenBazaar/OpenBazaar-Client#351]
Sellers willing to risk posting product _anywhere_ should be able to select 'Worldwide' from countries to ship to.

Edit: Also make worldwide shipping the default selection.

**Comment by drwasho** [comment]
Just to add to this, we should include continents/regions:
1. Europe
2. Asia
3. Pacific (technically Australia, we could put Asia-Pacific/Australia)
4. Africa
5. North America
6. South America
7. Antarctica

**Comment by cpacia** [comment]
needs to match this list https://github.com/OpenBazaar/OpenBazaar-Server/blob/master/protos/countries.proto

**Comment by drwasho** [comment]
Can launch the test release without this, but should be targeted for completion before mainnet launch.
