### ISSUE TITLE
Onboarding pops up randomly

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#359]
Client started normally, went into settings and the onboarding section popped up. It also was stuck; clicking next didn't do anything. There were some errors in the dev tools:

![image](https://cloud.githubusercontent.com/assets/6955773/11757486/bb358848-a02f-11e5-8ca0-1914a7dde63b.png)

**Comment by jjeffryes** [comment]
Does this happen every time you restart the client, or only the time you set a new server in the loading screen?

**Comment by SamPatt** [comment]
I can't replicate now.

**Comment by jjeffryes** [comment]
This should have been fixed in the last commit I did to that branch. 

Keep an eye out, if no one sees it again for a day or two I'll close this issue.
