### ISSUE TITLE
Chat and notification options

### ISSUE THREAD

**Issue by djbooth007** [OpenBazaar/OpenBazaar-Client#360]
Currently, it's not possible to determine whether a user is available for chat, unless their server is offline and avatar goes default.

I propose an enhancement with the addition of a new tab in Settings called 'Messages'.

This section allows the user to configure options for both chat and also email notifications.

**CHAT**
1. enable/disable chat.
2. clear chat history
3. set idle time for away message
4. optional away message

In the client when a chat user is 'away', an orange circle is placed on their avatar in top right corner.
When user active, the circle is green. Offline, red.
For incoming messages while away, 'away message' is automatically sent to chat user when  timePassed > idleTime

**NOTIFICATIONS**
1. email address to send notification of sales (if vendor) and checkbox to turn on/off.
2. email address to send notification of purchases and checkbox to turn on/off.
3. email address to send notification of chat message (only if timePassed > idleTime) and checkbox to turn on/off.

Q: in the buy flow, is the seller notified when an order is placed or ONLY when paid ?

A seller may like to communicate with a buyer when they have ordered but not paid. OB-Server could push a chat or notification message to the seller with buyer GUID/handle and order details so they can follow the sales lead.

**Comment by morebrownies** [comment]
I generally agree with everything you pointed out. In addition, users should also have privacy features integrated into chat:
1. Only people I follow can message me
2. Anyone can message me
3. Anyone can message me, but people I do not follow have to pay $X.XX to start a conversation with me (FB/Twitter have this, but the recipient doesn't make the money, FB does).  

A lot of these features will likely have to wait until after the initial release, unless we can get more community support to help knock some of these out.

**Comment by drwasho** [comment]
I don't think email is necessary as chat messages that are sent to a user that is offline will still make it to their intended target (stored in the DHT).

I agree with the top list though. While we're at it, I'm gonna suggest OTR as an optional security/privacy feature in chat.

**Comment by mariodian** [comment]
I think email notifications are necessary. I don't always run the client, but the server is on 24/7. In this case I have no way of knowing whether I have a new sale or not.

**Comment by hoffmabc** [comment]
@mariodian email notifications will be in this next release. Only the UI piece is missing right now.

**Comment by drwasho** [comment]
Chat is going to go through a major redesign for 2.0 and we already have email notifications working. Closing this issue. Thanks everyone.
