### ISSUE TITLE
[osx] "Close Application" behaves like Hide

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#363]
The "Close Application" button from the loading screen behaves like Hide. (It hides the window, but doesn't close the application.)

![screen shot 2015-12-12 at 16 09 26](https://cloud.githubusercontent.com/assets/731743/11762791/c055e212-a0ea-11e5-865a-1f2df99c64d7.png)

**Comment by hoffmabc** [comment]
Just on OS X

**Comment by morebrownies** [comment]
Yeah, that's just how it works in OSX, not sure we can change it. Closing for now.

**Comment by hoffmabc** [comment]
On OSX applications do not close fully, they hide. I've made sure it obeys that on OSX, but acts like a native app on others.
