### ISSUE TITLE
Hitting Tab on the "Description" input box brings to hidden search input

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#365]
In "Become a store", go to "Description", press Tab, and you'll get to the following buggy state:

![screen shot 2015-12-12 at 16 36 18](https://cloud.githubusercontent.com/assets/731743/11762924/ad0bfdbe-a0ee-11e5-95ba-f21ba5f0c58a.png)

**Comment by morebrownies** [comment]
Same as #334. Closing.
