### ISSUE TITLE
[osx] In full screen mode, clicking the top-left red circle to exit leaves a blank screen

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#367]
I would add a screenshot, but it'd be all black...

**Comment by morebrownies** [comment]
I cannot replicate this. Is it still happening for you @JustinDrake?

**Comment by JustinDrake** [comment]
Yes, I can still replicate on master. Exact steps:
1. Open the client
2. Go full screen (Ctrl + Cmd + F)
3. Click on the top-left red circle
4. Observe a completely black screen (I think it's a blank Mac OS X 'desktop')

**Comment by hoffmabc** [comment]
How are you even getting it full screen?

**Comment by hoffmabc** [comment]
Oh probably because it isn't supported yet. I'll take a look.

**Comment by JustinDrake** [comment]
@hoffmabc: I go full screen via View > Toggle Full Screen. Also, you can use the shortcut Ctrl + Cmd + F.

**Comment by drwasho** [comment]
Update @JustinDrake

**Comment by drwasho** [comment]
Is this still a problem @JustinDrake or @morebrownies ?

**Comment by JustinDrake** [comment]
Full screen functionality has been removed so I cannot trigger this bug. But then full screen seems essential.

**Comment by drwasho** [comment]
@morebrownies can you check on this?

**Comment by morebrownies** [comment]
As Justin said, it seems full screen has been disabled so the problem is kind of fixed, but now the question is do people want full screen support on mac? I would think yes, but definitely seems low priority at this point.

**Comment by drwasho** [comment]
Ok no problem. I can go full screen in Windows, so enabling full screen for OSX makes a lot of sense. We can target a fix before v1 mainnet release.

**Comment by rmisio** [comment]
@drwasho Are you sure you were going into fullscreen mode on Windows or just in a maximized window state? They are two different things, with the former being "chrome-less" (i.e. minimize, maximize and close buttons disappear... at least on OSX). (Please pardon me if you totally knew that :)

Anyhow, I've got a PR in for this issue:
https://github.com/OpenBazaar/OpenBazaar-Client/pull/960

**Comment by drwasho** [comment]
Oh right, I was referring to maximised. No I can't go F11 full screen.

**Comment by rmisio** [comment]
This was fixed. It's ready for verification.

**Comment by drwasho** [comment]
Fullscreen works, some modifications are in a PR to change the keyboard shortcut (which is minor).
