### ISSUE TITLE
[osx] Hover state for 'close, minimise and maximise' circles does not appear

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#368]
In a proper Mac OS X app, the three circles go to the following on hover:

![imgres-1](https://cloud.githubusercontent.com/assets/731743/11763026/53053520-a0f2-11e5-9d38-6b6112ab248d.jpg)

With the client they stay in the default state:

![imgres](https://cloud.githubusercontent.com/assets/731743/11763028/5d294136-a0f2-11e5-9a47-30ef1b777267.jpg)

**Comment by hoffmabc** [comment]
I'm not sure Electron supports Full Screen mode yet in OSX.

EDIT: Looks like it might I'll check into it.

**Comment by morebrownies** [comment]
Fixed in misc
