### ISSUE TITLE
Help shows Electron help, not OB client help

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#369]
On Mac OS X, focus on the app, and go to 'Help > Documentation'. This brings the user to a somewhat irrelevant page:

https://github.com/atom/electron/tree/master/docs#readme

**Comment by drwasho** [comment]
Update @JustinDrake

**Comment by JustinDrake** [comment]
Still the same. All menu items are Electron.

**Comment by hoffmabc** [comment]
This needs to get changed in main.js and has not been yet. Has nothing to do with @justindrake.

**Comment by drwasho** [comment]
@hoffmabc don't forget this one

**Comment by SamPatt** [comment]
@hoffmabc Any update here? I can't test on a Mac.

**Comment by JustinDrake** [comment]
I don't see the `Help > Documentation` anymore. Closing out.
