### ISSUE TITLE
Wrong drop-down arrow state

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#370]
In Settings > General > Language, click to bring the drop-down, then click again. Notice how the arrow state is wrong when the drop-down retracts. (Points up, instead of down.)

![screen shot 2015-12-12 at 17 15 51](https://cloud.githubusercontent.com/assets/731743/11763068/04a1275c-a0f4-11e5-9f71-b7c351da49f3.png)

**Comment by morebrownies** [comment]
Fixed in 'misc' branch.
