### ISSUE TITLE
Homepage listings slow loading

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Client#375]
I think part of the reason the home page listings are slow to load is the bitcoin price conversion. Or at least that's what was mentioned before. The UI waits for the exchange rate to be returned before displaying a product. 

We should probably make that so the product is shown immediately and the price is lazy loaded. That would make the loading seem much faster. 

But it also seems there is some kind of lag loading the second (and third, fourth) round of products. The server algorithm works like this: Pick 10 random vendors. For each vendor pick three random products and push over the websocket. If less than 30 are returned, loop back around to vendors with more than 3 products and push some more. 

So there is a little delay in the websockets when the server has to loop around and get more, but on the server side the delay is like half a second. On the client side, the delay is like 5 seconds or more. 

Not sure what causes that long of a delay, unless that is also due to loading the bitcoin exchange rate.

**Comment by cpacia** [comment]
~~I just timed it. It was a 12 second delay on the client side loading the second round of products.~~

One of the vendors went offline that's why there was such a long delay. I'm going to have to try to optimize that. 

So maybe the only delay is the bitcoin price loading.

**Comment by jjeffryes** [comment]
I just ran through some timing tests, in most cases the delay between each item being received over websockets was .001-.002 seconds, with a few of them jumping to 0.2-0.3 seconds, at least on my machine..  

I tried putting in lazy loading, the new price was being set on each item before the websocket data for the next item arrived, which made no visual difference other than making it a few miliseconds slower.

**Comment by cpacia** [comment]
Then it must be vendors timing out that causes it to lag like that. Though I have seen on occasion a single product or two loads very late after the rest have loaded. 

Here's an example in this video https://www.youtube.com/watch?v=zA6s4OiyJ2A&feature=youtu.be&hd=1

**Comment by cpacia** [comment]
@jjeffryes I'm changing the server side code. It will not loop back around again now and load more products. This way if a vendor times out it doesn't look like the app is broke when items come in late. 

That does mean that you will need to query the server again (using the same message ID) when the user scrolls to the bottom because no more items will be coming without an additional query. 

Same goes for the vendor list.

**Comment by jjeffryes** [comment]
Understood.
