### ISSUE TITLE
When mouse over buttons on payment screen, elements dance around

### ISSUE THREAD

**Issue by djbooth007** [OpenBazaar/OpenBazaar-Client#378]
See video for demo.
https://www.youtube.com/watch?v=U_XHkaDv2j0

**Comment by jjeffryes** [comment]
This appears to have been resolved. @djbooth007 can you confirm whether you still see this on the latest copy of master?

**Comment by djbooth007** [comment]
I can confirm the issue has been resolved now. Latest payment flow looks good :)
