### ISSUE TITLE
Remember window state

### ISSUE THREAD

**Issue by leighman** [OpenBazaar/OpenBazaar-Client#380]
Client doesn't remember window state on subsequent opening.

You can do something like this https://github.com/leighman/OpenBazaar-Client/commit/194bc0470e71ecefee2f5c12342fc06c73417aa8

Don't know if there are any other requirements.

**Comment by hoffmabc** [comment]
I haven't tested this but I'll take a look. Also we welcome pull requests if you've got the chops to submit some patches or updates. 

What do you mean by other requirements? Like beyond window location?

**Comment by leighman** [comment]
I am happy to submit a patch and the above works for me locally but it is literally my first time trying the client so I don't know if you have a preference not to add a random new dependency or about where config should be stored.

**Comment by hoffmabc** [comment]
I think it sounds compelling and we are not afraid to bring another dependency, but it will need testing. Let me get back to you on it.

**Comment by drwasho** [comment]
Done.
