### ISSUE TITLE
Don't use frameless window on Ubuntu

### ISSUE THREAD

**Issue by leighman** [OpenBazaar/OpenBazaar-Client#381]
main.js currently uses frame: false but this looks really out of place on Ubuntu.

Would be good to be able to enable system title bar easily but don't know what way you would want to do this.

**Comment by hoffmabc** [comment]
So just to play devils advocate for a second...doesn't it look just as "out of place" on other OSs as well? I'm not a long time Ubuntu user or anything but maybe you can help me understand why this would be problematic? Or is it just an aesthetic critique?

**Comment by leighman** [comment]
It's pretty common on Windows and the existing style looks to cater to OS X. It is primarily an aesthetic critique and personally I would like to be able to easily use system window decorations but don't know what kind of patch you would be prepared to accept.

**Comment by yagoulas** [comment]
Having the button to close the window on the left part of the title bar is definitely outlandish on windows. Other than that, it is quite usual for apps to have custom title bars.

**Comment by hoffmabc** [comment]
I believe the original plan was to make the custom chrome more system dependent but it sounds like you'd really like the default chrome period. I'd like @morebrownies to comment on this since its design.

**Comment by morebrownies** [comment]
Let's hold off on changing this for now. There are a number of smaller improvements we can make across each platform instead of switching back to the default title bar.

**Comment by gubatron** [comment]
looks like this kind of things could be a preference, some people will like it to be system independent, some won't. I say make it a UI Preference if possible, if not a config flag for the launcher.
