### ISSUE TITLE
Purchases page does not appear

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#382]
I've purchased a wristband, and was told to go to my "purchases page". I tried clicking on my avatar, then going to "Purchases", but nothing happens.

![screen shot 2015-12-14 at 15 12 37](https://cloud.githubusercontent.com/assets/731743/11784644/5ed19c70-a275-11e5-8682-cdba2d81ba6f.png)

![screen shot 2015-12-14 at 15 15 49](https://cloud.githubusercontent.com/assets/731743/11784679/97346da4-a275-11e5-9810-7453ba624070.png)

**Comment by hoffmabc** [comment]
You have hit the end of the Internet. We have not pushed code beyond that point yet. Sorry!

**Comment by hoffmabc** [comment]
Ping @jjeffryes just FYI

**Comment by jjeffryes** [comment]
This is working as it should. The purchases page is in progress.
