### ISSUE TITLE
Short description should have a max char length of 160

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#384]
<img width="954" alt="screenshot 2015-12-14 11 39 06" src="https://cloud.githubusercontent.com/assets/13066886/11788564/5f7dee9e-a257-11e5-84f0-5272d47ac650.png">

Not sure if this needs to be done on the server or client.

**Comment by jjeffryes** [comment]
We'd have to do it on both sides, since people can send data directly to the API and circumvent any limits we put in the entry fields.

**Comment by jjeffryes** [comment]
In the meantime, I found a CSS way to do it. I'll put it in my next commit.

**Comment by djbooth007** [comment]
It also appears that my description got cut short at first  " double quote.

**Comment by jjeffryes** [comment]
The client side of this has been resolved. I'll open an issue in the server for the server-side part. 

The quote mark issue may be a server problem as well.
