### ISSUE TITLE
Links not opening default browser.

### ISSUE THREAD

**Issue by beatljuice** [OpenBazaar/OpenBazaar-Client#387]
I went to the "About Open Bazaar" page in the client and then clicked on the Slack channel link. I expected the link to open in my default browser (Firefox), but instead it opened in the OB client. The main problem with that is that I couldn't figure out a way to navigate away from the Slack page and had to restart the OB client.

**Comment by SamPatt** [comment]
Can replicate; doesn't open links in external browser.

**Comment by morebrownies** [comment]
<img width="1209" alt="screenshot 2015-12-14 16 50 43" src="https://cloud.githubusercontent.com/assets/13066886/11796638/d905397c-a282-11e5-8a35-656c70007e82.png">

Ran into the same thing.
