### ISSUE TITLE
Some onboarding inputs not saved

### ISSUE THREAD

**Issue by djbooth007** [OpenBazaar/OpenBazaar-Client#390]
- Timezone not saved
- Handle inputted without @ should automatically add it for user (same goes for editing Settings > Page)

These issues turned up while recording a walkthrough:
https://youtu.be/Nmibz4o11hw

**Comment by djbooth007** [comment]
When becoming a store, there should be a reminder for vendor to input their bitcoin address in Settings. 

Either during onboarding, or when creating first listing (?)

**Comment by jjeffryes** [comment]
Vendors send their bitcoin address when they confirm a purchase. 

Buyers put in a return address (if they need a refund) in settings, or the first time they purchase an item. 

Timezone is not actually used right now, it's not certain we'll keep it. 

Handle is waiting for onename integration, it may be removed or moved, depending on changes onename is working on for their API.
