### ISSUE TITLE
Add "Create Another Listing" button

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#392]
When a store is finished adding one listing, it brings them to the page viewing that listing. If they want to add another listing, it's not clear how to do that. They would need to click the Store tab again, which isn't intuitive because it's already selected:

![image](https://cloud.githubusercontent.com/assets/6955773/11826111/3fa97d4a-a351-11e5-9245-632484617ce5.png)

I suggest that we add a button just to the left of the "Edit" button that says "Create Another Listing" or something to that effect, so that it would be easier to continue adding listings in a row.

**Comment by djbooth007** [comment]
Agreed. For consistency, the button should read '+ New Listing' - same as the store page.

**Comment by drwasho** [comment]
Fixed.
