### ISSUE TITLE
Show Product Default Image Based on Category (make images optional)

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#393]
Right now a new listing won't save unless a user adds an image.

I don't think we should force this, or at the very least, I don't think that we should force digital goods or services to have an image (what does an image of a service look like?).

If a user is lazy enough that they don't want to put in proper images for their products then they'll probably just put in random garbage anyway, which doesn't help anyone.

This would require having a default (or several) image for items that have no image. I'd suggest that we have a default image for each contract type.

@morebrownies and @jjeffryes, thoughts?

**Comment by morebrownies** [comment]
I'm in agreement that photos should be optional.

**Comment by djbooth007** [comment]
+1 optional

... although, this will mess with search and listing layouts. May need a placeholder image when none is used.

**Comment by SamPatt** [comment]
> this will mess with search and listing layouts

Yes I recommend placeholders for each contract type; I assume that's easy to do @jjeffryes?

Have a man at a desk for a service contract, some high-tech looking thing for digital goods, etc. I'm sure @morebrownies could think of better ones.

**Comment by morebrownies** [comment]
Loading a different placeholder based on the contract type is pretty simple. Designing the placeholders would take more time. Actually, we could probably use the ionicons library to find icons that represent digital, service and physical item.

**Comment by morebrownies** [comment]
These could probably work with an opacity of .5 with a 1px border around the entire placeholder div.

Physical item - ion-cube
Service - ion-wrench
Digital - ion-android-download

**Comment by jjeffryes** [comment]
We've already got it set up to use the generic item image if no image is loaded, so that's easy enough. 

Setting it to use placeholders based on category shouldn't be that hard.

**Comment by jjeffryes** [comment]
One snag: currently the listings don't include the product type, so the home page and store page can't show a different icon based on type. 

We'd need to modify the get_listings and get_homepage_listings APIs to provide the product type in order to show the right icon.

**Comment by hoffmabc** [comment]
That should be trivial for @cpacia to add.

**Comment by SamPatt** [comment]
With the new badges for different products types I think this issue can be closed.
