### ISSUE TITLE
Translations do not apply to input placeholders

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#405]
See the screenshot below. The label 'Rue' is correctly translated in French, but the corresponding placeholder 'Street' is still in English.

![screen shot 2015-12-17 at 11 02 08](https://cloud.githubusercontent.com/assets/731743/11868143/bfd7154c-a4ad-11e5-8e8d-50609b14c33f.png)

**Comment by morebrownies** [comment]
@JustinDrake want to take this one on? Otherwise, I can fix when I get a chance.

**Comment by JustinDrake** [comment]
@morebrownies: Sure. Can you assign the bug report to me?
