### ISSUE TITLE
Breadcrumb should be clickable to specific category

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#408]
<img width="384" alt="screenshot 2015-12-17 08 55 13" src="https://cloud.githubusercontent.com/assets/13066886/11872631/fb31ed0e-a49b-11e5-9ecd-e5353d6ade2b.png">

@cpacia @jjeffryes Now that the category drop down is in place (looks great btw), we also need the breadcrumb links to take the user to the correct category.

**Comment by hoffmabc** [comment]
I thought these were there already. Am I misunderstanding?
![image](https://cloud.githubusercontent.com/assets/45482/11872946/0f69f258-a4a6-11e5-83bf-09634edb209b.png)

**Comment by jjeffryes** [comment]
Closed in #518
