### ISSUE TITLE
Truncated digit

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#410]
In the screenshot below, the digit '9' in the text '1 of 9' is truncated on the right by 1px or 2px.

![screen shot 2015-12-17 at 15 19 29](https://cloud.githubusercontent.com/assets/731743/11873360/f9736656-a4d1-11e5-9178-91d7e4a0a5b2.png)

**Comment by JustinDrake** [comment]
Also, I find that the text in the modal is blurred. Am I the only one that sees text in modals as much less crisp than the rest?

**Comment by morebrownies** [comment]
Which OS are you on @JustinDrake?

**Comment by JustinDrake** [comment]
Mac OS 10.10.5

**Comment by morebrownies** [comment]
The blurred text issue should be fixed in #400. We'll be deploying it to master at some point today.

**Comment by morebrownies** [comment]
Fixed
