### ISSUE TITLE
Split languagesMd.js per language

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#420]
I want to help with the French translation, but this huge languagesMd.js file put me off. (It's harder to edit and maintain.)

Can I go ahead and split languagesMd.js per language?

**Comment by jjeffryes** [comment]
I find it a lot easier to add new words/phrases when it's a single file. 

If you're comfortable rewriting the code that loads the languages in various places to dynamically load different language models, give it a shot and we'll see what it looks like. 

Alternately, you could modify the language model to load the sub-models when it is instantiated.

**Comment by morebrownies** [comment]
I tend to agree with @jjeffryes on this. I like the languages in the single file; it makes it easy to jump across all languages quickly without having to have 15 files open at once.

I see the benefits of splitting it up too, but there's probably more impactful tasks we could be spending our time on.

**Comment by Kirvx** [comment]
I think this one need to be reopened.
It can be boring to work on a file with almost 7000 lines of code for a new translator, and it does not give a quick overview of what needs to be translated for a particular language.
Also, and because of the size of the file, there is a small lag of 1-2 seconds for me with the github web editor when editing a phrase (it wastes a little time and obliges to use a text editor).

> I find it a lot easier to add new words/phrases when it's a single file.

Not a problem, you can just update the futur en.js file, and I will update the rest of the files by watching the commits :)

It would be good to do this before calling the others translators to update their translations with the upcoming release of the final version of OpenBazaar.

**Comment by JustinDrake** [comment]
I agree the current setup is not ideal. One big file will only worsen as more languages are translated.

**Comment by pryds** [comment]
I agree that the current setup is a bit clumsy and might be quite overwhelming to new translators (myself, I did reconsider before finally deciding to contribute anyway). To say it differently, a translator almost also needs to be a programmer for them to keep track of this long file, including the many opening and closing brackets, etc.

Furthermore, splitting into one file per language would most likely enable the project to use a translation platform like transifex.com (also used by Bitcoin Core, Schildbach's Android wallet, Counterparty and others) which makes it extremely user friendly for translators.

> I find it a lot easier to add new words/phrases when it's a single file.

It almost sounds like this has to be done manually? Really? [Normally](https://www.gnu.org/software/gettext/), strings are only added/changed in the code itself, and a script then makes all necessary changes in all language files.

Anyway, I understand why this might not be a priority to the devs. There are probably many other issues that need to be solved first.

**Comment by mariodian** [comment]
I'm working on it.

**Comment by mariodian** [comment]
I resolved this in #1093 the least painful way I could think of. Only languagesMd.js and js/main.js needed to be modified.

**Comment by pryds** [comment]
Very nice. No comments in the language files now, though?

**Comment by jjeffryes** [comment]
Comments are invalid in json files, unfortunately.

**Comment by mariodian** [comment]
Those are not json files though, but regular javacsript objects.
