### ISSUE TITLE
When on a user page, I'd like to know if they're following me.

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#422]
Twitter does the following:

<img width="282" alt="screenshot 2015-12-19 11 51 34" src="https://cloud.githubusercontent.com/assets/13066886/11914432/f21045de-a646-11e5-8def-e6700d603bbf.png">

We should do something similar.

**Comment by drwasho** [comment]
Hell yeah.

**Comment by drwasho** [comment]
Kickass
