### ISSUE TITLE
Settings dialog should not appear on a new client (same server)

### ISSUE THREAD

**Issue by z3ntu** [OpenBazaar/OpenBazaar-Client#423]
When you use a new client on an existing (configured) server, you have to re-do the "Welcome" window with the initial settings dialog. The only thing that should be client-specific should be the language, I think.

**Comment by drwasho** [comment]
Update @jjeffryes ?

**Comment by jjeffryes** [comment]
This will be changed with the new startup process Rob is working on.

**Comment by drwasho** [comment]
:+1:

**Comment by morebrownies** [comment]
@jjeffryes i think this is fixed, yeah?

**Comment by jjeffryes** [comment]
Yes.
