### ISSUE TITLE
Onboarding is broken

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#432]
Something is overriding accordion-child and setting the width on the first step in onboarding to 0. I changed the width in the DOM to 525px and then the next button didn't seem to work either. 

@jjeffryes any ideas what is causing the issue? I'm not seeing any errors in the console and manually changing the DOM isn't fixing it locally... Possibly a JS issue?

**Comment by Kirvx** [comment]
Same problem.

**Comment by jjeffryes** [comment]
I made a change to the show/hide script, it's possible that stuck it at 0 width. I'll take a look.

**Comment by jjeffryes** [comment]
Fixed. 

There was a timing issue where the accordion code could run before the accordion parent element was unhidden, which set the width to zero.
