### ISSUE TITLE
Create listings priced in government currency

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#439]
When creating a listing, it is only possible to add a price in BTC. Having prices dynamically adjust to peg to a government currency is essential, as Bitcoin is not a widely used unit of account.

![screen shot 2016-01-02 at 18 06 21](https://cloud.githubusercontent.com/assets/731743/12075522/8d63c0da-b17b-11e5-9751-5acf3350009e.png)

**Comment by hoffmabc** [comment]
This is possible if you change your preferred currency in settings to your govt currency.

**Comment by JustinDrake** [comment]
@hoffmabc: Cheers. (Wasn't immediately obvious for me, but not many people should set 'Bitcoin' as their preferred currency.)
