### ISSUE TITLE
Polish launch page

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#441]
See the screenshot below. Two nits:

1) The placeholder `http://serverIPorURL/api/v1/` uses an inconsistent font. (On Mac, `font-family: '.AppleSystemUIFont';`)
2) The button "Set New Server" is not properly vertically centered in the input box.

![screen shot 2016-01-03 at 19 20 05](https://cloud.githubusercontent.com/assets/731743/12080333/56f9ddc0-b24f-11e5-890b-021cbfd0cae6.png)

**Comment by morebrownies** [comment]
On my list. Might be a week or so before I get around to it.

**Comment by morebrownies** [comment]
New designs here:
https://projects.invisionapp.com/share/S55QO4KND#/screens/130236262/comments
https://projects.invisionapp.com/share/AJ5QO42BW#/screens/130236261/comments

**Comment by morebrownies** [comment]
Finished
