### ISSUE TITLE
Remove focus on illegal activity

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#443]
Is the disclaimer a legal requirement? Can't we just remove it from the onboarding sequence?

Focusing on illegal activity in the very first paragraph sheds a bad light:

```
The OpenBazaar developers do not condone - and are not responsible for - any use of the platform for illegal activity.
```

**Comment by morebrownies** [comment]
@SamPatt

**Comment by drwasho** [comment]
I tend to agree. Let's keep working on this paragraph.

**Comment by morebrownies** [comment]
@SamPatt did you want to change anything with this?

**Comment by SamPatt** [comment]
It's one line among many and I think it's important to keep. Same with disclaimers on Bittorrent clients and the like.
