### ISSUE TITLE
Slim down on-boarding process

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#444]
Is it necessary to have 9 steps in the on-boarding process?
1. Language -> OK
2. Disclaimer -> Is that necessary? See #443
3. Country -> Is that necessary? Does it affect the search results?
4. Currency -> OK
5. Timezone -> Is that necessary? How does it affect the user experience?
6. Optional
7. Optional
8. Optional
9. Optional

**Comment by morebrownies** [comment]
Country is needed for showing products that are within your region. 
Timezone is needed to show you what time a notification, chat or order came through.
Disclaimer is helpful imo as well.

**Comment by JustinDrake** [comment]
@morebrownies: It commonplace nowadays to use whatever timezone is used by the user on his OS. No need to set a different one for OpenBazaar specifically.

How can I search for products within my region? (In which part of the UI is it, or will it be?)

**Comment by morebrownies** [comment]
Agreed. The goal is to move up the timezone we think is correct to the top of the list. However, if people are using 3rd party servers or a VPN, our suggestion for their timezone will likely be incorrect and the user will need the ability to override it. 

Search is still a WIP.

**Comment by JustinDrake** [comment]
> if people are using 3rd party servers or a VPN, our suggestion for their timezone will likely be incorrect

OpenBazaar is a _native_ app, not a web app. You don't have to derive timezone from IP address. Just use the OS time!

**Comment by drwasho** [comment]
This is still a WIP and I'm going to close this issue until we feel that we've finished. Please resubmit or reopen once we go into testing.
