### ISSUE TITLE
Background UI active during on-boarding sequence

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#445]
See the attached screenshot. I'm still in the on-boarding sequence, but the settings menu is active and clickable in the background.

![screen shot 2016-01-04 at 13 07 17](https://cloud.githubusercontent.com/assets/731743/12090181/5e8988b6-b2e4-11e5-84e8-b460e73e1120.png)

**Comment by morebrownies** [comment]
This is intended. Onboarding is required.

**Comment by JustinDrake** [comment]
@morebrownies: Sure. But why can I click "Discover", "Notifications", and "User" _during_ onboarding?

**Comment by morebrownies** [comment]
We haven't disabled the click events, but the user isn't able to do anything within the menus. Super low priority imo.

**Comment by jjeffryes** [comment]
This was fixed a while ago.
