### ISSUE TITLE
Updating avatar in the settings does not immediately update top-right avatar image

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#447]
Go to Settings -> Page -> Avatar, and Select New Avatar. Notice that the top-right avatar image does not update. Restarting the client works fine.

**Comment by drwasho** [comment]
Yep this is an annoying bug. Ideally I'd like it so that we can change the Avatar when we press the `Customisations` button.

**Comment by jjeffryes** [comment]
This re-broke when I fixed the issue with the onboarding lists not being searchable.

**Comment by drwasho** [comment]
Fixed.

**Comment by cpacia** [comment]
Looks like this might be back?

Started with the default icon and didn't change when I uploaded my own. It showed correctly after restarting the client.

**Comment by jjeffryes** [comment]
I can't reproduce this. It didn't change when you clicked the save button?

**Comment by cpacia** [comment]
No it was on a new profile though. Skipped the onboarding.

**Comment by jjeffryes** [comment]
I tried the same thing, and it worked normally. Did you see any error messages?

**Comment by drwasho** [comment]
Didn't see an error message, but I can confirm this bug is back.

**Comment by drwasho** [comment]
Update: seems to be only present during on-boarding. After on-boarding, switching avatars updates straight away.

**Comment by drwasho** [comment]
I believe this has been fixed.
