### ISSUE TITLE
Item or Listing?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#449]
The client is inconsistent regarding 'Item' or 'Listing':
- Links use 'item' (e.g. `e28ffb09eaadb541d5a294f0ffc70dd448f5227d/item/c9f5ee8a25f9668be1dea60e6dbf105286de8a4c`)
- In a store, there is a 'All Listings' link.
- In 'Discover', there is also an 'All Listings' link

**Comment by morebrownies** [comment]
Good catch. @jjeffryes can you change the url structure to use 'listing' instead of 'item'? Item doesn't work for services, so we moved to a more generic term.

**Comment by JustinDrake** [comment]
I recommend using the GitHub search for 'item' and remove all instances, including variable names.

**Comment by drwasho** [comment]
@jjeffryes I've introduced a new milestone here called 'Low Priority'. It may be a little redundant with the label, but the purpose of this milestone is for you to put this at the bottom pile of things to do for v1.0 (as in this issue shouldn't interrupt your progress towards 'Feature Complete'). At the same time, this will be important for v1.0 to have, so it will need to be done at some point by someone.

**Comment by jjeffryes** [comment]
@drwasho makes sense to me.
