### ISSUE TITLE
UI for Pricing Tweak

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#45]
![image](https://cloud.githubusercontent.com/assets/45482/10485844/3ebd83ae-725a-11e5-953f-ded92dc4eff7.png)

This should not say NaN if no value is set, but should either have a placeholder or no value.

Also fiat should only go out to two decimal places I would think (i.e. $23.34 USD).

**Comment by hoffmabc** [comment]
This is on the main screen by the way.

**Comment by hoffmabc** [comment]
Ok this actually does eventually switch to (0) but I still think that:
a) While it's loading price conversion maybe it shouldnt' say NaN.
b) 0 is not really the conversion is it if there's no value set? Doesn't this imply it's free?

**Comment by jjeffryes** [comment]
Sounds like 2 issues here.
1. The price should not display while it's loading. Or it should show a loading message or symbol. 
2. We need to decide if it's ok for someone to create an item with a price of zero (or blank).

**Comment by z3ntu** [comment]
This is fixed?

**Comment by jjeffryes** [comment]
This was resolved.
