### ISSUE TITLE
Set a handle outside of the onboarding process

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#450]
A user that doesn't set a handle in the onboarding process cannot set one in the settings, and is stuck without a handle.

**Comment by drwasho** [comment]
This issue is related to Blockchain ID integration, which hasn't been started. Feel free to reopen after this feature has been supported.

**Comment by JustinDrake** [comment]
Is Blockchain ID integration scheduled for the initial release?

**Comment by drwasho** [comment]
Yes!
