### ISSUE TITLE
Zoom not disabled

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#452]
On Mac OS, two-finger pinch zooms in. Zoom should be disabled on a native app.

![screen shot 2016-01-04 at 22 39 27](https://cloud.githubusercontent.com/assets/731743/12102645/0fb3d1a6-b334-11e5-992c-c2d84f7daf16.png)

**Comment by drwasho** [comment]
I disagree. 2 finger pinch is very useful for me when I use it.

**Comment by morebrownies** [comment]
The only problem with keeping it enabled is it messes up the navigation bar when you zoom. If we could modify it to only zoom the main content then I agree with @drwasho that it's helpful.

**Comment by drwasho** [comment]
2 finger pinch is disabled in Windows, which actually annoys me a lot.

@jjeffryes your thoughts?

**Comment by jjeffryes** [comment]
Touch screens are becoming more common on Windows computers, we should account for that. 

That said, I have a touchscreen Windows computer (Surface 3), I don't think I've ever used pinch zoom for anything on it, so I didn't notice it was disabled. 

I'll have to look into what is disabling it. I don't recall purposely turning it off. It may be a system setting.

**Comment by drwasho** [comment]
Ok. In that case I'll close this issue, which requests disabling it.

**Comment by JustinDrake** [comment]
@drwasho Still not disabled for me on Mac. Please reopen.

**Comment by drwasho** [comment]
Actually we want to keep the pinch zoom.
