### ISSUE TITLE
Message dismiss arrow not clickable within bounds

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#454]
Open an individual message conversation, and notice that the X is not clickable between the X and the bounds:

![cursor2](https://cloud.githubusercontent.com/assets/731743/12103797/7aa502e2-b33d-11e5-835f-e906f59eaf68.png)

Compare this to the "Messages" X which works properly.

**Comment by morebrownies** [comment]
Fixed
