### ISSUE TITLE
Vendor or seller?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#456]
The source code uses both vendor and seller to refer to the same thing. I thought the nomenclature for the three parties is "buyer, seller and moderator".

**Comment by drwasho** [comment]
Vendor, not seller. Where exactly does it have 'seller'?

**Comment by JustinDrake** [comment]
@drwasho: If you look at [What is OpenBazaar?](https://blog.openbazaar.org/what-is-openbazaar/), the word 'seller' appears 8 times. So is the official ruling on **buyer**, **vendor** and **moderator**?

**Comment by drwasho** [comment]
I believe that article was written just before we decided the terminology would be switched to Vendor.

**Comment by drwasho** [comment]
@JustinDrake is there anything in the client where we haven't been consistent?

**Comment by JustinDrake** [comment]
@drwasho: Yes, there's [one small inconsistency](https://github.com/OpenBazaar/OpenBazaar-Client/blob/440d0f917b4afa525a0d91856b6b4cced8c0f625/js/models/languagesMd.js#L248).

BTW, when you say "we decided the terminology", is there a written document with the agreed upon terminology you can link to?

**Comment by drwasho** [comment]
> BTW, when you say "we decided the terminology", is there a written document with the agreed upon terminology you can link to?

Lost in Slack's memory hole.

**Comment by jjeffryes** [comment]
I'm closing this, the terminology in the source code doesn't have any connection to phrases used in documentation and marketing.

**Comment by JustinDrake** [comment]
The phrasing in the client is wrong for [one of the messages](https://github.com/OpenBazaar/OpenBazaar-Client/blob/440d0f917b4afa525a0d91856b6b4cced8c0f625/js/models/languagesMd.js#L248):

```
The seller's server has rejected the purchase request
```

Please reopen.

**Comment by jjeffryes** [comment]
What is wrong with that message?

**Comment by drwasho** [comment]
Vendor vs Seller terminology

**Comment by jjeffryes** [comment]
We use synonyms for a variety of words in the language file.

**Comment by JustinDrake** [comment]
@jjeffryes: Consistency is key for clear communication of core concepts to the public.

**Comment by Avery3R** [comment]
Shows up as seller in dispute resolution, http://i.imgur.com/pkgoiKa.png
