### ISSUE TITLE
Default Store Header Image Blurry

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#46]
We need to get a new updated and better default store header image.

![image](https://cloud.githubusercontent.com/assets/45482/10485921/8de298e8-725a-11e5-875e-d6bab3faface.png)

**Comment by morebrownies** [comment]
Or have default templates that users choose from so that they never hit an empty state like this.

**Comment by z3ntu** [comment]
Fixed?

**Comment by morebrownies** [comment]
Yes, users will select a theme during on boarding so the default shouldn't
really be relevant anymore. With that said, I did improve the default cover
photo too
