### ISSUE TITLE
Search within Pages

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#467]
For tracking purposes.

We have a search bar for various pages that is yet to be wired up. We can track progress here and close the issue once it's done.

**Discover Page**
- [x] Search listings
- [x] Search pages

**Chat**
- [ ] ~~Search messages~~ `defer for v1.1` 

**User Page**
- [x] Search user page listings on store tab
- [x] Search followers/following list

**Orders Page**
- [x] Search purchases
- [x] Search sales
- [x] Search cases

**Comment by jjeffryes** [comment]
Are the two bullet points for searching chat and searching messages both referring to the same thing?

**Comment by drwasho** [comment]
Fixed.

**Comment by rmisio** [comment]
The two User Page bullet points are complete and ready for QA.

**Comment by jjeffryes** [comment]
For clarification, what should search messages in chat do?

Currently, the get_chat_conversations API doesn't return anything that can be searched against, other than guid. 

Does the search filter the conversation you're looking at?

**Comment by hoffmabc** [comment]
I thought I already implemented the search for chat which is just by GUID.

**Comment by jjeffryes** [comment]
Right, is it listed here because there should be more to search by than guid?

**Comment by hoffmabc** [comment]
I mean it would be nice if we could search conversations but that's not a 1.0. Should probably just consider this completed and defer full search until later.

**Comment by morebrownies** [comment]
<img width="701" alt="screenshot 2016-01-15 08 10 19" src="https://cloud.githubusercontent.com/assets/13066886/12355021/76480b98-bb5f-11e5-9851-baec8b3ccb6e.png">

**Comment by drwasho** [comment]
Happy to see 'search by conversation' bounce to post-v1.

Search by handle to find an open conversation would be great for v1, but probably a `stretch goal`.

**Comment by drwasho** [comment]
Searching a store page doesn't seem to be working. Can someone confirm?

**Comment by jjeffryes** [comment]
It's working normally for me in the master branch.

**Comment by drwasho** [comment]
I'm on `master`, and I can't search for any keywords when I go to a store page; Discover tab is working just fine for search.

**Comment by SamPatt** [comment]
I'm closing, @morebrownies or @jjeffryes feel free to re-open if it's premature.

**Comment by drwasho** [comment]
Thanks Sam!
