### ISSUE TITLE
Reputation functions for v1.0

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#472]
The following needs to be in place for v1.0:
- [x] Design documents for showing reputation data
- [ ] Display the raw reputation summary of the user based off all _trade summaries_
- [x] Show each individual rating + written feedback for all transactions

This will require a REST API to pull the _trade summaries_ from the Vendor and potentially a WS API to find _trade summaries_ from anyone on the network who has a _trade summary_ that the Vendor isn't hosting. Does this sound right @cpacia or am I off here?

@morebrownies we'll need a design document for this; add to the pile. @jjeffryes to coordinate.

**Comment by morebrownies** [comment]
I'll have documentation ready in the next week or so. This should be the last of the documentation, yay!  :)

**Comment by morebrownies** [comment]
At least for v1 hehe

**Comment by drwasho** [comment]
Lol

**Comment by drwasho** [comment]
Spinning off the remaining task into a separate issue for us to address before mainnet launch.
