### ISSUE TITLE
Integrate Blockchain ID to register handles and connect IDs

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#473]
Let's track our progress and tasks in this issue.

**Comment by drwasho** [comment]
Nearly there with this one. If you have a registered an OpenBazaar GUID to your Blockchain ID, you can navigate to their node according to their handle! 

~~What's left~~ Deferred to future releases:
- [ ]  Register or connect to a Blockchain ID within the client
- [ ]  Register a new OpenBazaar handle within the client (if possible)

**Comment by drwasho** [comment]
For v1 we won't support registering a Blockchain ID or a handle to a blockchain ID. If we have time we'll launch a link to the browser or something.

**Comment by hoffmabc** [comment]
Actually no...I'll open a new issue.

**Comment by jonathancross** [comment]
FYI: Blockchain ID was moved to #303 and #715.
