### ISSUE TITLE
User nav is inaccurate after becoming a store

### ISSUE THREAD

**Issue by sir-pinecone** [OpenBazaar/OpenBazaar-Client#477]
Related: #289. After becoming a store I continued to see the "Become a Store" link in the user nav. This option persisted until I restarted the client app.

**Comment by jjeffryes** [comment]
I can't replicate this issue. Can up get the latest code and check it again?

**Comment by sir-pinecone** [comment]
I tried it again. It still shows it after becoming a store, but I was wrong about the persistence. It goes away after I reload the page.

**Comment by jjeffryes** [comment]
Is anyone else experiencing this?

**Comment by SamPatt** [comment]
Cannot replicate. Closing and if anyone else has the problem they can re-open.
