### ISSUE TITLE
Some required listing fields are not in the on save validation error message

### ISSUE THREAD

**Issue by sir-pinecone** [OpenBazaar/OpenBazaar-Client#480]
### Problem 1:

If I leave the item's description blank, the field name is not included in the missing fields list.

Steps:
1. Create new listing then click save (doesn't matter if you fill in fields or not): the description is not included in the error
2. Fill all required fields except description then save: the missing fields list is now empty
### Problem 2:

The missing photos error is not displayed until all other required fields have been validated. Is this intentional? Why not perform the photos check at the time of validating the other fields and then include it in the error message? Also the error message is not the same as the one displayed for all the other required fields. 

Steps:
1. Fill in some required fields but leave some blank, including the images, then save: the missing images field is not included in the error.
2. Fill all required fields except images then save: it now says:
 "Data could not be saved.
  images"

**Comment by jjeffryes** [comment]
We will be allowing users to create items with no images, the code to inject a placeholder image hasn't been created yet.

**Comment by jjeffryes** [comment]
Part 1 is still a bug, reopening.

**Comment by jjeffryes** [comment]
This was fixed.
