### ISSUE TITLE
Template Variable Not Populated [Payment Confirmation Screen]

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#485]
Your payment has been sent to _%{recipient}_ @nima. The expected processing time for this order is 1 day. You can check the status of your order on your purchases page.

![image](https://cloud.githubusercontent.com/assets/45482/12203356/73137650-b5fc-11e5-9d37-f798f91bab39.png)

**Comment by jjeffryes** [comment]
fixed
