### ISSUE TITLE
Free shipping

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#486]
The minimum shipping fee is 0.0001. What not have free shipping as an option? Free shipping is especially relevant for digital goods.

![screen shot 2016-01-08 at 16 39 28](https://cloud.githubusercontent.com/assets/731743/12203365/70c275c0-b626-11e5-92e8-c21c73ecdb0c.png)

**Comment by jjeffryes** [comment]
Free Shipping is an option, right above those two fields.

**Comment by JustinDrake** [comment]
@jjeffryes: The UI/logic is still broken. What if I want to do free domestic shipping, but charge for international shipping?

I don't understand the point of the "Free Shipping" line. (Also, I didn't notice it first time round.)

**Comment by jjeffryes** [comment]
"I don't like it" != "broken".

**Comment by JustinDrake** [comment]
@jjeffryes: How can I do free domestic shipping, but charge for international shipping?
