### ISSUE TITLE
'Clear Expiration Date' button

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#487]
The 'Clear Expiration Date' button, with the default theme, is very hard to see.

![screen shot 2016-01-08 at 16 42 07](https://cloud.githubusercontent.com/assets/731743/12203434/e2e0d412-b626-11e5-902a-c59f8b12f7c0.png)

**Comment by morebrownies** [comment]
I'll fix this on my branch
