### ISSUE TITLE
Remove 'United States of America (The)' default

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#488]
OpenBazaar is global. Having localised defaults seems wrong.

![screen shot 2016-01-08 at 16 44 32](https://cloud.githubusercontent.com/assets/731743/12203478/1c90b1a0-b627-11e5-842a-dfd237406cab.png)

**Comment by jjeffryes** [comment]
It has to be something, since that is required data.

**Comment by JustinDrake** [comment]
I respectfully disagree. The 'Title' field is also required data and isn't profiled with anything (like 'Tasty American chewing gum').

:)

**Comment by jjeffryes** [comment]
The point is that it must be a country. One must be picked by default, so no matter what someone is going to say "but that's not the right one!"

So we picked the one were most of our user base currently is.

**Comment by JustinDrake** [comment]
@jjeffryes: Still not convinced. [This issue](https://github.com/OpenBazaar/OpenBazaar-Client/issues/351) recommends adding 'Worldwide' as a shipping option.

'Worldwide' is the canonical option for a global project such as OpenBazaar.
