### ISSUE TITLE
Expiration dropdown cannot be dropped back up

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#489]
In the 'New listing' page, there is a drop-down that shows the button 'Clear Expiration Date'. When trying to make the drop-down go back up, I keep hitting the date-picker instead.

![screen shot 2016-01-08 at 16 45 34](https://cloud.githubusercontent.com/assets/731743/12203519/4fa6ad42-b627-11e5-8015-04b1727f87a7.png)

**Comment by morebrownies** [comment]
You can click away from the calendar for it to go away. Maybe I'm missing something?

**Comment by JustinDrake** [comment]
@morebrownies I'm not talking about the calendar date-picker. I'm talking about the original drop-down. Try clicking that little triangle pointing downwards.

**Comment by morebrownies** [comment]
@JustinDrake we're using the standard HTML5 datetime input. You can see it in action here: http://www.aquim.com/web-article-240.html Not much we can do at this point to change the behavior of the input other than ditching it and going with something entirely new. 

I'm going to close this for now since this doesn't really seem to be a bug, but more so a suggestion on how the standard html input behavior should be changed.

**Comment by JustinDrake** [comment]
@morebrownies: I think you've misunderstood me. Maybe it's something only on Mac OS X. There's definitely a bug here.

**Comment by JustinDrake** [comment]
@morebrownies: Here's a way to understand the bug:
1. Get the button "Clear Expiration Date" to appear.
2. Now try to hide the button again. Notice you can't.

**Comment by morebrownies** [comment]
Ok, so the "Clear Expiration Date" button doesn't hide on click? Is that the only issue?

**Comment by JustinDrake** [comment]
Not only does the "Clean Expiration Date" button not hide when the white triangle is clicked, the date picker opens instead!

**Comment by morebrownies** [comment]
Wait hang on... The triangle is intended to open the datepicker. That's how it comes by default in html5. You may want to post a screen recording to show me what is going on...

**Comment by JustinDrake** [comment]
I'm referring to the OpenBazaar triangle, not the two native html5 triangles. See the screenshot below for the triangle I am referring to:

![screen shot 2016-01-11 at 21 14 29](https://cloud.githubusercontent.com/assets/731743/12246812/8293b014-b8a8-11e5-8873-2e7f3e8f7a6f.png)

**Comment by morebrownies** [comment]
That triangle is part of the input. Again, see how it works here: http://www.aquim.com/web-article-240.html

**Comment by JustinDrake** [comment]
It seems you are right. My bad!

**Comment by morebrownies** [comment]
No worries, I agree they could have designed the input much better.
