### ISSUE TITLE
Windows: Images are not displaying correctly or at all

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#49]
- Avatar images are not displaying in the admin panel
- When I attempt to call the image directly via the browser
  - Command: `http://localhost:18469/api/v1/get_image?hash=92158530f0f4f47a061d008eeb2c919d80f1fe74`

The image looks like this:
![image](https://cloud.githubusercontent.com/assets/3887694/10500662/4544fe50-731d-11e5-9c89-9012c42f31ed.png)

**Comment by hoffmabc** [comment]
![looks good to me](http://cdn.meme.am/instances/250x250/60445340.jpg)

**Comment by drwasho** [comment]
Ok, @cpacia fixed it.
