### ISSUE TITLE
Missing notification

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#490]
Brian just followed me (I got a Mac OS X notification). This event doesn't appear in the notifications:

![screen shot 2016-01-08 at 16 59 54](https://cloud.githubusercontent.com/assets/731743/12203932/5f194346-b629-11e5-94bd-e9cb2cab8c30.png)

(BTW, notice the padding for 'No notifications' is unpleasant to the eye.)

**Comment by morebrownies** [comment]
I fixed the padding in my branch.

**Comment by drwasho** [comment]
This has been fixed.
