### ISSUE TITLE
Error: OpenBazaar@0.1.0 start: `electron main.js`

### ISSUE THREAD

**Issue by raullenchai** [OpenBazaar/OpenBazaar-Client#495]
npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! OpenBazaar@0.1.0 start: `electron main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the OpenBazaar@0.1.0 start script 'electron main.js'.
npm ERR! This is most likely a problem with the OpenBazaar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls OpenBazaar
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/raullenchai/OpenBazaar-Client/npm-debug.log

/home/raullenchai/OpenBazaar-Client/npm-debug.log has the following:
...
6 info prestart OpenBazaar@0.1.0
7 info start OpenBazaar@0.1.0
8 verbose unsafe-perm in lifecycle true
9 info OpenBazaar@0.1.0 Failed to exec start script
10 verbose stack Error: OpenBazaar@0.1.0 start: `electron main.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1016:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
11 verbose pkgid OpenBazaar@0.1.0
12 verbose cwd /home/raullenchai/OpenBazaar-Client
13 error Linux 3.19.0-33-generic
14 error argv "/usr/bin/node" "/usr/bin/npm" "start"
15 error node v0.12.9
16 error npm  v2.14.9
17 error code ELIFECYCLE
18 error OpenBazaar@0.1.0 start: `electron main.js`
18 error Exit status 1
19 error Failed at the OpenBazaar@0.1.0 start script 'electron main.js'.
19 error This is most likely a problem with the OpenBazaar package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     electron main.js
19 error You can get their info via:
19 error     npm owner ls OpenBazaar
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

This looks like https://github.com/OpenBazaar/OpenBazaar-Client/issues/151 but "sudo npm install electron-prebuilt" doesn't address the problem.

**Comment by hoffmabc** [comment]
Are you running npm install first?

**Comment by drwasho** [comment]
Hi @raullenchai ,

Thanks for posting and we're really keen on helping you out. Could you please join our [Slack group](https://openbazaar-slackin-drwasho.herokuapp.com/) for support? There are 3 channels where we handle technical support: #support-linux, #support-mac, & #support-windows

We're trying to keep Issues for fixing and requesting features in the client rather than technical support.

**Comment by redfacedquark** [comment]
Tried slack. Silence.

**Comment by hoffmabc** [comment]
We are actually working through this in #installation-issues
