### ISSUE TITLE
Selected Moderators aren't being saved during store creation (edited)

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#496]
@SamPatt confirmed this bug.

**Comment by jjeffryes** [comment]
When do you select moderators during onboarding?

Do you mean when creating a store?

**Comment by drwasho** [comment]
Sorry yes.

**Comment by drwasho** [comment]
One day I'll learn how to spell before pressing 'enter'.

**Comment by jjeffryes** [comment]
I can't reproduce this. How were you getting it to happen?

**Comment by drwasho** [comment]
Josh suggested the problem is due to a typical API response delay + bad connection. Will reopen if it's a widespread issue.

**Comment by jjeffryes** [comment]
No, that was about the issue with following people and them not being marked as followed.

Are you still seeing a problem with selecting moderators and then not seeing the same moderators saved in your settings view?

**Comment by jjeffryes** [comment]
Sorry about being unclear as to what issue I was talking about in the Slack channel.
