### ISSUE TITLE
Formatting of user text in client

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Client#497]
As far as I can tell, it is not possible to format text that a user enters for their store or items. It would be great to be able to use standard markup or html formatting commands.

**Comment by jjeffryes** [comment]
This is currently turned off to prevent malicious or annoying content (such as huge images, spam links, etc.). We have the addition of markdown and/or safe html formatting on the roadmap for future iterations. 

Duplicate of #143
