### ISSUE TITLE
Error opening app

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#500]
I can no longer open the app on Mac OS X. It fails with the following error:

![screen shot 2016-01-11 at 20 14 56](https://cloud.githubusercontent.com/assets/731743/12245378/0c26a560-b8a0-11e5-9605-556601df0908.png)

**Comment by morebrownies** [comment]
Try npm install

**Comment by hoffmabc** [comment]
you need to upgrade electron @JustinDrake .

```
npm install electron-prebuilt@0.36.2
```

**Comment by JustinDrake** [comment]
Cheers guys.
