### ISSUE TITLE
Free domestic shipping and paid-for international shipping

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#501]
The shipping fee logic does not allow for free domestic shipping and paid-for international shipping. (Can only do both free, or both paid-for.)

![screen shot 2016-01-11 at 20 33 26](https://cloud.githubusercontent.com/assets/731743/12245875/29a84258-b8a3-11e5-800e-1a51f75969cf.png)

**Comment by drwasho** [comment]
Great point. Makes sense.

**Comment by gubatron** [comment]
not sure if this is the same issue, but If I'm only shipping for a single country only (my country), it shouldn't give me an error if I don't add a price on international shipping
<img width="557" alt="screen shot 2016-02-29 at 5 32 44 pm" src="https://cloud.githubusercontent.com/assets/163977/13411344/99a622c2-df0a-11e5-909e-874e38e9ac4b.png">

**Comment by drwasho** [comment]
Yep that's important. We'll have to fix it after the testnet release.
