### ISSUE TITLE
Change "Ships to" default to Worldwide

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#502]
As a follow-up to #351, a more appropriate default for the default "Ships to" field would be Worldwide, instead of the US. (More global, more neutral.)

![screen shot 2016-01-11 at 20 40 05](https://cloud.githubusercontent.com/assets/731743/12245979/b6c767f4-b8a3-11e5-85fd-a460c5db6051.png)

**Comment by morebrownies** [comment]
It would probably be best to default to the vendor's country instead of worldwide.

**Comment by JustinDrake** [comment]
@morebrownies: :+1:

**Comment by drwasho** [comment]
Combining this with #351
