### ISSUE TITLE
Discover (Optional) -> Keywords impossible to delete when is too long

### ISSUE THREAD

**Issue by trashMeNow** [OpenBazaar/OpenBazaar-Client#503]
When inserted a long keyword, i'm no more able to delete it, because the "x" is not showed.
check red ellipse.
![image](https://cloud.githubusercontent.com/assets/9824947/12246498/a2b416d0-b863-11e5-81c1-76fa784b0dfb.png)

**Comment by drwasho** [comment]
Thanks for flagging this.
