### ISSUE TITLE
Admin Panel: Handle

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#51]
At the moment it's not obvious that the user needs to add `@` before whatever handle they want. 

![image](https://cloud.githubusercontent.com/assets/3887694/10505489/508d5fc6-7351-11e5-8266-995f0bf24d96.png)

Isn't this going to be tied to Onename's blockchain ID? If so, then I guess we'll be circling back to this issue.

**Comment by hoffmabc** [comment]
Yes it is but this is a temporary hack-in for development so validation is fine being missing right now.
