### ISSUE TITLE
Placeholder help text in top search bar

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#510]
After interacting with a user, there was some confusion when they were trying to find my node by GUID. They were entering the GUID in the wrong search bar... and I suspect visa versa could happen.

I suggest we add 'Type in GUID or Handle...' or some placeholder text in that search bar so that users know what to do.

**Comment by morebrownies** [comment]
Fix coming in my next branch

**Comment by morebrownies** [comment]
Fixed in misc3
