### ISSUE TITLE
Notifications issues.

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Client#516]
For my screen the "read" notifications are way too dark. Unreadable unless there is no light in my room except the monitor. 

Also, the "unread" notifications are not highlighted when you first click the icon. It looks like it might set them to read before loading the list?

**Comment by morebrownies** [comment]
Agreed. This is something I need to circle around to at some point and clean up.

**Comment by SamPatt** [comment]
Also a user should be able to click on an incoming notification regarding the status of an order or case (a new order, or funded, or shipped, etc) and be taken right into the modal in purchases, sales, or cases.

**Comment by morebrownies** [comment]
The visual part of this issue is finished.

**Comment by drwasho** [comment]
Done
