### ISSUE TITLE
Transactions Improvements

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#523]
The Purchases, Sales, and Cases tabs in the transactions view should be sortable by date and status.

The next action step (such as confirm order) should be visible on the orderShort subview, not only in the modal.

**Comment by jjeffryes** [comment]
Add a section to look at the JSON version of the contract.

Cases will show whether contract is valid or not. Show the reason. 

Add open dispute button.

**Comment by morebrownies** [comment]
I updated the sections to sort by most recent about a week back, so we should be good there, but we'll need to get it working with Cases too.

**Comment by drwasho** [comment]
Done
