### ISSUE TITLE
Private / Unlisted stores and items

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#524]
We need to allow users to be able to list items that aren't immediately accessible to the rest of the network. 

I think the easiest approach for listings will be the "unlisted" approach, where a listing it's visible unless you have a link and navigate directly to the product. But there are other approaches possible to achieve this.

Not sure how to approach unlisted stores.

This is largely a client issue but would also need changes to the backend, I'm not sure how extensive, @cpacia can weigh in here.

This issue is to prompt discussion of how best to accomplish this.

**Comment by morebrownies** [comment]
Very similar to #187, can probably close one of these.

**Comment by SamPatt** [comment]
Good catch Wolf. I'll close this.
