### ISSUE TITLE
Country dropdown looks odd

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#53]
![image](https://cloud.githubusercontent.com/assets/45482/10517101/470049a0-7329-11e5-865a-d04c0b06c473.png)

**Comment by morebrownies** [comment]
I've removed this in my branch. I can't think of a reason to set a location
in store creation since they already set a location during onboarding. It
seems redundant.

**Comment by hoffmabc** [comment]
ok
