### ISSUE TITLE
Drag and dropping a file into the client locks up your client

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#541]
If you accidentally drag a file into OpenBazaar, the file overtakes the entire application and leaves you stuck on this screen. 
<img width="1280" alt="screenshot 2016-01-18 20 46 26" src="https://cloud.githubusercontent.com/assets/13066886/12408291/99b08462-be24-11e5-90e1-fb577ea95274.png">

**Comment by hoffmabc** [comment]
Wow that's odd. Maybe because it's just a chromium browser window....

**Comment by jjeffryes** [comment]
Closed in #542
