### ISSUE TITLE
Enter button outside of the background

### ISSUE THREAD

**Issue by Kirvx** [OpenBazaar/OpenBazaar-Client#543]
![capture du 2016-01-19 09-41-58](https://cloud.githubusercontent.com/assets/6627786/12427260/8e58a062-bede-11e5-91d3-9288828dddbe.png)

**Comment by morebrownies** [comment]
Good catch. I need to remove the fixed height on that, my fault.

**Comment by Kirvx** [comment]
Very nice UI :thumbsup:

**Comment by morebrownies** [comment]
ty :+1:

**Comment by drwasho** [comment]
Update @morebrownies ?
