### ISSUE TITLE
There's no way to unfollow someone that is permanently offline

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#545]
This is fine for people that temporarily go offline because I can unfollow them when they come back online, but for those that never come back online, it's basically impossible for me to remove them from my following list.

**Comment by drwasho** [comment]
On the REST API side you can do it, but it's not built into the client.

**Comment by jjeffryes** [comment]
I don't believe that's correct. The unfollow doesn't complete until it receives a message back from the other user, or it did the last time Chris and I talked about it. Has that changed?

**Comment by drwasho** [comment]
Nope I'm wrong, you can't unfollow them unless they're online. That's odd, but I'm sure there's a good reason @cpacia?

**Comment by jjeffryes** [comment]
The reason is that if they are only temporarily offline, when they come back online there's no method of storing unfollows they've gotten while they were offline and applying them.

**Comment by drwasho** [comment]
We'll probably have to circle back on how to make this process better after v1 release.

**Comment by Bitfinger** [comment]
This also becomes a problem when someone deletes their old installation of OB by accident and sets up a new one... the old store will never come online again and will clog up users "Following" list. It could become quite messy.

**Comment by drwasho** [comment]
I don't believe this can be fixed (easily at least) with the current application and I'm not sure how it will work for 2.0. In any case I'm closing the issue.

**Comment by morebrownies** [comment]
Why close this? It's still an issue in the app, even if it's complex to fix.

**Comment by jjeffryes** [comment]
I think he was closing it because we're considering this a "will never fix in 1.x" issue, since the nature of how unfollowing works makes it pretty close to impossible without major changes.

**Comment by morebrownies** [comment]
Sure, but there may be other ways of going about solving the underlying UX issue. Maybe instead of a true "Unfollow" action, we could introduce an action to "Remove from list", which would allow you to follow pages, but without them displaying on your page. Something like that could be a decent short term solution while we figure out how to support Unfollowing.

**Comment by cpacia** [comment]
This will be fixed in 2.0

**Comment by jjeffryes** [comment]
This will be fixed in v2, we are not currently planning to fix it in v1.
