### ISSUE TITLE
Don't load last app state if launching with an inbound link

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#552]
If someone uses a ob: external link to launch the app, use that link instead of loading the last app state in app.js.

**Comment by drwasho** [comment]
@jjeffryes is this still in progress?

**Comment by jjeffryes** [comment]
Yes.

**Comment by drwasho** [comment]
Revisit issue when we have an updated Windows installer.

**Comment by drwasho** [comment]
@jjeffryes What's the update on this?

**Comment by jjeffryes** [comment]
@drwasho Brian is working on it.

**Comment by jjeffryes** [comment]
This has been completed.
