### ISSUE TITLE
In Discover listings view, if user has no handle, empty grey tooltip is shown

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#554]
When looking at listings on the Discover view, if a user does not have a handle, an empty grey tooltip is shown when you hover over their user icon. 

The tooltip should either not be shown, or have their guid in it.

**Comment by morebrownies** [comment]
Let's fall back to the guid.

Also is there any way to get short_description in here? It would be really helpful to do the following on hover:

handle/guid — short_description. 

I'd be very happy if we could do that. :)

**Comment by morebrownies** [comment]
@jjeffryes I can take this one. Do I have access to the short_description here?

**Comment by jjeffryes** [comment]
The data we have for each listing is this:

"contract_hash": "", 
        "origin": "", 
        "handle": "", 
        "price": , 
        "nsfw": , 
        "thumbnail_hash": "", 
        "guid": "", 
        "category": "", 
        "title": "", 
        "ships_to": [
            ""
        ], 
        "avatar_hash": "", 
        "currency_code": ""

**Comment by morebrownies** [comment]
Ok we'll have to add the description later, fix coming for the missing handle.
