### ISSUE TITLE
Prevent new follower notification spam

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#562]
I can hit the follow/unfollow button as many times as I want and it will trigger both a notification and sound on the recipients end, which can become very annoying, especially if it is abused.

We should do something clever and check the timestamp of the new follower notification, if a notification already exists from the same user, and it came within a few days of today's date, do not alert the recipient or add it to their notification tray.

**Comment by hoffmabc** [comment]
At some point we should probably have more fine-grained access to controlling notifications.

**Comment by drwasho** [comment]
Is this factored into the ban score @cpacia ?

**Comment by hoffmabc** [comment]
Is this closed because it's done?

**Comment by rabfulton** [comment]
I have been getting a lot of duplicate notifications as of late. Not the popups, but when I open notifications I see:

xxxx is now following
xxxx is now following
xxxx is now following
....

Latest server on VPS and latest client running locally.
