### ISSUE TITLE
Better reporting of timeouts on User Page

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#574]
I haven't figured out how to replicate consistently, but I've seen this several times on updated client and server.

This particular time it happened when I tried to follow a store from the store's page itself.

![screenshot from 2016-01-25 10 47 56](https://cloud.githubusercontent.com/assets/6955773/12555894/5260e66a-c351-11e5-8e0d-afc82df31bf5.png)

**Comment by jjeffryes** [comment]
For some users, one or more call on the user page is timing out. For any of the tab calls, instead of popping up the error modal, if the call fails we should put a message in the tab area saying data could not be retrieved. 

The calls are:
get_following
get_followers
get_listings

**Comment by drwasho** [comment]
I've seen this type of error from chat conversations where the node has been deleted or is offline. This is why I've been pushing for #342, apart from being a nice UX feature.
