### ISSUE TITLE
Create Store Modal: Height

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#59]
Could the height of this modal be expanded?

![image](https://cloud.githubusercontent.com/assets/3887694/10592959/02fb7b7a-7703-11e5-949e-2df2cc07a8f7.png)

**Comment by morebrownies** [comment]
Yes. I actually already have this fixed in one of my branches. Just need to do some clean up and then I'll push it up.

**Comment by drwasho** [comment]
![image](https://cloud.githubusercontent.com/assets/3887694/10593036/a6caac4e-7703-11e5-8e2b-b84b5057f335.png)
