### ISSUE TITLE
Wire up filter in following/followers tab of User View

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#592]
The select box that allows filtering followers/following by type should be coded on the following/followers tab of the User View

**Comment by jjeffryes** [comment]
This requires changes to the get_following and get_followers API calls, currently neither one returns the data needed to filter the follower or following lists.

**Comment by jjeffryes** [comment]
If the API isn't updated before launch, the select boxes for filtering should be hidden.

**Comment by drwasho** [comment]
@jjeffryes don't forget about this one... probably should remove the filter dropdown and add the `v1 mainnet requirement` tag.

**Comment by SamPatt** [comment]
@jjeffryes With the recent changes to following is this issue obsolete?

**Comment by jjeffryes** [comment]
The backend doesn't support this kind of filtering, both due to the data not being available in get_followers/get_following and due to lazy loading (ie: it could only filter the loaded data).

I recommend this be closed. We should discuss whether we want some kind of filtering/searching of followers, and what that would require in a new API.
