### ISSUE TITLE
Tooltip hidden by error message

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#602]
See screenshot. The "Discover" tooltip in the top-right corner is truncated by the error message.

![screen shot 2016-01-28 at 14 32 43](https://cloud.githubusercontent.com/assets/731743/12645723/31ecaaf4-c5cc-11e5-8bf5-474d4a034c98.png)

**Comment by jjeffryes** [comment]
This is correct behavior, if the tooltip is still open when a modal appears, it should be covered by the modal.

**Comment by morebrownies** [comment]
We're going to change these error modals in the future too, so best to just hold off on this for now.
