### ISSUE TITLE
Moderator min service fee not respected

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#603]
The client has

```
Service fee
Percentage of transaction price (max 25, min 0.001)
```

But when I put `0` service fee it is accepted.

![screen shot 2016-01-28 at 14 39 18](https://cloud.githubusercontent.com/assets/731743/12645833/f04dd572-c5cc-11e5-8f87-12a945d7f9e8.png)

**Comment by drwasho** [comment]
I would argue that Moderators should be allowed to charge nothing for their services if they feel so altruistically inclined.

**Comment by jjeffryes** [comment]
This was closed the other day, zero fees are allowed, the language just needed to be updated.

**Comment by JustinDrake** [comment]
@jjeffryes Was the language updated? Please link the to commit.
