### ISSUE TITLE
Keyword search not working

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#604]
The following item has tag #teapot:

b1fa3cd831ed7b4d7335a8408238b9902991ee5b/item/acb22bc158731182fede69459324b8c4c018e4fa

However, when I search for #teapot I get 

```
No listings found in your network tagged with #teapot
```

![screen shot 2016-01-28 at 14 45 03](https://cloud.githubusercontent.com/assets/731743/12645973/bb160e5a-c5cd-11e5-8d00-37f92a1f31bc.png)

![screen shot 2016-01-28 at 14 45 32](https://cloud.githubusercontent.com/assets/731743/12645985/cd0e9ff0-c5cd-11e5-8bcc-7684db4bb737.png)

**Comment by jjeffryes** [comment]
It takes a few seconds for the item to be searchable. If you try again, you will find the teapot.

**Comment by morebrownies** [comment]
I'm experiencing a similar issue. Washington has some items tagged as 'retro', but when I search, none of them come up.

**Comment by jjeffryes** [comment]
Ok, I can reproduce this with Wash's listings. 

The search request appears to be correct, but no listings are returned. I'll close this and repost it as a server issue.
