### ISSUE TITLE
activate-with-no-open-windows event is deprecated

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#605]
In the bash console I get the following message

```
Electron Helper[3092:254017] Couldn't set selectedTextBackgroundColor from default ()
(electron) 'activate-with-no-open-windows' event is deprecated. Use 'activate' event instead.
```

![screen shot 2016-01-28 at 14 50 02](https://cloud.githubusercontent.com/assets/731743/12646116/6efa463e-c5ce-11e5-8183-b3d51d8c25de.png)

**Comment by hoffmabc** [comment]
Already fixing this @jjeffryes
