### ISSUE TITLE
Wrong app icon on Mac OS

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#607]
On Mac OS, the app icon is that of Electron, not OpenBazaar:

![screen shot 2016-01-28 at 14 54 27](https://cloud.githubusercontent.com/assets/731743/12646242/1bd6e1a0-c5cf-11e5-860a-4153f1b915dd.png)

**Comment by hoffmabc** [comment]
This will only show properly when installed through the .app distribution.
