### ISSUE TITLE
OpenBazaar ID or GUID?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#609]
The user interface has both "OpenBazaar ID" and "GUID". To me, "GUID" is too technical for the user interface, and I would stick with just "OpenBazaar ID", which is much clearer for the average Joe.

![screen shot 2016-01-28 at 15 02 35](https://cloud.githubusercontent.com/assets/731743/12646427/52a8ffb4-c5d0-11e5-8649-af93b9e723e1.png)

**Comment by SamPatt** [comment]
I tend to agree. End users will understand OpenBazaar ID (or OpenBazaar Address) or OB ID better than GUID.

**Comment by morebrownies** [comment]
Agreed, OpenBazaar ID is probably best
