### ISSUE TITLE
Chat Message Avatar routes to who you're chatting with

### ISSUE THREAD

**Issue by wmpedersen** [OpenBazaar/OpenBazaar-Client#612]
Any avatar you click in chat routes to that user's page even if you click on your own. The goToUserProfile() in chatAppVw overrides the same code in chatMessageVw avatarClick().

I found that the first step to getting the proper GUID of the user you clicked on is to set the GUID of an outgoing chatMessage when retrieving the chat. The second step would probably be deferring goToUserProfile to avatarClick so that you're not calling the same code twice.

The code in question:
chatMessageVw.js
`avatarClick: function(){
    var targ = $('.js-navNotificationsMenu');
    targ.addClass('hide');
    $('#overlay').addClass('hide');
    Backbone.history.navigate('#userPage/'+this.model.get('guid')+'/store', {trigger: true});
  },`

chatAppVw.js
`gotoChatUserProfile: function() {
    if (this.currentChatId) {
      Backbone.history.navigate('#userPage/'+this.currentChatId+'/store', {trigger: true});
    }
  }`

**Comment by drwasho** [comment]
Fixed
