### ISSUE TITLE
What is SKU?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#614]
Never encountered SKU. Sounds cryptic.

![screen shot 2016-01-28 at 17 32 19](https://cloud.githubusercontent.com/assets/731743/12650952/1b735016-c5e5-11e5-8bbe-7a64f7c49447.png)

**Comment by morebrownies** [comment]
https://en.wikipedia.org/wiki/Stock_keeping_unit
