### ISSUE TITLE
Automatically send digital goods when payment received

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#617]
Right now a vendor selling digital goods receives payment and then manually enters a link and (optionally) a password when they confirm they've received payment.

Ideally we could automate the sending of the link and password as soon as payment is received (though probably after one or two confirmations). The vendor would obviously need to put in the link and password at the time of the listing.

@morebrownies might have ideas on how best to implement this.

I'll create a duplicate issue on the server side since it would require changes there as well.

**Comment by ulrichard** [comment]
As you're going to integrate ipfs anyway, the file could be just added to ipfs.
The hash would be revealed only when the payment verifies. This wouldn't even require a password.

**Comment by jjeffryes** [comment]
This feature is planned for v2.
