### ISSUE TITLE
Stale 'block' label on blocked user

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#621]
On a blocked user, the action label "block" should become "unblock".

![screen shot 2016-01-29 at 12 27 34](https://cloud.githubusercontent.com/assets/731743/12674515/cfba153e-c683-11e5-9604-9508461fd630.png)

**Comment by drwasho** [comment]
Gonna flag this for post v1 release.

**Comment by morebrownies** [comment]
Blocked users no longer display in chat
