### ISSUE TITLE
Message notification doesn't clear on unblocked user

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#622]
See the screenshot. I've unblocked a user, read the messages, and the messages notification (7 in an orange circle) is still there.

![screen shot 2016-01-29 at 12 30 01](https://cloud.githubusercontent.com/assets/731743/12674561/2947cbd2-c684-11e5-8cb7-8e9e166ae0c0.png)

**Comment by drwasho** [comment]
Fixed
