### ISSUE TITLE
Chat user without tooltip

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#623]
See screenshot. The little black rectangle is an empty tooltip when I hover my mouse on the chat 3rd user. I think this third user is a bug, somehow created it when having a discussion with a real user.

![screen shot 2016-01-29 at 14 46 17](https://cloud.githubusercontent.com/assets/731743/12677389/f06bd640-c698-11e5-97d1-aff1d1eca9b3.png)

**Comment by hoffmabc** [comment]
No screenshot

**Comment by JustinDrake** [comment]
@hoffmabc Ooops. Fixed.

**Comment by morebrownies** [comment]
This isn't a HTML/CSS issue. That conversation doesn't have a GUID, which seems like it should be impossible so something goofy is likely going on with the JS or API. Josh/Rob will need to take a look at this one.

**Comment by morebrownies** [comment]
@rmisio another one to make sure is fixed with the refactor

**Comment by drwasho** [comment]
Fixed
