### ISSUE TITLE
Moderator fee rounding

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#625]
Something's gone wrong with the rounding. JavaScript to blame?

![screen shot 2016-01-29 at 14 54 44](https://cloud.githubusercontent.com/assets/731743/12677309/537f992a-c698-11e5-9793-538d57b08c0d.png)

**Comment by hoffmabc** [comment]
This one we are aware of and Chris is fixing on the server side.

**Comment by JustinDrake** [comment]
@hoffmabc Cool. If possible, linking to dupes would be great.
