### ISSUE TITLE
GUI restarts when pressing Enter on moderator fee page

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#626]
To repro:

1) Open the moderator fee modal
2) Focus the service input box
3) Change the amount
4) Press Enter (do not click 'Save')
5) Notice the GUI restarts

**Comment by jjeffryes** [comment]
I can't reproduce this on Windows.

@JustinDrake what is the moderator fee page? Is it the Moderator Tab in Settings, or the Moderator Modal in the User view? 

Were elements in focus when you hit enter?

**Comment by JustinDrake** [comment]
@jjeffryes It's the modal titled "Moderator Settings".

Yes, the input box is focused when I hit enter.

**Comment by drwasho** [comment]
I can confirm this bug on Windows.
