### ISSUE TITLE
Client unresponsive with error

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#628]
The client will no longer show. (Don't know how I got it in this state.) I keep getting the following error modal:

![screen shot 2016-01-29 at 15 10 03](https://cloud.githubusercontent.com/assets/731743/12677658/d13cf1c6-c69a-11e5-8897-f80c227d7991.png)

**Comment by morebrownies** [comment]
On a mac, if you hit CMD + W you can replicate this.

**Comment by hoffmabc** [comment]
Ok it's because the app doesn't handle closing subwondows.

**Comment by drwasho** [comment]
Please update @JustinDrake if this is still an issue.

**Comment by JustinDrake** [comment]
Yes, still an issue. To repro, do CMD + W and then click on the Electron icon in the dock (on Mac).

**Comment by drwasho** [comment]
Awesome, thanks.

**Comment by drwasho** [comment]
Has this been fixed @hoffmabc or @rmisio ?

**Comment by hoffmabc** [comment]
I'll test today.

**Comment by rmisio** [comment]
@drwasho Yes, it's been fixed. Cmd + W is the command to close a window. Since our app is a one window app, upon cmd + w, I set it to quit the app.
