### ISSUE TITLE
Populate my shop from the CLI

### ISSUE THREAD

**Issue by Jzarecta** [OpenBazaar/OpenBazaar-Client#632]
Anyway to get this done? I am looking for a way to maybe process a store in a VPS and update it programmatically with new listings, update prices, and descriptions.

**Comment by drwasho** [comment]
For the moment you may have to build your own using [docopt](https://github.com/docopt/docopt) and the [REST/WS APIs](https://github.com/OpenBazaar/OpenBazaar-Server/tree/master/api).

**Comment by drwasho** [comment]
Apart from that you can host the server remotely on a VPS (like I do) and connect to it remotely with the client. Let me know if you want help with that.
