### ISSUE TITLE
Option to backup data

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#633]
Both the database itself and all the data in the folder need to be able to be backed up easily.

For extra credit we could optionally let the user sync their data to an online service, such as Dropbox or SpiderOak.

This issue is also opened on the server side:

https://github.com/OpenBazaar/OpenBazaar-Server/issues/186

**Comment by jjeffryes** [comment]
We've decided not to do this.

**Comment by SmileyChris** [comment]
This seems like an odd decision. So you lose your hdd and you've lost all your stock entries, customers, transaction history, and ratings?

**Comment by hoffmabc** [comment]
Sorry this is not clear enough. We don't plan to support it for version 1.1.x. We will be supporting backups for the next major version!
