### ISSUE TITLE
Window size shown during resize

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#638]
Look at the top-right corner in the following screenshot.

![screen shot 2016-02-01 at 15 53 08](https://cloud.githubusercontent.com/assets/731743/12720639/0bfbe37c-c8fc-11e5-9c30-628b1cbdd587.png)

**Comment by hoffmabc** [comment]
OSX? I don't recall ever seeing that.

**Comment by morebrownies** [comment]
This happens sometimes when you open Developer tools and then close it. It's a Chrome thing.

**Comment by hoffmabc** [comment]
Can I close this as developer debug info? We won't be enabling dev tools by default and if users do it they should expect that data.

**Comment by hoffmabc** [comment]
Nvm already closed.
