### ISSUE TITLE
Blocked user does not appear in the blocked list

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#639]
I just blocked someone. He doesn't appear in the blocked list...

![screen shot 2016-02-01 at 15 55 27](https://cloud.githubusercontent.com/assets/731743/12720709/49a09ace-c8fc-11e5-931f-2bb22d6bde54.png)

**Comment by morebrownies** [comment]
I can't replicate. When you log these issues can you also say how to replicate them, if possible. Ty

**Comment by JustinDrake** [comment]
To reproduce:

1) Go the the "Blocked" page, and remember the list.
2) Find someone who is not blocked.
3) Block that person.
4) Go to the "Blocked" page, and notice the list hasn't changed.

**Comment by morebrownies** [comment]
Seems to be working for me. @SamPatt @drwasho want to play around with this some more to see if you can replicate?

**Comment by SamPatt** [comment]
@morebrownies I can't replicate; when I block from discover it works fine.

However the block feature on a user's page itself doesn't seem to work.

**Comment by JustinDrake** [comment]
Aha, I'm blocking from the user's page.

**Comment by morebrownies** [comment]
Ah, yeah that one hasn't been wired yet.
