### ISSUE TITLE
Payment countdown

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#641]
A purchase quote has no countdown, which means the user may pay 30 minutes later, and the price could be significantly different.

![screen shot 2016-02-01 at 16 30 17](https://cloud.githubusercontent.com/assets/731743/12721643/1c4f593e-c901-11e5-8997-4330a63da754.png)

**Comment by drwasho** [comment]
The order essentially expires in 10 minutes if no transaction is submitted to the Bitcoin network (doesn't need to be in the block, just submitted). Handling of the unfunded order still needs work, which will probably require its own dedicated issue.

**Comment by JustinDrake** [comment]
@drwasho 

```
The order essentially expires in 10 minutes if no transaction is submitted to the Bitcoin network
```

How is this communicated to the user? Would it help to have a timer?
