### ISSUE TITLE
Padding missing on "1 blocked item not shown"

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#642]
See screenshot. A bit tight.

![screen shot 2016-02-01 at 16 38 02](https://cloud.githubusercontent.com/assets/731743/12721878/3f294fae-c902-11e5-9c18-6cb105817edf.png)

**Comment by morebrownies** [comment]
I'm going to remove this as I don't think it is needed.

**Comment by JustinDrake** [comment]
@morebrownies I was pleasantly surprised when I saw it!

**Comment by morebrownies** [comment]
Yeah, same. I'll remove it today

**Comment by jjeffryes** [comment]
I think it's useful to show the number of items blocked.

**Comment by morebrownies** [comment]
I wouldn't mind it displaying in the Blocked Settings tab, but having it always display in the top of Discover seems a bit distracting to what the user is trying to accomplish.

**Comment by morebrownies** [comment]
I removed in the branch that went live yesterday, we can revisit later on if needed.
