### ISSUE TITLE
OP interface translation

### ISSUE THREAD

**Issue by shayanb** [OpenBazaar/OpenBazaar-Client#643]
[Feature request]

Is there any plans to have a string json or any other methods to have translation of OP interface to other languages?

**Comment by jjeffryes** [comment]
We currently have this feature. Was there a specific language you're looking for?

**Comment by morebrownies** [comment]
I think this question may have been geared more towards translations on Listings and any user entered text in the client.

**Comment by jjeffryes** [comment]
Having translations in a listing would be handy, but that may get complicated, both interface and code wise. Let's remember this for a later iteration.

**Comment by shayanb** [comment]
@jjeffryes I couldn't find it by skimming the source code, where is this feature? is it automated on a set of pre-defined languages or it's possible to add more?

@morebrownies That'd be an interesting thing to add, although I was talking about the default UI.

**Comment by jjeffryes** [comment]
@shayanb you can find the language model in models/languagesMd.js. 

It currently has several translations, to create a new one copy an existing language object, translate it, and add it to the model with the BCP 47 language tag as the langCode value.

**Comment by shayanb** [comment]
cool. thanks, will add it to my day-job-procrastination-to-do-list :)
