### ISSUE TITLE
Chat sent messages go into a new conversation

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#645]
![image](https://cloud.githubusercontent.com/assets/1584275/12729120/26d80418-c8f3-11e5-9ed3-c49fd53f1d7b.png)

Sometimes when sending a chat message the new message becomes part of a new conversation with an undefined other participant rather than the original conversation.

**Comment by SamPatt** [comment]
Can replicate.

**Comment by cpacia** [comment]
Was this happening before the latest changes to the server code?

**Comment by jjeffryes** [comment]
I'm not sure. I haven't seen it before today.

**Comment by morebrownies** [comment]
@rmisio did your latest branch fix this?

**Comment by rmisio** [comment]
@morebrownies there's a good chance, it was a complete refactor. I wasn't aware of this issue, so I can't say I've tested it, but I've definitely not had it come up. I guess we'll need to keep an eye out for it. Let me know if it does come up.

**Comment by drwasho** [comment]
Fixed
