### ISSUE TITLE
Sanitize All Inputs

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#648]
We should add code to globally sanitize all inputs, rather than applying it on each input.

**Comment by rmisio** [comment]
Wouldn't it be better to do the sanitization on the server? Any type of sanitization on the client can be bypassed and potentially result in malicious code making it's way into the DB. Even if the other OB clients are cleaning that up before rendering the UI, we still have crap in the DB.

What do you think @cpacia ?

**Comment by ghost** [comment]
IMO the server needs to sanitize and validate everything, no question. But I think the client should do as much as it reasonably can before sending to the server.

**Comment by jjeffryes** [comment]
Yes. 

The plan is to sanitize outgoing data from the client, incoming data on the server, outgoing data on the server, and incoming data on the client. 

Which might be overkill, but if it's not a huge amount of effort seems worth it. 

Sanitizing outgoing data on the client is also beneficial because it should allow us to flag it before it's sent, and show the user how their data will be changed, which are both better experiences then sending it and getting back an error message or having your content changed silently when you don't expect it.

**Comment by rmisio** [comment]
Not sure if it's a huge effort to accomplish this, but it's definitely not trivial and there are some drawbacks that concern me.

I think to satisfy the req's you mentioned, a couple of things would be needed on the client:

1.) In the base view's render method, put a change handler on all inputs, which will sanitize the content. This will require all views to be updated to extend the base view and it will be critical that all their render methods call the render of the base view.

A mild concern of mine is that I've had situations where perhaps your are updating a model as input is entered (perhaps on keyup). If there's suddenly some change handler potentially updating the input later, your model would be out of sync with the displayed content. The developer would need to be aware that this handler is in place and potentially write code to account for it.

Anyways, this would accomplish sanitizing any input entered by the user (via the UI) and the fields would be updated to reflect any changes as a result of the sanitization.

2.) To accomplish sanitizing data coming from the server... We could modify the loadTemplate function to send back a wrapped version of Underscore's template function where after the template is compiled, we parse through the output and sanitize any inputs.

A mild concern with this is that we are adding some processing every time a template is rendered; we basically have to iterate through the markup, send the content of any inputs to our sanitzer, have that thing do it's thing, and then update the inputs with the sanitzed values. Granted... this is all happening off the DOM, so the processing overhead is probably not massive, but still something.

# 

Of course, none of this is going to prevent a savvy user from updating the fields via the console or sending ajax requests via the console or CURL for that matter.

Anyhow, it just seems like a good amount of overhead to account for probably a incredibly tiny set of users who will try to add in some malicious content. Why should we be so concerned with ensuring their experience regarding this is top-notch and consequently adding complexity to the client code? Just my two cents...

**Comment by drwasho** [comment]
Where are we on this?

**Comment by jjeffryes** [comment]
We've decided not to sanitize all inputs on the client side, since they are already sanitized on the server, and it can cause bugs in some cases.
