### ISSUE TITLE
Add visual indicator that client is not completed

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#657]
As we get close to feature complete status we're going to have people who want to use it for real trade, but may run into problems. They should be aware that it's not tested and we aren't calling it ready for real trade yet. We should add something visually that establishes this in the client, then remove it right before full release.

I don't know how best to do this, @jjeffryes and @morebrownies may have suggestions.

**Comment by jjeffryes** [comment]
This was completed.
