### ISSUE TITLE
User Can Follow/Block Self (Seemingly) Through Search Results

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#668]
If you search for a keyword in a product you list (i.e. #ebook) then you get the About | Follow | Block controls and you can Follow yourself with no error. It seems as though it's rejected by the backend as you don't show in your list of Following, but it's misleading in the UI.

Blocking does however add you to the list of blocked users and hides all your content. Not detrimental, but odd nonetheless.

**Comment by jjeffryes** [comment]
We will want to fix this on both the client and the server, so you can't accidentally block yourself through a script or a custom client.
