### ISSUE TITLE
Clean install: won't connect, logs `failed user ssl` in console

### ISSUE THREAD

**Issue by AronVanAmmers** [OpenBazaar/OpenBazaar-Client#68]
Latest from master. Reproduced on Windows 8.1 and Ubuntu 14.04.

Client shows:

```
http://localhost:18469/api/v1/cannot be reached.
Check your server and restart the client application
```

Console repeats:

```
/home/aron/Development/OpenBazaar/OpenBazaar-Client/js/app.js:58 4c549b00300518eaf85d48806d7fb339a020c666
/home/aron/Development/OpenBazaar/OpenBazaar-Client/js/app.js:62 Object {}
/home/aron/Development/OpenBazaar/OpenBazaar-Client/js/app.js:89 failed user ssl
```

Disabling this check (https://github.com/OpenBazaar/OpenBazaar-Client/blob/7809242c61695e27888bfa1a05a47b063ea0aa70/js/app.js#L65) makes it skip through to the product view.

**Comment by hoffmabc** [comment]
I believe this is just when you get nothing back an empty object it won't have the ssl property so it fails. This is when your server daemon is either not running, reachable or potentially a new bug @jjeffryes ?

**Comment by jjeffryes** [comment]
This was fixed in a commit yesterday, I removed the check on the settings API.
