### ISSUE TITLE
Entering my handle into the address bar redirects me to my page and then displays the GUID in the address bar

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#683]
When I enter my handle into the address and hit enter it takes me to my page correctly, but the address bar changes to the GUID instead of the handle. It should display the handle whenever possible. 

<img width="691" alt="screenshot 2016-02-09 15 08 58" src="https://cloud.githubusercontent.com/assets/13066886/12930655/2fff7bd2-cf3f-11e5-9101-bfb365c19585.png">

**Comment by jjeffryes** [comment]
Check and make sure your profile is saved in settings. 

If a handle maps to a guid on OneName, but isn't stored in your profile, the user page will use the guid instead.

**Comment by morebrownies** [comment]
Yeah it is there

**Comment by jjeffryes** [comment]
Nuts. Then I don't know why it isn't showing up.

**Comment by morebrownies** [comment]
Seems to be working correctly now
