### ISSUE TITLE
Change the maximum number of images per contract to 10

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#690]
This used to be at 10 but is recently limited to 5. This should go back to the original value.

**Comment by drwasho** [comment]
Clarification: I've found that the maximum number I can upload at one time is 5. Not sure whether this is arbitrarily set or if there is some technical basis for this limitation.

Upon further inspection, I was able to add at least 22 images to a contract. So we should enforce a limit to the number of images per contract; I suggest 10 based on my chats with Vendors on eBay and other platforms.

**Comment by jjeffryes** [comment]
Can you put this in as an issue on the server side too? We'll want to limit it on both sides.

**Comment by drwasho** [comment]
Server issue: https://github.com/OpenBazaar/OpenBazaar-Server/issues/214

**Comment by jjeffryes** [comment]
This was done.
