### ISSUE TITLE
Moderators aren't saved during on-boarding or in settings

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#699]
Tested in Linux (remote) and Windows (local). Delete your `db` and start with a fresh node. Moderators fail to be saved in the `Store` tab, irrespective of whether they're added during on-boarding or in settings.

**Comment by jjeffryes** [comment]
The data is being sent to the settings API correctly, but it doesn't appear that the backend is saving it. I think this is a server issue.

**Comment by drwasho** [comment]
This issue was fixed by Chris, but it required me to blow my database away.
