### ISSUE TITLE
Moderation of dispute failing and causing other order problems

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#701]
I managed to replicate this bug twice, with fresh nodes from the Buyer and Moderator. I couldn't use a fresh node for the Vendor because of issue #699 

**Steps:**
1. Vendor adds the Moderator node in the settings.
2. Vendor creates a new listing (physical item)
3. Buyer purchases the listing
4. Vendor confirms the order
5. Buyer files a dispute
6. Moderator attempts to close the dispute
- Adds a message
- Splits the funds 50/50
- Presses `Send`
  1. The following error is returned:

![image](https://cloud.githubusercontent.com/assets/3887694/12969470/98a54840-d0cc-11e5-8f4f-953386892085.png)

The Moderator is now unable to open the order details of that transaction or **any** transaction.

**Comment by jjeffryes** [comment]
The error message, it turned out, was just a timeout issue. That was fixed.
