### ISSUE TITLE
Is it possible to have CMD + N trigger a new version of the client to open?

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#706]
I find myself wanting to do this often so that I can look at multiple listings at once or have different sections open simultaneously.

**Comment by jonasbits** [comment]
me to

**Comment by SamPatt** [comment]
Based on the introduction of tabs in the future don't think this feature is as important and I'm closing; anyone can reopen if they feel it's still valuable.
