### ISSUE TITLE
Saved Settings Modal Message Windows is Bland

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#708]
![image](https://cloud.githubusercontent.com/assets/45482/13009584/3a38391c-d16b-11e5-9686-44bcc6c00544.png)

It looks kind of random.

**Comment by Kirvx** [comment]
+1

**Comment by morebrownies** [comment]
Agreed. I'll make it pretty when I get a chance.

**Comment by rmisio** [comment]
This issue is no longer relevant since the settings save dialog was converted into a status bar message on the bottom of the screen. Unless, that guy is also bland?

**Comment by jjeffryes** [comment]
I think it's sufficiently non-bland now.
