### ISSUE TITLE
Link to info about Blockchain ID in Settings Page tab

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#715]

**Comment by drwasho** [comment]
Misread, apologies.

**Comment by jjeffryes** [comment]
Just to clarify, the request here is to change the text of the link so instead of Check Status it is clear you can click on it to learn more about Blockchain ID?

Or should we have a 2nd link that opens a FAQ article about your handle?

**Comment by drwasho** [comment]
From our discussion with @shea256, the button will encode information that pre-fills the 'App settings' fields with `openbazaar` + `GUID` so when a user clicks the link, it opens a onename.com page, then the user clicks “save".

@morebrownies will also add something like 'Powered by Blockchain ID' underneath the `Handle` in the Settings. Perhaps 'Blockchain ID' could also link to http://blog.onename.com/blockchain-id/

Being realistic about the timeline, this will need to be added during the v1 test release, but absolutely before v1 release on the mainnet.

**Comment by morebrownies** [comment]
Very nice. I'll plan on working this in during the test phase.

**Comment by jjeffryes** [comment]
Do we have information on how to open a onename page with credentials prefilled? I don't see a way to do it with their published API.

**Comment by shea256** [comment]
Hey @jjeffryes we haven't added that yet but we will support it shortly and will circle back.

**Comment by muneeb-ali** [comment]
Is there a separate Github issue for integrating support for registering a Blockstack ID directly in the OB app? That's probably the best long-term solution, the OB users won't need to leave the app.

**Comment by hoffmabc** [comment]
I don't believe we do. I'll check.

**Comment by jjeffryes** [comment]
The info link was added. We're not currently planning to use a direct API in v1, this may be a feature in v2.
