### ISSUE TITLE
Font Color Issue in Order Details

### ISSUE THREAD

**Issue by MajorPaynei86** [OpenBazaar/OpenBazaar-Client#716]
Unable to set font color in the order details window where it doesn't default to the default font color

![screenshot from 2016-02-13 18 29 59](https://cloud.githubusercontent.com/assets/17226562/13030932/7df070fc-d288-11e5-85a1-ef4620babe39.png)

**Comment by morebrownies** [comment]
Fix coming soon

**Comment by morebrownies** [comment]
Fixed
