### ISSUE TITLE
Create store button is still showing after I make myself a vendor

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#72]
I use the Create Store button to make myself a vendor and it kicks me back to the main homepage. The Create Store button is still active until I refresh it. Looks like the view is not updating immediately.

**Comment by jjeffryes** [comment]
Which create store button? The one on the homepage, or the one on the user page?

**Comment by hoffmabc** [comment]
Homepage

**Comment by jjeffryes** [comment]
Is this bug still happening? I can't reproduce it.
