### ISSUE TITLE
Cannot start application

### ISSUE THREAD

**Issue by saltduck** [OpenBazaar/OpenBazaar-Client#727]
While I run `npm start`, a dialog like following opened. After I press the OK button, the dialog disappered and the application hanged. I have to press CTRL+C to quit it.

The error is: BrowserWindow is not a function

![2016-02-17 09 07 55](https://cloud.githubusercontent.com/assets/1237249/13096680/0f997736-d556-11e5-9066-424675033488.png)

I'm on the master branch, updated to newest commit.

**Comment by ac225519** [comment]
Hong what is your running environment ?
OS / version ?
Language / charset ?

**Comment by hoffmabc** [comment]
Did you run npm install?

**Comment by saltduck** [comment]
OS: Ubuntu 15.10 64bit Simplified Chinese(zh_CN) @ac225519 

Yes, I ran `npm install` before `npm start` @hoffmabc

**Comment by ac225519** [comment]
Please try my portable no-install build:
https://www.mediafire.com/folder/mpjxf3cocpof7/OpenBazaar_Test_LINUX_Builds

**Comment by saltduck** [comment]
I delete node_modules subdir and reinstall npm packages. It works.
