### ISSUE TITLE
Different image for chat

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#737]
The Duo Money store (66e1f65cb122df9f1a7295ec37ddf2c289a91fa4/about) has a single image (the logo) for the store.

In the store's main page, the logo looks good. In chat mode, the logo is really small and a different image is required.

Can we have two separate images, one for the storefront, and one for the chat?

**Comment by morebrownies** [comment]
This seems like it has the potential to really confuse users. If I choose an image for chat that is completely different than what I use as my avatar on my page, users will not be able to easily identify who they're talking to.
