### ISSUE TITLE
Need to click "Discover" twice

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#738]
The "Discover" pane is acting a little funny. It's very reproducible for me:
- Click "Discover"
- Click on any listing
- Click "Discover" -> Notice no results show up
- Click "Discover" -> Notice listings show up properly

**Comment by morebrownies** [comment]
Not happening for me. @SamPatt @drwasho please test and close if you cannot replicate

**Comment by drwasho** [comment]
I think any problems 4 days ago related to this issue have been fixed.
