### ISSUE TITLE
Style the loading widget

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#74]
This looks mighty horrible at the moment. Get to it when you can.

![image](https://cloud.githubusercontent.com/assets/45482/10695647/c4b5d8e8-7972-11e5-83cd-67944a867cf1.png)

**Comment by jjeffryes** [comment]
Which OS is that on? It is aligned on Windows.

**Comment by morebrownies** [comment]
It is aligned on my mac too

**Comment by hoffmabc** [comment]
Both OSX and Linux it looks like this.

**Comment by hoffmabc** [comment]
I'll check to make sure I have latest code.

**Comment by hoffmabc** [comment]
Fixed.
