### ISSUE TITLE
Back button logic broken

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#740]
Steps to reproduce:
- Click "Buy" on any item
- Answer "Do you have a Bitcoin wallet?" with "Yes"
- Click "Back"
- Notice you are now (incorrectly) on the "Create a wallet" page

**Comment by drwasho** [comment]
95% sure @jjeffryes fixed this recently. Please reopen if it isn't.

**Comment by JustinDrake** [comment]
@drwasho I don't have reopen rights.
