### ISSUE TITLE
Clarify refund address

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#741]
I find the pane "Enter your Bitcoin Address" confusingly titled. Two issues:
- it's not clear from the title that a refund address is required
- one does not have a unique Bitcoin address

I suggest changing the title to "Refund Address".

![screen shot 2016-02-19 at 19 28 47](https://cloud.githubusercontent.com/assets/731743/13184953/07e950ca-d73f-11e5-97c1-afbd1dfdb765.png)

Same goes in the Settings page:

![screen shot 2016-02-19 at 20 45 18](https://cloud.githubusercontent.com/assets/731743/13187123/c1b89e70-d749-11e5-905d-c2bbe14ca63e.png)

Would rename to "Refund Address"

**Comment by morebrownies** [comment]
The thing is if you're unsure what "refund address" means and you google "Bitcoin refund address" it doesn't point you in the right direction. The user at this point is entering a bitcoin address that so happens to be used for refunds, so I think the current language is accurate. We had exactly what you're suggesting before and it was confusing people. We'll have to keep an eye on this once we launch, and longer term we can completely remove this if/when we integrate a wallet into the client.

**Comment by JustinDrake** [comment]
@morebrownies Very interesting comment. I'll definitely keep an eye on user behaviour.
