### ISSUE TITLE
URL bookmark tooltip broken

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#742]
Please see screenshot. The tooltip is visibly broken (e.g. the black background).

![screen shot 2016-02-19 at 19 29 51](https://cloud.githubusercontent.com/assets/731743/13184997/43a8280c-d73f-11e5-81f2-ac5744acffad.png)

**Comment by morebrownies** [comment]
@jjeffryes any idea what broke this?

**Comment by jjeffryes** [comment]
Fixed in the last PR.
