### ISSUE TITLE
Message counter reappears after a search

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#743]
Steps to reproduce:
- Pick a chat conversation with a counter
- Clear the counter
- Type something in the search bar
- Clear the search bar
- Notice the chat conversation counter reappears (see "27" in screenshot)

![screen shot 2016-02-19 at 19 32 02](https://cloud.githubusercontent.com/assets/731743/13185088/9ddd8b3c-d73f-11e5-8532-3de9830baa4f.png)

**Comment by morebrownies** [comment]
@rmisio we should make sure this is fixed too

**Comment by morebrownies** [comment]
Actually this is related to #284
