### ISSUE TITLE
Black on black

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#744]
The texts "Type a name..." and "Enter message..." are black on a black background, making them hard to read.

![screen shot 2016-02-19 at 19 54 38](https://cloud.githubusercontent.com/assets/731743/13185686/bee1d218-d742-11e5-9829-b049168fc00a.png)

**Comment by ac225519** [comment]
Preventing the same text/background colour (and add a minimum diff. to make it at least visible or refuse loading at all) should be part of the theme loading code.

**Comment by morebrownies** [comment]
Fixed
