### ISSUE TITLE
Image displays with a glitch

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#745]
Steps to reproduce:
- Go to b68b2252c74d0e68e4a9e6c5d7219076559ca98f/item/af9442b7586b79b83d2102dc8be695301d8496ab
- Click the wallpaper image
- Notice it appears in two fast and glitchy steps

![screen shot 2016-02-19 at 19 58 09](https://cloud.githubusercontent.com/assets/731743/13185768/21e03b02-d743-11e5-846a-fd2dbba22a19.png)

**Comment by drwasho** [comment]
Please recheck to see if this bug is still a problem.

**Comment by JustinDrake** [comment]
Yes, still an issue, on all images.

**Comment by drwasho** [comment]
Can you describe exactly what the glitch is? I'm not sure what I should be seeing.

**Comment by JustinDrake** [comment]
(I can't seem to connect to the OB network now.) The glitch occurs when clicking a listing image to enlarge it. When doing so, the image appears in two steps where the first step lasts a fraction of a second and is just a few pixels off from the second step.

It's possible that this is related to the way the scrollbars disappear in Mac OS X, and hence only reproducible on Mac OS X.

**Comment by drwasho** [comment]
Make sure you `git checkout v0.1.0-rc2` for the server.

**Comment by drwasho** [comment]
Please retest @JustinDrake
