### ISSUE TITLE
Duplicate hashes

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#746]
Check out here: b68b2252c74d0e68e4a9e6c5d7219076559ca98f/item/af9442b7586b79b83d2102dc8be695301d8496ab

The item's tags have two hashes:

![screen shot 2016-02-19 at 19 59 35](https://cloud.githubusercontent.com/assets/731743/13185802/52bb24ee-d743-11e5-89c0-579558db93fa.png)

**Comment by drwasho** [comment]
Feature, not a bug.

**Comment by hoffmabc** [comment]
This would be if someone actually typed the hash marks though correct? Is that confusing @drwasho?

**Comment by drwasho** [comment]
Yep, they'd have to type in the extra hash to make that happen. I was being facetious, we should auto remove the extra hash.
