### ISSUE TITLE
Add ability to move the header image around and pick the area you like

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#75]
This should work like Facebook and Twitter's functionality.

![image](https://cloud.githubusercontent.com/assets/45482/10695678/f15164b2-7972-11e5-844d-d15361d15011.png)

**Comment by jjeffryes** [comment]
The best way to do this would be to switch to base64 encoding of the images so we can crop and resize them.

**Comment by jjeffryes** [comment]
Closed in #154
