### ISSUE TITLE
Visual glitch

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#750]
To repro go to: eed93b940f260e87ae59d5d05dd57daa81ca9563/following

Click on "All types" and select it. Notice an extraneous gray line:

![screen shot 2016-02-19 at 20 08 24](https://cloud.githubusercontent.com/assets/731743/13186093/b19d4ff4-d744-11e5-9944-0224eaac20ff.png)

**Comment by drwasho** [comment]
Can't reproduce. Please reopen if you see the bug again.

**Comment by JustinDrake** [comment]
@drwasho: Please don't do this. I don't have reopen rights.

**Comment by drwasho** [comment]
Is the bug still there?

**Comment by drwasho** [comment]
I can't reproduce this error so I'm going to leave it closed.
