### ISSUE TITLE
Wording issue

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#751]
The "Licensing" pane has the following text:

```
OpenBazaar is open source software using the MIT license.
```

I believe it's standard to write "under the MIT license" not "using the MIT license".

**Comment by morebrownies** [comment]
@SamPatt

**Comment by drwasho** [comment]
@SamPatt

**Comment by drwasho** [comment]
@SamPatt and @morebrownies

**Comment by morebrownies** [comment]
I'm happy to change this. @SamPatt just let me know what you want me to change.

**Comment by SamPatt** [comment]
@morebrownies That's fine to change it to:

> OpenBazaar is open source software under the MIT license.

**Comment by morebrownies** [comment]
Fixed
