### ISSUE TITLE
Don't know why I get this "Caution" message

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#754]
Randomly got this:

![screen shot 2016-02-19 at 20 16 20](https://cloud.githubusercontent.com/assets/731743/13186260/b607e206-d745-11e5-9548-4177d950237b.png)

**Comment by morebrownies** [comment]
We're going to have to circle back and clean this up after launch. The modal was put in place to give the user a chance to write down their credentials. Both Josh and I agree the UX is bad, but there's not a simple work around at the moment.
