### ISSUE TITLE
Hide "Store" under Settings when not a store

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#756]
When not a store, the "Store" pane in Settings is still shown. This is somewhat confusing, and not explained.

Can the "Store" pane simply be hidden away for non-store nodes?

![screen shot 2016-02-19 at 20 23 03](https://cloud.githubusercontent.com/assets/731743/13186457/9d064972-d746-11e5-9c84-311a800a8e85.png)

**Comment by drwasho** [comment]
Chatting with Josh last night and he mentioned that he's already set this occur once we're ready for production release.
