### ISSUE TITLE
Pressing "Tab" brings you to a strange place

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#757]
To repro:
- To go "Become a store"
- Press the Tab key twice
- Notice you're in a funny place (see screenshot)

![screen shot 2016-02-19 at 20 33 05](https://cloud.githubusercontent.com/assets/731743/13186803/25ce7b52-d748-11e5-85ce-1a59ea4e0c4b.png)

**Comment by drwasho** [comment]
Can you see if this has been fixed with the latest code commits?
