### ISSUE TITLE
Remove mock "Feed" page

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#758]
In anticipation of the Testnet release on March 1st, should the mock "Feed" page be removed?

![screen shot 2016-02-19 at 20 47 32](https://cloud.githubusercontent.com/assets/731743/13187204/1de5982e-d74a-11e5-8d2a-912635edb6e3.png)

**Comment by morebrownies** [comment]
Ok. I think i'm convinced to remove this for now
