### ISSUE TITLE
Remove Admin Panel

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#759]
In anticipation of the March 1st testnet release, should the Admin Panel be removed?

![screen shot 2016-02-19 at 20 49 10](https://cloud.githubusercontent.com/assets/731743/13187292/a5ec0528-d74a-11e5-9740-e08edfb13c25.png)

**Comment by jjeffryes** [comment]
It will be removed when testing is completed, and the vendor true/false code has been added to settings.

**Comment by morebrownies** [comment]
Duplicate #658
