### ISSUE TITLE
Change the placeholder if no listings found

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#760]
See screenshot. I pressed the "Discover" button, and it interpreted the search as a tag search:

![screen shot 2016-02-19 at 20 54 19](https://cloud.githubusercontent.com/assets/731743/13187399/15fd635c-d74b-11e5-8adc-08196e74df25.png)

**Comment by drwasho** [comment]
You must have lost connectivity.

**Comment by JustinDrake** [comment]
The bug here is the sentence abruptly ends with "tagged with" (see screenshot). Please reopen.

**Comment by drwasho** [comment]
Ok, that wasn't clear from the issue description so we discussed fixing another problem.

**Comment by rmisio** [comment]
this is fixed, please validate.

**Comment by drwasho** [comment]
Fixed.
