### ISSUE TITLE
Internationalization (translation) using e.g. gettext

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#761]
Internationalization ought to be done using proper i18n methods. The current practice of adding to a huge file of more or less static strings has several downsides, although it may seem to work for some languages -- especially languages that resemble English a lot.

One of the oldest and most widely used systems for i18n in the open source world is GNU Gettext. It has support for even languages with very complex structures and grammar, and it comes with tools that makes the process a lot easier for developers, e.g. when new strings are added or old ones are changed, and some of them may or may not already have been translated. There are other systems as well that would handle this just as well as Gettext.

Here are some examples of potential problems that systems like Gettext would solve:
- While in English, "." is normally used as a digit separator and "," is a thousands separator, in many other languages, it is quite the opposite. So "10,000,000.00" would be "10.000.000,00". This is potentially ambiguous; if a user has set their language to one that uses "," as digit separator, how would they interpret the following bitcoin amount: "1.000" -- as 1 BTC or as 1000 BTC? Gettext solves this without the individual dev should take any special care, other than to make sure to use Gettext to show amounts.
- With Gettext, variables (ints, floats, strings, ...) can be used inside strings, and in a translated string a variable doesn't have to be placed in the same position as in the English string. This eliminates the need for pre- or postfixing variables like these current strings, where the prefixes might need to go inside the string for it to make sense in that particular grammar:
  
  > NotificationFollow: "is now following you",
  > NotificationDispute: "has opened a new dispute",
  > NotificationNewOrder: "has made a purchase",
- Problems with plural forms is bound to arise if a system like Gettext is not used. Here I refer to the fact that grammar changes with any numeral variable in the string, e.g. "1 house", "2 houses". Apparently this has been attempted fixed where needed by introducing two strings, one for singular and one for plural. While this works nicely for English, remember that some languages work very differently from English. Even in French, which is not very different from English, grammar wise, we have a problem, since in English plural form is used for zero ("0 houses"), while in French singular form is used for zero. When we move to more complex languages, many Eastern European languages have 3 plural forms, not just singular and plural, and languages like Arabic have even 6.

For more text on plural forms, see https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html

For a list of plural forms that Gettext takes care of, see http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html

**Comment by hoffmabc** [comment]
I think this is an interesting suggestion, but we are already at present using polyglot which pretty much does the same thing and is supported by Airbnb.

**Comment by pryds** [comment]
Ok, that sounds good. Guess I didn't realize since honestly (no offence intended), the practice of adding a lot of lines to an already large file containing all translations seems a bit unstructured to me. But maybe that's just how polyglot works (I'm not familiar with it).

I would still suggest to actually use polyglot's features for proper plural strings, string variables (instead of concatenating translated strings with variables outside of polyglot, or even concatenating several translated strings). Omitting this is bound to create nightmares for translators and really bad translations.

Maybe you would also consider using a translation service such as [Transifex](https://www.transifex.com/) which would help translators a great deal with keeping track of which strings are translated, untranslated, changed, etc.

**Comment by hoffmabc** [comment]
I think these are great suggestions and I totally agree. I would say we put rather modest effort in to implement the i8n capability and most work done by translators submitting PRs so there is a lot of work to be done to improve it. I think that very soon as we get closer to release we can put some more attention on it and we would love more assistance if you or anyone else has experience here.

**Comment by jjeffryes** [comment]
We do use string variables in several places, and concatenating strings should have been mostly removed, that's was something that was done by mistake early in the project. 

We haven't used plural functions that polyglot provides yet, this is mostly because our translators aren't all also developers, and it's a little complicated to set up. We definitely intend to put it in place in the future.
