### ISSUE TITLE
Change currency in create listing dialogue is broken

### ISSUE THREAD

**Issue by ac225519** [OpenBazaar/OpenBazaar-Client#763]
Operating System: Linux Mint LMDE2
OpenBazzar version:
    OpenBazaar-Client: git ID:f618035 downloaded 2016-Feb-19 18:36:47 UTC
    OpenBazaar-Server: git ID:922cc80 downloaded 2016-Feb-14 20:20:38 UTC
Reproducible: Always
Steps to reproduce:
1. Click Discover
2. Click Create Listing
3. Click "Change currency"
4. Change from "BitCoin" to "Australian Dollar"
5. Click "Save Changes"

Observed Behaviour:
Error: Data could not be saved.   Database is locked

Expected Behaviour:
Save of the changed currency

![screenshot at 2016-02-21 22 42 14](https://cloud.githubusercontent.com/assets/16848241/13202005/7193bf82-d8ee-11e5-9de9-e18a38164e8c.png)

OpenBazaar-Server Console Traceback:
https://gist.github.com/ac225519/88ba7cf63728aec2e6d6

**Comment by jjeffryes** [comment]
If your database is locked, that's probably not specific to changing currency. We've seen this a few times, we're working on updates to the server that will prevent this.

**Comment by ac225519** [comment]
And closing this issue is helping being reminded to check that the fix in the server code also fixing this reproducible issue ? @hoffmabc @jjeffryes

**Comment by jjeffryes** [comment]
I can't reproduce it on the client, and I believe we've already fixed the issue in the server.
