### ISSUE TITLE
Moderators show up twice sometimes for selection in Settings

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#764]
![image](https://cloud.githubusercontent.com/assets/45482/13202509/5cf71228-d86b-11e5-9b3e-75769528c9e9.png)

**Comment by drwasho** [comment]
Definitely still a problem

![image](https://cloud.githubusercontent.com/assets/3887694/13312608/ce47aebc-dbe3-11e5-9f57-16d8f8a0acf0.png)
