### ISSUE TITLE
Chat unusable while modal is on screen

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#765]
After using the application for a while there are times when I'm having a conversation with someone (perhaps the merchant) and I'm also say purchasing an item. If I receive a message from anyone I am required to finish or exit the modal flow before I can respond. This is going to be annoying because then I can't actually ask someone for help or if I have questions participate in a chat about it without abandoning the checkout. 

I propose that we exclude the chat sidebar from the disable feature that modals place on the rest of the app when they are at the forefront.

**Comment by morebrownies** [comment]
+1 

z-index issue
