### ISSUE TITLE
Refunds ?

### ISSUE THREAD

**Issue by ac225519** [OpenBazaar/OpenBazaar-Client#767]
How does it work ?
- A item is bought
- The buyer opens a dispute to stop funds from being released ?
- The buyer ask for a refund of a not processed and not delivered item.
  Is it a good or bad idea to open a dispute for refund ?
  What is/will be the recommended procedure ?
  ![screenshot dispute](https://cloud.githubusercontent.com/assets/16848241/13186589/c6086494-d7ab-11e5-8f53-eebefff5e0be.png)

**Comment by hoffmabc** [comment]
I would think that is a good idea to dispute. I would recommend trying to work with the merchant to resolve first via chat before dispute but if it's not fixable I would raise the dispute.@sampatt wrote some moderator guidelines he can share.

**Comment by drwasho** [comment]
The full refund mechanics aren't complete yet. Going to close this for now until Josh, Rob and Chris have finished putting this together.
