### ISSUE TITLE
[Digital Goods] URL for good scrolled off the modal window

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#769]
![image](https://cloud.githubusercontent.com/assets/45482/13217870/a81904aa-d933-11e5-8494-8d44370c1be3.png)

**Comment by drwasho** [comment]
Confirmed

![image](https://cloud.githubusercontent.com/assets/3887694/13312503/e63fbd44-dbe2-11e5-8674-5a6e11143f81.png)

**Comment by morebrownies** [comment]
Fixed
