### ISSUE TITLE
Cannot search UTF-8 Tags

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#771]
Brief Description: Can't search UTF-8 tags.

Operating System (OS and version): OSX 10.11
OpenBazaar version (shown on `About OpenBazaar` page in menu): 0.9

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Create listing with UTF-8 tag
2. Search for the tag

Observed Behavior:
No listing results

Expected Behavior: 
Find results.

Additional info (links, images, etc go here):
![image](https://cloud.githubusercontent.com/assets/45482/13223806/ca6c1392-d953-11e5-9e22-25e1a8290fcb.png)

**Comment by rmisio** [comment]
@cpacia 

I believe this is a server issue. The client is making the socket request for utf8 tags the same as with non-utf8 tags. But, in the former, the server is not sending anything back.

![image](https://cloud.githubusercontent.com/assets/794517/13446172/0311ea78-dfc6-11e5-9b45-cb74cbd837fd.png)

(and yes, my item with the utf-8 tag is being returned in the general (non-tagged) search, it's just when I search specifically for the tag, it's not returned)

Server issue has been created:
https://github.com/OpenBazaar/OpenBazaar-Server/issues/259

**Comment by drwasho** [comment]
@cpacia was this fixed with your recent commits? Can we close this?

**Comment by SamPatt** [comment]
I believe this is fixed. @hoffmabc feel free to reopen if you've still got the problem.
