### ISSUE TITLE
Include a store's listings in the Discover Tab

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#779]
As the title suggests. These listings should been seen when the 'All Stores' pull-down is selected.

Stretch features: remove the 'Follow/Unfollow' and 'Block' tabs when hovering over... or grey them out?

**Comment by morebrownies** [comment]
@drwasho  It would be nice to hover and see edit/clone/delete on your own items (like it currently works on your store page)

**Comment by drwasho** [comment]
@morebrownies yeah definitely!

**Comment by drwasho** [comment]
Bumping this to a feature-complete requirement. I can see users thinking that they're node is offline because they can't see their listings in the Discover tab.

**Comment by jjeffryes** [comment]
I think this is a server issue, not a client issue. The client doesn't do anything to stop you from seeing your own items in discover, they're just never sent from the server.

I will open an issue on the server.
