### ISSUE TITLE
Clicking on Top Avatar in Conversation Doesn't Open User Page

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#788]
Brief Description: when the chat sidebar is open and a conversation is active, clicking on the topmost avatar (in the grey header bar) doesn't do anything. It should navigate to that user's user view (the same as clicking on a user avatar in the body of the conversation below the grey bar).

Operating System (OS and version): Win 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): 0.9
Hardware: HP Desktop

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. open a chat conversation
2. click on the top avatar 

Observed Behavior: clicking doesn't navigate to the user's page

Expected Behavior: clicking should navigate to the user's page

Additional info (links, images, etc go here):

**Comment by drwasho** [comment]
Fixed
