### ISSUE TITLE
Bitcoin Prices Need thousands separator

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#791]
Bitcoin prices don't have separators in large numbers.

![image](https://cloud.githubusercontent.com/assets/45482/13301715/4c682aae-db14-11e5-88f4-012c1779534c.png)

**Comment by morebrownies** [comment]
Also probably do not need to display four decimal places if it's a whole number.

**Comment by ghost** [comment]
You should take into account that while some countries use dot (i.e. 1.5 BTC) as decimal mark, others use comma (i.e. 1,5 BTC).

**Comment by jjeffryes** [comment]
This was done.
