### ISSUE TITLE
Placeholder text in the Order Modal

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#796]
**Brief Description:**

![image](https://cloud.githubusercontent.com/assets/3887694/13312439/465286cc-dbe2-11e5-8419-d0eebfadb544.png)

Replace the placeholder with something more descriptive for the user.

*_Operating System (OS and version): *_

Win10

**OpenBazaar version:**

0.9

**Reproducible:** 

Always

**Steps to reproduce:**
Check any sales by your node.

**Expected Behavior:**

Plaintext description inviting the Vendor to write comments when confirming the order.

**Comment by jjeffryes** [comment]
This is fixed in the branch I'm working on.
