### ISSUE TITLE
Select your language dialog remains visible when switching to a configured server.

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#797]
I made a new server with a new database and pointed the client there. The very first setup dialog showed 'select your language'. Then I started an old configured server and pointed the same client there and the dialog was still showing.

**Comment by rmisio** [comment]
Were the two servers were on the same machine? Currently, this isn't supported since (afaik) the database path is not configurable, so your two servers share the same DB. When you blew away the DB for the new server, you essentially blew it away for the old one. So, if you didn't complete onboarding on the new server, the old one (using the same db) expects you to.

**Comment by dsmurrell** [comment]
No, different machines.

I'll try and be more specific. I run a fresh server on localhost, then I part way complete the onboarding process, then I stop the server. The client detects this and asks for new connection details. Then I enter in the ip address for an openbazaar server running in the cloud (that has already completed onboarding and has been set up with graphics etc). It connects and I can see what I should like the pictures and the listings in the background, but the onboarding process is still visible and forces you to go through it to complete it. I'm not sure what completing it does to the state of the server.

The behaviour I expect would be for the client to realise that the new server has been onboarded and configured and then stop trying to get you to complete the onboarding process by forcing it to the foreground and not allowing you to close it without going through it.

**Comment by rmisio** [comment]
ah, good catch. we'll get that taken care of.

**Comment by dsmurrell** [comment]
Thanks.

**Comment by dsmurrell** [comment]
Just went through the zombie onboarding on the already configured server... it resets all the configuration to whatever you put into the zombie onboarding dialogs.

**Comment by rmisio** [comment]
did you pull latest from pr #886? That has the fix in it to remove the zombie, so the last comment should be a moot point.

**Comment by dsmurrell** [comment]
Ok, no problem. I've not pulled the latest yet. You are right. It is moot.

**Comment by rmisio** [comment]
this is fixed.
