### ISSUE TITLE
3 letter ISO 4217 codes are not used

### ISSUE THREAD

**Issue by ac225519** [OpenBazaar/OpenBazaar-Client#803]
USD, AUD, EUR, etc not used.

Operating System (OS and version): 
Linux LMDE2

OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Client git ID:cd6c316 downloaded 2016-Feb-26 06:05:09 UTC

Hardware:  Intel
Reproducible: Always

Steps to reproduce:
1. Menu -> Settings -> Local currency: "Australian Dollar" -> Save Changes
2. Click Discover
3. Example: Rock 0.0010 BTC (A$0.59)

Observed Behavior:
0.0010 BTC (A$0.59)

Expected Behavior:
0.0010 BTC (AUD $0.59)

Additional info (links, images, etc go here):
The correct  3 letter ISO 4217 codes are already here: OpenBazaar-Client/js/models/countriesMd.js
There are just not correct displayed.

**Comment by jjeffryes** [comment]
The client uses the symbol for each currency, which is the standard setting for international currencies.
