### ISSUE TITLE
Default following list on client doesn't get applied.

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#805]
On setup, there are three nodes in the default following list (@OB1, @Themes, @OpenBazaar). They are all checked by default. When the setup completes, your node is not following any of these.

Will this be working for the 1st March?
Will the default be checked boxes? (i.e. opt out)

**Comment by morebrownies** [comment]
Yes, this needs to be wired up still.

**Comment by JustinDrake** [comment]
@morebrownies: Just to make sure I understand, the suggestions to follow are opt-out, not opt-in?

**Comment by morebrownies** [comment]
opt-out

**Comment by morebrownies** [comment]
Twitter does something similar: https://www.useronboard.com/how-twitter-onboards-new-users/?slide=41

**Comment by JustinDrake** [comment]
@morebrownies :+1: Thanks for the added info.

**Comment by jjeffryes** [comment]
One thing to note, following a node only works if the node is online. We will be hard-coding the handles for these nodes (that will allow us to change the guids, but keep the same handles), so both of the following will need to be true:
1. each of these nodes is always online. 
2. the handle is up to date, and points at a valid online guid

If either of the above is false, following will not work for that node.

**Comment by jjeffryes** [comment]
Closed in #866

**Comment by rmisio** [comment]
This is fixed, but with some caveats... please see the description in the PR:
https://github.com/OpenBazaar/OpenBazaar-Client/pull/866
