### ISSUE TITLE
Remove @themes from the suggestions to follow?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#807]
During signup, it's suggested to follow @themes. Should this be removed for the March 1 release?

**Comment by morebrownies** [comment]
My vote is keep it. Getting high quality themes is going to be important so that the network isnt filled with horribly designed pages. People can uncheck if they do not care for it.

**Comment by hoffmabc** [comment]
I think it's fine as long as that store actually is up and exist

**Comment by JustinDrake** [comment]
@morebrownies I can't seem to access the @themes store. How can users get high quality themes? Are they listings on the @themes store that one can buy?

**Comment by morebrownies** [comment]
Yes for purchase. Eventually if we add the ability for free listings, there could be a bunch more free ones too. Node will be up this weekend.

**Comment by JustinDrake** [comment]
Cool. :)

Please close this issue when the node is up.

**Comment by morebrownies** [comment]
Will do

**Comment by morebrownies** [comment]
It's live here: 2dab3d9de6da4efface672a3e33a37c5e29c0d89 @themes
