### ISSUE TITLE
Address bar placeholder text only displays when in Discover section

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#808]
Go to transactions or settings and you'll see that it disappears. 

<img width="1201" alt="screenshot 2016-02-26 10 26 59" src="https://cloud.githubusercontent.com/assets/13066886/13358161/81ad3dfc-dc73-11e5-9ed6-9cbf8aeaf49e.png">

**Comment by jjeffryes** [comment]
I can't reproduce this. It was either a fluke or was fixed.

**Comment by morebrownies** [comment]
I'm still running into the same issue. @drwasho want to test?

**Comment by drwasho** [comment]
Yep, can confirm.

**Comment by jjeffryes** [comment]
Interesting. This only happens if you use a default theme and don't customize your page.
