### ISSUE TITLE
Notifications tray lost the placeholder text

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#809]
I don't have any notifications and this is what I see now
<img width="500" alt="screenshot 2016-02-26 10 44 42" src="https://cloud.githubusercontent.com/assets/13066886/13358673/187e4e7c-dc76-11e5-9c44-841cf80ba213.png">

**Comment by jjeffryes** [comment]
@rmisio take a look at this when you have a chance.

**Comment by rmisio** [comment]
@morebrownies If you pull latest, this should be fixed.

**Comment by morebrownies** [comment]
I wasn't able to confirm since I have notifications now. @drwasho can you test and close if you can confirm it is working?

**Comment by drwasho** [comment]
Definitely fixed.
