### ISSUE TITLE
Clicking reviews should display the Review tab and scroll you to the section

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#815]
Currently not clickable, but would be nice to click and take you to the tab.

<img width="291" alt="screenshot 2016-02-26 13 35 38" src="https://cloud.githubusercontent.com/assets/13066886/13363224/f1e9f1b8-dc8d-11e5-9403-636cbc8b85cc.png">

**Comment by rmisio** [comment]
this was fixed and is ready for verification.
