### ISSUE TITLE
If an item does not have any reviews, display a placeholder for "No reviews"

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#816]
Similar to how we do it on the followers/following tab

<img width="1049" alt="screenshot 2016-02-26 13 43 57" src="https://cloud.githubusercontent.com/assets/13066886/13363449/18a57a06-dc8f-11e5-81c6-1651c19a0d1c.png">
<img width="1018" alt="screenshot 2016-02-26 13 44 27" src="https://cloud.githubusercontent.com/assets/13066886/13363450/18b2bb9e-dc8f-11e5-99a4-5006f0640aef.png">

**Comment by rmisio** [comment]
this is fixed.
