### ISSUE TITLE
Timestamp completely off

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#817]
In the chat, my timestamp shows as Mar 6 (today is Feb 26). See the screenshot for a live discussion.

Using Mac OS X, system time is correct, never had an issue with time on my computer.

![screen shot 2016-02-26 at 19 59 45](https://cloud.githubusercontent.com/assets/731743/13363853/95ef48d2-dcc3-11e5-940f-3863e4fc64fa.png)

**Comment by JustinDrake** [comment]
Ok, time seems to be progressing _very_ fast on my machine. Went from Mar 6 to Mar 8 and Mar 9 in just a few minutes.

![screen shot 2016-02-26 at 20 03 42](https://cloud.githubusercontent.com/assets/731743/13363966/2cc41fda-dcc4-11e5-83e2-9be00cfcacdd.png)

**Comment by hoffmabc** [comment]
Sounds like a timestamp formatting issue.

**Comment by JustinDrake** [comment]
My chat buddy, also on a Mac, is not having the same issue.
