### ISSUE TITLE
Unable to save new listing due to inputPrice error

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#82]
If I do something wrong I get an inputPrice error and then I cannot save the item ever after that.

**Comment by jjeffryes** [comment]
I haven't been able to reproduce this, try again with the latest update.

**Comment by drwasho** [comment]
I also can't add a float to the price... it has to be a whole number.

**Comment by jjeffryes** [comment]
Fixed in #114

**Comment by drwasho** [comment]
Kickass
