### ISSUE TITLE
Load Avatar in Onboarding Fails Sometimes

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#825]
Brief Description: when trying to upload an avatar in onboarding, sometimes nothing happens

Operating System (OS and version): Win10
Hardware: HP Desktop
Reproducible Sometimes

Steps to reproduce:
1. Go through onboarding
2. Attempt to upload an avatar

Observed Behavior: after selecting an image, the image does not appear in the avatar window, and is not uploaded to the server.

Sometimes this error on lin3 608 of cropit.js is seen in the Dev Tools console
Uncaught TypeError: Cannot read property 'x' of undefined

The code being affected:
var newX = this.previewSize.w / 2 - (this.previewSize.w / 2 - this.offset.x) \* newZoom / oldZoom;

Expected Behavior:
Avatar should appear on-screen and be uploaded to the server at the end of onboarding.

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
Addendum: sometimes when getting into this state, the JS error stops completion of onboarding from working, and the user has to close the client and start again.

**Comment by hoffmabc** [comment]
Have you tried different types of images and sizes? Or is this with same image?

**Comment by jjeffryes** [comment]
I always use a new image when going through onboarding. I haven't tracked it yet to see if a specific image or image type triggers the bug.

**Comment by jjeffryes** [comment]
I've tested this, and it doesn't appear to depend on the image.

**Comment by jjeffryes** [comment]
I believe this is fixed.
