### ISSUE TITLE
Error adding/saving item to store.

### ISSUE THREAD

**Issue by trashMeNow** [OpenBazaar/OpenBazaar-Client#829]
Brief Description: 

Operating System (OS and version): windows 7 64bit
OpenBazaar version (shown on `About OpenBazaar` page in menu): latest (28/02/2016)
Hardware: intel i7

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. Create listing
2. fill all fields
3. save changesd

Observed Behavior:
i get the error "the items could not be saved", but then i find it in store like a new article

Expected Behavior:
i expet a message like "Item added to store succesfully"

Additional info (links, images, etc go here):

**Comment by hoffmabc** [comment]
Are there any fields with a red border? Time to process?

**Comment by trashMeNow** [comment]
no redbox fields...
ty for answering.

2016-02-28 17:36 GMT+01:00 Brian Hoffman notifications@github.com:

**Comment by jjeffryes** [comment]
Without more information, we can't reproduce this issue.
