### ISSUE TITLE
Refund request from the Buyer shouldn't involve the Moderator

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#839]
Currently, to trigger a refund before the Vendor has 'Confirmed/Shipped', the Buyer has to launch a dispute in order to trigger a refund. This means the Moderator needs to be involved to trigger the refund, where they pick up a fee.

This is unnecessary. The Buyer should be able to request a refund, which the Vendor can consent to. If the Vendor has a problem, then they should be able to trigger a full dispute and involve the Moderator.

**Comment by jjeffryes** [comment]
There is a refund order button right next to the confirm order button. No moderator involved.
