### ISSUE TITLE
Create listing button no longer working in discover

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#843]
<img width="1236" alt="screenshot 2016-02-29 08 38 30" src="https://cloud.githubusercontent.com/assets/13066886/13397487/d50f519e-debf-11e5-9f95-f7f84ffd6f39.png">

**Comment by jjeffryes** [comment]
What does this mean?

Both the listings tab and the Create Listing link in the nav menu work on master when I try them?

**Comment by morebrownies** [comment]
<img width="238" alt="screenshot 2016-02-29 09 17 51" src="https://cloud.githubusercontent.com/assets/13066886/13398749/5b6313d4-dec5-11e5-8ab9-5468ddf50c29.png">

Try the one in Discover, it doesn't seem to do anything when clicked now

**Comment by Kirvx** [comment]
I confirm the bug

**Comment by jjeffryes** [comment]
Oh, that button. There are so many of them...
