### ISSUE TITLE
Blockchain ID Validation Error

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#844]
Brief Description: Set your Blockchain ID in Settings before it has validated on Onename.com and it will never validate until you set it and save it in Settings again.

Operating System (OS and version): OSX
OpenBazaar version (shown on `About OpenBazaar` page in menu): 0.9

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. In Settings set your Blockchain ID to some value (eg. @spammer)
2. Go to Onename.com and signup for an account using that handle.
3. Go to Settings and click the Check Validation button for your blockchain ID.

Observed Behavior:
Your Blockchain ID never validates on OpenBazaar and so you are not accessible via your handle.

Expected Behavior:
It's expected that as soon as Blockchain ID has validated on the blockchain that it's functional in OB. You can only do this at this point by waiting until it's validated and then manually going and re-saving your handle in Settings.

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
The server only checks the validation again when the profile is saved. 

A button has been added to recheck the validation, if we want the handle to be validated in another way there should be an issue opened on the server.
