### ISSUE TITLE
Chat panel conversations not being reordered by most recent

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#847]
<img width="155" alt="screenshot 2016-02-29 09 37 13" src="https://cloud.githubusercontent.com/assets/13066886/13399266/11298bba-dec8-11e5-9beb-33ce08842088.png">

The conversation with the notification should be at the top since it is the most recent

**Comment by jjeffryes** [comment]
Closed in #851
