### ISSUE TITLE
Payment pending transactions do not seem to open

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#849]
When I click the top order, the modal never opens and the console spits out the following error:

<img width="1245" alt="screenshot 2016-02-29 13 01 29" src="https://cloud.githubusercontent.com/assets/13066886/13405560/a4aa4a0c-dee4-11e5-84ba-03b9a4cdd32c.png">

**Comment by jjeffryes** [comment]
This was fixed earlier today.
