### ISSUE TITLE
Not remembering NSFW preference in same session

### ISSUE THREAD

**Issue by gubatron** [OpenBazaar/OpenBazaar-Client#850]
Brief Description: 

I opened the `@spammer/followers` page, I get the "This user is hidden because their page is listed as NSFW" dialog, I click on "Show this user's page, and all NSFW listings", but every time I come back to the page I get the same dialog again.

Operating System (OS and version): 
MacOSX 10.10.5

OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: Macbook Pro (Retina 15-inch

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Open NSFW store 
2. Click on "Show this user's page, and all NSFW listings"
3. Open same page, or refresh after clicking.

Observed Behavior:
Dialog reappears.

Expected Behavior:
Dialog should not appear again

**Comment by jjeffryes** [comment]
This isn't a bug, it's working as intended. I'm re-categorizing as an enhancement.

Clicking on an item reloads the page, which triggers the warning. We should add code to handle that circumstance. 

Adding code to remember NSFW pages that you've said it was ok to look at is a bigger issue, since we would also need to add a way to re-hide them if you change your mind later.

**Comment by gubatron** [comment]
I thought I told it to just show me everything and not nag me again, maybe you're joking or you're serious, I'm lost. It's clearly a bug, although coders tend to joke like that as "unintended features"

**Comment by jjeffryes** [comment]
No joking here.

We do plan to make this feature better, but a planned enhancement is not the same as a bug.

Currently the feature lets you decide to see a page that is NSFW, if you have set your account to not view NSFW content. That choice to view an individual page isn't saved anywhere. 

So, within the limits of the current feature, it is working as intended. Though maybe we're not clearly communicating how the feature works to the user.

The future feature will save your choice to view a particular page, and have a yet to be determined UI element that lets you change your saved choice, so if you don't want to see something any more you can re-block it.

**Comment by gubatron** [comment]
oh I get it now, thanks for the clarification :)

**Comment by drwasho** [comment]
Can we get an update on this @gubatron or @jjeffryes ?

**Comment by jjeffryes** [comment]
I think this is a post launch enhancement.

My recommended solution is when the user clicks "show NSFW" there would also be a checkbox for "remember this choice". If that is checked when the show button is clicked, the guid will be saved in local storage similar to how the avatarHashes are currently saved. 

When viewing a page, the code would check for the guid, and if it is found skip the warning, but show (I'm not sure where, maybe as a bottom bar, or in the fold out bar under the nav) a message that this store or listing is NSFW, but you have chosen to view it. The message would have a "hide this again" button that would re-hide the content and remove the guid from localStorage.
