### ISSUE TITLE
Chat panel is now covering user menu and tooltip

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#853]
<img width="480" alt="screenshot 2016-02-29 14 45 16" src="https://cloud.githubusercontent.com/assets/13066886/13408373/1f46ccfa-def3-11e5-81e3-ab25afaf3bb5.png">

**Comment by jjeffryes** [comment]
And that's why we don't set z-indexes to 999...

**Comment by rmisio** [comment]
yeah, there's always this kind of a game with z-index's. So, obviously, we need to set it to something above all the modals but under the nav menu's. I'll look into it.

**Comment by jjeffryes** [comment]
Don't worry about it, I'm fixing it.

**Comment by rmisio** [comment]
groovy, another issue you might want to look at while you're at it is that when a modal is up, the menus go behind the modal overlay.

**Comment by jjeffryes** [comment]
I fixed that too.

**Comment by rmisio** [comment]
+1
