### ISSUE TITLE
Avatar's top and bottom borders get lost on page listing.

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#854]
I put a faint dark red border around my avatar. It looks like the top and bottom borders are getting lost.

![screen shot 2016-02-29 at 21 33 22](https://cloud.githubusercontent.com/assets/4035854/13409764/4f903e26-df2c-11e5-9225-c193b5942ee5.png)

**Comment by drwasho** [comment]
I think this got fixed.
