### ISSUE TITLE
Conversation message order and timestamping is off

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#856]
The latest message is displaying at the top of the conversation instead of the bottom (notice the timestamps) 

<img width="254" alt="screenshot 2016-02-29 16 25 46" src="https://cloud.githubusercontent.com/assets/13066886/13411140/335dfff2-df01-11e5-942f-8b5157bb23c9.png">

**Comment by drwasho** [comment]
![image](https://cloud.githubusercontent.com/assets/3887694/13415409/3a21af8c-dfa6-11e5-8d77-1454eb4aade4.png)

Timestamping is going crazy.

**Comment by jjeffryes** [comment]
The ordering is fixed.
