### ISSUE TITLE
Enable Buyer ratings if they win a disputed transaction

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#860]
Buyers who have won a dispute transaction (i.e. not a refund) need to be able to leave a rating for the Vendor.

**Comment by jjeffryes** [comment]
Make this an issue on the server side too, we'll need a new API or changes to the existing API.

**Comment by drwasho** [comment]
@jjeffryes I recommend that a 'win' for the buyer is considered to be a payment >50%.

**Comment by jjeffryes** [comment]
This has been finished.
