### ISSUE TITLE
Do we need to show ob:// all the time in the address bar?

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#862]
What I'd suggest we do instead is sho @themes/store and when/if the user copies the url in the address bar, auto prepend ob://@themes/store into the clipboard. 

<img width="304" alt="screenshot 2016-02-29 19 58 08" src="https://cloud.githubusercontent.com/assets/13066886/13415239/d143a2a4-df1e-11e5-9def-be73fd7bb37a.png">

**Comment by jjeffryes** [comment]
I think that would be confusing. 

You don't have to put the ob:// in the address bar if you don't want to, it works without it.

**Comment by morebrownies** [comment]
Right, but if it works without it then why show it?

**Comment by morebrownies** [comment]
It's really needed to share with people outside of the app, but within the app it adds zero value.

**Comment by jjeffryes** [comment]
It also subtracts zero value.

**Comment by hoffmabc** [comment]
The idea should be that you can copy paste these elsewhere. If they see the links without ob:// then they will get no advantage of other apps expanding those links

**Comment by hoffmabc** [comment]
Try copying a Spotify: link into the Slack for instance

**Comment by morebrownies** [comment]
Ok we can keep them

**Comment by hoffmabc** [comment]
Thanks dad :) let's use the testing period to see how it goes
