### ISSUE TITLE
Notification sound issues on Mac

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#878]
Two sounds are triggering at once: our custom notification sound and what appears to be a default Mac sound.  @hoffmabc can you confirm you're hearing this too?

**Comment by hoffmabc** [comment]
I have not heard this but I'll listen for it specifically now.

**Comment by morebrownies** [comment]
I'm hearing it on both of my computers now. Seems like it just recently started happening, possibly after installing from the dmg

**Comment by morebrownies** [comment]
My friend installed from the dmg yesterday and the same issue was happening on his machine. He's never had OpenBazaar installed before so it seems to happen when you install from the installer. Can other people running OSx confirm this?
