### ISSUE TITLE
Avatar not displaying correctly in chat

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#881]
Notice @drwasho's avatar displays in the conversation but not in the title of the conversation

<img width="152" alt="screenshot 2016-03-01 13 50 59" src="https://cloud.githubusercontent.com/assets/13066886/13439795/b7b375c6-dfb4-11e5-9af9-e59aa7e3edb2.png">

**Comment by rmisio** [comment]
This is ultimately a server-side issue. The chat message and chat heads come from different API's and the avatar hash is not being provided consistently.
@cpacia

**Comment by drwasho** [comment]
Fixed from what I can tell.
