### ISSUE TITLE
Handle not displaying correctly to users

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#885]
When I view my own page it displays fine in the address bar and in the hero section.
<img width="1280" alt="screenshot 2016-03-01 16 19 59" src="https://cloud.githubusercontent.com/assets/13066886/13444014/7e137e6e-dfc9-11e5-88de-99b6281cffac.png">

However, when I view my page from another node it does not display.
![screen_shot_2016-03-01_at_4 19 50_pm_1024](https://cloud.githubusercontent.com/assets/13066886/13444061/bd5fc726-dfc9-11e5-9b60-b41ca18dc29d.png)

**Comment by jjeffryes** [comment]
How are you getting to your store from the other node? When I enter your handle or click on any link to your store, I see the handle.

**Comment by morebrownies** [comment]
From chat

**Comment by morebrownies** [comment]
I click their big avatar in the conversation bar

**Comment by jjeffryes** [comment]
When I click on your avatar in chat, it shows your handle in the address bar.

**Comment by morebrownies** [comment]
But it also seems to happen when I click an item in discover

**Comment by jjeffryes** [comment]
This is on rc1.04? I can't duplicate it in master.

**Comment by morebrownies** [comment]
Yup

**Comment by morebrownies** [comment]
I just tried refreshing the client and I see the same problem

**Comment by morebrownies** [comment]
Maybe it is just me, not sure, but we should keep an eye on it.

**Comment by jjeffryes** [comment]
It's possible we updated something in master this afternoon that inadvertently fixed it.

**Comment by morebrownies** [comment]
Going to close for now. I'll reopen if I see it happen again
