### ISSUE TITLE
Payment received notification should not be sent to the buyer

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#891]
I just bought this item and received a notification that my payment was received. 

<img width="524" alt="screenshot 2016-03-01 17 10 08" src="https://cloud.githubusercontent.com/assets/13066886/13445206/8800432e-dfd0-11e5-938b-7cdea1fd99c1.png">

**Comment by jjeffryes** [comment]
This is a server issue, not a client issue.

**Comment by jjeffryes** [comment]
It might be good to tell the buyer their payment has gone through, in case they leave the buying flow while the spinner is still going, but currently the message from the server is identical for the buyer and seller, which makes it confusing.

**Comment by morebrownies** [comment]
Chris told me it was a client issue yesterday :(

**Comment by jjeffryes** [comment]
Hmm. I suppose we can check the guid to see if it's yours, and format the message differently. 

You'd still get it though.

**Comment by jjeffryes** [comment]
It turns out this is only sent to the buyer, and what it means is your payment has completed. I put in a patch that changes the language to match that.
