### ISSUE TITLE
Clicking on a "New Review" notification doesn't take you to the rating

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#899]
Brief Description: I received a notification for a new review. When clicking on the notification it just closed the notifications window instead of taking me to see the review.

Operating System (OS and version): OSX 10.10.5 (14F1021)
OpenBazaar version (shown on `About OpenBazaar` page in menu): Version 1.0.4 (tag v0.1.0 for Server and v1.0.4 for Client)

Hardware: Macbook Pro Retina

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Receive (or send from another node) a review notification
2. Click on notification
3. Observer the window close and it not take you to the review

Observed Behavior:
Closing the notification window and not taking me to the review

Expected Behavior:
Closing the notification window and taking me to the review

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
I'm not sure what this ticket is referring to. There is no new review notification. The closest thing is the payment received notification, which is sent when an order is finalized (this is when the review is made). That notification is working correctly.

**Comment by ghost** [comment]
I should say "Rating notification". When I click on a [notification like this](http://content.screencast.com/users/TylerBSmith/folders/Jing/media/d24b7fe7-9a3b-4db0-b999-f6f843abb85c/00000436.png) it simply closes the notification pane instead of taking me to the rating screen for that order.
