### ISSUE TITLE
"Enter your Bitcoin Address" input marked invalid even for valid Bitcoin addresses

### ISSUE THREAD

**Issue by miller46** [OpenBazaar/OpenBazaar-Client#900]
Brief Description: When trying to buy an item, I can't get past the Enter your Bitcoin Address screen.  No matter what Bitcoin address I put in the screen shows the address as invalid.  Examples of attempts are 3MXYUBLWNETa5HTewZp1xMTt7AW9kbFNqs and 1NWSPwLHwquY4dwVBJZYnYHF26rERVKrUh

Operating System (OS and version): Ubuntu 14.04 LTS 64 bit
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Click on a product listing
2. Click Buy Now
3. "Do you have a Bitcoin Address"? select Yes
4. Select moderator
5. Enter Bitcoin address

Observed Behavior:
Input marked invalid for valid Bitcoin addresses

Expected Behavior:
Input not marked invalid or the screen simply allows user to proceed

Additional info (links, images, etc go here):

**Comment by drwasho** [comment]
Hey @miller46 ,

Currently OpenBazaar is on the Testnet, which means you need testnet coins. Ping me if you need some, but you can pick them up for free from a few faucets.

**Comment by JustinDrake** [comment]
Might make sense to add "Testnet" for the testnet client.
