### ISSUE TITLE
Creating listing with short description causes buggy listing

### ISSUE THREAD

**Issue by tanner37** [OpenBazaar/OpenBazaar-Client#903]
Brief Description: If you create a new listing and save it a short description, it will cause a bugged listing. When you go to edit the bugged listing, all the fields are blank.

Operating System (OS and version): Debian stretch/sid x64
OpenBazaar version (shown on `About OpenBazaar` page in menu): Version 1.0.6
Hardware: i5-4670K desktop

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Create listing
2. Fill in title, price "0.1 BTC", processing time "Instant", free shipping enabled.
3. Set the description to a period, followed by a space : '. '
4. Delete the period, leaving only a space behind: ' '
5. Save Listing. Try to Access it.

Observed Behavior: Listing appears in the store section, but when you click on it, it tries to load, flashes, and brings you back to the store page.

When you go to edit said listing, all the fields are blank. If you hit cancel from this point, it will bring you to the bugged listing, but everything will be blank as well (see picture).

If you want to try, here's my store page: ob://3c7a83b2be537bb9571acbea9b97a742f99acb4b/store
Try both the "Helicopter Key" and the "Buggy listing x". I'm going to bed soon though. Will be back online in the morning (Alberta).

Expected Behavior: Listing shouldn't get bugged based on description.

Additional info (links, images, etc go here):
https://i.imgur.com/vkuqMrv.png

**Comment by jjeffryes** [comment]
This has been fixed on master, and will be included in release 1.0.7
