### ISSUE TITLE
Item quantity - enhancements label

### ISSUE THREAD

**Issue by TheButterZone** [OpenBazaar/OpenBazaar-Client#904]
Currently, buyer can change quantity even if you're selling a 1-of-a-kind physical good. Suggest adding this field to Create Listing, and default at 1, then limit buyers to whatever number hasn't been sold.

**Comment by rssalerno** [comment]
+1 Imperative IMO for sellers to be able to control avail qty of items for sale.

**Comment by jjeffryes** [comment]
Inventory control is on our roadmap, and will be added in a future release.
