### ISSUE TITLE
Shipping rate limbo

### ISSUE THREAD

**Issue by TheButterZone** [OpenBazaar/OpenBazaar-Client#905]
I have a large product inventory, widely varied; there are only a few multiple units of the same thing... here's a cleaned up version of my messages in the #openbazaar IRC:

So... shipping settings are going to be difficult for me, I wonder if anybody else too.

https://blog.openbazaar.org/wp-content/uploads/2016/02/createlistingshipping.png

In the US, usually the cheapest shipping carrier is USPS. Some of USPS's services are flat rate, some are fixed-rate (based on weight & dimensional limits, but not destination vs origin, aka "zone"), and some are variable rate, based on weight/dimensions and zone. Flat rate boxes and envelopes won't necessarily be cheaper than fixed or variable rate every time.

I can't fix my shipping prices into the OB form pictured above or select free shipping, without ripping me or my customer off.

Every time I ship something, I make sure the dimensions of the smallest package it can be safely packed in are within regulation (I have a huge compressed supply of recycled Amazon & other boxes, padded & unpadded envelopes, flat rate boxes & padded & unpadded envelopes, and padding materials, that I uncompress, mix and match at the last minute), weigh and measure it, and select the cheapest method based on the recipient's zip code (I only ship within US; if an international buyer wants it, they'll need a forwarder based in the US).

I'm not sure how to modify that form simply enough and have it still work.

Most of all, before the customer pays, I need to know their zip code, so that I can calculate them a total price with cheapest shipping.

One ham-fisted way to work around it, would be to mark everything as free shipping, but put in the terms & conditions something like "Buyer agrees to pay cost of actual shipping (to be calculated by seller after receiving buyer's shipping address and payment for item) separately."

Another would be for each ad to tell the buyer to send their zip code in advance as a "question", then the ad would be cloned off, with their actual shipping cost plugged in the form, and "for shipping to [zip] #####" appended to the title or description, then the seller would notify them of their personalized listing.

P.S. I will be accepting direct payment only; my [WoT](http://b-otc.com/vg?nick=TheButterZone) standing since 2012 either means something or it doesn't.

**Comment by jae-wd** [comment]
This is a big issue that will determine whether OB is usable for real business or not.

Real sellers who ship items internationally have to calculate shipping case by case based on contextual information:
- destination country
- shipping method
- weight of the products to be shipped (quantity \* base weight)
- volume of the products

The devs should realize that **_shipping fees that sellers have to pay differ massively depending on context_**, sometimes the same items can cost X if shipped to a neighboring country and 5X if shipped somewhere else. 

**The solution:**

Let sellers upload a shipping fee matrix (JSON, cvs, xml) where it's possible to specify different shipping prices based on:
- destination country
- total weight (enable assigning weights to items): it must be possible to specify an unlimited number of weight intervals, ie: under 500g, 500-1000g, 1kg-1.5kg, etc.
- total volume (enable assigning dimensions to items)

Unless this feature gets implemented, serious sellers will not be able to use OB at all.

**Comment by drwasho** [comment]
Thanks for your post @jae-wd 

I think you need to appreciate that OB isn't a finished product and more flexibility will be added with future releases.

**Comment by jae-wd** [comment]
That's great to hear @drwasho! 

Just wanted to make sure this problem is known to developers so they can pay attention to it when time allows for it. So far the checkout experience looks like its focused on local US trades, international sellers will need a set of different features.

Another thing, some countries (like Hong Kong) don't use ZIP codes, so they shouldn't be mandatory on checkout.

**Comment by drwasho** [comment]
Thanks for the tip about zip codes! 

Ultimately I'd like for users to be able to optionally use APIs from services like Shippo and import the shipping data/cost from there.

**Comment by jae-wd** [comment]
Just checked out Shippo, it looks great. Unfortunately again mostly for North American market.

I'm trying to figure out how it could be possible to work around the problem without implementing the functionality so people can start using OB as soon as it's out. 

Perhaps there could be a "custom fee" field which would allow buyers to add extra money with the order. This would basically solve all possible unexpected costs, not just shipping.

Practical example: 
I set shipping fee to 0 but write in description that shipping must be confirmed via chat before ordering. If buyer agrees, he can then place the order and include whatever fee we agreed on.

**Comment by jae-wd** [comment]
Or is it currently the case that if the buyer simply pays more to the escrow address all the BTC gets forwarded to the seller? That would solve the problem before a solution gets implemented.

**Comment by bumi** [comment]
From my experience international shipping rates are way too complex as that it can be abstracted into a general rule enforced by a software. There are too many variables defining the price and one of the main reasons is probably that logistics is so different in many countries. 
OpenBazaar should not assume the US/EU only and consider countries outside of the "western bubble".
I'd also suggest to keep the system as open and flexible as possible and leave it up to the seller/buyer to agree on shipping and price.

**Comment by jjeffryes** [comment]
We're consolidating shipping issues in #1263
