### ISSUE TITLE
PGP key not being saved in profile

### ISSUE THREAD

**Issue by goodc0re** [OpenBazaar/OpenBazaar-Client#907]
Brief Description: 
PGP key is not being saved in user profile. 

Operating System (OS and version): OS X System Version: OS X 10.10.5 (14F1605)
OpenBazaar version : Version 1.0.6

Reproducible Always

Steps to reproduce:
1. Edit user profile
2. Add PGP Key and save
3. Visit user profile again, PGP key not there

**Comment by jjeffryes** [comment]
Did you also enter a signature?

**Comment by goodc0re** [comment]
No I did not, it was not obvious that it is required.

**Comment by jjeffryes** [comment]
Just checking to make sure what the issue was. We'll add something to make it more obvious, and to throw an error if you enter one without the other.

**Comment by goodc0re** [comment]
No, I did not enter a signature, only the public key. It was not obvious that it is required.
