### ISSUE TITLE
Step 2 is empty in Romanian

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#909]
Operating System (OS and version): Ubuntu 14.04
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.6
Hardware: 

Reproducible: Always

Steps to reproduce:
1. Install OpenBazaar
2. On step 2 it will be empty (no text)

Expected Behavior:
There must be some text

Additional info (links, images, etc go here): 

![screenshot from 2016-03-02 10 38 52](https://cloud.githubusercontent.com/assets/1475489/13455629/51bc289a-e067-11e5-92fa-274e46ae9175.png)

**Comment by jjeffryes** [comment]
Most of our translations are currently incomplete, they were originally created by volunteers, not all of whom have continued to add new phrases as the amount of text in the app increased.

If you're interested in helping with translations, let us know, we'd love to have your help.

**Comment by ghost** [comment]
If a phrase is not translated the original/english version should be used.

**Comment by ghost** [comment]
Romanian is 100% translated, it should fix this issue

https://www.transifex.com/ob1/dashboard/all_resources/ro/?project=openbazaar
