### ISSUE TITLE
Integrate keyboard shortcuts to quickly navigate to core pages

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#91]
Hitting the following keys should take you to the appropriate sections. We also need to output the hotkeys in the user navigation (like below) so it's apparent they exist. I tried to select keys that aren't already mapped to shortcuts like ⌘c for example.

![openbazaar-keyboard-shortcuts](https://cloud.githubusercontent.com/assets/13066886/10738717/b00b4c7c-7be6-11e5-9d4f-61eef8b8e10b.png)

In addition, ⌘h should take you home. 

Also, we'll need to support multiple operating systems, so if the user is on Windows, ⌘ should be replaced with CTRL.

@jjeffryes this may be a good one for one of your helpers or someone in the community looking to contribute and add a meaningful enhancement.

**Comment by hoffmabc** [comment]
Can’t use those shortcut texts though. Going to make it OS specific?

**Comment by morebrownies** [comment]
We should be able to. We'd have to check the user's OS and set the shortcut text based on what they're using.

**Comment by morebrownies** [comment]
@djbooth007 want to take a stab at this one?

**Comment by mariodian** [comment]
FYI, cmd + M is a shortcut for minimizing the current window, cmd + A for "select All" and you can't type "~" without holding the Shift key.

If we come up with right shortcuts and nobody is currently working on this feature, I have some spare time to code it.

**Comment by morebrownies** [comment]
Good call. We'll need to be sure not to overlap with any native OS keyboard shortcuts. Nobody else is working on this one, so if you're interested in taking it on, it's all yours.

**Comment by mariodian** [comment]
Ok I'll take it.

**Comment by morebrownies** [comment]
Looking forward to it :)

**Comment by mariodian** [comment]
I think combination of cmd+shift/ctrl+shift would work OK. What do you think?

Not totally sure about ctrl+shift though, I don’t have a windows PC so I can’t check how it feels from the UX standpoint.

**Comment by morebrownies** [comment]
I'm open to using the shift key. However we should make the shortcuts as easy to remember so that people use them often. Current;y we only have 7 shortcuts planned for. Do we not feel we can find 7 keys that we can use with only the CMD / CTRL key?

**Comment by mariodian** [comment]
Here's my suggestion then so it's also related to corresponding labels or their actions:

My Page => cmd + H (As "Home")
Purchases => cmd + P (doesn't trigger printing on OB, however I can imagine this feature being implemented in the future? In that case perhaps "T" as "transactions" would be better)
Cases => cmd + B (As "Briefcase" which is the current icon for the link)
Settings => cmd + comma (used in Safari for Preferences, so at least OS X users are familiar)

// edit
Create Listing => cmd + N (As "New" listing)

**Comment by morebrownies** [comment]
That sounds good for now. Let's go with cmd + t for purchases and we'll also need a shortcut to get to discover. Can we use cmd + d for that?

**Comment by mariodian** [comment]
Yes, cmd + d sounds good.

Btw is there any application config file which could be used for defining those keys? I don't want to hardcode it to the template and to the event handler. Thanks!

**Comment by morebrownies** [comment]
@jjeffryes would know best
