### ISSUE TITLE
.dmg file is almost 74 MB

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#910]
The file OpenBazaar-1.0.6.dmg is 73.9 MB which seems excessively large. (74 Bitcoin blocks, guys!)

Can some fat be trimmed?

**Comment by hoffmabc** [comment]
Most of that TBH is electron packing the Chromium browser in there. I'm not sure how much we can improve this but we can re assess.

**Comment by rmisio** [comment]
Off the top of my head, one area where we could do some pruning is for the default theme images. They are 1900 px wide and consequently some of them are close to 2MB, and there's 6 of them in total.

@morebrownies @jjeffryes Do they need to be that large?

**Comment by jjeffryes** [comment]
I believe they only need to be 950 x 400.

**Comment by morebrownies** [comment]
We need the higher resolution images for retina screens. We could maybe compress them a bit more, but the savings would likely only be a mb or two.

**Comment by hoffmabc** [comment]
I think this is not a huge issue personally. Our application is really not that huge in relation to other apps of this caliber.
