### ISSUE TITLE
Empty Screens

### ISSUE THREAD

**Issue by nanomo** [OpenBazaar/OpenBazaar-Client#911]
The identified screens with empty data are:

The Startup Wizzard "Introduction"
The "About" screen in Menu->About

Operating System : Windows 7 64bits updated
OpenBazaar version: 1.0.6
Language: Spanish

Reproducible: Always

**Comment by jjeffryes** [comment]
The Spanish translation, along with most of our other translations, is not complete, and is missing some content. 

We are actively seeking volunteers to complete our existing translation files, or create new ones.
