### ISSUE TITLE
Preview and set price in multiple currencies

### ISSUE THREAD

**Issue by Dekker3D** [OpenBazaar/OpenBazaar-Client#912]
Brief Description: It would be nice if you could preview a store item's price in multiple currencies, like eur/usd/btc so you know what they look like. Many ordinary stores already price items just below round numbers, because $99,99 looks cheaper than $100,00, for example.

OpenBazaar version: 1.0.6

Observed Behavior: You only see and edit a store item's price in your currency of choice.

Expected Behavior: You select multiple relevant currencies, and get an edit/preview field for all of them. If you change the price in one of those fields, the price in the other fields is automatically adjusted to match. Price suggestions could also be added, showing the nearest price that's close but below a round number, both upward and downward.

**Comment by jjeffryes** [comment]
This might create confusion, as the value of currencies changes relative to each other. If you price something at USD 0.99, the price that translates to in Australian dollars will be different tomorrow than it is today.

**Comment by Dekker3D** [comment]
You could add a checkbox, to set which currency the price will be based on. It could default to the last currency you actually used to set the price. I'm sure OpenBazaar already does this internally anyway, with the preferred currency.

As for the confusion: by default it would only use your one preferred currency, and hide the checkbox since it's not needed. A "show other currencies" button would be used to add more currencies.

**Comment by morebrownies** [comment]
I agree with Josh.  I'm concerned about the complexity this will introduce. It's difficult enough to explain and keep up with the bitcoin price and one fiat currency. In addition, currencies are constantly changing value amongst each other so seting fixed prices in multiple fiat currencies just seems like bad practice to me.

**Comment by drwasho** [comment]
I agree. Thanks for the suggestions @Dekker3D but we may pass on this for now.
