### ISSUE TITLE
@handle field lets you delete the @ but considers it mandatory anyway.

### ISSUE THREAD

**Issue by Dekker3D** [OpenBazaar/OpenBazaar-Client#913]
Brief Description: The Handle field in Settings -> Page lets you enter a handle without an @, but marks it as invalid because it lacks the @.

OpenBazaar version: 1.0.6

Observed Behavior: See description.

Expected Behavior: The @ should be next to the actual text field, so it can't be deleted. Or if symbols other than @ can be used, a clear explanation should be given to the user if no such symbol is supplied.

Additional info (links, images, etc go here): http://puu.sh/ns4U9/46d9ea9536.png is an image of the field I'm talking about.

**Comment by rmisio** [comment]
this is fixed and ready for verification.
