### ISSUE TITLE
Mac OS: Unidentified developer

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#916]
I'm running the .dmg for the first time (normally use the Git repos). I got this message when opening:

![screen shot 2016-03-02 at 14 36 48](https://cloud.githubusercontent.com/assets/731743/13461837/5b94b34c-e084-11e5-881d-31505b026b82.png)

**Comment by rmisio** [comment]
This is an OS security feature that, by default, is turned on on OSX. It's not anything for us to handle. If you google the warning, you can find ways to by-pass it, be it on a one-off basis or globally.

**Comment by JustinDrake** [comment]
```
 It's not anything for us to handle.
```

What about signing the app?

**Comment by hoffmabc** [comment]
I will verify the signature and update if necessary.

**Comment by rmisio** [comment]
ah, @JustinDrake . Wasn't even aware of that. Good to know!

**Comment by hoffmabc** [comment]
Hey @JustinDrake which OSX are you using btw?

**Comment by JustinDrake** [comment]
@hoffmabc Version 10.10.5 (14F1605)

**Comment by hoffmabc** [comment]
I used an Apple cert and it seems it's getting a non-trusted issuer error so I'll see what's up.

**Comment by JustinDrake** [comment]
@rmisio Are you working on an OpenBazaar project? When did you get involved with OB?

**Comment by rmisio** [comment]
Are you questioning my authority!?

Just Kidding :) I started back in January and I work mainly on the client.

**Comment by JustinDrake** [comment]
@rmisio Cool. Are you paid by OB1? Volunteer?

**Comment by rmisio** [comment]
I am paid.

**Comment by drwasho** [comment]
All releases will be signed correctly from here on.
