### ISSUE TITLE
Can't add Bitcoin address

### ISSUE THREAD

**Issue by sabotrax** [OpenBazaar/OpenBazaar-Client#919]
Brief Description:  Can't save Bitcoin address under settings -> general.

Operating System (OS and version):  Windows 7 Pro 74 bit
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.6
Hardware: PC

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Go to "Settings"
2. Under "General" enter a valid Bitcoin address
3. Click "Save Changes" 

Observed Behavior:
Error message "Data could not be saved"

Expected Behavior:
Save changed data with Bitcoin address

Additional info (links, images, etc go here):
I'm able to save settings after emptying the Bitcoin address field again.

**Comment by jjeffryes** [comment]
@sabotrax did you use a testnet address when you tried this?

We are currently on the testnet, and only testnet bitcoin addresses are usable.

**Comment by drwasho** [comment]
@sabotrax need to use a testnet address. Let me know if you need some testnet coins.
