### ISSUE TITLE
Add Local Read of Username/Password to Reset Defaults

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#920]
If a user has a local server, when they reset to the local default settings in the server config modal if possible read the username and password from the config file and populate them in the modal.

**Comment by rmisio** [comment]
On multiple levels what you are proposing sounds scary!

The config file is a server file and controlled by the server. The client would need to know the path and if the server adjusts the path, the client would need to know about it. What if the server decides to make the path a configurable option?

Furthermore, we would need to parse a file the server controls and can change at any time. If the server changes the implementation of the file (e.g. changes the format, changes the names of the credential vars, etc...), the client would always need to play catch up and adjust their algorithm.

For most local server set-ups, does the server even use the config file? I thought that is a file the user can override, but if they don't override the creds, the server will generate them and store the generated values in the DB.

**Comment by jjeffryes** [comment]
The client controls the server, so it already knows the path, it's in main.js.

@cpacia will have to answer about the config file.

The goal is to have a way to rescue the user if they are using a local server, and the username and password gets set but the client doesn't have it.

Right now the only way to repair that is to delete the database and start again, which isn't ideal.

**Comment by rmisio** [comment]
~~That's the path where the server lives and is started, not where the config file lives. We'd need some type of API or some way of the client knowing that path. Alternatively, maybe the server can make that path configurable as a command line option, so then the client can provide that path.~~

But, in general parsing the server config file sounds really hacky.

I totally agree the problem we're trying to solve here is a problem. I think we need to talk with @cpacia and find out how we could go about solving it. I think a server issue should be logged for this as well. The server needs to be onboard with some type of password recovery scheme.

**Comment by bdunbar** [comment]
I should experiment with this first but .. if you edit user/pass values in ob.cfg and restart does it not update the database with the new values?

**Comment by rmisio** [comment]
We're talking about a scenario with a user using the desktop app who will never touch (or even know about) the .cfg file.

**Comment by bdunbar** [comment]
Sure.
1. That is the way it works?
2. If they find themselves locked out, a work instruction stating 'do this, do that, restart' would be sufficient, while someone codes a workaround, no?

**Comment by rmisio** [comment]
@bdunbar 

1.) Yes, by default the credentials are commented out in the cfg file. If you don't uncomment them and set them there (which a binary user won't), the server will generate them for you.

2.) It probably wouldn't be sufficient, because the only work-around at this moment if you are locked out is to delete your DB and re-start the server (or entire app if you are using the binary). That's a pretty heavy handed workaround. Plus, I imagine many of the binary users may not even be tech saavy enough to find and delete their DB. Being locked out like this is definitely an edge case (there must have been a server or net failure at a fairly specific time), but it's probably something we shouldn't just disregard.

**Comment by bdunbar** [comment]
Thanks for patiently explaining the issue, @rmisio .
