### ISSUE TITLE
Default Listing Image is Blank

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#922]
When listing images 404, the default listing image is just a transparent pixel, which leaves a blank space in the image listing. 

We should change that to either a solid color, or an image similar to the default user. 

Optional: also put in a offline image like we do for user avatars.

![image](https://cloud.githubusercontent.com/assets/1584275/13464727/82f25760-e060-11e5-9476-cb18dd8d71cb.png)

**Comment by morebrownies** [comment]
Josh on the user store page we display the secondary color as a placeholder while the listing photo is loading. Could we do the same in discover?

**Comment by rmisio** [comment]
@morebrownies What color did you have in mind? Since this isn't a user page driven by the theme, we could just directly set the background-color in the css file.

**Comment by morebrownies** [comment]
Good call, I'll make the change @rmisio
