### ISSUE TITLE
Some messages displayed in wrong order.

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Client#926]
I think what happened is I shutdown in the middle of a conversation causing the other person's messages to hit the DHT. But I started back up before they were fully saved so it didn't download them from the DHT until an hour later when it made the next attempt to fetch messages from the DHT. 

When that happened the messages got pushed to the UI, which displayed them out of order relative to the timestamps. 

I presume we would want them displayed in the proper order?
![image](https://cloud.githubusercontent.com/assets/4504708/13468546/21d23c5a-e071-11e5-90fd-34825a71f72d.png)

**Comment by jjeffryes** [comment]
Refresh the client and check this conversation again. If it's using the REST call, they should be in order. 

If it's using a combination of the REST and the websockets, then it might get out of order. 

If you still see it like this after a refresh, there may be an issue with how we're sorting the timestamps.

**Comment by drwasho** [comment]
This got fixed AFAIK.

**Comment by rmisio** [comment]
@jjeffryes @drwasho This is a legitimate not-yet-solved bug. It's very much an edge case though. The client code assumes that a message coming in via the web socket is the most recent and just adds it to the bottom of the list. If there's a case as Chris describes, where the server could crash and then the socket messages could be delayed (up to an hour), while I presume new ones are coming through, then that assumption burns us.

The client code would need to be tweaked to account for this and always use the timestamp to determine ordering. Once again, it's an edge case with the server shutting down (or crashing).

**Comment by rmisio** [comment]
@jjeffryes Ok, I misread your comment. You did seem to grasp the situation and I guess it's not soooo huge of a deal, because it's such an edge case.

**Comment by jjeffryes** [comment]
Np
