### ISSUE TITLE
Enum CountryCode has no value defined for name GREENLAND

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#933]
Brief Description: During creation of a listing, when selecting Greenland as shipping destination, the following error is given: "Enum CountryCode has no value defined for name GREENLAND"

Operating System (OS and version): Ubuntu 14.04
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.6
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Create new listing for physical item
2. Fill out required fields
3. In "Shipping" -> "Ships to", include Greenland.
4. Click "Save changes" button.

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
Thank you for reporting this, @pryds, we've fixed this in master, it'll be in the next release.
