### ISSUE TITLE
"Licensing" and "Support" links open invalid URLs

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#938]
Brief Description: Clicking the "Licensing" or "Support" links in the "About OpenBazaar" panel opens Chrome to the url "http://undefined/"

Operating System (OS and version): OSX 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.6
Hardware: Macbook pro

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Open the "About OpenBazaar" page from the nav dropdown
2. Click on "Licensing"

**Comment by jjeffryes** [comment]
This was fixed.
