### ISSUE TITLE
Single sale appears as multiple orders from different buyers

### ISSUE THREAD

**Issue by rssalerno** [OpenBazaar/OpenBazaar-Client#939]
Brief Description: 

Operating System (OS and version): Buyer: Windows 10  Seller: OSX 10.10.5
OpenBazaar version (shown on `About OpenBazaar` page in menu): Version 1.0.6
Hardware: Buyer: ASUS VivoBook   Seller: iMac Retina 5K

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Did not attempt.

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior:
After a single purchase was made from my store, six orders were listed in the Transactions>Sales tab.  Same item, different order number, different buyer ID (see attached screenshot).

Expected Behavior:
Expected one order to be created.

<img width="1258" alt="ob-multiple-order" src="https://cloud.githubusercontent.com/assets/1527028/13480933/6076e0e4-e0af-11e5-80eb-b7898f5c37a0.png">

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
Are you certain this isn't 6 different orders from different people? They all happened at different times, and appear to be from different users.

There is no limit to the number of times an item can be purchased, or the number of people that can purchase it.

**Comment by rssalerno** [comment]
It does indeed appear that multiple sales were made by different buyers.  I didn't realize this was possible.

**Comment by jjeffryes** [comment]
This is an area we're working to make more clear.

**Comment by morebrownies** [comment]
This is why we really need the buyer's avatar here to show some differentiation between orders. Otherwise they all look the same and it's difficult to know where you left off

**Comment by rssalerno** [comment]
Please have a look at issue/enhancement request #904.  Need a way to specify available quantity of an item.  If only x of an item is available, and x has been bought, no further purchases should be accepted.
