### ISSUE TITLE
Expected string or buffer

### ISSUE THREAD

**Issue by nanomo** [OpenBazaar/OpenBazaar-Client#940]
Brief Description: After setting my Bitcoin wallet to recieve founds and setting the description for a pending item to be sold and i recieve the message "expected string or buffer" after a few tries the plataform accepts the pending sale.

Windows 7, updated.

**Comment by jjeffryes** [comment]
@cpacia any thoughts on what this error message indicates? Possibly related to unexpected characters in the description?

**Comment by jjeffryes** [comment]
This issue has not been possible to reproduce.
