### ISSUE TITLE
Rating descriptions need to be added

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#942]
In the original design we intended for the ratings page to have a 1 sentence description to add a standard context/meaning to each rating. It would be great if we could somehow add this during the testnet phase. 

Reference: http://www.slideshare.net/drwasho/openbazaar-ratings-reviews-and-reputation (slides 31-39)

**Comment by ac225519** [comment]
![rate](https://cloud.githubusercontent.com/assets/16848241/13487803/9c44ee40-e181-11e5-9c22-e47cbd26509c.png)
This is what we have so far.
Huge help: http://image.slidesharecdn.com/ratingsreviewsandreputationv5-150709113059-lva1-app6892/95/openbazaar-ratings-reviews-and-reputation-33-638.jpg?cb=1442809187

**Comment by morebrownies** [comment]
We should display the description on hover of a star. So for example, If I'm hovering 5 star rating for Quality, it should display "I was very happy with the quality...".

@drwasho can we try to shorten the descriptions? People aren't going to spend the time reading a block of text that long for each and every star. For example, something like "I was very happy with the quality of the item/content/service. I would purchase it again and recommend it to others without hesitation" could simply become "Excellent quality". 

Those long descriptions may get lost in translation as well. I'd suggest going to something simple like below:

OVERALL
5 - Excellent all around
4 - Good
3 - Average 
2 - Poor
1 - Terrible 

QUALITY
5 - Excellent quality
4 - Good quality 
3 - Average quality
2 - Poor quality
1 - Terrible quality

MATCHED DESCRIPTION
5 - Exactly as described
4 - Mostly as described
3 - Somewhat matched the description
2 - Mostly not as described 
1 - Did not match description

DELIVERY SPEED
5 - Extremly fast
4 - Good
3 - Average
2 - Slow 
1 - Terribly slow

CUSTOMER SERVICE
5 - Excellent
4 - Good
3 - Average
2 - Poor
1 - Terrible

**Comment by drwasho** [comment]
http://www.reactiongifs.com/r/ilt.gif

**Comment by drwasho** [comment]
![0](http://www.reactiongifs.com/r/ilt.gif)

**Comment by morebrownies** [comment]
Perfect, will be ready soon. @drwasho let me know if you want to change any of the labels. I slapped those together quickly.

**Comment by drwasho** [comment]
For customer service, I want to predominantly communicate that it's related to the quality and speed of communication. Not quite sure the best way how to do that is.
