### ISSUE TITLE
Shop item location get derived from Settings:Addresses. Not edible.

### ISSUE THREAD

**Issue by ac225519** [OpenBazaar/OpenBazaar-Client#943]
Brief Description: The location of a shop item get derived from Settings:Addresses not Settings:General and is not edible.

Operating System (OS and version): Linux LMDE2
OpenBazaar version: 1.0.6 git ID:5dbca08 downloaded 2016-Mar-02 02:27:02 UTC
Hardware: Intel

Reproducible: Always

Steps to reproduce:
1. Change your Addresses country
2. Create a shop item

Observed Behaviour:
Shop item get the 'Addresses' country location.
And the item location is not edible

Expected Behaviour:
Shop item get the 'General' country location and the item location is edible.

**Comment by jjeffryes** [comment]
I've tested this, and on my own system the shipping_origin of a listing is always taken from the value in Settings/General/Country.

Is that what you're describing?
