### ISSUE TITLE
Add TestNet Warning to Bitcoin Address fields

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Client#945]
On all bitcoin fields, add warning that the address must be valid for testnet, until we switch to the mainnet.

**Comment by TheButterZone** [comment]
Concur.

**Comment by JustVic** [comment]
What bitcoin addresses is valid for test net?

**Comment by jjeffryes** [comment]
@JustVic any address from a testnet wallet. CoPay is one that's easy to set up for the testnet.
