### ISSUE TITLE
Questions regarding translation of OpenBazaar

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#948]
In translating OpenBazaar, I have come over some strings that I need more info about in order to make a better translation (I hope it is not too confusing that I copy/paste from the strings that I have already (partially) translated):

> Change: "Ændring",

Is this a verb or a noun, i.e. as in "a change" or "to change"?

> Enter: "Indtast",

What's the context of this?

> HandleResolver: "Handle Resolver",

What's the context of this? Also, is "handle" a verb or a noun here, i.e. "to handle a resolver" or "a resolver for a handle"?

> transferReceipt: "Overførselskvittering",

What's the context of this? Also, is "transfer" a verb or a noun here, i.e. "to transfer a receipt" or "a receipt for a transfer"?

> FundOrder: "Financiér ordre", // Better translation?

Am I right that this refers to the action of sending bitcoin to an address and thereby paying for the item(s) in an order? If not, what's the context?

> connectExisting: "Forbind til eksisterende",

What's the context of this?

> returnAddress: "Returneringsadresse",

I assume that "return" is a noun here. In either case, what's the context? Which kind of address is this? BTC address? For change? For refund? Postal address?

**Comment by jjeffryes** [comment]
Thank you for asking for clarification, and for stepping in to help with a translation.

Change: a verb, to change something. This is used on buttons. 

Enter: this is used on a button in a tooltip asking if users want to look at the Discover section. In this context it means "Go inside" or "Go to this place"

HandleResolver: This is related to the Handle phrase. A Handle is a unique name that starts with @ that users can register with OneName. For example, "@joshob1". If a user wants to use a different web service to resolve Handles, they can put in the URL of a Handle Resolver in this field.

Transfer Receipt: this is the bitcoin receipt for a transfer

FundOrder: you are correct, this means to fund an order by sending bitcoin to an address

connectExisting: it looks like this is no longer used, I don't remember the context. Don't worry about it, I'll remove it from the language file.

returnAddress: This is the bitcoin address you enter in case a refund is issued by the vendor. They will refund your bitcoin transfer to this address.

**Comment by pryds** [comment]
@jjeffryes Thank you for the clarification. I found out that my initial translations were wrong at several places because I assumed context wrongly. Is there a way to show context descriptions like the ones you give above to translators by default?

**Comment by jjeffryes** [comment]
@pryds we could put in comments on every value in the language file explaining what it means, though that might take a while. It's a good best practice going forward.

**Comment by pryds** [comment]
I need the context of a few new strings, also:

```
      BuyerPayout: "Buyer Payout", // not translated
      SellerPayout: "Seller Payout", // not translated
      BuyerAmout: "Buyer Amout", // not translated
      SellerAmout: "Seller Amout", // not translated
```

Thanks!

**Comment by jjeffryes** [comment]
BuyerPayout = if a dispute has been resolved by a moderator, this is the amount paid to the buyer
SellerPayout = if a dispute has been resolved by a moderator, this is the amount paid to the seller

**Comment by jjeffryes** [comment]
I found BuyerAmount and SellerAmount, editing my comment above.

BuyerAmount is the label for the input field in the dispute resolution screen where the moderator enters the percentage of the transaction funds the buyer will receive.

SellerAmount is the same thing for the seller.
