### ISSUE TITLE
Add an automatic installation for RPi2 (Raspberry Pi) with Raspbian, please

### ISSUE THREAD

**Issue by Nogreedy** [OpenBazaar/OpenBazaar-Client#953]
Add an automatic installation for RPi (Linux raspberry Pi2-ARMv7) with Raspbian, please.
Is it possible to use Linux .deb automatic installation?

**Comment by Nogreedy** [comment]
Sorry for the mistake... it concerns OpenBazaar-Server...

**Comment by jjeffryes** [comment]
@Nogreedy can you re-submit this in the installer repo?
