### ISSUE TITLE
Change the 'Saved' modal

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#959]
If something is changed in the 'Saved' modal we see this:

![image](https://cloud.githubusercontent.com/assets/3887694/13513559/7c7404cc-e1ed-11e5-952b-8843ba7a1ed4.png)

It's kind of annoying that I need to manually close the modal every time. Instead, could we have something like this popup at the bottom of the window for 3 seconds and then fade out?

![image](https://cloud.githubusercontent.com/assets/3887694/13513584/b098c5e4-e1ed-11e5-8f6c-b813812d8421.png)

Ping @jjeffryes @morebrownies

**Comment by TheButterZone** [comment]
Concur.

**Comment by drwasho** [comment]
Done
