### ISSUE TITLE
PGP/GnuPG Key not saving

### ISSUE THREAD

**Issue by M45t3rJC** [OpenBazaar/OpenBazaar-Client#961]
Brief Description: When saving after adding GnuPG key and signature an error occurs..
Data could not be saved.
GnuPG is not installed!

Operating System (OSX 10.10.5): 
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: 

Reproducible (Always): 

Steps to reproduce:
1. add GnuPG key and signature
2. click save changes
3. 

Observed Behavior:
doesn't save data

Expected Behavior:
save data

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
Thank you for reporting this issue, @M45t3rJC. This is a known server issue, we will be adding a PGP library to our installation package in a future release.
