### ISSUE TITLE
Ability to Sell Legal Documents

### ISSUE THREAD

**Issue by RedPillTalk** [OpenBazaar/OpenBazaar-Client#962]
Hello Tech Team, 
I work independently in teaching others about their Political Status, and have developed very important documents that I sell as a result of my 40 years of studying. I was wondering if OpenBazaar can have the ability to host securely these documents on their server. I need to have complete control over who gets to buy these documents, because education is strongly needed before the use of these files I own. So I was thinking, maybe, that I can have some sort of permission settings, like my clients having to enter a special code or link, sent by email from me, to have the purchase button available to them to purchase. That way not just anybody can purchase this. If just anyone can obtain these without my guidance first, they might end up in jail for a long time with serious repercussions. So this method of purchasing for such occasions that I have mentioned, as you can see, is very important. If a better method can be thought of let me know. I am very serious in this issue. Let me know what you think. Thank you for your time.

Respectfully yours

Red

PS: These Documents I have are many. So a bundle purchase will be the way I will go about selling these. Again I don't want just anyone being able to purchase these. Thank you.

**Comment by ac225519** [comment]
Red are you from Nigeria ?

**Comment by RedPillTalk** [comment]
United States

**Comment by hoffmabc** [comment]
I'm gonna drop this issue as its out of scope for the product.
