### ISSUE TITLE
Show number of nodes in the network

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#963]
We can estimate this data from the seed server, and it's a nice non-essential feature that makes the user feel they're part of  something big. Not sure what technical requirements are necessary for that.

**Comment by jjeffryes** [comment]
Adding an issue on the server for this.

**Comment by jjeffryes** [comment]
Look at the no longer used adminPanelVw.js file, it has code to fetch the connected peers. 

This should probably be done as a button in the settings/advanced tab.

When the tab is activated, the call to connected_peers can be made, and the number shown (in a row above the server on/of button would be good). 

There could also be a button next to the number for "show peers" that when pressed, expands the row into a scrollable table that shows 6 rows at a time, each row being one peer and the information about the peer.

Each peer should be clickable, clicking on it would navigate the client to that peer's userPage.

**Comment by ameliagoodman** [comment]
https://github.com/OpenBazaar/OpenBazaar-Client/pull/1824

**Comment by drwasho** [comment]
@ameliagoodman great job!
