### ISSUE TITLE
Add a "Clear conversation" function to chat.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/OpenBazaar-Client#971]
Breaking this out of another issue, since that issue deals with something slightly different.
https://github.com/OpenBazaar/OpenBazaar-Client/issues/342

Also, an API is already in place for this, so we could do this one when we get to it.

Anyhow, the idea is to add a "Clear conversation" line item to the Chat conversation sub-menu which would delete all the messages from a conversation:
![image](https://cloud.githubusercontent.com/assets/794517/13535011/cbc4288c-e1ec-11e5-84d7-b49f8301ecab.png)

**Comment by rmisio** [comment]
@morebrownies FWIW, are we sure we want this functionality? If the user clears their conversation, they will never be able to recover that history.

**Comment by morebrownies** [comment]
Yeah that is the entire point of the feature @rmisio :)

We've had a lot of people ask for this

**Comment by ac225519** [comment]
+1

**Comment by rmisio** [comment]
this is fixed and ready for verification.
