### ISSUE TITLE
Seemingly mandatory order comment is suggested as optional

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#979]
Brief Description: When as a seller you are confirming an order, in the screen where you also paste your Bitcoin-address, the placeholder text for the comment field suggests that a comment is optional, though the field seems to be mandatory, really.

OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.6

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Sell an item, and click "Order details", then "Confirm order".
2. Fill in your BTC address, and leave the comments field empty.
3. Click "Save".

Observed Behavior:
The Comments field is highlighed, even though its placeholder text suggests that it is optional.

Expected Behavior:
The order will be confirmed with an empty comment field -- or the text is changed to reflect that a comment must be entered.

**Comment by jjeffryes** [comment]
This was fixed.
