### ISSUE TITLE
If BTC is currency then we get redundant pricing

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#98]
If BTC we shouldn't show another BTC in parenthesis.

![image](https://cloud.githubusercontent.com/assets/45482/10747806/0596d564-7c30-11e5-87d1-3ad2565147ce.png)

**Comment by jjeffryes** [comment]
Recommended solution: in the item short and item templates, add logic so that if the currency code is BTC the btc value is not shown.

**Comment by hoffmabc** [comment]
Or list it in Dogecoin

**Comment by z3ntu** [comment]
This is fixed/implemented?

**Comment by jjeffryes** [comment]
Yes, this was resolved.
