### ISSUE TITLE
No newlines in listing description

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#980]
Brief Description: It is not possible to add a newline in the description of a listing. Since it is possible to format text as e.g. h2 and h3 headlines, it doesn't make sense that you cannot also have text that's not formatted a headline.

Operating System (OS and version): Ubuntu 14.04 LTS
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.6

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce):
Always

Steps to reproduce:
1. Add a new listing.
2. Place the cursor in the description field
3. Press Enter on the keyboard

Observed Behavior:
Nothing.

Expected Behavior:
A newline is added.

**Comment by jjeffryes** [comment]
This was fixed in release 1.0.7
