### ISSUE TITLE
A long description text clutters layout

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#981]
Brief Description: In creating a listing, if you add a long description text, the layout is rendered too wide and becomes close to unusable.

Operating System (OS and version): Ubuntu 14.04 LTS
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.6

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Add a new listing.
2. Type in a quite long description text. I copy/pasted a lot of random characters.

Observed Behavior:
The layout of the page becomes too wide, so that some of the fields are only half visible, and some are not visible at all.

Expected Behavior:
The description text box grows vertically, not horizontally, or adds scroll bars.

Additional info (links, images, etc go here):
![openbazaar-layoutdescription](https://cloud.githubusercontent.com/assets/4420584/13546510/40d2c8b8-e2b0-11e5-90a2-6accedb4406a.png)

**Comment by pryds** [comment]
It seems that the reason was very long "words", i.e. many characters between spaces. Changing the random characters into a long Lorem Ipsum text solved the problem. This might still be a problem for users who want to include long URL's or similar in their descriptions, though.

**Comment by morebrownies** [comment]
Good catch. It seems like we need to force word warp in the Description field.

**Comment by jjeffryes** [comment]
This has been fixed, I believe in release 1.0.7, if not then in the master branch.
