### ISSUE TITLE
Many shipping destinations clutter layout for buyer

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#982]
Brief Description: When buying a listing that ships to many locations, the window that shows these locations is formatted in a way that not all locations can be seen.

Operating System (OS and version): Ubuntu 14.04 LTS
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.6

Steps to reproduce:
1. Create a listing with many shipping destinations, or find one in the market.
2. Start the buying process, and click to the screen where buyer can select or type their address.

Observed Behavior:
List of countries is too wide, so that not all locations can be seen (see screenshot). Also, user's adress(es) are pushed way down so that it is not obvious what the purpose of this screen is.

Expected Behavior:
A list of countries that fits the window, plus perhaps the list goes below the addresses so that the addresses are not pushed out of view.

Additional info (links, images, etc go here):
![openbazaar-layoutcountries](https://cloud.githubusercontent.com/assets/4420584/13546680/e73bbc0a-e2b5-11e5-8616-75703f201a5e.png)

**Comment by morebrownies** [comment]
Outputting a list of all the available countries does not feel like the best experience here. It's basically leaving the work on the user to dig through that giant list and figure out if they can have the item shipped to their country or not.

Ideally, as a user, I'd like to know before the checkout experience if an item can be shipped to me or not. I'd suggest we remove the list in the modal and bubble up some of this information into the listing detail view. We know the country of the user, so near the "BUY NOW" button I'd like to display "Ships to the _United States_" or "Does not ship to the _United States_"
- = The country of the user

An added benefit is this will save the user a few clicks and simplify the order modal a bit. In the future, Discover should also probably only display listings that you can actually have shipped to your country.

**Comment by pryds** [comment]
> In the future, Discover should also probably only display listings that you can actually have shipped to your country.

Nice. I would suggest this as adjustable in the settings or elsewhere, though, as you might have users living close to a border, or in some other way being able to receive goods to addresses in different countries, but haven't typed in (all) their addresses yet.

(Sorry for the close/reopen; fat fingers)

**Comment by mariodian** [comment]
What if the list of countries that you can ship to was only visible on the map above (with the addition to the information whether the vendor ships to your country or not)? 

On the most far zoom level you could use the heat map so you get an approximate area where you can ship https://developers.google.com/maps/documentation/javascript/examples/layer-heatmap on the closest zoom level a pin should be sufficient enough.
