### ISSUE TITLE
Exception on undoing too much in text field.

### ISSUE THREAD

**Issue by Dekker3D** [OpenBazaar/OpenBazaar-Client#983]
Brief Description: When you press ctrl-z to undo, in a text field, while there's nothing to undo, you get an exception. It doesn't seem to break anything, but it should probably be fixed at some point.

Operating System (OS and version): Windows 7
OpenBazaar version: 1.0.7

Reproducible: Always

Steps to reproduce:
1. Click any text field
2. Press ctrl-z (or whatever undo is on your system) until there's nothing to undo, and then once more.
3. You get an exception. You will get another error when you close the client.

**Comment by ghost** [comment]
I got the same error in Windows 7 64 bits, OB version 1.0.9

**Comment by jjeffryes** [comment]
It appears Electron is trying to fire Menu.sendActionToFirstResponder when control z is pressed too many times. 

From the documentation, that's a call for Mac OS X. https://github.com/atom/electron/blob/master/docs/api/menu.md#menusendactiontofirstresponderaction-os-x

This may be a bug in Electron.

**Comment by drwasho** [comment]
If you select the Discovery search and press `ctrl z` it refreshes the listings below... actually kinda cool!
