### ISSUE TITLE
Tags for stores

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#986]
This is a feature request. At the moment tags are for listings. I think having store tags would be useful for store search.

**Comment by morebrownies** [comment]
These actually already exist, you enter them when you first "Become a store". We need to also add them in Settings > Store.

**Comment by JustinDrake** [comment]
@morebrownies: Cheers!

**Comment by jjeffryes** [comment]
It should be noted that you can enter tags for a store, but they currently don't do anything, as search for stores doesn't exist yet.
