### ISSUE TITLE
Can't edit a previously saved service fee in  Settings > Moderator

### ISSUE THREAD

**Issue by bangers89** [OpenBazaar/OpenBazaar-Client#989]
Brief Description: Can't edit a previously saved service fee in  Settings > Moderator

Operating System (OS and version): OSX Yosemite v 10.10.4
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.7
Hardware: MacBook Pro (Retina, 13-inch, Late 2013)

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Go to Settings > Moderator and set a service fee and save
2. Go back to Settings > Moderator and try to revert the service fee to zero - after saving it reverts to the previous setting. N.B. this only happens if reverting to zero and not any other value

Observed Behavior: Get confirmation of saved edit but still not updating

Expected Behavior: For the new fee I've entered to be correct

Additional info (links, images, etc go here):

**Comment by hoffmabc** [comment]
There is something wrong with setting the value to 0%. This might be a server side thing @cpacia .

**Comment by hoffmabc** [comment]
Other values seem to work properly.

**Comment by hoffmabc** [comment]
Actually @bangers89 you can set it properly from your User Page Moderator Settinsg to get around this for now.

**Comment by jjeffryes** [comment]
This appears to be a server issue. It's being sent to the API, but the original value is returned regardless of where you save it. 

I'll file a server issue.
