### ISSUE TITLE
I can buy my own product

### ISSUE THREAD

**Issue by vassilichacal** [OpenBazaar/OpenBazaar-Client#990]
Brief Description: You can buy your own products

Operating System (OS and version): Debian 64bits
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior: 

Expected Behavior: Buying button shouldn't be even visible if you are at your own store

Additional info (links, images, etc go here):

**Comment by hoffmabc** [comment]
I was not able to get to a payment QR though just as a caveat @jjeffryes most likely because of networking trying to connect to myself.

**Comment by morebrownies** [comment]
I agree that you shouldn't be able to purchase your own items. However, I do think that vendors should be able to see their checkout flow on their own store. By being able to see it they may realize their colors choices don't render well in the modal and can also review the moderators that are servicing their store. So basically I think what we have now works well.

**Comment by mariodian** [comment]
I agree the option of buying own items is needed for debugging purposes, however I think a reminder, that the vendor is using his own checkout page should be visible at all times, so he's aware of it.

**Comment by morebrownies** [comment]
A reminder to tell the user they're on their own store seems like overkill. What we have in place now should be good enough.
