### ISSUE TITLE
Back Button Behavior

### ISSUE THREAD

**Issue by DonGateley** [OpenBazaar/OpenBazaar-Client#994]
Brief Description: Back Buttton always goes back to top of page

Operating System (OS and version): Windows 7

OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.7

Hardware: Lenovo Y570 Laptop

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. From any page scroll down a few screens full and select something
2. From the page arrived at click the back button
3. 

Observed Behavior: Goes back to the top of the previous page

Expected Behavior: Go back to the place in the page from which the prior selection was made.

Additional info (links, images, etc go here):

I find that when I select from some position on a page and then hit the back button I am taken back to the top of the previous page rather than where I was when I clicked on the selection.

I strongly advise a friendly global design discipline that takes one back to exactly where he was at the point of selection. I'd like to see this done early in the game because experience has shown me that it is rare in an application, especially after it has matured, to get that fixed later on.

**Comment by SamPatt** [comment]
@jjeffryes Any updates on this?

**Comment by jjeffryes** [comment]
This is a low-priority feature that has not been worked on.

**Comment by jjeffryes** [comment]
Cached pages maintain their scroll state.
