### ISSUE TITLE
Code Length Overflow for QR

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#995]
Brief Description: I tried to purchase this item (ob://9a791e0e2e4936754b103a6cc3cf22e77c8e507b/listing/913f8d10a9213102a5d1e730b3febff4cdc97486) and got a blank QR code.

Operating System (OS and version): OSX 10.11
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.7
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Visit ob://9a791e0e2e4936754b103a6cc3cf22e77c8e507b/listing/913f8d10a9213102a5d1e730b3febff4cdc97486
2. Purchase using moderated flow

Observed Behavior:
At QR screen you get:
![image](https://cloud.githubusercontent.com/assets/45482/13555520/3f637c44-e390-11e5-9dc5-b58b128bce86.png)

Expected Behavior:
See QR for payment.

Additional info (links, images, etc go here):
![image](https://cloud.githubusercontent.com/assets/45482/13555528/58f80b70-e390-11e5-808a-5aa7291c5f39.png)

purchase_contract

```
{
    "order_id": "71aa409bb143bc95c04e0e117cfbff85b5c662ab", 
    "amount": 0.15, 
    "payment_address": "2Mu4jQMi8RcvMKrpiPiCg8yYHdYCJCkve2i", 
    "success": true
}
```

**Comment by jjeffryes** [comment]
Closed by #1128
