### ISSUE TITLE
Last item listed should be shown first (enhancement)

### ISSUE THREAD

**Issue by PolyDeveloper** [OpenBazaar/OpenBazaar-Client#996]
Brief Description: 
A proposal to improve sorting of items allowing to show the last item you list as the first one on your store page. That way store always looks fresh with renewed items.
Additionally, it would be great to have extra sorting features, such as: Featured or Top Seller items.
Operating System (OS and version): All

**Comment by morebrownies** [comment]
+1

**Comment by drwasho** [comment]
Great idea. 
Linked to #572
