### ISSUE TITLE
Unreadable text in Order after dispute

### ISSUE THREAD

**Issue by AdamISZ** [OpenBazaar/OpenBazaar-Client#999]
Brief Description: 
Text shows up with a black/very dark gray background (my theme has a white overall background) in the chat for a disputed order, for text written by the moderator, in the message which contains "DISPUTE CLOSED". See imgur link at bottom

Operating System (OS and version): Ubuntu 14.10

OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.7
Hardware: n/a

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Don't know

Steps to reproduce:
1. Normal payment workflow, open dispute
2. Moderator closes dispute and writes a message with the closure
3. Buyer (don't know for seller) can't read the message (may depend on background colour of theme)

Observed Behavior:
Unreadable text

Expected Behavior:
Readable text

Additional info (links, images, etc go here):

http://imgur.com/1g1bLmF

**Comment by morebrownies** [comment]
I'll fix this one. I need to spend some time cleaning up the dispute experience.

**Comment by jjeffryes** [comment]
I believe this was fixed after 1.0.7. It currently shows the correct color in master. 

![image](https://cloud.githubusercontent.com/assets/1584275/13582023/cb5b28e0-e477-11e5-86b2-d99f2ca133fc.png)

**Comment by AdamISZ** [comment]
The scenario was in the 'END DISPUTE' message, not 'START DISPUTE'. Not sure if that matters.

**Comment by jjeffryes** [comment]
Good catch, @AdamISZ

I missed it only being in dispute closed. Fixed in #1007
